//! Authenticated wire evidence for the repository-owned hardened-egress gateway.
//!
//! The Worker is not allowed to fetch a tenant-controlled URL directly. It
//! sends the URL and a narrowly-scoped request description to the fixed AOS
//! gateway, authenticated with [`sign_request`]. The gateway returns its
//! connect-time peer and final URL in an envelope authenticated with
//! [`sign_response`]. Both encodings are length-prefixed and versioned so field
//! boundaries are unambiguous and future contracts cannot be confused with
//! this one.

use anyhow::{bail, Result};
use base64::Engine as _;
use hmac::{Hmac, Mac as _};
use sha2::{Digest as _, Sha256};

/// Exact protocol identifier accepted by both the Worker and gateway.
pub const CONTRACT: &str = "aos-hardened-egress-v3";

type HmacSha256 = Hmac<Sha256>;

/// Fields authenticated before the gateway makes an upstream request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RequestEvidence<'a> {
    /// Unix timestamp, bounded by the receiver's replay window.
    pub timestamp: i64,
    /// Per-request random base64url nonce.
    pub nonce: &'a str,
    /// Exact target URL, including a presigned query when applicable.
    pub target_url: &'a str,
    /// Closed uppercase HTTP method.
    pub method: &'a str,
    /// SHA-256 hex of the complete request body.
    pub body_sha256: &'a str,
    /// Optional upstream content type.
    pub content_type: Option<&'a str>,
    /// Optional upstream byte range.
    pub range: Option<&'a str>,
    /// Optional upstream conditional ETag.
    pub if_match: Option<&'a str>,
    /// Optional operator-supplied upstream authorization value.
    pub authorization: Option<&'a str>,
    /// Closed webhook event header, present only for signed webhook POSTs.
    pub webhook_event: Option<&'a str>,
    /// Closed `sha256=<hex>` webhook signature header.
    pub webhook_signature: Option<&'a str>,
    /// Stable webhook delivery identity used for receiver deduplication.
    pub webhook_delivery_id: Option<&'a str>,
}

/// Gateway facts authenticated before the Worker accepts an upstream response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResponseEvidence<'a> {
    /// Unix timestamp generated by the gateway.
    pub timestamp: i64,
    /// Request nonce this response answers.
    pub nonce: &'a str,
    /// Exact final URL after validated redirects.
    pub final_url: &'a str,
    /// Connected global IP address.
    pub peer_ip: &'a str,
    /// Upstream HTTP status.
    pub status: u16,
}

/// Fields in the installer-to-gateway authenticated readiness challenge.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChallengeEvidence<'a> {
    /// Unix timestamp, bounded by the receiver's replay window.
    pub timestamp: i64,
    /// Per-challenge random base64url nonce.
    pub nonce: &'a str,
}

/// Returns lowercase SHA-256 hex for a complete request body.
#[must_use]
pub fn body_sha256(body: &[u8]) -> String {
    hex::encode(Sha256::digest(body))
}

/// Signs one Worker-to-gateway request envelope.
///
/// # Errors
///
/// Returns an error when the shared key is shorter than 32 bytes or an input
/// violates the closed protocol bounds.
pub fn sign_request(key: &[u8], evidence: &RequestEvidence<'_>) -> Result<String> {
    validate_key(key)?;
    validate_request(evidence)?;
    sign_encoded(key, &encode_request(evidence))
}

/// Returns the stable SHA-256 digest committed by durable nonce admission.
///
/// # Errors
///
/// Returns an error when request evidence violates the closed protocol bounds.
pub fn request_digest(evidence: &RequestEvidence<'_>) -> Result<String> {
    validate_request(evidence)?;
    Ok(hex::encode(Sha256::digest(encode_request(evidence))))
}

/// Verifies one Worker-to-gateway request envelope in constant time.
///
/// # Errors
///
/// Returns an error for an invalid key, malformed evidence, signature encoding,
/// or signature mismatch.
pub fn verify_request(key: &[u8], evidence: &RequestEvidence<'_>, signature: &str) -> Result<()> {
    let expected = sign_request(key, evidence)?;
    verify_encoded(&expected, signature)
}

/// Signs one gateway-to-Worker response evidence envelope.
///
/// # Errors
///
/// Returns an error when the shared key is shorter than 32 bytes or an input
/// violates the closed protocol bounds.
pub fn sign_response(key: &[u8], evidence: &ResponseEvidence<'_>) -> Result<String> {
    validate_key(key)?;
    validate_response(evidence)?;
    sign(key, b"aos-hardened-egress-response-v3\0", |message| {
        push_i64(message, evidence.timestamp);
        push_field(message, evidence.nonce);
        push_field(message, evidence.final_url);
        push_field(message, evidence.peer_ip);
        message.extend_from_slice(&evidence.status.to_be_bytes());
    })
}

/// Verifies one gateway-to-Worker response envelope in constant time.
///
/// # Errors
///
/// Returns an error for an invalid key, malformed evidence, signature encoding,
/// or signature mismatch.
pub fn verify_response(key: &[u8], evidence: &ResponseEvidence<'_>, signature: &str) -> Result<()> {
    let expected = sign_response(key, evidence)?;
    verify_encoded(&expected, signature)
}

/// Signs one installer readiness challenge.
///
/// # Errors
///
/// Returns an error for a short key or malformed challenge evidence.
pub fn sign_challenge(key: &[u8], evidence: &ChallengeEvidence<'_>) -> Result<String> {
    validate_key(key)?;
    validate_challenge(evidence)?;
    sign(key, b"aos-hardened-egress-challenge-v3\0", |message| {
        push_i64(message, evidence.timestamp);
        push_field(message, evidence.nonce);
    })
}

/// Verifies one installer readiness challenge in constant time.
///
/// # Errors
///
/// Returns an error for a short key, malformed evidence, or signature mismatch.
pub fn verify_challenge(
    key: &[u8],
    evidence: &ChallengeEvidence<'_>,
    signature: &str,
) -> Result<()> {
    verify_encoded(&sign_challenge(key, evidence)?, signature)
}

/// Signs the gateway's answer to an installer readiness challenge.
///
/// # Errors
///
/// Returns an error for a short key or malformed challenge evidence.
pub fn sign_challenge_response(key: &[u8], evidence: &ChallengeEvidence<'_>) -> Result<String> {
    validate_key(key)?;
    validate_challenge(evidence)?;
    sign(
        key,
        b"aos-hardened-egress-challenge-response-v3\0",
        |message| {
            push_i64(message, evidence.timestamp);
            push_field(message, evidence.nonce);
        },
    )
}

/// Verifies the gateway's answer to an installer readiness challenge.
///
/// # Errors
///
/// Returns an error for a short key, malformed evidence, or signature mismatch.
pub fn verify_challenge_response(
    key: &[u8],
    evidence: &ChallengeEvidence<'_>,
    signature: &str,
) -> Result<()> {
    verify_encoded(&sign_challenge_response(key, evidence)?, signature)
}

fn validate_key(key: &[u8]) -> Result<()> {
    if key.len() < 32 {
        bail!("hardened-egress shared key must contain at least 32 bytes");
    }
    Ok(())
}

fn validate_request(evidence: &RequestEvidence<'_>) -> Result<()> {
    if evidence.nonce.len() < 32 || evidence.nonce.len() > 128 {
        bail!("hardened-egress nonce length is invalid");
    }
    if evidence.target_url.is_empty() || evidence.target_url.len() > 16 * 1024 {
        bail!("hardened-egress target URL length is invalid");
    }
    if !matches!(evidence.method, "GET" | "HEAD" | "POST" | "PUT" | "DELETE") {
        bail!("hardened-egress method is invalid");
    }
    if evidence.body_sha256.len() != 64
        || !evidence
            .body_sha256
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
    {
        bail!("hardened-egress body digest is invalid");
    }
    for (value, cap) in [
        (evidence.content_type, 512),
        (evidence.range, 128),
        (evidence.if_match, 1024),
        (evidence.authorization, 8 * 1024),
    ] {
        if value.is_some_and(|value| {
            value.is_empty() || value.len() > cap || value.chars().any(char::is_control)
        }) {
            bail!("hardened-egress optional header is invalid");
        }
    }
    let webhook_count = [
        evidence.webhook_event,
        evidence.webhook_signature,
        evidence.webhook_delivery_id,
    ]
    .into_iter()
    .flatten()
    .count();
    if webhook_count != 0 && webhook_count != 3 {
        bail!("hardened-egress webhook headers must be supplied as one closed set");
    }
    if let (Some(event), Some(signature), Some(delivery_id)) = (
        evidence.webhook_event,
        evidence.webhook_signature,
        evidence.webhook_delivery_id,
    ) {
        if evidence.method != "POST" || evidence.content_type != Some("application/json") {
            bail!("hardened-egress webhook headers require a JSON POST");
        }
        if !crate::webhook::is_safe_event_header_value(event) {
            bail!("hardened-egress webhook event is invalid");
        }
        let digest = signature.strip_prefix("sha256=").unwrap_or_default();
        if digest.len() != 64
            || !digest
                .bytes()
                .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
        {
            bail!("hardened-egress webhook signature is invalid");
        }
        if delivery_id.is_empty()
            || delivery_id.len() > 64
            || !delivery_id
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        {
            bail!("hardened-egress webhook delivery id is invalid");
        }
    }
    Ok(())
}

fn validate_response(evidence: &ResponseEvidence<'_>) -> Result<()> {
    if evidence.nonce.len() < 32
        || evidence.nonce.len() > 128
        || evidence.final_url.is_empty()
        || evidence.final_url.len() > 16 * 1024
        || evidence.peer_ip.is_empty()
        || evidence.peer_ip.len() > 64
        || !(100..=599).contains(&evidence.status)
    {
        bail!("hardened-egress response evidence is invalid");
    }
    Ok(())
}

fn validate_challenge(evidence: &ChallengeEvidence<'_>) -> Result<()> {
    if evidence.nonce.len() < 32
        || evidence.nonce.len() > 128
        || evidence.nonce.chars().any(char::is_control)
    {
        bail!("hardened-egress challenge nonce is invalid");
    }
    Ok(())
}

fn encode_request(evidence: &RequestEvidence<'_>) -> Vec<u8> {
    let mut message = b"aos-hardened-egress-request-v3\0".to_vec();
    push_i64(&mut message, evidence.timestamp);
    push_field(&mut message, evidence.nonce);
    push_field(&mut message, evidence.target_url);
    push_field(&mut message, evidence.method);
    push_field(&mut message, evidence.body_sha256);
    push_optional(&mut message, evidence.content_type);
    push_optional(&mut message, evidence.range);
    push_optional(&mut message, evidence.if_match);
    push_optional(&mut message, evidence.authorization);
    push_optional(&mut message, evidence.webhook_event);
    push_optional(&mut message, evidence.webhook_signature);
    push_optional(&mut message, evidence.webhook_delivery_id);
    message
}

fn sign_encoded(key: &[u8], message: &[u8]) -> Result<String> {
    let mut mac = HmacSha256::new_from_slice(key)?;
    mac.update(message);
    Ok(base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(mac.finalize().into_bytes()))
}

fn sign(key: &[u8], domain: &[u8], append: impl FnOnce(&mut Vec<u8>)) -> Result<String> {
    let mut message = domain.to_vec();
    append(&mut message);
    sign_encoded(key, &message)
}

fn verify_encoded(expected: &str, supplied: &str) -> Result<()> {
    let expected = base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(expected)?;
    let supplied = base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(supplied)?;
    if expected.len() != supplied.len()
        || !expected
            .iter()
            .zip(&supplied)
            .fold(0_u8, |difference, (left, right)| {
                difference | (left ^ right)
            })
            .eq(&0)
    {
        bail!("hardened-egress evidence signature mismatch");
    }
    Ok(())
}

fn push_i64(message: &mut Vec<u8>, value: i64) {
    message.extend_from_slice(&value.to_be_bytes());
}

fn push_field(message: &mut Vec<u8>, value: &str) {
    message.extend_from_slice(&(value.len() as u64).to_be_bytes());
    message.extend_from_slice(value.as_bytes());
}

fn push_optional(message: &mut Vec<u8>, value: Option<&str>) {
    match value {
        Some(value) => {
            message.push(1);
            push_field(message, value);
        }
        None => message.push(0),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn evidence_is_domain_separated_and_tamper_evident() {
        let key = [7_u8; 32];
        let request = RequestEvidence {
            timestamp: 1_700_000_000,
            nonce: "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG",
            target_url: "https://cache.example/object?signature=secret",
            method: "GET",
            body_sha256: &body_sha256(&[]),
            content_type: None,
            range: Some("bytes=0-31"),
            if_match: None,
            authorization: None,
            webhook_event: None,
            webhook_signature: None,
            webhook_delivery_id: None,
        };
        let signature = sign_request(&key, &request).unwrap();
        assert!(verify_request(&key, &request, &signature).is_ok());
        let mut tampered = request.clone();
        tampered.method = "DELETE";
        assert!(verify_request(&key, &tampered, &signature).is_err());
        assert_eq!(request_digest(&request).unwrap().len(), 64);

        let response = ResponseEvidence {
            timestamp: request.timestamp,
            nonce: request.nonce,
            final_url: request.target_url,
            peer_ip: "203.0.113.9",
            status: 200,
        };
        assert_ne!(
            signature,
            sign_response(&key, &response).unwrap(),
            "request and response signatures must be domain separated"
        );

        let challenge = ChallengeEvidence {
            timestamp: request.timestamp,
            nonce: request.nonce,
        };
        let challenge_signature = sign_challenge(&key, &challenge).unwrap();
        assert!(verify_challenge(&key, &challenge, &challenge_signature).is_ok());
        assert!(verify_challenge_response(&key, &challenge, &challenge_signature).is_err());
        let response_signature = sign_challenge_response(&key, &challenge).unwrap();
        assert!(verify_challenge_response(&key, &challenge, &response_signature).is_ok());
    }

    #[test]
    fn webhook_headers_are_closed_bounded_and_authenticated() {
        let key = [9_u8; 32];
        let digest = body_sha256(br#"{"event":"release.published"}"#);
        let request = RequestEvidence {
            timestamp: 1_700_000_000,
            nonce: "webhookabcdefghijklmnopqrstuvwxyz0123456789ABCDE",
            target_url: "https://hooks.example.test/aos",
            method: "POST",
            body_sha256: &digest,
            content_type: Some("application/json"),
            range: None,
            if_match: None,
            authorization: None,
            webhook_event: Some("release.published"),
            webhook_signature: Some(
                "sha256=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
            ),
            webhook_delivery_id: Some("delivery_01HZX"),
        };
        let signed = sign_request(&key, &request).unwrap();
        assert!(verify_request(&key, &request, &signed).is_ok());
        let mut tampered_event = request.clone();
        tampered_event.webhook_event = Some("release.deleted");
        assert!(verify_request(&key, &tampered_event, &signed).is_err());
        let mut tampered_signature = request.clone();
        tampered_signature.webhook_signature =
            Some("sha256=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
        assert!(verify_request(&key, &tampered_signature, &signed).is_err());
        let mut tampered_id = request.clone();
        tampered_id.webhook_delivery_id = Some("delivery_other");
        assert!(verify_request(&key, &tampered_id, &signed).is_err());

        let mut partial = request.clone();
        partial.webhook_delivery_id = None;
        assert!(sign_request(&key, &partial).is_err());
        let mut control = request.clone();
        control.webhook_event = Some("release.published\r\nX-Evil: yes");
        assert!(sign_request(&key, &control).is_err());
        let mut wrong_method = request.clone();
        wrong_method.method = "GET";
        assert!(sign_request(&key, &wrong_method).is_err());
        let mut tampered_body = request.clone();
        let tampered_body_sha256 = body_sha256(b"different");
        tampered_body.body_sha256 = &tampered_body_sha256;
        assert!(verify_request(&key, &tampered_body, &signed).is_err());
    }
}
