//! Flat-merge golden used as the module-evaluation parity oracle.
//!
//! Snapshots [`aos_package::render_package_config`] for a hand-authored
//! multi-artifact fixture package and pins three properties that the
//! content-addressing model depends on:
//!
//! 1. the render equals the committed golden under `tests/fixtures/`;
//! 2. re-rendering with **shuffled** artifact and field input order produces a
//!    byte-identical canonical snapshot (order independence);
//! 3. the render is idempotent across two calls.
//!
//! This is the upstream determinism guarantee for the future
//! `checks.config-parity` oracle: once the expose surface is module-evaluated,
//! its render is diffed against this same flat-merge golden. The golden is
//! regenerated by running this test with `AOS_REGENERATE_GOLDENS=1`, which
//! rewrites `web.golden` from the live render — a reviewed, intentional change.

use std::collections::BTreeMap;

use aos_package::config_artifact::render_package_config;
use aos_package::types::{ConfigArtifactFormat, ConfigArtifactMeta, ConfigReloadPolicy};

/// Path to the committed golden, relative to the crate root.
const GOLDEN_PATH: &str = "tests/fixtures/golden_config_artifact/web.golden";
const GOLDEN: &str = include_str!("fixtures/golden_config_artifact/web.golden");

/// Build one artifact-metadata record for the fixture corpus.
fn artifact(
    name: &str,
    format: ConfigArtifactFormat,
    required: &[&str],
    optional: &[&str],
) -> ConfigArtifactMeta {
    ConfigArtifactMeta {
        name: name.into(),
        path: format!("/etc/aos/packages/web/{name}"),
        format,
        required: required.iter().map(|s| (*s).into()).collect(),
        optional: optional.iter().map(|s| (*s).into()).collect(),
        units: vec!["web.service".into()],
        reload: ConfigReloadPolicy::Reload,
    }
}

/// The fixture artifacts in declaration order: a 3-artifact package spanning all
/// three serialization formats and multiple config fields.
fn fixture_artifacts() -> Vec<ConfigArtifactMeta> {
    vec![
        artifact("env", ConfigArtifactFormat::Env, &["TOKEN"], &["URL"]),
        artifact("json", ConfigArtifactFormat::Json, &["a"], &["b"]),
        artifact("toml", ConfigArtifactFormat::Toml, &["k"], &[]),
    ]
}

/// Build the desired-config map from an ordered list of `(artifact, fields)`
/// pairs so callers can shuffle the *insertion* order and prove it is irrelevant.
fn desired_from(
    pairs: Vec<(&str, Vec<(&str, toml::Value)>)>,
) -> BTreeMap<String, BTreeMap<String, toml::Value>> {
    pairs
        .into_iter()
        .map(|(artifact, fields)| {
            (
                artifact.to_string(),
                fields
                    .into_iter()
                    .map(|(field, value)| (field.to_string(), value))
                    .collect(),
            )
        })
        .collect()
}

/// The desired values for the fixture, in one canonical insertion order.
fn fixture_desired() -> BTreeMap<String, BTreeMap<String, toml::Value>> {
    desired_from(vec![
        (
            "env",
            vec![
                ("TOKEN", toml::Value::String("abc 123".into())),
                ("URL", toml::Value::String("https://x".into())),
            ],
        ),
        (
            "json",
            vec![
                ("a", toml::Value::Integer(1)),
                ("b", toml::Value::String("two".into())),
            ],
        ),
        ("toml", vec![("k", toml::Value::String("v".into()))]),
    ])
}

/// Serialize a render result into the order-independent golden form: each
/// artifact's bytes under a sorted `=== <name> ===` header.
fn canonicalize(rendered: &[(&ConfigArtifactMeta, Vec<u8>)]) -> String {
    let mut by_name: BTreeMap<&str, &[u8]> = BTreeMap::new();
    for (artifact, bytes) in rendered {
        let inserted = by_name.insert(artifact.name.as_str(), bytes.as_slice());
        assert!(inserted.is_none(), "duplicate artifact {}", artifact.name);
    }
    let mut out = String::new();
    for (name, bytes) in by_name {
        out.push_str(&format!("=== {name} ===\n"));
        out.push_str(std::str::from_utf8(bytes).expect("rendered artifact is valid UTF-8"));
    }
    out
}

#[test]
fn render_matches_committed_golden() {
    let artifacts = fixture_artifacts();
    let desired = fixture_desired();
    let rendered = render_package_config("web", &artifacts, Some(&desired))
        .expect("fixture corpus renders cleanly");
    let canonical = canonicalize(&rendered);

    if std::env::var_os("AOS_REGENERATE_GOLDENS").is_some() {
        std::fs::write(GOLDEN_PATH, &canonical).expect("rewrite golden");
        return;
    }

    assert_eq!(
        canonical, GOLDEN,
        "render diverged from committed golden ({GOLDEN_PATH}); rerun with \
         AOS_REGENERATE_GOLDENS=1 to update intentionally"
    );
}

#[test]
fn render_is_order_independent() {
    let canonical_baseline = {
        let artifacts = fixture_artifacts();
        let desired = fixture_desired();
        let rendered =
            render_package_config("web", &artifacts, Some(&desired)).expect("baseline renders");
        canonicalize(&rendered)
    };

    // Shuffle both axes: artifact declaration order AND field insertion order.
    let shuffled_artifacts = vec![
        artifact("toml", ConfigArtifactFormat::Toml, &["k"], &[]),
        artifact("env", ConfigArtifactFormat::Env, &["TOKEN"], &["URL"]),
        artifact("json", ConfigArtifactFormat::Json, &["a"], &["b"]),
    ];
    let shuffled_desired = desired_from(vec![
        ("toml", vec![("k", toml::Value::String("v".into()))]),
        (
            "json",
            vec![
                ("b", toml::Value::String("two".into())),
                ("a", toml::Value::Integer(1)),
            ],
        ),
        (
            "env",
            vec![
                ("URL", toml::Value::String("https://x".into())),
                ("TOKEN", toml::Value::String("abc 123".into())),
            ],
        ),
    ]);

    let rendered = render_package_config("web", &shuffled_artifacts, Some(&shuffled_desired))
        .expect("shuffled corpus renders");
    let canonical_shuffled = canonicalize(&rendered);

    assert_eq!(
        canonical_baseline, canonical_shuffled,
        "render output depends on input order — determinism violated"
    );
    assert_eq!(canonical_shuffled, GOLDEN, "shuffled render must still match the golden");
}

#[test]
fn render_is_idempotent() {
    let artifacts = fixture_artifacts();
    let desired = fixture_desired();
    let first = render_package_config("web", &artifacts, Some(&desired)).expect("first render");
    let second = render_package_config("web", &artifacts, Some(&desired)).expect("second render");
    assert_eq!(
        canonicalize(&first),
        canonicalize(&second),
        "two renders of identical inputs produced different bytes"
    );
}
