//! Flat-merge to module-evaluation configuration parity oracle.
//!
//! Snapshots [`aos_package::render_package_config`] for both the legacy expose
//! metadata and the independently Nix-module-evaluated projection pinned by
//! `checks.config-parity`. It pins the migration properties that the
//! content-addressing model depends on:
//!
//! 1. the render equals the committed golden under `tests/fixtures/`;
//! 2. re-rendering with **shuffled** artifact and field input order produces a
//!    byte-identical canonical snapshot (order independence);
//! 3. the render is idempotent across two calls.
//!
//! 4. module-evaluated and legacy inputs produce identical artifact bytes and
//!    reload/restart sets;
//! 5. a mixed migrated/flat generation is stable under package ordering;
//! 6. changing module-evaluated bytes or policy is detected.
//!
//! The golden is regenerated by running this test with
//! `AOS_REGENERATE_GOLDENS=1`, which rewrites `web.golden` from the live legacy
//! render - a reviewed, intentional change.

use std::collections::BTreeMap;

use aos_package::config_artifact::render_package_config;
use aos_package::types::{ConfigArtifactFormat, ConfigArtifactMeta, ConfigReloadPolicy};
use serde::Deserialize;

/// Path to the committed golden, relative to the crate root.
const GOLDEN_PATH: &str = "tests/fixtures/golden_config_artifact/web.golden";
const GOLDEN: &str = include_str!("fixtures/golden_config_artifact/web.golden");
const MODULE_EVAL: &str = include_str!("fixtures/golden_config_artifact/web.module-eval.json");

/// Pure-data result emitted by the Nix module fixture in `checks.config-parity`.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct ModuleProjection {
    /// Typed artifact declarations after module defaults and merges.
    artifacts: Vec<ConfigArtifactMeta>,
    /// Desired values projected from the evaluated package root.
    desired: BTreeMap<String, BTreeMap<String, toml::Value>>,
}

/// Parses the independently pinned module-evaluation projection.
fn module_projection() -> ModuleProjection {
    serde_json::from_str(MODULE_EVAL).expect("module-eval fixture must be valid")
}

/// Derives the exact reload/restart policy sets from artifact metadata.
fn reconciliation_actions(
    artifacts: &[ConfigArtifactMeta],
) -> (
    std::collections::BTreeSet<String>,
    std::collections::BTreeSet<String>,
) {
    let mut reload = std::collections::BTreeSet::new();
    let mut restart = std::collections::BTreeSet::new();
    for artifact in artifacts {
        match artifact.reload {
            ConfigReloadPolicy::Reload => reload.extend(artifact.units.iter().cloned()),
            ConfigReloadPolicy::Restart => restart.extend(artifact.units.iter().cloned()),
            ConfigReloadPolicy::None => {}
        }
    }
    (reload, restart)
}

/// Build one artifact-metadata record for the fixture corpus.
fn artifact(
    name: &str,
    format: ConfigArtifactFormat,
    required: &[&str],
    optional: &[&str],
) -> ConfigArtifactMeta {
    ConfigArtifactMeta {
        name: name.into(),
        path: format!("/etc/aos/packages/web/{name}"),
        format,
        required: required.iter().map(|s| (*s).into()).collect(),
        optional: optional.iter().map(|s| (*s).into()).collect(),
        units: vec!["web.service".into()],
        reload: ConfigReloadPolicy::Reload,
    }
}

/// The fixture artifacts in declaration order: a 3-artifact package spanning all
/// three serialization formats and multiple config fields.
fn fixture_artifacts() -> Vec<ConfigArtifactMeta> {
    vec![
        artifact("env", ConfigArtifactFormat::Env, &["TOKEN"], &["URL"]),
        artifact("json", ConfigArtifactFormat::Json, &["a"], &["b"]),
        artifact("toml", ConfigArtifactFormat::Toml, &["k"], &[]),
    ]
}

/// Build the desired-config map from an ordered list of `(artifact, fields)`
/// pairs so callers can shuffle the *insertion* order and prove it is irrelevant.
fn desired_from(
    pairs: Vec<(&str, Vec<(&str, toml::Value)>)>,
) -> BTreeMap<String, BTreeMap<String, toml::Value>> {
    pairs
        .into_iter()
        .map(|(artifact, fields)| {
            (
                artifact.to_string(),
                fields
                    .into_iter()
                    .map(|(field, value)| (field.to_string(), value))
                    .collect(),
            )
        })
        .collect()
}

/// The desired values for the fixture, in one canonical insertion order.
fn fixture_desired() -> BTreeMap<String, BTreeMap<String, toml::Value>> {
    desired_from(vec![
        (
            "env",
            vec![
                ("TOKEN", toml::Value::String("abc 123".into())),
                ("URL", toml::Value::String("https://x".into())),
            ],
        ),
        (
            "json",
            vec![
                ("a", toml::Value::Integer(1)),
                ("b", toml::Value::String("two".into())),
            ],
        ),
        ("toml", vec![("k", toml::Value::String("v".into()))]),
    ])
}

/// Serialize a render result into the order-independent golden form: each
/// artifact's bytes under a sorted `=== <name> ===` header.
fn canonicalize(rendered: &[(&ConfigArtifactMeta, Vec<u8>)]) -> String {
    let mut by_name: BTreeMap<&str, &[u8]> = BTreeMap::new();
    for (artifact, bytes) in rendered {
        let inserted = by_name.insert(artifact.name.as_str(), bytes.as_slice());
        assert!(inserted.is_none(), "duplicate artifact {}", artifact.name);
    }
    let mut out = String::new();
    for (name, bytes) in by_name {
        out.push_str(&format!("=== {name} ===\n"));
        out.push_str(std::str::from_utf8(bytes).expect("rendered artifact is valid UTF-8"));
    }
    out
}

#[test]
fn render_matches_committed_golden() {
    let artifacts = fixture_artifacts();
    let desired = fixture_desired();
    let rendered = render_package_config("web", &artifacts, Some(&desired))
        .expect("fixture corpus renders cleanly");
    let canonical = canonicalize(&rendered);

    if std::env::var_os("AOS_REGENERATE_GOLDENS").is_some() {
        std::fs::write(GOLDEN_PATH, &canonical).expect("rewrite golden");
        return;
    }

    assert_eq!(
        canonical, GOLDEN,
        "render diverged from committed golden ({GOLDEN_PATH}); rerun with \
         AOS_REGENERATE_GOLDENS=1 to update intentionally"
    );
}

#[test]
fn render_is_order_independent() {
    let canonical_baseline = {
        let artifacts = fixture_artifacts();
        let desired = fixture_desired();
        let rendered =
            render_package_config("web", &artifacts, Some(&desired)).expect("baseline renders");
        canonicalize(&rendered)
    };

    // Shuffle both axes: artifact declaration order AND field insertion order.
    let shuffled_artifacts = vec![
        artifact("toml", ConfigArtifactFormat::Toml, &["k"], &[]),
        artifact("env", ConfigArtifactFormat::Env, &["TOKEN"], &["URL"]),
        artifact("json", ConfigArtifactFormat::Json, &["a"], &["b"]),
    ];
    let shuffled_desired = desired_from(vec![
        ("toml", vec![("k", toml::Value::String("v".into()))]),
        (
            "json",
            vec![
                ("b", toml::Value::String("two".into())),
                ("a", toml::Value::Integer(1)),
            ],
        ),
        (
            "env",
            vec![
                ("URL", toml::Value::String("https://x".into())),
                ("TOKEN", toml::Value::String("abc 123".into())),
            ],
        ),
    ]);

    let rendered = render_package_config("web", &shuffled_artifacts, Some(&shuffled_desired))
        .expect("shuffled corpus renders");
    let canonical_shuffled = canonicalize(&rendered);

    assert_eq!(
        canonical_baseline, canonical_shuffled,
        "render output depends on input order — determinism violated"
    );
    assert_eq!(
        canonical_shuffled, GOLDEN,
        "shuffled render must still match the golden"
    );
}

#[test]
fn render_is_idempotent() {
    let artifacts = fixture_artifacts();
    let desired = fixture_desired();
    let first = render_package_config("web", &artifacts, Some(&desired)).expect("first render");
    let second = render_package_config("web", &artifacts, Some(&desired)).expect("second render");
    assert_eq!(
        canonicalize(&first),
        canonicalize(&second),
        "two renders of identical inputs produced different bytes"
    );
}

#[test]
fn module_evaluation_matches_flat_bytes_and_actions() {
    let flat_artifacts = fixture_artifacts();
    let flat_desired = fixture_desired();
    let module = module_projection();

    let flat = render_package_config("web", &flat_artifacts, Some(&flat_desired))
        .expect("legacy flat projection renders");
    let migrated = render_package_config("web", &module.artifacts, Some(&module.desired))
        .expect("module-evaluated projection renders");

    assert_eq!(
        canonicalize(&flat),
        canonicalize(&migrated),
        "module evaluation changed materialized artifact bytes"
    );
    assert_eq!(
        reconciliation_actions(&flat_artifacts),
        reconciliation_actions(&module.artifacts),
        "module evaluation changed reload/restart actions"
    );
    assert_eq!(canonicalize(&migrated), GOLDEN);
}

#[test]
fn module_projection_is_order_independent() {
    let module = module_projection();
    let baseline = render_package_config("web", &module.artifacts, Some(&module.desired))
        .expect("module projection renders");

    let mut shuffled_artifacts = module.artifacts.clone();
    shuffled_artifacts.reverse();
    let shuffled = render_package_config("web", &shuffled_artifacts, Some(&module.desired))
        .expect("shuffled module projection renders");

    assert_eq!(canonicalize(&baseline), canonicalize(&shuffled));
    assert_eq!(
        reconciliation_actions(&module.artifacts),
        reconciliation_actions(&shuffled_artifacts)
    );
}

#[test]
fn parity_oracle_detects_module_tampering() {
    let flat_artifacts = fixture_artifacts();
    let flat_desired = fixture_desired();
    let flat = render_package_config("web", &flat_artifacts, Some(&flat_desired))
        .expect("legacy flat projection renders");

    let mut byte_tamper = module_projection();
    byte_tamper
        .desired
        .get_mut("env")
        .expect("env artifact")
        .insert("TOKEN".into(), toml::Value::String("tampered".into()));
    let tampered = render_package_config("web", &byte_tamper.artifacts, Some(&byte_tamper.desired))
        .expect("byte-tampered module projection still renders");
    assert_ne!(
        canonicalize(&flat),
        canonicalize(&tampered),
        "byte tampering must trip the parity oracle"
    );

    let mut policy_tamper = module_projection();
    policy_tamper.artifacts[0].reload = ConfigReloadPolicy::Restart;
    assert_ne!(
        reconciliation_actions(&flat_artifacts),
        reconciliation_actions(&policy_tamper.artifacts),
        "reload-policy tampering must trip the parity oracle"
    );
}

#[test]
fn mixed_migrated_and_flat_packages_are_order_independent() {
    let module = module_projection();
    let module_render = render_package_config("web", &module.artifacts, Some(&module.desired))
        .expect("migrated package renders");

    let legacy_artifacts = vec![ConfigArtifactMeta {
        name: "legacy".into(),
        path: "/etc/aos/packages/legacy/legacy.env".into(),
        format: ConfigArtifactFormat::Env,
        required: Vec::new(),
        optional: vec!["VALUE".into()],
        units: vec!["legacy.service".into()],
        reload: ConfigReloadPolicy::Restart,
    }];
    let legacy_desired = desired_from(vec![(
        "legacy",
        vec![("VALUE", toml::Value::String("flat".into()))],
    )]);
    let legacy_render = render_package_config("legacy", &legacy_artifacts, Some(&legacy_desired))
        .expect("legacy fallback package renders");

    let package_snapshot = |module_first: bool| {
        let mut packages = if module_first {
            vec![
                ("web", canonicalize(&module_render)),
                ("legacy", canonicalize(&legacy_render)),
            ]
        } else {
            vec![
                ("legacy", canonicalize(&legacy_render)),
                ("web", canonicalize(&module_render)),
            ]
        };
        packages.sort_by_key(|(name, _)| *name);
        packages
    };

    assert_eq!(package_snapshot(true), package_snapshot(false));
    assert_eq!(
        reconciliation_actions(&module.artifacts).0,
        std::collections::BTreeSet::from(["web.service".to_string()])
    );
    assert_eq!(
        reconciliation_actions(&legacy_artifacts).1,
        std::collections::BTreeSet::from(["legacy.service".to_string()])
    );
}
