##! modules/services/bind.nix — BIND authoritative and recursive DNS service
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.aos.services.bind;
  portType = lib.types.addCheck lib.types.int (value: value >= 1 && value <= 65535);
  renderAddresses = values:
    if values == []
    then "none"
    else lib.concatStringsSep "; " values;
  ipv4Addresses = renderAddresses cfg.listenIPv4;
  ipv6Addresses = renderAddresses cfg.listenIPv6;
  forwarders = lib.concatStringsSep "; " cfg.forwarders;
  namedConf = ''
    // Generated by modules/services/bind.nix.
    options {
      directory "/var/lib/bind";
      pid-file "/run/named/named.pid";
      session-keyfile "/run/named/session.key";
      managed-keys-directory "/var/lib/bind";
      listen-on port ${toString cfg.port} { ${ipv4Addresses}; };
      listen-on-v6 port ${toString cfg.port} { ${ipv6Addresses}; };
      recursion ${
      if cfg.recursion
      then "yes"
      else "no"
    };
      dnssec-validation auto;
      empty-zones-enable yes;
      ${lib.optionalString (cfg.forwarders != []) "forwarders { ${forwarders}; };"}
    };

    ${cfg.extraConfig}
  '';
in {
  options.aos.services.bind = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Run the BIND DNS server.";
    };

    port = lib.mkOption {
      type = portType;
      default = 53;
      description = "TCP and UDP port on which named listens.";
    };

    listenIPv4 = lib.mkOption {
      type = lib.types.listOf (lib.types.strMatching "[A-Za-z0-9:.%_-]+");
      default = ["127.0.0.1"];
      description = "IPv4 addresses on which named listens.";
    };

    listenIPv6 = lib.mkOption {
      type = lib.types.listOf (lib.types.strMatching "[A-Za-z0-9:.%_-]+");
      default = ["::1"];
      description = "IPv6 addresses on which named listens.";
    };

    recursion = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Answer recursive DNS queries.";
    };

    forwarders = lib.mkOption {
      type = lib.types.listOf (lib.types.strMatching "[A-Za-z0-9:.%_-]+");
      default = [];
      description = "Upstream DNS servers used as forwarders.";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Additional named.conf declarations, such as zone definitions.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.listenIPv4 != [] || cfg.listenIPv6 != [];
        message = "BIND must listen on at least one IPv4 or IPv6 address";
      }
      {
        assertion = !(config.aos.services.dnsmasq.enable && config.aos.services.dnsmasq.port == cfg.port);
        message = "BIND and dnsmasq cannot both listen on the same DNS port";
      }
    ];

    environment.systemPackages = [pkgs.bind pkgs.dnsutils];
    environment.etc."bind/named.conf".text = namedConf;
    systemd.services.named = {
      description = "BIND Domain Name Server";
      wantedBy = ["multi-user.target"];
      after = ["network.target" "systemd-tmpfiles-setup.service"];
      wants = ["network.target"];
      requires = ["systemd-tmpfiles-setup.service"];
      serviceConfig = {
        Type = "notify";
        ExecStart = "${pkgs.bind}/sbin/named -f -c /etc/bind/named.conf";
        ExecReload = "${pkgs.bind}/sbin/rndc reload";
        DynamicUser = true;
        User = "named";
        Group = "named";
        RuntimeDirectory = "named";
        RuntimeDirectoryMode = "0750";
        StateDirectory = "bind";
        StateDirectoryMode = "0750";
        AmbientCapabilities = ["CAP_NET_BIND_SERVICE"];
        CapabilityBoundingSet = ["CAP_NET_BIND_SERVICE"];
        Restart = "on-failure";
        ProtectHome = true;
        ProtectSystem = "strict";
        PrivateTmp = true;
        NoNewPrivileges = true;
        ReadWritePaths = ["/run/named" "/var/lib/bind"];
      };
    };

    system.checks.bind = {
      description = "BIND DNS service checks";
      checks = [
        {
          name = "named-config";
          description = "The generated BIND configuration is valid";
          script = ''
            vm.succeed("named-checkconf /etc/bind/named.conf")
          '';
        }
        {
          name = "named-active";
          description = "named reaches its ready state";
          script = ''
            vm.wait_until_succeeds(
                "systemctl is-active --quiet named.service", timeout=30
            )
            vm.succeed("dig -p ${toString cfg.port} @127.0.0.1 version.bind TXT CH +short")
          '';
        }
      ];
    };
  };
}
