##! modules/services/nginx.nix — nginx web server module
##!
##! Configures the nginx HTTP server with automatic TLS certificate management
##! via the nginx-acme dynamic module. Generates nginx.conf, systemd service,
##! and virtual host configurations with ACME support.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.aos.services.nginx;

  # Apply submodule defaults — AOS submodule merge doesn't auto-apply nested
  # option defaults, so we provide them here for any omitted fields.
  applyVhostDefaults = vhost: {
    serverName = vhost.serverName;
    acme = vhost.acme or true;
    basicAuth = vhost.basicAuth or false;
    basicAuthFile = vhost.basicAuthFile or "/etc/nginx/htpasswd";
    root = vhost.root or null;
    autoindex = vhost.autoindex or false;
    locations = vhost.locations or { };
    extraConfig = vhost.extraConfig or "";
  };

  # Build virtual host server blocks for port 443.
  vhostBlocks = lib.mapAttrsToList (
    name: raw:
    let
      vhost = applyVhostDefaults raw;
      acmeDirectives = lib.optionalString vhost.acme ''
        acme ${vhost.serverName};
        ssl_certificate $acme_certificate;
        ssl_certificate_key $acme_certificate_key;
      '';
      authDirectives = lib.optionalString vhost.basicAuth ''
        auth_basic "Restricted";
        auth_basic_user_file ${vhost.basicAuthFile};
      '';
      locationBlocks = lib.mapAttrsToList (locPath: locCfg: ''
        location ${locPath} {
          ${lib.optionalString (locCfg ? root) "root ${locCfg.root};"}
          ${lib.optionalString (locCfg ? proxyPass) "proxy_pass ${locCfg.proxyPass};"}
          ${lib.optionalString (locCfg ? extraConfig) locCfg.extraConfig}
        }
      '') vhost.locations;
      rootDirective = lib.optionalString (vhost.root != null) "root ${vhost.root};";
      autoindexDirective = lib.optionalString vhost.autoindex "autoindex on;";
    in
    ''
      server {
        listen 443 ssl;
        server_name ${vhost.serverName};
        ${acmeDirectives}
        ${authDirectives}
        ${rootDirective}
        ${autoindexDirective}
        ${builtins.concatStringsSep "\n    " locationBlocks}
        ${vhost.extraConfig}
      }
    ''
  ) cfg.virtualHosts;

  # Full nginx.conf
  nginxConf = ''
    # /etc/nginx/nginx.conf — generated by modules/services/nginx.nix
    # Do not edit manually.

    worker_processes auto;
    pid /run/nginx.pid;
    error_log /var/log/nginx/error.log warn;

    load_module ${pkgs.nginx-acme}/lib/nginx/modules/ngx_http_acme_module.so;

    events {
      worker_connections 1024;
    }

    http {
      include ${pkgs.nginx}/etc/nginx/mime.types;
      default_type application/octet-stream;

      access_log /var/log/nginx/access.log;

      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      server_tokens off;

      # ACME configuration for automatic TLS certificates
      acme_client https://acme-v02.api.letsencrypt.org/directory;
      resolver 1.1.1.1 8.8.8.8 valid=300s;
      resolver_timeout 5s;

      acme_zone acme 1m;

      ${lib.optionalString (cfg.acmeEmail != "") ''
        acme_email ${cfg.acmeEmail};
      ''}

      # HTTP server — ACME challenges + redirect to HTTPS
      server {
        listen 80 default_server;
        server_name _;

        location /.well-known/acme-challenge/ {
          acme;
        }

        location / {
          return 301 https://$host$request_uri;
        }
      }

      # HTTPS virtual hosts
      ${builtins.concatStringsSep "\n  " vhostBlocks}
    }
  '';
in
{
  options.aos.services.nginx = {
    ## Enable the nginx web server with ACME TLS support.
    ##
    ## # See Also
    ## - `aos.services.nginx.virtualHosts`, `aos.services.nginx.acmeEmail`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable the nginx web server with ACME TLS support.";
    };

    ## Contact email for Let's Encrypt ACME registration.
    acmeEmail = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Contact email for Let's Encrypt ACME registration.";
    };

    ## Directory for ACME certificate state.
    acmeStatePath = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/nginx/acme";
      description = "Directory for ACME certificate state.";
    };

    ## nginx virtual host definitions.
    ##
    ## # Examples
    ## ```nix
    ## aos.services.nginx.virtualHosts.mysite = {
    ##   serverName = "mysite.example.com";
    ##   acme = true;
    ##   root = "/var/www/mysite";
    ## };
    ## ```
    virtualHosts = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule {
          options = {
            ## Server name for this virtual host.
            serverName = lib.mkOption {
              type = lib.types.str;
              description = "Server name for this virtual host.";
            };
            ## Enable ACME automatic TLS for this host.
            acme = lib.mkOption {
              type = lib.types.bool;
              default = true;
              description = "Enable ACME automatic TLS for this host.";
            };
            ## Enable HTTP basic authentication.
            basicAuth = lib.mkOption {
              type = lib.types.bool;
              default = false;
              description = "Enable HTTP basic authentication.";
            };
            ## Path to htpasswd file for basic auth.
            basicAuthFile = lib.mkOption {
              type = lib.types.str;
              default = "/etc/nginx/htpasswd";
              description = "Path to htpasswd file for basic auth.";
            };
            ## Document root directory.
            root = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Document root directory.";
            };
            ## Enable directory listing (autoindex).
            autoindex = lib.mkOption {
              type = lib.types.bool;
              default = false;
              description = "Enable directory listing (autoindex).";
            };
            ## Location blocks for this virtual host.
            locations = lib.mkOption {
              type = lib.types.attrsOf (lib.types.attrsOf lib.types.str);
              default = { };
              description = "Location blocks for this virtual host.";
            };
            ## Extra nginx configuration for this server block.
            extraConfig = lib.mkOption {
              type = lib.types.str;
              default = "";
              description = "Extra nginx configuration for this server block.";
            };
          };
        }
      );
      default = { };
      description = "nginx virtual host definitions.";
    };
  };

  config = lib.mkIf cfg.enable {
    system.checks.nginx = lib.mkCheckGroup {
      name = "nginx";
      description = "nginx web server checks";
      checks = [
        (lib.mkCheck {
          name = "config-exists";
          description = "nginx.conf is generated";
          script = ''
            assert_success "test -f /etc/nginx/nginx.conf" \
              "nginx.conf exists"
          '';
        })
        (lib.mkCheck {
          name = "config-worker-processes";
          description = "nginx.conf has worker_processes directive";
          script = ''
            assert_output_contains "cat /etc/nginx/nginx.conf" "worker_processes" \
              "nginx.conf contains worker_processes"
          '';
        })
        (lib.mkCheck {
          name = "config-listen-80";
          description = "nginx.conf listens on port 80";
          script = ''
            assert_output_contains "cat /etc/nginx/nginx.conf" "listen 80" \
              "nginx.conf contains listen 80"
          '';
        })
        (lib.mkCheck {
          name = "config-listen-443";
          description = "nginx.conf has HTTPS server block";
          script = ''
            assert_output_contains "cat /etc/nginx/nginx.conf" "listen 443 ssl" \
              "nginx.conf contains listen 443 ssl"
          '';
        })
        (lib.mkCheck {
          name = "config-acme";
          description = "nginx.conf loads ACME module";
          script = ''
            assert_output_contains "cat /etc/nginx/nginx.conf" "ngx_http_acme_module" \
              "nginx.conf loads ACME module"
          '';
        })
        (lib.mkCheck {
          name = "service-loaded";
          description = "nginx systemd service unit exists";
          script = ''
            assert_success "systemctl cat nginx" \
              "nginx service unit is loaded"
          '';
        })
        (lib.mkCheck {
          name = "tmpfiles-config";
          description = "nginx tmpfiles config exists";
          script = ''
            assert_success "test -f /etc/tmpfiles.d/aos-nginx.conf" \
              "nginx tmpfiles config exists"
          '';
        })
        (lib.mkCheck {
          name = "firewall-http";
          description = "Firewall allows port 80";
          script = ''
            assert_output_contains "cat /etc/nftables.conf" "80" \
              "nftables config includes port 80"
          '';
        })
        (lib.mkCheck {
          name = "firewall-https";
          description = "Firewall allows port 443";
          script = ''
            assert_output_contains "cat /etc/nftables.conf" "443" \
              "nftables config includes port 443"
          '';
        })
      ];
    };

    environment.systemPackages = [
      pkgs.nginx
      pkgs.nginx-acme
    ];

    # /etc/nginx/nginx.conf
    environment.etc."nginx/nginx.conf" = {
      text = nginxConf;
    };

    # nginx.service — HTTP server daemon.
    systemd.services."nginx" = {
      description = "nginx HTTP Server";
      wantedBy = [ "multi-user.target" ];
      after = [
        "network-online.target"
        "local-fs.target"
      ];
      wants = [ "network-online.target" ];
      serviceConfig = {
        Type = "forking";
        PIDFile = "/run/nginx.pid";
        ExecStartPre = "${pkgs.nginx}/bin/nginx -t -c /etc/nginx/nginx.conf";
        ExecStart = "${pkgs.nginx}/bin/nginx -c /etc/nginx/nginx.conf";
        ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        ExecStop = "${pkgs.coreutils}/bin/kill -QUIT $MAINPID";
        Restart = "on-failure";
        RestartSec = "5s";
        # Security hardening.
        ProtectHome = true;
        NoNewPrivileges = true;
        PrivateTmp = true;
      };
    };

    # Ensure nginx directories exist.
    environment.etc."tmpfiles.d/aos-nginx.conf" = {
      text = ''
        # nginx state directories.
        d /var/log/nginx 0750 root root -
        d /var/lib/nginx 0750 root root -
        d /var/lib/nginx/acme 0750 root root -
        d /run/nginx 0755 root root -
      '';
    };

    # ZFS dataset for nginx state (ACME certs, logs).
    aos.filesystems.zfs.datasets."var/lib/nginx" = {
      mountpoint = "/var/lib/nginx";
      compression = "zstd-3";
      atime = "off";
    };

    # Open HTTP and HTTPS ports in the firewall.
    aos.firewall.allowedTCP = [
      80
      443
    ];
  };
}
