##! modules/services/sssd.nix — SSSD identity and authentication module
##!
##! Configures the System Security Services Daemon (SSSD) for centralized
##! identity and authentication. SSSD provides NSS and PAM integration with
##! LDAP, Active Directory, FreeIPA, and other identity backends. It caches
##! credentials locally for offline authentication and reduces load on
##! directory servers.
##!
##! Options:
##!   [services.sssd] enable, domains, services, config

{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.aos.services.sssd;

  # Build sssd.conf from module options.
  sssdConf = ''
    # /etc/sssd/sssd.conf — generated by modules/services/sssd.nix
    # Do not edit manually.

    [sssd]
    services = ${builtins.concatStringsSep ", " cfg.services}
    domains = ${builtins.concatStringsSep ", " cfg.domains}
    config_file_version = 2

    ${cfg.config}
  '';

in
{
  options.aos.services.sssd = {
    ## Enable SSSD for centralized identity and authentication.
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the System Security Services Daemon (SSSD). Provides
        centralized identity and authentication via NSS and PAM modules,
        with support for LDAP, Active Directory, and FreeIPA backends.
      '';
    };

    ## SSSD domain names to enable.
    ##
    ## # Examples
    ## ```nix
    ## aos.services.sssd.domains = [ "example.com" ];
    ## ```
    domains = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = ''
        List of SSSD domain names to enable. Each domain must have a
        corresponding [domain/<name>] section in the config option.
        Example: [ "example.com" ]
      '';
    };

    ## SSSD services to enable (nss, pam, sudo, ssh).
    services = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "nss"
        "pam"
      ];
      description = ''
        List of SSSD services to enable. Common values:
        - "nss" — Name Service Switch (user/group lookups)
        - "pam" — Pluggable Authentication Modules
        - "sudo" — sudo rules from LDAP
        - "ssh" — SSH key retrieval from LDAP
      '';
    };

    ## Additional SSSD configuration appended to sssd.conf.
    config = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = ''
        Additional SSSD configuration appended to sssd.conf. Use this
        for [domain/...] sections and any extra directives not covered
        by the structured options above.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs.sssd ];

    # /etc/sssd/sssd.conf — SSSD configuration.
    environment.etc."sssd/sssd.conf" = {
      text = sssdConf;
      mode = "0600";
    };

    # sssd.service — System Security Services Daemon.
    systemd.services."sssd" = {
      description = "System Security Services Daemon";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      serviceConfig = {
        Type = "notify";
        ExecStart = "${pkgs.sssd}/sbin/sssd -i --logger=files";
        Restart = "on-failure";
        RestartSec = "5s";
        PIDFile = "/run/sssd.pid";
        # Security hardening.
        ProtectHome = true;
        NoNewPrivileges = true;
        PrivateTmp = true;
      };
    };

    # Ensure SSSD state directories exist.
    environment.etc."tmpfiles.d/aos-sssd.conf" = {
      text = ''
        # SSSD state directories.
        d /var/lib/sss 0700 root root -
        d /var/lib/sss/db 0700 root root -
        d /var/lib/sss/mc 0755 root root -
        d /var/lib/sss/pipes 0755 root root -
        d /var/lib/sss/pipes/private 0700 root root -
        d /var/log/sssd 0750 root root -
      '';
    };
  };
}
