# modules/services/update.nix — Update agent configuration module
#
# Configures the AOS update system: periodic check timer, update download
# and apply service, health check after update, and automatic rollback on
# failure. Uses systemd-bless-boot for boot counting — if the system fails
# to mark the boot as successful within bootTries attempts, the boot loader
# falls back to the previous generation.
#
# Absorbed TOML config values:
#   [update] enable, server, channel, check_interval, auto_update
#   [update] max_retries, retry_delay, boot_tries, signing_key_path
#   [update.gc] schedule, keep_generations, min_age_hours

{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.aos.update;
in
{
  options.aos.update = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the AOS update agent.";
    };

    server = lib.mkOption {
      type = lib.types.str;
      default = "https://update.aos.internal";
      description = "Update server URL for checking and downloading OS updates.";
    };

    channel = lib.mkOption {
      type = lib.types.str;
      default = "stable";
      description = ''
        Update channel to subscribe to. Available channels:
        "stable", "testing", "unstable".
      '';
    };

    checkInterval = lib.mkOption {
      type = lib.types.int;
      default = 3600;
      description = "Interval in seconds between update checks.";
    };

    autoUpdate = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Automatically apply updates when available. When false, updates
        are downloaded and staged but not applied until explicitly triggered.
      '';
    };

    maxRetries = lib.mkOption {
      type = lib.types.int;
      default = 3;
      description = "Maximum number of retry attempts for failed update operations.";
    };

    retryDelay = lib.mkOption {
      type = lib.types.int;
      default = 300;
      description = "Delay in seconds between retry attempts.";
    };

    bootTries = lib.mkOption {
      type = lib.types.int;
      default = 3;
      description = ''
        Number of boot attempts before the boot loader rolls back to the
        previous generation. Uses systemd-bless-boot and the boot counter
        mechanism in systemd-boot.
      '';
    };

    signingKeyPath = lib.mkOption {
      type = lib.types.str;
      default = "/etc/aos/update-signing-key.pub";
      description = ''
        Path to the Ed25519 public key used to verify update signatures.
        Updates are rejected if they cannot be verified with this key.
      '';
    };

    gc = {
      schedule = lib.mkOption {
        type = lib.types.str;
        default = "weekly";
        description = "systemd calendar expression for garbage collection of old generations.";
      };

      keepGenerations = lib.mkOption {
        type = lib.types.int;
        default = 5;
        description = "Number of old OS generations to keep after garbage collection.";
      };

      minAgeHours = lib.mkOption {
        type = lib.types.int;
        default = 168;
        description = ''
          Minimum age in hours before a generation can be garbage collected.
          Default is 168 hours (7 days).
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs.zstd ];

    # Update agent configuration file.
    environment.etc."aos/update.conf" = {
      text = ''
        # /etc/aos/update.conf — generated by modules/services/update.nix
        [update]
        server = "${cfg.server}"
        channel = "${cfg.channel}"
        auto_update = ${if cfg.autoUpdate then "true" else "false"}
        max_retries = ${toString cfg.maxRetries}
        retry_delay = ${toString cfg.retryDelay}
        boot_tries = ${toString cfg.bootTries}
        signing_key = "${cfg.signingKeyPath}"

        [gc]
        keep_generations = ${toString cfg.gc.keepGenerations}
        min_age_hours = ${toString cfg.gc.minAgeHours}
      '';
    };

    # update-check.timer — periodic timer to check for updates.
    systemd.timers."aos-update-check" = {
      description = "AOS Update Check Timer";
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnBootSec = "5min";
        OnUnitActiveSec = "${toString cfg.checkInterval}s";
        RandomizedDelaySec = "300s";
        Persistent = true;
      };
    };

    # update-check.service — checks for available updates and downloads them.
    systemd.services."aos-update-check" = {
      description = "AOS Update Check";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "/usr/bin/aos-update check --server=${cfg.server} --channel=${cfg.channel} --signing-key=${cfg.signingKeyPath}";
        # Run as a dedicated system user for privilege separation.
        DynamicUser = true;
        User = "aos-update";
        Group = "aos-update";
        # Security hardening for the update checker.
        ProtectSystem = "strict";
        ProtectHome = true;
        NoNewPrivileges = true;
        PrivateTmp = true;
        ReadWritePaths = [ "/var/lib/aos/updates" ];
      };
    };

    # update.service — applies a staged update by switching the boot entry.
    systemd.services."aos-update-apply" = {
      description = "AOS Update Apply";
      after = [ "aos-update-check.service" ];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "/usr/bin/aos-update apply --boot-tries=${toString cfg.bootTries}";
        # Needs root to write boot entries and manage generations.
      };
    };

    # health-check.service — marks the current boot as successful.
    # Runs after the system is fully booted and healthy. If this does
    # not run within bootTries attempts, systemd-boot rolls back.
    systemd.services."aos-health-check" = {
      description = "AOS Boot Health Check";
      wantedBy = [ "multi-user.target" ];
      after = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        # Check system health: are critical services running?
        ExecStart = "/usr/bin/aos-update health-check";
        # If healthy, bless this boot so the counter stops.
        ExecStartPost = "/usr/bin/systemd-bless-boot good";
      };
    };

    # rollback.service — emergency rollback to previous generation.
    # Triggered manually or by the boot counter reaching zero.
    systemd.services."aos-rollback" = {
      description = "AOS Emergency Rollback";
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "/usr/bin/aos-update rollback";
      };
    };

    # Ensure update state directories exist.
    environment.etc."tmpfiles.d/aos-update.conf" = {
      text = ''
        # AOS update directories.
        d /var/lib/aos 0755 root root -
        d /var/lib/aos/updates 0750 aos-update aos-update -
        d /var/lib/aos/generations 0755 root root -
      '';
    };
  };
}
