# modules/services/vault-agent.nix — HashiCorp Vault agent module
#
# Configures a Vault agent sidecar that handles automatic authentication
# and secret templating. The agent authenticates to a Vault server using
# the configured auth method (e.g., Kubernetes service account) and
# renders secret templates to local files. This eliminates the need for
# applications to implement Vault client logic directly.
#
# Options:
#   [services.vaultAgent] enable, address, role, authPath, templates, autoAuth

{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.aos.services.vaultAgent;

  # Build template stanzas from the templates attrset.
  templateStanzas = builtins.concatStringsSep "\n" (
    lib.mapAttrsToList (name: tmpl: ''
      template {
        destination = "${tmpl.destination or "/run/vault-agent/${name}"}"
        contents    = <<-EOT
      ${tmpl.contents or ""}
        EOT
        ${lib.optionalString (tmpl ? perms) "perms = \"${tmpl.perms}\""}
        ${lib.optionalString (tmpl ? command) "command = \"${tmpl.command}\""}
      }
    '') cfg.templates
  );

  # Build auto_auth stanza from the autoAuth attrset.
  autoAuthStanza = ''
    auto_auth {
      method "kubernetes" {
        mount_path = "${cfg.authPath}"
        config = {
          role = "${cfg.role}"
          ${lib.optionalString (cfg.autoAuth ? tokenPath) "token_path = \"${cfg.autoAuth.tokenPath}\""}
        }
      }

      sink "file" {
        config = {
          path = "/run/vault-agent/.vault-token"
          mode = 0640
        }
      }
    }
  '';

  # Full Vault agent configuration in HCL format.
  vaultAgentConfig = ''
    # /etc/vault-agent.d/config.hcl — generated by modules/services/vault-agent.nix
    # Do not edit manually.

    vault {
      address = "${cfg.address}"
    }

    ${autoAuthStanza}

    ${templateStanzas}
  '';

in
{
  options.aos.services.vaultAgent = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the HashiCorp Vault agent. The agent handles automatic
        authentication and renders secret templates to local files,
        eliminating the need for applications to integrate Vault
        client libraries directly.
      '';
    };

    address = lib.mkOption {
      type = lib.types.str;
      default = "https://vault.internal:8200";
      description = ''
        Address of the Vault server. Typically an internal HTTPS
        endpoint. The agent connects here for authentication and
        secret retrieval.
      '';
    };

    role = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = ''
        Vault role name for authentication. This must match a role
        configured in the Vault auth backend (e.g., a Kubernetes
        auth role bound to a service account).
      '';
    };

    authPath = lib.mkOption {
      type = lib.types.str;
      default = "auth/kubernetes/login";
      description = ''
        Mount path for the Vault auth method. The default is the
        standard Kubernetes auth mount point.
      '';
    };

    templates = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      description = ''
        Attribute set of secret templates. Each key is a template name
        and the value is an attrset with:
        - destination: output file path
        - contents: Go template string for rendering secrets
        - perms: file permissions (optional)
        - command: command to run after rendering (optional)
      '';
    };

    autoAuth = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      description = ''
        Additional auto-auth configuration. Supports:
        - tokenPath: path to the Kubernetes service account token
          (default: /var/run/secrets/kubernetes.io/serviceaccount/token)
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs.vault ];

    # /etc/vault-agent.d/config.hcl — Vault agent configuration.
    environment.etc."vault-agent.d/config.hcl" = {
      text = vaultAgentConfig;
    };

    # vault-agent.service — HashiCorp Vault agent daemon.
    systemd.services."vault-agent" = {
      description = "HashiCorp Vault Agent";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      serviceConfig = {
        Type = "simple";
        ExecStart = "/usr/bin/vault agent -config=/etc/vault-agent.d/config.hcl";
        Restart = "on-failure";
        RestartSec = "5s";
        # Run as a dedicated user with minimal privileges.
        DynamicUser = true;
        User = "vault-agent";
        Group = "vault-agent";
        # Security hardening.
        ProtectSystem = "full";
        ProtectHome = true;
        NoNewPrivileges = true;
        PrivateTmp = true;
        RuntimeDirectory = "vault-agent";
        RuntimeDirectoryMode = "0750";
        # Resource limits.
        MemoryMax = "256M";
      };
    };

    # Ensure Vault agent directories exist.
    environment.etc."tmpfiles.d/aos-vault-agent.conf" = {
      text = ''
        # Vault agent state directories.
        d /run/vault-agent 0750 vault-agent vault-agent -
      '';
    };
  };
}
