[package]
name = "aos-doc"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
aos-core = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
atty = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
glob = { workspace = true }
ignore = { workspace = true }
