##! modules/sandbox/kernel-export-owner.nix — opt-in closed kernel owner peer
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.aos.sandbox.kernelExportOwner;
  storageStageSigner = config.aos.sandbox.storageBroker.kernelExportStageSignerCredential;
  verifiersConfigured = cfg.leaseVerifierCredential != null && cfg.stageVerifierCredential != null;
in {
  options.aos.sandbox.kernelExportOwner = {
    enable = lib.mkEnableOption "the closed authenticated kernel-export owner peer";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.aos-sandbox-kernel-export-ownerd;
      defaultText = "pkgs.aos-sandbox-kernel-export-ownerd";
      description = "Closed root-side Storage peer; it never stages or releases a grant.";
    };

    mapOwnerPackage = lib.mkOption {
      type = lib.types.package;
      default = pkgs.aos-sandbox-kernel-export-owner;
      defaultText = "pkgs.aos-sandbox-kernel-export-owner";
      description = "Privileged C BPF-map custodian used only for fail-closed startup recovery.";
    };

    leaseVerifierCredential = lib.mkOption {
      type = lib.types.nullOr lib.serviceTypes.credentialName;
      default = null;
      description = "Externally provisioned 112-byte mutable-origin Storage lease public verifier; never generated by the image.";
    };

    stageVerifierCredential = lib.mkOption {
      type = lib.types.nullOr lib.serviceTypes.credentialName;
      default = null;
      description = "Externally provisioned, distinct 112-byte AOSKGA02 stage public verifier; no production stage signer is wired.";
    };

    reportIngress = {
      enable = lib.mkEnableOption "the closed, one-shot PREPARED report ingress precursor";

      handoffCredential = lib.mkOption {
        type = lib.types.nullOr lib.serviceTypes.credentialName;
        default = null;
        description = "Externally provisioned 344-byte AOSKGH01 comparison frame; its unkeyed ID does not authenticate Storage.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = config.aos.sandbox.storageBroker.enable;
        message = "kernelExportOwner requires the authenticated Storage broker";
      }
      {
        assertion = config.aos.sandbox.networkWorker.enable;
        message = "kernelExportOwner requires the protected node bpffs mount from sandbox.networkWorker";
      }
      {
        assertion = verifiersConfigured;
        message = "kernelExportOwner requires both externally provisioned, role-specific public verifier credentials";
      }
      {
        assertion = !verifiersConfigured || cfg.leaseVerifierCredential != cfg.stageVerifierCredential;
        message = "kernelExportOwner lease and stage verifier credential names must differ";
      }
      {
        assertion =
          storageStageSigner
          == null
          || (storageStageSigner != cfg.leaseVerifierCredential && storageStageSigner != cfg.stageVerifierCredential);
        message = "Storage's reserved stage signer credential name must differ from both owner public verifier names";
      }
      {
        assertion = !cfg.reportIngress.enable || cfg.reportIngress.handoffCredential != null;
        message = "kernelExportOwner report ingress requires an external handoff comparison credential";
      }
      {
        assertion = !cfg.reportIngress.enable;
        message = "kernelExportOwner report ingress remains unavailable until an exact reporter descriptor-origin sender and enforcing MAC/socket custody are deployed";
      }
    ];

    # This endpoint is root-only and remains nonauthorizing. Storage has no
    # production sender yet; an accepted three-FD packet is measured, closed,
    # and acknowledged only with an unsigned physical readback.
    systemd.sockets.aos-sandbox-kernel-export-ownerd = {
      description = "AOS closed kernel-export Storage peer socket";
      wantedBy = ["sockets.target"];
      requires = ["aos-bpffs-mount.service"];
      after = ["aos-bpffs-mount.service"];
      socketConfig = {
        ListenSequentialPacket = "/run/aos/kernel-export-owner/control.sock";
        FileDescriptorName = "aos-sandbox-kernel-export-ownerd";
        Service = "aos-sandbox-kernel-export-ownerd.service";
        Accept = false;
        PassCredentials = true;
        PassPIDFD = true;
        SocketUser = "root";
        SocketGroup = "root";
        SocketMode = "0600";
        DirectoryMode = "0700";
        RemoveOnStop = true;
      };
    };

    # The read-only endpoint is packaged and fully specified, but enabling it
    # remains blocked above until a MAC-confined sender owns exact descriptors.
    systemd.sockets.aos-sandbox-kernel-export-owner-prepared-report = lib.mkIf cfg.reportIngress.enable {
      description = "AOS closed PREPARED map report socket";
      wantedBy = ["sockets.target"];
      requires = ["aos-bpffs-mount.service"];
      after = ["aos-bpffs-mount.service"];
      socketConfig = {
        ListenSequentialPacket = "/run/aos/kernel-export-owner/prepared-report.sock";
        FileDescriptorName = "aos-sandbox-kernel-export-owner-prepared-report";
        Service = "aos-sandbox-kernel-export-owner-report-ingressd.service";
        Accept = false;
        PassCredentials = true;
        PassPIDFD = true;
        SocketUser = "root";
        SocketGroup = "root";
        SocketMode = "0600";
        DirectoryMode = "0700";
        RemoveOnStop = true;
      };
    };

    systemd.services.aos-sandbox-kernel-export-owner-report-ingressd = lib.mkIf cfg.reportIngress.enable {
      description = "AOS closed one-shot PREPARED map report ingress";
      requires = [
        "aos-sandbox-kernel-export-owner-prepared-report.socket"
        "aos-sandbox-kernel-export-owner-recover.service"
      ];
      after = [
        "aos-sandbox-kernel-export-owner-prepared-report.socket"
        "aos-sandbox-kernel-export-owner-recover.service"
      ];
      unitConfig.RequiresMountsFor = ["/sys/fs/cgroup"];
      serviceConfig = {
        Type = "exec";
        Sockets = ["aos-sandbox-kernel-export-owner-prepared-report.socket"];
        ExecStart = "${cfg.package}/bin/aos-sandbox-kernel-export-owner-report-ingressd ${pkgs.aos-selinux-production-policy}/etc/selinux/aos/policy/policy.33";
        LoadCredential = [
          "kernel-export-report-handoff-v1:/run/credentials/@system/${cfg.reportIngress.handoffCredential}"
        ];
        Restart = "no";
        RuntimeMaxSec = "3s";
        UMask = "0077";
        User = "root";
        Group = "root";
        CapabilityBoundingSet = "";
        DevicePolicy = "closed";
        LimitNOFILE = 32;
        LimitCORE = 0;
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateNetwork = true;
        PrivateTmp = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectProc = "invisible";
        ProtectSystem = "strict";
        RestrictAddressFamilies = ["AF_UNIX"];
        RestrictNamespaces = true;
        RestrictRealtime = true;
        Slice = "aos-control.slice";
        TasksMax = 4;
      };
    };

    # Recovery has BPF capability; the long-lived peer does not. An exact
    # first-boot empty state succeeds, while ambiguous state/pins fail closed.
    systemd.services.aos-sandbox-kernel-export-owner-recover = {
      description = "AOS kernel-export owner cold revoke or verified-empty check";
      wantedBy = ["multi-user.target"];
      requires = ["aos-bpffs-mount.service"];
      after = ["aos-bpffs-mount.service" "local-fs.target"];
      before = ["aos-sandbox-kernel-export-ownerd.service"];
      unitConfig.RequiresMountsFor = ["/sys/fs/bpf" "/var/lib/aos"];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = false;
        ExecStart = "${cfg.mapOwnerPackage}/bin/aos-sandbox-kernel-export-owner recover";
        StateDirectory = "aos/kernel-export-owner";
        StateDirectoryMode = "0700";
        UMask = "0077";
        User = "root";
        Group = "root";
        CapabilityBoundingSet = "CAP_BPF CAP_SYS_ADMIN CAP_SYS_RESOURCE";
        LimitMEMLOCK = "infinity";
        NoNewPrivileges = false;
        PrivateDevices = true;
        PrivateNetwork = true;
        ProtectHome = true;
        ProtectSystem = "strict";
        ReadWritePaths = ["/sys/fs/bpf/aos" "/var/lib/aos/kernel-export-owner"];
        Slice = "aos-control.slice";
      };
    };

    systemd.services.aos-sandbox-kernel-export-ownerd = {
      description = "AOS closed authenticated Storage-to-kernel-export owner peer";
      requires = [
        "aos-sandbox-kernel-export-ownerd.socket"
        "aos-sandbox-kernel-export-owner-recover.service"
        "aos-storaged.service"
      ];
      after = [
        "aos-sandbox-kernel-export-ownerd.socket"
        "aos-sandbox-kernel-export-owner-recover.service"
        "aos-storaged.service"
      ];
      unitConfig.RequiresMountsFor = ["/sys/fs/cgroup"];
      serviceConfig = {
        Type = "simple";
        Sockets = ["aos-sandbox-kernel-export-ownerd.socket"];
        ExecStart = "${cfg.package}/bin/aos-sandbox-kernel-export-ownerd";
        LoadCredential = lib.optionals verifiersConfigured [
          "kernel-export-lease-verifier-v1:/run/credentials/@system/${cfg.leaseVerifierCredential}"
          "kernel-export-stage-verifier-v2:/run/credentials/@system/${cfg.stageVerifierCredential}"
        ];
        Restart = "on-failure";
        RestartSec = "2s";
        UMask = "0077";
        User = "root";
        Group = "root";
        CapabilityBoundingSet = "";
        DevicePolicy = "closed";
        LimitNOFILE = 64;
        LimitCORE = 0;
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateNetwork = true;
        PrivateTmp = true;
        ProcSubset = "all";
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectProc = "invisible";
        ProtectSystem = "strict";
        RestrictAddressFamilies = ["AF_UNIX"];
        RestrictNamespaces = true;
        RestrictRealtime = true;
        Slice = "aos-control.slice";
        TasksMax = 16;
      };
    };
  };
}
