[package]
name = "crucible-qemu"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[features]
default = []
test-support = ["crucible/test-double"]

[lints]
workspace = true

[dependencies]
crucible = { path = "../crucible" }
crucible-device = { path = "../crucible-device" }
crucible-protocol = { path = "../crucible-protocol" }
crucible-shmem = { path = "../crucible-shmem" }
libc = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rustix = { workspace = true, features = ["process"] }

[[example]]
name = "crucible-qemu-live-plugin-quantum"
required-features = ["test-support"]

[[example]]
name = "crucible-qemu-live-plugin-preemption"
required-features = ["test-support"]
