[package]
name = "crucible-qemu"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[features]
default = []
test-support = ["crucible/test-double"]

[lints]
workspace = true

[dependencies]
blake3 = { workspace = true }
crucible = { path = "../crucible" }
crucible-device = { path = "../crucible-device" }
crucible-linux-resource = { path = "../crucible-linux-resource", default-features = false }
crucible-protocol = { path = "../crucible-protocol" }
crucible-shmem = { path = "../crucible-shmem" }
libc = { workspace = true }
rustix = { workspace = true, features = ["param", "process"] }
serde_json = { workspace = true }
serde = { workspace = true }
ciborium = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
crucible = { path = "../crucible", features = ["test-double"] }
crucible-campaign = { path = "../crucible-campaign" }

[[example]]
name = "crucible-qemu-live-plugin-quantum"
required-features = ["test-support"]

[[example]]
name = "crucible-qemu-live-plugin-preemption"
required-features = ["test-support"]
