[package]
name = "crucible-qemu"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
crucible = { path = "../crucible", features = ["test-double"] }
crucible-device = { path = "../crucible-device" }
crucible-protocol = { path = "../crucible-protocol" }
crucible-shmem = { path = "../crucible-shmem" }
libc = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rustix = { workspace = true, features = ["process"] }
