//! 9p submit, poll, and burst-done callback core.
//!
//! The 9p QEMU patch path treats virtio-9p as a raw-message pipe while Crucible
//! simulation mode is active. This module routes those raw 9p messages through
//! the reserved deterministic 9p executor rings and holds device-I/O virtual
//! time for the whole device invocation burst.

use std::{array, cell::Cell};

use thiserror::Error;

use crucible_shmem::{
    DirectedRing, FrameDeliveryKey, FrameEntry, FrameEntryError, NodeSlot, RingHeader, SLOT_9P_IO,
    SpscRingError,
};

use crate::{
    DeviceIoBurstState, DeviceIoFreezeError, DeviceIoRequestRelease, DeviceIoRequestToken,
    PluginDeviceIoFreeze, shmem_ordering::PluginShmemOrdering,
};

const NINEP_IO_SLOT_U32: u32 = SLOT_9P_IO as u32;
const MAX_NINEP_IN_FLIGHT_REQUESTS: usize = 256;
const NINEP_WIRE_HEADER_LEN: usize = 7;
const NINEP_RLERROR: u8 = 7;
const NINEP_NOTAG: u16 = u16::MAX;
const NINEP_EIO: u32 = 5;
const NINEP_EINVAL: u32 = 22;
const NINEP_ENOSYS: u32 = 38;
const NINEP_EROFS: u32 = 30;

/// Registration-time-fixed 9p callback state.
#[derive(Debug)]
pub struct PluginNinePIo {
    vm_slot: u32,
    ninep_slot: u32,
    outbound_ring_index: u32,
    inbound_ring_index: u32,
    next_request_id: Cell<u32>,
    pending_request_ids: PendingNinePRequests,
}

impl PluginNinePIo {
    /// Builds 9p callback state from the directed rings selected at registration.
    ///
    /// # Errors
    ///
    /// Returns [`NinePIoError::WrongOutboundRing`] or
    /// [`NinePIoError::WrongInboundRing`] when either ring is not the reserved
    /// 9p executor ring for `vm_slot`.
    pub fn from_directed_rings(
        vm_slot: u32,
        outbound_ring: DirectedRing,
        inbound_ring: DirectedRing,
    ) -> Result<Self, NinePIoError> {
        if outbound_ring.src_slot != vm_slot || outbound_ring.dst_slot != NINEP_IO_SLOT_U32 {
            return Err(NinePIoError::WrongOutboundRing {
                expected_src_slot: vm_slot,
                expected_dst_slot: NINEP_IO_SLOT_U32,
                expected_ring_index: None,
                actual_src_slot: outbound_ring.src_slot,
                actual_dst_slot: outbound_ring.dst_slot,
                actual_ring_index: outbound_ring.index,
            });
        }
        if inbound_ring.src_slot != NINEP_IO_SLOT_U32 || inbound_ring.dst_slot != vm_slot {
            return Err(NinePIoError::WrongInboundRing {
                expected_src_slot: NINEP_IO_SLOT_U32,
                expected_dst_slot: vm_slot,
                expected_ring_index: None,
                actual_src_slot: inbound_ring.src_slot,
                actual_dst_slot: inbound_ring.dst_slot,
                actual_ring_index: inbound_ring.index,
            });
        }

        Ok(Self::new(vm_slot, outbound_ring.index, inbound_ring.index))
    }

    /// Builds 9p callback state for the reserved 9p rings.
    #[must_use]
    pub fn new(vm_slot: u32, outbound_ring_index: u32, inbound_ring_index: u32) -> Self {
        Self {
            vm_slot,
            ninep_slot: NINEP_IO_SLOT_U32,
            outbound_ring_index,
            inbound_ring_index,
            next_request_id: Cell::new(0),
            pending_request_ids: PendingNinePRequests::new(),
        }
    }

    /// Returns the VM slot whose 9p device this state serves.
    #[must_use]
    pub const fn vm_slot(&self) -> u32 {
        self.vm_slot
    }

    /// Returns the reserved 9p executor slot.
    #[must_use]
    pub const fn ninep_slot(&self) -> u32 {
        self.ninep_slot
    }

    /// Returns the outbound 9p ring index.
    #[must_use]
    pub const fn outbound_ring_index(&self) -> u32 {
        self.outbound_ring_index
    }

    /// Returns the inbound 9p ring index.
    #[must_use]
    pub const fn inbound_ring_index(&self) -> u32 {
        self.inbound_ring_index
    }

    /// Returns the request id that the next successful submit will assign.
    #[must_use]
    pub fn next_request_id(&self) -> u32 {
        self.next_request_id.get()
    }

    /// Starts one multi-request 9p burst.
    ///
    /// # Errors
    ///
    /// Returns [`NinePIoError`] when the device-I/O freeze state rejects the
    /// burst transition.
    pub fn begin_burst(
        &self,
        freeze: &mut PluginDeviceIoFreeze,
        slot: &NodeSlot,
    ) -> Result<DeviceIoBurstState, NinePIoError> {
        freeze
            .begin_burst(slot)
            .map_err(|source| NinePIoError::DeviceIoFreeze { source })
    }

    /// Submits one raw 9p request message to the reserved 9p executor.
    ///
    /// Submit requires an active burst so the `device_io_active` hold spans every
    /// request generated by the same 9p device invocation.
    ///
    /// # Errors
    ///
    /// Returns [`NinePIoError`] when the ring does not match registration state,
    /// no burst is active, the request id overflows, frame construction fails,
    /// the freeze state rejects the request, or the outbound SPSC enqueue fails.
    pub fn submit_request(
        &self,
        freeze: &mut PluginDeviceIoFreeze,
        slot: &NodeSlot,
        outbound_ring: &mut NinePOutboundRing<'_>,
        submit_icount: u64,
        request: &NinePRequest,
    ) -> Result<NinePSubmit, NinePIoError> {
        self.check_outbound_ring(outbound_ring)?;
        if !freeze.burst_active() {
            return Err(NinePIoError::SubmitOutsideBurst);
        }

        let request_id = self.next_request_id.get();
        let next_request_id = request_id
            .checked_add(1)
            .ok_or(NinePIoError::RequestIdOverflow { request_id })?;
        let frame = FrameEntry::new(submit_icount, self.vm_slot, request_id, request.payload())
            .map_err(|source| NinePIoError::Frame { source })?;
        self.pending_request_ids.insert(request_id)?;
        let device_token = freeze.begin_submit(slot, submit_icount).map_err(|source| {
            let _ = self.pending_request_ids.remove(request_id);
            NinePIoError::DeviceIoFreeze { source }
        })?;

        if let Err(source) = PluginShmemOrdering::enqueue_outbound_frame(
            outbound_ring.header,
            outbound_ring.entries,
            &frame,
        ) {
            let release = freeze
                .fail_request(slot, device_token)
                .map_err(|source| NinePIoError::DeviceIoFreeze { source })?;
            self.pending_request_ids.remove(request_id)?;
            return Err(NinePIoError::RingEnqueueFailed {
                ring_index: self.outbound_ring_index,
                source,
                release,
            });
        }

        self.next_request_id.set(next_request_id);
        Ok(NinePSubmit {
            ring_index: self.outbound_ring_index,
            submit_icount,
            request_id,
            payload_len: request.payload().len(),
            token: NinePRequestToken {
                request_id,
                device_token,
            },
        })
    }

    /// Polls one raw 9p response and delivers it when its delivery icount is due.
    ///
    /// # Errors
    ///
    /// Returns [`NinePIoError`] when the inbound ring does not match registration
    /// state, the due response is malformed or for another request, the SPSC
    /// dequeue fails, delivery to QEMU fails, or the device-I/O token cannot be
    /// completed or failed.
    pub fn poll_response<D>(
        &self,
        freeze: &mut PluginDeviceIoFreeze,
        slot: &NodeSlot,
        inbound_ring: &NinePInboundRing<'_>,
        deliver: &mut D,
        current_icount: u64,
        token: NinePRequestToken,
    ) -> Result<NinePPoll, NinePIoError>
    where
        D: NinePGuestCompletion + ?Sized,
    {
        self.check_inbound_ring(inbound_ring)?;
        let Some(head) = peek_head_frame(inbound_ring)? else {
            return Ok(NinePPoll::NotReady { token });
        };
        if head.delivery_icount > current_icount {
            return Ok(NinePPoll::NotReady { token });
        }

        if head.src_node != self.ninep_slot {
            let release = self.fail_polled_request(freeze, slot, token)?;
            return Err(NinePIoError::UnexpectedSource {
                expected_src_node: self.ninep_slot,
                actual_src_node: head.src_node,
                frame: head.delivery_key(),
                release,
            });
        }
        if head.seq != token.request_id {
            if self.pending_request_ids.contains(head.seq) {
                return Ok(NinePPoll::NotReady { token });
            }
            let expected_request_id = token.request_id;
            let release = self.fail_polled_request(freeze, slot, token)?;
            return Err(NinePIoError::UnexpectedResponse {
                expected_request_id,
                actual_request_id: head.seq,
                frame: head.delivery_key(),
                release,
            });
        }

        let payload = match head.payload() {
            Ok(payload) => payload.to_vec(),
            Err(source) => {
                let release = self.fail_polled_request(freeze, slot, token)?;
                return Err(NinePIoError::MalformedResponse {
                    ring_index: self.inbound_ring_index,
                    frame: head.delivery_key(),
                    source,
                    release,
                });
            }
        };
        let response = NinePResponse::new(head.seq, payload);
        let request_id = token.request_id;
        let release = freeze
            .complete_request(slot, token.device_token)
            .map_err(|source| NinePIoError::DeviceIoFreeze { source })?;
        self.pending_request_ids.remove(request_id)?;

        let Some(dequeued) =
            PluginShmemOrdering::dequeue_inbound_frame(inbound_ring.header, inbound_ring.entries)
                .map_err(|source| NinePIoError::RingDequeue {
                ring_index: self.inbound_ring_index,
                source,
            })?
        else {
            return Err(NinePIoError::DequeuedUnexpectedFrame {
                ring_index: self.inbound_ring_index,
                expected: head.delivery_key(),
                actual: None,
            });
        };
        if dequeued.delivery_key() != head.delivery_key() {
            return Err(NinePIoError::DequeuedUnexpectedFrame {
                ring_index: self.inbound_ring_index,
                expected: head.delivery_key(),
                actual: Some(dequeued.delivery_key()),
            });
        }

        deliver.complete_9p_response(&response).map_err(|source| {
            NinePIoError::GuestCompletion {
                request_id: response.request_id(),
                release,
                source,
            }
        })?;
        Ok(NinePPoll::Completed { response, release })
    }

    /// Ends one 9p device burst after all request tokens have completed.
    ///
    /// # Errors
    ///
    /// Returns [`NinePIoError`] when no burst is active, a request is still
    /// pending, or the release wake fails.
    pub fn burst_done(
        &self,
        freeze: &mut PluginDeviceIoFreeze,
        slot: &NodeSlot,
    ) -> Result<DeviceIoBurstState, NinePIoError> {
        freeze
            .burst_done(slot)
            .map_err(|source| NinePIoError::DeviceIoFreeze { source })
    }

    fn fail_polled_request(
        &self,
        freeze: &mut PluginDeviceIoFreeze,
        slot: &NodeSlot,
        token: NinePRequestToken,
    ) -> Result<DeviceIoRequestRelease, NinePIoError> {
        let request_id = token.request_id;
        freeze
            .fail_request(slot, token.device_token)
            .map_err(|source| NinePIoError::DeviceIoFreeze { source })
            .and_then(|release| {
                self.pending_request_ids.remove(request_id)?;
                Ok(release)
            })
    }

    fn check_outbound_ring(&self, ring: &NinePOutboundRing<'_>) -> Result<(), NinePIoError> {
        if ring.ring_index != self.outbound_ring_index
            || ring.src_slot != self.vm_slot
            || ring.dst_slot != self.ninep_slot
        {
            Err(NinePIoError::WrongOutboundRing {
                expected_src_slot: self.vm_slot,
                expected_dst_slot: self.ninep_slot,
                expected_ring_index: Some(self.outbound_ring_index),
                actual_src_slot: ring.src_slot,
                actual_dst_slot: ring.dst_slot,
                actual_ring_index: ring.ring_index,
            })
        } else {
            Ok(())
        }
    }

    fn check_inbound_ring(&self, ring: &NinePInboundRing<'_>) -> Result<(), NinePIoError> {
        if ring.ring_index != self.inbound_ring_index
            || ring.src_slot != self.ninep_slot
            || ring.dst_slot != self.vm_slot
        {
            Err(NinePIoError::WrongInboundRing {
                expected_src_slot: self.ninep_slot,
                expected_dst_slot: self.vm_slot,
                expected_ring_index: Some(self.inbound_ring_index),
                actual_src_slot: ring.src_slot,
                actual_dst_slot: ring.dst_slot,
                actual_ring_index: ring.ring_index,
            })
        } else {
            Ok(())
        }
    }
}

/// A fixed-size pending request table for one 9p callback state.
#[derive(Debug)]
struct PendingNinePRequests {
    slots: [Cell<Option<u32>>; MAX_NINEP_IN_FLIGHT_REQUESTS],
}

impl PendingNinePRequests {
    fn new() -> Self {
        Self {
            slots: array::from_fn(|_| Cell::new(None)),
        }
    }

    fn insert(&self, request_id: u32) -> Result<(), NinePIoError> {
        let mut first_free = None;
        for (index, slot) in self.slots.iter().enumerate() {
            match slot.get() {
                Some(existing) if existing == request_id => {
                    return Err(NinePIoError::DuplicatePendingRequest { request_id });
                }
                None if first_free.is_none() => first_free = Some(index),
                _ => {}
            }
        }

        let Some(index) = first_free else {
            return Err(NinePIoError::PendingRequestCapacityExceeded {
                capacity: MAX_NINEP_IN_FLIGHT_REQUESTS,
            });
        };
        self.slots[index].set(Some(request_id));
        Ok(())
    }

    fn contains(&self, request_id: u32) -> bool {
        self.slots.iter().any(|slot| slot.get() == Some(request_id))
    }

    fn remove(&self, request_id: u32) -> Result<(), NinePIoError> {
        for slot in &self.slots {
            if slot.get() == Some(request_id) {
                slot.set(None);
                return Ok(());
            }
        }
        Err(NinePIoError::PendingRequestMissing { request_id })
    }
}

/// Handles one safe 9p burst-start callback body.
///
/// # Errors
///
/// Returns [`NinePIoError`] when the freeze state rejects the burst start.
pub fn handle_9p_burst_start_callback(
    ninep_io: &PluginNinePIo,
    freeze: &mut PluginDeviceIoFreeze,
    slot: &NodeSlot,
) -> Result<DeviceIoBurstState, NinePIoError> {
    ninep_io.begin_burst(freeze, slot)
}

/// Handles one safe 9p submit callback body.
///
/// # Errors
///
/// Returns [`NinePIoError`] when submit validation, freeze state, or ring enqueue
/// fails.
pub fn handle_9p_submit_callback(
    ninep_io: &PluginNinePIo,
    freeze: &mut PluginDeviceIoFreeze,
    slot: &NodeSlot,
    outbound_ring: &mut NinePOutboundRing<'_>,
    submit_icount: u64,
    request: &NinePRequest,
) -> Result<NinePSubmit, NinePIoError> {
    ninep_io.submit_request(freeze, slot, outbound_ring, submit_icount, request)
}

/// Handles one safe 9p poll callback body.
///
/// # Errors
///
/// Returns [`NinePIoError`] when ring validation, response delivery, or
/// freeze-token completion fails.
pub fn handle_9p_poll_callback<D>(
    ninep_io: &PluginNinePIo,
    freeze: &mut PluginDeviceIoFreeze,
    slot: &NodeSlot,
    inbound_ring: &NinePInboundRing<'_>,
    deliver: &mut D,
    current_icount: u64,
    token: NinePRequestToken,
) -> Result<NinePPoll, NinePIoError>
where
    D: NinePGuestCompletion + ?Sized,
{
    ninep_io.poll_response(freeze, slot, inbound_ring, deliver, current_icount, token)
}

/// Handles one safe 9p burst-done callback body.
///
/// # Errors
///
/// Returns [`NinePIoError`] when the freeze state rejects the burst completion.
pub fn handle_9p_burst_done_callback(
    ninep_io: &PluginNinePIo,
    freeze: &mut PluginDeviceIoFreeze,
    slot: &NodeSlot,
) -> Result<DeviceIoBurstState, NinePIoError> {
    ninep_io.burst_done(freeze, slot)
}

/// A mutable view of the outbound 9p executor ring.
pub struct NinePOutboundRing<'a> {
    ring_index: u32,
    src_slot: u32,
    dst_slot: u32,
    header: &'a RingHeader,
    entries: &'a mut [FrameEntry],
}

impl<'a> NinePOutboundRing<'a> {
    /// Builds an outbound 9p ring view.
    #[must_use]
    pub fn new(
        ring_index: u32,
        src_slot: u32,
        dst_slot: u32,
        header: &'a RingHeader,
        entries: &'a mut [FrameEntry],
    ) -> Self {
        Self {
            ring_index,
            src_slot,
            dst_slot,
            header,
            entries,
        }
    }
}

/// An immutable consumer view of the inbound 9p executor ring.
#[derive(Clone, Copy)]
pub struct NinePInboundRing<'a> {
    ring_index: u32,
    src_slot: u32,
    dst_slot: u32,
    header: &'a RingHeader,
    entries: &'a [FrameEntry],
}

impl<'a> NinePInboundRing<'a> {
    /// Builds an inbound 9p ring view.
    #[must_use]
    pub const fn new(
        ring_index: u32,
        src_slot: u32,
        dst_slot: u32,
        header: &'a RingHeader,
        entries: &'a [FrameEntry],
    ) -> Self {
        Self {
            ring_index,
            src_slot,
            dst_slot,
            header,
            entries,
        }
    }
}

/// A raw 9p request message forwarded from QEMU.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NinePRequest {
    payload: Vec<u8>,
}

impl NinePRequest {
    /// Builds a raw 9p request.
    #[must_use]
    pub fn new(payload: Vec<u8>) -> Self {
        Self { payload }
    }

    /// Returns the raw 9p request payload.
    #[must_use]
    pub fn payload(&self) -> &[u8] {
        &self.payload
    }
}

/// A raw 9p response message ready to expose to QEMU.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NinePResponse {
    request_id: u32,
    payload: Vec<u8>,
}

impl NinePResponse {
    /// Builds a raw 9p response.
    #[must_use]
    pub fn new(request_id: u32, payload: Vec<u8>) -> Self {
        Self {
            request_id,
            payload,
        }
    }

    /// Returns the request id associated with this response.
    #[must_use]
    pub const fn request_id(&self) -> u32 {
        self.request_id
    }

    /// Returns the raw 9p response payload.
    #[must_use]
    pub fn payload(&self) -> &[u8] {
        &self.payload
    }
}

/// A parsed 9p message envelope carried as a raw plugin payload.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NinePWireMessage {
    message_type: u8,
    tag: u16,
    payload: Vec<u8>,
}

impl NinePWireMessage {
    /// Builds a parsed 9p message envelope.
    #[must_use]
    pub fn new(message_type: u8, tag: u16, payload: Vec<u8>) -> Self {
        Self {
            message_type,
            tag,
            payload,
        }
    }

    /// Returns the 9p message type byte.
    #[must_use]
    pub const fn message_type(&self) -> u8 {
        self.message_type
    }

    /// Returns the 9p tag.
    #[must_use]
    pub const fn tag(&self) -> u16 {
        self.tag
    }

    /// Returns the body bytes following the 9p header.
    #[must_use]
    pub fn payload(&self) -> &[u8] {
        &self.payload
    }

    /// Encodes the message envelope as one 9p wire message.
    ///
    /// # Errors
    ///
    /// Returns [`NinePWireError::MessageSizeOverflow`] when the message length
    /// cannot fit in the 9p `size[4]` field.
    pub fn encode(&self) -> Result<Vec<u8>, NinePWireError> {
        let len = NINEP_WIRE_HEADER_LEN
            .checked_add(self.payload.len())
            .ok_or(NinePWireError::MessageSizeOverflow {
                len: self.payload.len(),
            })?;
        let size = u32::try_from(len).map_err(|_| NinePWireError::MessageSizeOverflow { len })?;
        let mut out = Vec::with_capacity(len);
        out.extend_from_slice(&size.to_le_bytes());
        out.push(self.message_type);
        out.extend_from_slice(&self.tag.to_le_bytes());
        out.extend_from_slice(&self.payload);
        Ok(out)
    }

    /// Decodes exactly one 9p wire message envelope.
    ///
    /// # Errors
    ///
    /// Returns [`NinePWireError`] when the buffer is shorter than the fixed
    /// header, has an impossible declared size, or contains trailing bytes after
    /// the declared message.
    pub fn decode(frame: &[u8]) -> Result<Self, NinePWireError> {
        Self::decode_with_msize(frame, u32::MAX)
    }

    /// Decodes exactly one 9p wire message envelope under a negotiated `msize`.
    ///
    /// # Errors
    ///
    /// Returns [`NinePWireError`] when the frame is malformed or its declared
    /// size exceeds `msize`.
    pub fn decode_with_msize(frame: &[u8], msize: u32) -> Result<Self, NinePWireError> {
        if frame.len() < NINEP_WIRE_HEADER_LEN {
            return Err(NinePWireError::ShortHeader { len: frame.len() });
        }
        let size = u32::from_le_bytes(
            frame[0..4]
                .try_into()
                .map_err(|_| NinePWireError::ShortHeader { len: frame.len() })?,
        );
        if size < NINEP_WIRE_HEADER_LEN as u32 {
            return Err(NinePWireError::DeclaredSizeTooSmall { size });
        }
        if size > msize {
            return Err(NinePWireError::DeclaredSizeExceedsMsize { size, msize });
        }
        let size_usize =
            usize::try_from(size).map_err(|_| NinePWireError::DeclaredSizeExceedsFrame {
                size,
                available: frame.len(),
            })?;
        if size_usize > frame.len() {
            return Err(NinePWireError::DeclaredSizeExceedsFrame {
                size,
                available: frame.len(),
            });
        }
        if size_usize != frame.len() {
            return Err(NinePWireError::DeclaredSizeHasTrailingBytes {
                size,
                frame_len: frame.len(),
            });
        }
        let message_type = frame[4];
        let tag = u16::from_le_bytes(
            frame[5..7]
                .try_into()
                .map_err(|_| NinePWireError::ShortHeader { len: frame.len() })?,
        );
        Ok(Self {
            message_type,
            tag,
            payload: frame[NINEP_WIRE_HEADER_LEN..].to_vec(),
        })
    }
}

/// Result of running arbitrary 9p bytes through the fuzz-safe wire handler.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NinePWireHandlerOutcome {
    request: Result<NinePWireMessage, NinePWireError>,
    response: NinePWireMessage,
    errno: u32,
}

impl NinePWireHandlerOutcome {
    /// Returns the request decode result.
    pub const fn request(&self) -> &Result<NinePWireMessage, NinePWireError> {
        &self.request
    }

    /// Returns the deterministic 9p error response.
    #[must_use]
    pub const fn response(&self) -> &NinePWireMessage {
        &self.response
    }

    /// Returns the Linux errno encoded in the response payload.
    #[must_use]
    pub const fn errno(&self) -> u32 {
        self.errno
    }
}

/// Handles arbitrary 9p wire bytes for the fuzz target.
///
/// This is a fail-closed, state-free wire handler: it validates the 9p envelope
/// under the negotiated `msize` and returns a deterministic `Rlerror` response.
/// The real read-only filesystem server remains a separate I/O sub-node
/// implementation, but this path proves the raw wire boundary never panics and
/// always yields either a typed reject or a well-formed 9p error response.
#[must_use]
pub fn handle_ninep_wire_fuzz_message(frame: &[u8], msize: u32) -> NinePWireHandlerOutcome {
    match NinePWireMessage::decode_with_msize(frame, msize) {
        Ok(request) => {
            let errno = errno_for_valid_ninep_message(request.message_type());
            NinePWireHandlerOutcome {
                response: ninep_lerror(request.tag(), errno),
                request: Ok(request),
                errno,
            }
        }
        Err(error) => {
            let tag = tag_from_header(frame).unwrap_or(NINEP_NOTAG);
            NinePWireHandlerOutcome {
                request: Err(error),
                response: ninep_lerror(tag, NINEP_EINVAL),
                errno: NINEP_EINVAL,
            }
        }
    }
}

/// A request token that must be consumed by poll completion or failure handling.
#[must_use = "9p request tokens must be consumed by 9p poll completion or failure"]
#[derive(Debug, PartialEq, Eq)]
pub struct NinePRequestToken {
    request_id: u32,
    device_token: DeviceIoRequestToken,
}

impl NinePRequestToken {
    /// Returns the 9p request id.
    #[must_use]
    pub const fn request_id(&self) -> u32 {
        self.request_id
    }

    /// Returns the submit icount carried by the device-I/O token.
    #[must_use]
    pub const fn submit_icount(&self) -> u64 {
        self.device_token.submit_icount()
    }
}

/// Metadata returned after one successful 9p submit.
#[derive(Debug, PartialEq, Eq)]
pub struct NinePSubmit {
    ring_index: u32,
    submit_icount: u64,
    request_id: u32,
    payload_len: usize,
    token: NinePRequestToken,
}

impl NinePSubmit {
    /// Returns the outbound ring index.
    #[must_use]
    pub const fn ring_index(&self) -> u32 {
        self.ring_index
    }

    /// Returns the submit icount stamped onto the frame.
    #[must_use]
    pub const fn submit_icount(&self) -> u64 {
        self.submit_icount
    }

    /// Returns the assigned request id.
    #[must_use]
    pub const fn request_id(&self) -> u32 {
        self.request_id
    }

    /// Returns the raw 9p payload length.
    #[must_use]
    pub const fn payload_len(&self) -> usize {
        self.payload_len
    }

    /// Consumes this submit metadata and returns the completion token.
    pub fn into_token(self) -> NinePRequestToken {
        self.token
    }
}

/// The result of one 9p poll callback.
#[derive(Debug, PartialEq, Eq)]
pub enum NinePPoll {
    /// No matching response is ready; the token is returned to the caller.
    NotReady {
        /// The still-pending request token.
        token: NinePRequestToken,
    },
    /// A due response was delivered and the request token was released.
    Completed {
        /// The raw response delivered to the guest.
        response: NinePResponse,
        /// Device-I/O request release metadata.
        release: DeviceIoRequestRelease,
    },
}

/// A safe adapter for delivering a decoded raw 9p response to QEMU.
pub trait NinePGuestCompletion {
    /// Completes one guest 9p request.
    ///
    /// # Errors
    ///
    /// Returns [`NinePGuestCompletionError`] when the QEMU-facing completion path
    /// cannot expose the response and must fail loudly.
    fn complete_9p_response(
        &mut self,
        response: &NinePResponse,
    ) -> Result<(), NinePGuestCompletionError>;
}

/// A loud 9p guest-completion failure.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
#[error("9p guest completion failed: {message}")]
pub struct NinePGuestCompletionError {
    message: String,
}

impl NinePGuestCompletionError {
    /// Builds a guest-completion error.
    #[must_use]
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

/// A 9p wire-envelope decode or encode error.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum NinePWireError {
    /// The frame is shorter than the fixed 9p header.
    #[error("9p frame length {len} is shorter than header")]
    ShortHeader {
        /// The observed frame length.
        len: usize,
    },
    /// The declared message size is smaller than the header.
    #[error("9p declared size {size} is smaller than header")]
    DeclaredSizeTooSmall {
        /// The declared size field.
        size: u32,
    },
    /// The declared message size exceeds the supplied frame bytes.
    #[error("9p declared size {size} exceeds available frame length {available}")]
    DeclaredSizeExceedsFrame {
        /// The declared size field.
        size: u32,
        /// The supplied frame length.
        available: usize,
    },
    /// The frame has bytes after the declared single message.
    #[error("9p declared size {size} leaves trailing bytes in frame length {frame_len}")]
    DeclaredSizeHasTrailingBytes {
        /// The declared size field.
        size: u32,
        /// The supplied frame length.
        frame_len: usize,
    },
    /// The declared message size exceeds the negotiated `msize`.
    #[error("9p declared size {size} exceeds negotiated msize {msize}")]
    DeclaredSizeExceedsMsize {
        /// The declared size field.
        size: u32,
        /// The negotiated maximum message size.
        msize: u32,
    },
    /// An encoded message length cannot fit in the wire size field.
    #[error("9p message length {len} cannot fit in u32")]
    MessageSizeOverflow {
        /// The unrepresentable message length.
        len: usize,
    },
}

fn ninep_lerror(tag: u16, errno: u32) -> NinePWireMessage {
    NinePWireMessage::new(NINEP_RLERROR, tag, errno.to_le_bytes().to_vec())
}

fn tag_from_header(frame: &[u8]) -> Option<u16> {
    if frame.len() < NINEP_WIRE_HEADER_LEN {
        return None;
    }
    Some(u16::from_le_bytes([frame[5], frame[6]]))
}

fn errno_for_valid_ninep_message(message_type: u8) -> u32 {
    match message_type {
        14 | 26 | 72 | 74 | 76 | 118 => NINEP_EROFS,
        8 | 12 | 22 | 24 | 30 | 40 | 100 | 104 | 108 | 110 | 116 | 120 => NINEP_EIO,
        _ => NINEP_ENOSYS,
    }
}

/// An error produced by 9p callback handling.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum NinePIoError {
    /// The callback was handed a ring other than the fixed outbound 9p ring.
    #[error(
        "9p outbound ring mismatch: expected src={expected_src_slot} dst={expected_dst_slot} ring={expected_ring_index:?}, got src={actual_src_slot} dst={actual_dst_slot} ring={actual_ring_index}"
    )]
    WrongOutboundRing {
        /// The VM slot fixed at registration.
        expected_src_slot: u32,
        /// The 9p executor slot fixed at registration.
        expected_dst_slot: u32,
        /// The outbound ring index fixed at registration, if known.
        expected_ring_index: Option<u32>,
        /// The supplied ring's producer slot.
        actual_src_slot: u32,
        /// The supplied ring's consumer slot.
        actual_dst_slot: u32,
        /// The supplied ring's index.
        actual_ring_index: u32,
    },
    /// The callback was handed a ring other than the fixed inbound 9p ring.
    #[error(
        "9p inbound ring mismatch: expected src={expected_src_slot} dst={expected_dst_slot} ring={expected_ring_index:?}, got src={actual_src_slot} dst={actual_dst_slot} ring={actual_ring_index}"
    )]
    WrongInboundRing {
        /// The 9p executor slot fixed at registration.
        expected_src_slot: u32,
        /// The VM slot fixed at registration.
        expected_dst_slot: u32,
        /// The inbound ring index fixed at registration, if known.
        expected_ring_index: Option<u32>,
        /// The supplied ring's producer slot.
        actual_src_slot: u32,
        /// The supplied ring's consumer slot.
        actual_dst_slot: u32,
        /// The supplied ring's index.
        actual_ring_index: u32,
    },
    /// A 9p submit arrived without an active burst hold.
    #[error("9p submit arrived without an active burst")]
    SubmitOutsideBurst,
    /// The request id counter cannot represent another request.
    #[error("9p request id overflow at {request_id}")]
    RequestIdOverflow {
        /// The exhausted request id.
        request_id: u32,
    },
    /// The fixed pending-request table already contains this request id.
    #[error("9p request id {request_id} is already pending")]
    DuplicatePendingRequest {
        /// The duplicated request id.
        request_id: u32,
    },
    /// The fixed pending-request table has no free slot.
    #[error("9p pending request table is full at {capacity} requests")]
    PendingRequestCapacityExceeded {
        /// The fixed pending-request capacity.
        capacity: usize,
    },
    /// The fixed pending-request table was missing a request id being released.
    #[error("9p request id {request_id} was not pending")]
    PendingRequestMissing {
        /// The missing request id.
        request_id: u32,
    },
    /// Constructing a shared-memory frame failed.
    #[error("9p frame construction failed: {source}")]
    Frame {
        /// The frame construction error.
        source: FrameEntryError,
    },
    /// Device-I/O freeze state rejected a transition.
    #[error("9p device-I/O freeze failed: {source}")]
    DeviceIoFreeze {
        /// The device-I/O freeze error.
        source: DeviceIoFreezeError,
    },
    /// The outbound request enqueue failed after the freeze token was created.
    #[error("9p ring {ring_index} enqueue failed after freeze submit: {source}")]
    RingEnqueueFailed {
        /// The outbound ring index.
        ring_index: u32,
        /// The enqueue failure.
        source: SpscRingError,
        /// The release created by failing the just-created freeze token.
        release: DeviceIoRequestRelease,
    },
    /// The inbound ring operation failed.
    #[error("9p ring {ring_index} dequeue failed: {source}")]
    RingDequeue {
        /// The inbound ring index.
        ring_index: u32,
        /// The dequeue failure.
        source: SpscRingError,
    },
    /// The inbound ring head could not be decoded as a 9p response frame.
    #[error("9p ring {ring_index} malformed response at {frame:?}: {source}")]
    MalformedResponse {
        /// The inbound ring index.
        ring_index: u32,
        /// The frame key used to localize the malformed response.
        frame: FrameDeliveryKey,
        /// The frame payload error.
        source: FrameEntryError,
        /// The request release created by failing the pending token.
        release: DeviceIoRequestRelease,
    },
    /// The due response frame was not produced by the reserved 9p executor.
    #[error(
        "9p response source node {actual_src_node} does not match reserved 9p source {expected_src_node}"
    )]
    UnexpectedSource {
        /// The reserved 9p executor slot.
        expected_src_node: u32,
        /// The frame's advertised producer node.
        actual_src_node: u32,
        /// The response frame key.
        frame: FrameDeliveryKey,
        /// The request release created by failing the pending token.
        release: DeviceIoRequestRelease,
    },
    /// The due response did not match the request token being polled.
    #[error(
        "9p response request id {actual_request_id} does not match token {expected_request_id}"
    )]
    UnexpectedResponse {
        /// The token's request id.
        expected_request_id: u32,
        /// The response request id.
        actual_request_id: u32,
        /// The response frame key.
        frame: FrameDeliveryKey,
        /// The request release created by failing the pending token.
        release: DeviceIoRequestRelease,
    },
    /// The dequeued response did not match the previously peeked head.
    #[error("9p ring {ring_index} dequeued {actual:?} after peeking {expected:?}")]
    DequeuedUnexpectedFrame {
        /// The inbound ring index.
        ring_index: u32,
        /// The previewed frame key.
        expected: FrameDeliveryKey,
        /// The dequeued frame key, if any.
        actual: Option<FrameDeliveryKey>,
    },
    /// Delivering the raw response to the guest failed.
    #[error("9p request {request_id} guest completion failed: {source}")]
    GuestCompletion {
        /// The request id being completed.
        request_id: u32,
        /// The request release created before attempting guest completion.
        release: DeviceIoRequestRelease,
        /// The guest completion error.
        source: NinePGuestCompletionError,
    },
}

fn peek_head_frame(ring: &NinePInboundRing<'_>) -> Result<Option<FrameEntry>, NinePIoError> {
    let Some(delivery_icount) =
        PluginShmemOrdering::peek_inbound_delivery_icount(ring.header, ring.entries).map_err(
            |source| NinePIoError::RingDequeue {
                ring_index: ring.ring_index,
                source,
            },
        )?
    else {
        return Ok(None);
    };
    let slot = (PluginShmemOrdering::consumer_read_index(ring.header)
        & (ring.entries.len() as u64 - 1)) as usize;
    let frame = ring.entries[slot].clone();
    if frame.delivery_icount != delivery_icount {
        return Err(NinePIoError::DequeuedUnexpectedFrame {
            ring_index: ring.ring_index,
            expected: FrameDeliveryKey {
                delivery_icount,
                src_node: frame.src_node,
                seq: frame.seq,
            },
            actual: Some(frame.delivery_key()),
        });
    }
    Ok(Some(frame))
}

#[cfg(test)]
mod tests {
    use super::*;

    use crucible_shmem::{
        KIND_VM, MAX_FRAME_DATA, RegionConfig, RegionLayout, ReservedExecutorSlot,
    };

    #[test]
    fn ninep_io_state_binds_reserved_9p_rings() {
        let layout = layout();
        let (outbound, inbound) = ninep_rings(layout, 1);
        let ninep = match PluginNinePIo::from_directed_rings(1, outbound, inbound) {
            Ok(ninep) => ninep,
            Err(error) => panic!("9p rings should bind: {error}"),
        };

        assert_eq!(ninep.vm_slot(), 1);
        assert_eq!(ninep.ninep_slot(), NINEP_IO_SLOT_U32);
        assert_eq!(ninep.outbound_ring_index(), outbound.index);
        assert_eq!(ninep.inbound_ring_index(), inbound.index);

        let wrong = DirectedRing {
            index: outbound.index,
            src_slot: 1,
            dst_slot: ReservedExecutorSlot::BlockIo.slot() as u32,
        };
        assert_eq!(
            match PluginNinePIo::from_directed_rings(1, wrong, inbound) {
                Ok(_) => panic!("wrong 9p outbound ring should be rejected"),
                Err(error) => error,
            },
            NinePIoError::WrongOutboundRing {
                expected_src_slot: 1,
                expected_dst_slot: NINEP_IO_SLOT_U32,
                expected_ring_index: None,
                actual_src_slot: 1,
                actual_dst_slot: ReservedExecutorSlot::BlockIo.slot() as u32,
                actual_ring_index: outbound.index,
            }
        );
    }

    #[test]
    fn ninep_submit_requires_active_burst() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        let header = RingHeader::new();
        let mut entries = empty_entries(4);
        let mut ring = outbound_ring(10, 2, &header, &mut entries);

        assert_eq!(
            ninep.submit_request(
                &mut freeze,
                &slot,
                &mut ring,
                77,
                &NinePRequest::new(b"Twalk".to_vec()),
            ),
            Err(NinePIoError::SubmitOutsideBurst)
        );
        assert_eq!(freeze.pending_requests(), 0);
        assert_eq!(slot.snapshot().device_io_active, 0);
        assert_eq!(header.write_index(), 0);
    }

    #[test]
    fn ninep_submit_encodes_raw_message_stamps_icount_and_holds_burst() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        let header = RingHeader::new();
        let mut entries = empty_entries(4);
        let mut ring = outbound_ring(10, 2, &header, &mut entries);
        start_burst(&ninep, &mut freeze, &slot);

        let submit = match handle_9p_submit_callback(
            &ninep,
            &mut freeze,
            &slot,
            &mut ring,
            77,
            &NinePRequest::new(b"Tread".to_vec()),
        ) {
            Ok(submit) => submit,
            Err(error) => panic!("9p submit should enqueue: {error}"),
        };

        assert_eq!(submit.ring_index(), 10);
        assert_eq!(submit.submit_icount(), 77);
        assert_eq!(submit.request_id(), 0);
        assert_eq!(submit.payload_len(), 5);
        assert_eq!(ninep.next_request_id(), 1);
        assert_eq!(freeze.pending_requests(), 1);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);
        assert_eq!(header.write_index(), 1);
        assert_frame(&ring.entries[0], 77, 2, 0);
        assert_eq!(ring.entries[0].payload(), Ok(&b"Tread"[..]));
    }

    #[test]
    fn ninep_poll_holds_burst_until_burst_done_after_all_requests_complete() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let outbound_header = RingHeader::new();
        let mut outbound_entries = empty_entries(4);
        let mut outbound = outbound_ring(10, 2, &outbound_header, &mut outbound_entries);
        let token = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 77).into_token();
        let inbound_header = RingHeader::new();
        let mut inbound_entries = empty_entries(4);
        enqueue(
            &inbound_header,
            &mut inbound_entries,
            response_frame(90, 0, b"Rread"),
        );
        let inbound = inbound_ring(11, 2, &inbound_header, &inbound_entries);
        let mut completion = RecordingCompletion::default();

        let poll =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 90, token) {
                Ok(poll) => poll,
                Err(error) => panic!("due 9p response should complete: {error}"),
            };
        let NinePPoll::Completed { response, release } = poll else {
            panic!("due response should complete");
        };
        assert_eq!(response.payload(), b"Rread");
        assert_eq!(release.pending_requests(), 0);
        assert!(release.burst_active());
        assert!(release.device_io_active());
        assert_eq!(inbound_header.read_index(), 1);
        assert_eq!(completion.responses, vec![response]);
        assert_eq!(slot.snapshot().device_io_active, 1);

        let done = match handle_9p_burst_done_callback(&ninep, &mut freeze, &slot) {
            Ok(done) => done,
            Err(error) => panic!("burst done should release completed 9p burst: {error}"),
        };
        assert_eq!(done.pending_requests(), 0);
        assert!(!done.burst_active());
        assert!(!done.device_io_active());
        assert_eq!(slot.snapshot().device_io_active, 0);
    }

    #[test]
    fn ninep_poll_returns_not_ready_until_delivery_icount_is_reached() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let outbound_header = RingHeader::new();
        let mut outbound_entries = empty_entries(4);
        let mut outbound = outbound_ring(10, 2, &outbound_header, &mut outbound_entries);
        let token = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 77).into_token();
        let inbound_header = RingHeader::new();
        let mut inbound_entries = empty_entries(4);
        enqueue(
            &inbound_header,
            &mut inbound_entries,
            response_frame(90, 0, b"Rwalk"),
        );
        let inbound = inbound_ring(11, 2, &inbound_header, &inbound_entries);
        let mut completion = RecordingCompletion::default();

        let token =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 89, token) {
                Ok(NinePPoll::NotReady { token }) => token,
                other => panic!("future response should not be ready: {other:?}"),
            };

        assert_eq!(inbound_header.read_index(), 0);
        assert_eq!(freeze.pending_requests(), 1);
        assert!(completion.responses.is_empty());

        let poll =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 90, token) {
                Ok(poll) => poll,
                Err(error) => panic!("due 9p response should complete: {error}"),
            };
        assert!(matches!(poll, NinePPoll::Completed { .. }));
    }

    #[test]
    fn ninep_poll_allows_out_of_order_due_response_for_another_pending_token() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let outbound_header = RingHeader::new();
        let mut outbound_entries = empty_entries(4);
        let mut outbound = outbound_ring(10, 2, &outbound_header, &mut outbound_entries);
        let token0 = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 77).into_token();
        let token1 = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 78).into_token();
        let inbound_header = RingHeader::new();
        let mut inbound_entries = empty_entries(4);
        enqueue(
            &inbound_header,
            &mut inbound_entries,
            response_frame(90, 1, b"Rsecond"),
        );
        enqueue(
            &inbound_header,
            &mut inbound_entries,
            response_frame(91, 0, b"Rfirst"),
        );
        let inbound = inbound_ring(11, 2, &inbound_header, &inbound_entries);
        let mut completion = RecordingCompletion::default();

        let token0 =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 90, token0) {
                Ok(NinePPoll::NotReady { token }) => token,
                other => panic!("response for another pending token should not fail: {other:?}"),
            };
        assert_eq!(inbound_header.read_index(), 0);
        assert_eq!(freeze.pending_requests(), 2);
        assert!(completion.responses.is_empty());

        let second =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 90, token1) {
                Ok(NinePPoll::Completed { response, release }) => {
                    assert_eq!(release.pending_requests(), 1);
                    response
                }
                other => panic!("second response should complete first: {other:?}"),
            };
        assert_eq!(second.request_id(), 1);
        assert_eq!(second.payload(), b"Rsecond");
        assert_eq!(inbound_header.read_index(), 1);
        assert_eq!(freeze.pending_requests(), 1);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);

        let first =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 91, token0) {
                Ok(NinePPoll::Completed { response, release }) => {
                    assert_eq!(release.pending_requests(), 0);
                    response
                }
                other => panic!("first response should complete after head advances: {other:?}"),
            };
        assert_eq!(first.request_id(), 0);
        assert_eq!(first.payload(), b"Rfirst");
        assert_eq!(completion.responses, vec![second, first]);
        assert_eq!(inbound_header.read_index(), 2);
        assert_eq!(freeze.pending_requests(), 0);
        assert!(freeze.burst_active());

        let done = match ninep.burst_done(&mut freeze, &slot) {
            Ok(done) => done,
            Err(error) => panic!("burst done should release out-of-order burst: {error}"),
        };
        assert!(!done.device_io_active());
        assert_eq!(slot.snapshot().device_io_active, 0);
    }

    #[test]
    fn ninep_poll_rejects_unknown_request_id_and_releases_request_token() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let outbound_header = RingHeader::new();
        let mut outbound_entries = empty_entries(4);
        let mut outbound = outbound_ring(10, 2, &outbound_header, &mut outbound_entries);
        let token = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 77).into_token();
        let inbound_header = RingHeader::new();
        let mut inbound_entries = empty_entries(4);
        enqueue(
            &inbound_header,
            &mut inbound_entries,
            response_frame(90, 1, b"wrong"),
        );
        let inbound = inbound_ring(11, 2, &inbound_header, &inbound_entries);
        let mut completion = RecordingCompletion::default();

        let error =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 90, token) {
                Ok(_) => panic!("wrong request id should fail"),
                Err(error) => error,
            };
        match error {
            NinePIoError::UnexpectedResponse {
                expected_request_id: 0,
                actual_request_id: 1,
                frame,
                release,
            } => {
                assert_eq!(frame, response_frame(90, 1, b"wrong").delivery_key());
                assert_eq!(release.pending_requests(), 0);
                assert_eq!(release.outcome(), crate::DeviceIoRequestOutcome::Failed);
                assert!(release.burst_active());
                assert!(release.device_io_active());
            }
            other => panic!("wrong request id should be unexpected response: {other:?}"),
        }
        assert_eq!(inbound_header.read_index(), 0);
        assert_eq!(freeze.pending_requests(), 0);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);
        assert!(completion.responses.is_empty());
    }

    #[test]
    fn ninep_poll_rejects_wrong_response_source_and_releases_request_token() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let outbound_header = RingHeader::new();
        let mut outbound_entries = empty_entries(4);
        let mut outbound = outbound_ring(10, 2, &outbound_header, &mut outbound_entries);
        let token = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 77).into_token();
        let inbound_header = RingHeader::new();
        let mut inbound_entries = empty_entries(4);
        let malformed_source = frame(90, 99, 0, b"bad-source");
        enqueue(
            &inbound_header,
            &mut inbound_entries,
            malformed_source.clone(),
        );
        let inbound = inbound_ring(11, 2, &inbound_header, &inbound_entries);
        let mut completion = RecordingCompletion::default();

        let error =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 90, token) {
                Ok(_) => panic!("wrong response source should fail"),
                Err(error) => error,
            };
        match error {
            NinePIoError::UnexpectedSource {
                expected_src_node: NINEP_IO_SLOT_U32,
                actual_src_node: 99,
                frame,
                release,
            } => {
                assert_eq!(frame, malformed_source.delivery_key());
                assert_eq!(release.pending_requests(), 0);
                assert_eq!(release.outcome(), crate::DeviceIoRequestOutcome::Failed);
                assert!(release.burst_active());
                assert!(release.device_io_active());
            }
            other => panic!("wrong response source should be unexpected source: {other:?}"),
        }
        assert_eq!(inbound_header.read_index(), 0);
        assert_eq!(freeze.pending_requests(), 0);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);
        assert!(completion.responses.is_empty());
    }

    #[test]
    fn ninep_poll_guest_completion_failure_still_releases_request_token() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let outbound_header = RingHeader::new();
        let mut outbound_entries = empty_entries(4);
        let mut outbound = outbound_ring(10, 2, &outbound_header, &mut outbound_entries);
        let token = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 77).into_token();
        let inbound_header = RingHeader::new();
        let mut inbound_entries = empty_entries(4);
        enqueue(
            &inbound_header,
            &mut inbound_entries,
            response_frame(90, 0, b"Rread"),
        );
        let inbound = inbound_ring(11, 2, &inbound_header, &inbound_entries);
        let mut completion = RecordingCompletion {
            fail_message: Some("guest completion failure"),
            ..RecordingCompletion::default()
        };

        let error =
            match ninep.poll_response(&mut freeze, &slot, &inbound, &mut completion, 90, token) {
                Ok(_) => panic!("guest completion failure should be returned"),
                Err(error) => error,
            };
        match error {
            NinePIoError::GuestCompletion {
                request_id: 0,
                release,
                source,
            } => {
                assert_eq!(release.pending_requests(), 0);
                assert_eq!(release.outcome(), crate::DeviceIoRequestOutcome::Completed);
                assert!(release.burst_active());
                assert!(release.device_io_active());
                assert_eq!(
                    source,
                    NinePGuestCompletionError::new("guest completion failure")
                );
            }
            other => panic!("guest failure should be guest completion error: {other:?}"),
        }
        assert_eq!(inbound_header.read_index(), 1);
        assert_eq!(freeze.pending_requests(), 0);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);
        assert!(completion.responses.is_empty());
    }

    #[test]
    fn ninep_submit_full_ring_releases_request_token_and_pending_id() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let header = RingHeader::new();
        let mut entries = empty_entries(1);
        enqueue(&header, &mut entries, frame(70, 2, 99, b"occupied"));
        let mut ring = outbound_ring(10, 2, &header, &mut entries);

        let error = match ninep.submit_request(
            &mut freeze,
            &slot,
            &mut ring,
            77,
            &NinePRequest::new(b"Tread".to_vec()),
        ) {
            Ok(_) => panic!("full 9p ring should fail"),
            Err(error) => error,
        };
        assert!(matches!(
            error,
            NinePIoError::RingEnqueueFailed {
                source: SpscRingError::QueueFull { capacity: 1 },
                ..
            }
        ));
        assert_eq!(freeze.pending_requests(), 0);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);
        assert_eq!(ninep.next_request_id(), 0);
    }

    #[test]
    fn ninep_submit_rejects_request_id_overflow_before_freezing() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        ninep.next_request_id.set(u32::MAX);
        start_burst(&ninep, &mut freeze, &slot);
        let header = RingHeader::new();
        let mut entries = empty_entries(4);
        let mut ring = outbound_ring(10, 2, &header, &mut entries);

        assert_eq!(
            ninep.submit_request(
                &mut freeze,
                &slot,
                &mut ring,
                77,
                &NinePRequest::new(b"Tread".to_vec()),
            ),
            Err(NinePIoError::RequestIdOverflow {
                request_id: u32::MAX,
            })
        );
        assert_eq!(freeze.pending_requests(), 0);
        assert_eq!(header.write_index(), 0);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);
    }

    #[test]
    fn ninep_burst_done_rejects_pending_requests_and_keeps_hold_active() {
        let slot = NodeSlot::new(KIND_VM);
        let mut freeze = PluginDeviceIoFreeze::new();
        let ninep = PluginNinePIo::new(2, 10, 11);
        start_burst(&ninep, &mut freeze, &slot);
        let outbound_header = RingHeader::new();
        let mut outbound_entries = empty_entries(4);
        let mut outbound = outbound_ring(10, 2, &outbound_header, &mut outbound_entries);
        let _token = submit_raw(&ninep, &mut freeze, &slot, &mut outbound, 77).into_token();

        assert_eq!(
            handle_9p_burst_done_callback(&ninep, &mut freeze, &slot),
            Err(NinePIoError::DeviceIoFreeze {
                source: DeviceIoFreezeError::BurstDoneWithPendingRequests {
                    pending_requests: 1,
                },
            })
        );
        assert_eq!(freeze.pending_requests(), 1);
        assert!(freeze.burst_active());
        assert_eq!(slot.snapshot().device_io_active, 1);
    }

    #[derive(Default)]
    struct RecordingCompletion {
        responses: Vec<NinePResponse>,
        fail_message: Option<&'static str>,
    }

    impl NinePGuestCompletion for RecordingCompletion {
        fn complete_9p_response(
            &mut self,
            response: &NinePResponse,
        ) -> Result<(), NinePGuestCompletionError> {
            if let Some(message) = self.fail_message {
                return Err(NinePGuestCompletionError::new(message));
            }
            self.responses.push(response.clone());
            Ok(())
        }
    }

    fn layout() -> RegionLayout {
        match RegionLayout::for_config(RegionConfig::new(2, 4, 0)) {
            Ok(layout) => layout,
            Err(error) => panic!("layout should be valid: {error}"),
        }
    }

    fn ninep_rings(layout: RegionLayout, vm_slot: u32) -> (DirectedRing, DirectedRing) {
        let rings_per_vm = ReservedExecutorSlot::all().len() as u32 * 2;
        let index = vm_slot * rings_per_vm + 4;
        assert!(index + 1 < layout.ring_count);
        (
            DirectedRing {
                index,
                src_slot: vm_slot,
                dst_slot: NINEP_IO_SLOT_U32,
            },
            DirectedRing {
                index: index + 1,
                src_slot: NINEP_IO_SLOT_U32,
                dst_slot: vm_slot,
            },
        )
    }

    fn empty_entries(capacity: usize) -> Vec<FrameEntry> {
        vec![FrameEntry::default(); capacity]
    }

    fn outbound_ring<'a>(
        ring_index: u32,
        vm_slot: u32,
        header: &'a RingHeader,
        entries: &'a mut [FrameEntry],
    ) -> NinePOutboundRing<'a> {
        NinePOutboundRing::new(ring_index, vm_slot, NINEP_IO_SLOT_U32, header, entries)
    }

    fn inbound_ring<'a>(
        ring_index: u32,
        vm_slot: u32,
        header: &'a RingHeader,
        entries: &'a [FrameEntry],
    ) -> NinePInboundRing<'a> {
        NinePInboundRing::new(ring_index, NINEP_IO_SLOT_U32, vm_slot, header, entries)
    }

    fn start_burst(ninep: &PluginNinePIo, freeze: &mut PluginDeviceIoFreeze, slot: &NodeSlot) {
        if let Err(error) = handle_9p_burst_start_callback(ninep, freeze, slot) {
            panic!("9p burst should start: {error}");
        }
    }

    fn submit_raw(
        ninep: &PluginNinePIo,
        freeze: &mut PluginDeviceIoFreeze,
        slot: &NodeSlot,
        outbound: &mut NinePOutboundRing<'_>,
        submit_icount: u64,
    ) -> NinePSubmit {
        match ninep.submit_request(
            freeze,
            slot,
            outbound,
            submit_icount,
            &NinePRequest::new(b"Tread".to_vec()),
        ) {
            Ok(submit) => submit,
            Err(error) => panic!("9p submit should succeed: {error}"),
        }
    }

    fn response_frame(delivery_icount: u64, request_id: u32, payload: &[u8]) -> FrameEntry {
        frame(delivery_icount, NINEP_IO_SLOT_U32, request_id, payload)
    }

    fn frame(delivery_icount: u64, src_node: u32, seq: u32, payload: &[u8]) -> FrameEntry {
        match FrameEntry::new(delivery_icount, src_node, seq, payload) {
            Ok(frame) => frame,
            Err(error) => panic!("test frame should construct: {error}"),
        }
    }

    fn enqueue(header: &RingHeader, entries: &mut [FrameEntry], frame: FrameEntry) {
        if let Err(error) = PluginShmemOrdering::enqueue_outbound_frame(header, entries, &frame) {
            panic!("test frame should enqueue: {error}");
        }
    }

    fn assert_frame(frame: &FrameEntry, delivery_icount: u64, src_node: u32, seq: u32) {
        assert_eq!(frame.delivery_icount, delivery_icount);
        assert_eq!(frame.src_node, src_node);
        assert_eq!(frame.seq, seq);
        assert!(usize::from(frame.len) <= MAX_FRAME_DATA);
    }
}
