# modules/kubernetes/control-plane.nix — Kubernetes control plane module
#
# Configures the Kubernetes control plane components (API server, etcd,
# controller manager, scheduler). Generates a kubeadm configuration file
# and adds firewall rules for control plane ports. The actual control plane
# pods run as static pods managed by kubelet from /etc/kubernetes/manifests/.
#
# Absorbed TOML config values:
#   [kubernetes.control_plane] enable, advertise_address, api_server_port
#   [kubernetes.control_plane] etcd_data_dir

{ config, pkgs, lib, ... }:

let
  cfg = config.aos.kubernetes.controlPlane;
  netCfg = config.aos.kubernetes.network;
in
{
  options.aos.kubernetes.controlPlane = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable this node as a Kubernetes control plane node. This generates
        the kubeadm configuration for bootstrapping the control plane and
        opens the required firewall ports (API server, etcd, scheduler,
        controller manager).
      '';
    };

    advertiseAddress = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = ''
        IP address the API server will advertise to cluster members.
        If empty, kubeadm auto-detects the default interface address.
      '';
    };

    apiServerPort = lib.mkOption {
      type = lib.types.port;
      default = 6443;
      description = "TCP port for the Kubernetes API server.";
    };

    etcdDataDir = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/etcd";
      description = ''
        Data directory for the etcd key-value store. Should be on a
        fast disk (SSD/NVMe). On AOS this is a dedicated ZFS dataset
        with recordsize=4K and sync=always for optimal etcd performance.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # kubeadm configuration for control plane initialization.
    # This file is consumed by `kubeadm init --config <path>`.
    environment.etc."kubernetes/kubeadm-config.yaml" = {
      text = ''
        # /etc/kubernetes/kubeadm-config.yaml
        # Generated by modules/kubernetes/control-plane.nix
        # Use with: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
        ---
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: InitConfiguration
        localAPIEndpoint:
          ${lib.optionalString (cfg.advertiseAddress != "") "advertiseAddress: \"${cfg.advertiseAddress}\""}
          bindPort: ${toString cfg.apiServerPort}
        nodeRegistration:
          criSocket: "unix:///run/containerd/containerd.sock"
          taints:
            - key: "node-role.kubernetes.io/control-plane"
              effect: "NoSchedule"
        ---
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        kubernetesVersion: "v1.31.4"
        networking:
          podSubnet: "${netCfg.podCIDR}"
          serviceSubnet: "${netCfg.serviceCIDR}"
          dnsDomain: "${config.aos.kubernetes.kubelet.clusterDomain}"
        etcd:
          local:
            dataDir: "${cfg.etcdDataDir}"
        apiServer:
          extraArgs:
            authorization-mode: "Node,RBAC"
            enable-admission-plugins: "NodeRestriction,PodSecurity"
            audit-log-path: "/var/log/kubernetes/audit.log"
            audit-log-maxage: "30"
            audit-log-maxbackup: "10"
            audit-log-maxsize: "100"
            anonymous-auth: "false"
            profiling: "false"
            request-timeout: "300s"
        controllerManager:
          extraArgs:
            bind-address: "0.0.0.0"
            terminated-pod-gc-threshold: "100"
            profiling: "false"
        scheduler:
          extraArgs:
            bind-address: "0.0.0.0"
            profiling: "false"
      '';
    };

    # Ensure etcd data directory exists with correct permissions.
    environment.etc."tmpfiles.d/aos-control-plane.conf" = {
      text = ''
        # Kubernetes control plane directories.
        d ${cfg.etcdDataDir} 0700 root root -
        d /var/log/kubernetes 0750 root root -
      '';
    };

    # Enable kubelet and networking prerequisites on control plane nodes.
    aos.kubernetes.kubelet.enable = true;
    aos.kubernetes.network.enable = true;

    # Add control-plane-specific taints to the kubelet.
    aos.kubernetes.kubelet.nodeTaints = [
      "node-role.kubernetes.io/control-plane:NoSchedule"
    ];

    # Open control plane ports in the firewall.
    # These are additional to the base kubelet port (10250).
    aos.firewall.allowedTCP = [
      22                 # SSH
      cfg.apiServerPort  # kube-apiserver
      2379               # etcd client
      2380               # etcd peer
      10250              # kubelet API
      10257              # kube-controller-manager
      10259              # kube-scheduler
    ];
  };
}
