##! modules/kubernetes/containerd.nix — Container runtime module
##!
##! Configures containerd as the CRI-compatible container runtime for
##! Kubernetes. Generates /etc/containerd/config.toml in TOML format and
##! the containerd systemd service. Uses the systemd cgroup driver for
##! proper cgroup v2 integration.
##!
##! Absorbed TOML config values:
##!   [kubernetes.containerd] enable, snapshotter, runtime_type
##!   [kubernetes.containerd] cgroup_driver, sandbox_image, registry_mirrors
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.kubernetes.containerd;

  # Build registry mirror host directory configuration (v2 format).
  registryHostConfigs =
    lib.mapAttrsToList (registry: mirror: ''
      [plugins."io.containerd.grpc.v1.cri".registry.configs."${registry}".tls]
        insecure_skip_verify = false
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."${registry}"]
        endpoint = ["${mirror}"]
    '')
    cfg.registryMirrors;

  # Full containerd config.toml (v2 format with CRI v2 plugin paths).
  containerdConfig = ''
    # /etc/containerd/config.toml — generated by modules/kubernetes/containerd.nix
    # Do not edit manually.

    version = 2
    root = "/var/lib/containerd"
    state = "/run/containerd"

    [grpc]
      address = "/run/containerd/containerd.sock"
      max_recv_message_size = 16777216
      max_send_message_size = 16777216

    [plugins]
      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "${cfg.sandboxImage}"
        max_concurrent_downloads = ${toString cfg.maxConcurrentDownloads}
        [plugins."io.containerd.grpc.v1.cri".containerd]
          snapshotter = "${cfg.snapshotter}"
          default_runtime_name = "runc"
          discard_unpacked_layers = ${
      if cfg.discardUnpackedLayers
      then "true"
      else "false"
    }
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              runtime_type = "${cfg.runtimeType}"
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                SystemdCgroup = ${
      if cfg.cgroupDriver == "systemd"
      then "true"
      else "false"
    }
        [plugins."io.containerd.grpc.v1.cri".cni]
          bin_dir = "/opt/cni/bin"
          conf_dir = "/etc/cni/net.d"
    ${lib.optionalString (cfg.registryMirrors != {}) ''
          [plugins."io.containerd.grpc.v1.cri".registry]
      ${builtins.concatStringsSep "\n" registryHostConfigs}
    ''}
  '';
in {
  options.aos.kubernetes.containerd = {
    ## Enable the containerd container runtime.
    ##
    ## # See Also
    ## - `aos.kubernetes.kubelet`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the containerd container runtime. Required for Kubernetes
        nodes (both workers and control plane).
      '';
    };

    ## Containerd snapshotter backend (overlayfs, native, devmapper).
    snapshotter = lib.mkOption {
      type = lib.types.str;
      default = "overlayfs";
      description = ''
        Containerd snapshotter backend. "overlayfs" is the standard choice.
        Alternatives: "native" (for ZFS-backed storage), "devmapper".
      '';
    };

    ## OCI runtime type (v2 shim is the current standard).
    runtimeType = lib.mkOption {
      type = lib.types.str;
      default = "io.containerd.runc.v2";
      description = "OCI runtime type. The v2 shim is the current standard.";
    };

    ## Cgroup driver for container management (must match kubelet).
    cgroupDriver = lib.mkOption {
      type = lib.types.str;
      default = "systemd";
      description = ''
        Cgroup driver for container cgroup management. Must match the
        kubelet's cgroup driver. "systemd" is required for cgroup v2
        (which AOS uses exclusively).
      '';
    };

    ## Container image for the pod sandbox (pause container).
    sandboxImage = lib.mkOption {
      type = lib.types.str;
      default = "registry.k8s.io/pause:3.10";
      description = ''
        Container image for the pod sandbox (pause container). This image
        is pulled on first use and should be pinned to a specific version
        for reproducible builds.
      '';
    };

    ## Registry mirror mappings (original registry to mirror URL).
    ##
    ## # Examples
    ## ```nix
    ## aos.kubernetes.containerd.registryMirrors = {
    ##   "docker.io" = "https://mirror.internal/v2";
    ## };
    ## ```
    registryMirrors = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {};
      description = ''
        Registry mirror mappings. Each key is the original registry
        (e.g. "docker.io") and the value is the mirror URL
        (e.g. "https://mirror.internal/v2").
      '';
    };

    ## Maximum number of concurrent image layer downloads.
    maxConcurrentDownloads = lib.mkOption {
      type = lib.types.int;
      default = 3;
      description = "Maximum number of concurrent image layer downloads.";
    };

    ## Discard unpacked image layers after extraction to save disk.
    discardUnpackedLayers = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Discard unpacked image layers after extraction. Saves disk space
        at the cost of needing to re-extract if layers are needed again.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    system.checks.container-support = {
      description = "Container kernel feature checks";
      checks = [
        {
          name = "cgroups-v2";
          description = "cgroups v2 filesystem is mounted";
          script = ''
            assert_success "test -d /sys/fs/cgroup" \
              "cgroups filesystem is mounted"
          '';
        }
        {
          name = "pid-namespace";
          description = "PID namespaces available";
          script = ''
            assert_success "test -f /proc/self/ns/pid" \
              "PID namespaces available"
          '';
        }
        {
          name = "net-namespace";
          description = "Network namespaces available";
          script = ''
            assert_success "test -f /proc/self/ns/net" \
              "Network namespaces available"
          '';
        }
        {
          name = "mnt-namespace";
          description = "Mount namespaces available";
          script = ''
            assert_success "test -f /proc/self/ns/mnt" \
              "Mount namespaces available"
          '';
        }
      ];
    };

    system.checks.containerd = {
      description = "Container runtime checks";
      checks = [
        {
          name = "containerd-active";
          description = "containerd service is active";
          script = ''
            assert_success "systemctl is-active containerd" \
              "containerd service is active"
          '';
        }
        {
          name = "containerd-socket";
          description = "containerd socket exists";
          script = ''
            assert_success "test -S /run/containerd/containerd.sock" \
              "containerd socket exists"
          '';
        }
        {
          name = "containerd-config";
          description = "containerd config.toml exists";
          script = ''
            assert_success "test -f /etc/containerd/config.toml" \
              "containerd config.toml exists"
          '';
        }
      ];
    };

    # ZFS dataset for containerd state (container images, snapshots).
    aos.filesystems.zfs.datasets = lib.mkIf config.aos.filesystems.zfs.enable {
      "var/lib/containerd" = {
        mountpoint = "/var/lib/containerd";
        compression = "zstd-3";
        atime = "off";
        recordsize = "128K";
      };
    };

    environment.systemPackages = [
      pkgs.containerd
      pkgs.runc
    ];

    # /etc/containerd/config.toml — containerd configuration.
    environment.etc."containerd/config.toml" = {
      text = containerdConfig;
    };

    # containerd.service — container runtime daemon.
    #
    # Stage 7 of the systemd refactor (spec v3.1 §7): the base unit
    # file comes from `pkgs.containerd`'s upstream `containerd.service`
    # (installed into `$out/lib/systemd/system/`, with `/usr/local/bin/
    # containerd` and `/sbin/modprobe` path-fixed to the package's own
    # store paths). This pulls in all of upstream's baseline:
    # `Type=notify`, `Delegate=yes`, `KillMode=process`, `Restart=always`,
    # `RestartSec=5`, `LimitNPROC=infinity`, `LimitCORE=infinity`,
    # `TasksMax=infinity`, `OOMScoreAdjust=-999`, and the
    # `ExecStartPre=-${kmod}/bin/modprobe overlay` hook.
    #
    # `generateUnits` picks up the file via `systemd.packages`, and the
    # `asDropin` declaration below layers AOS-specific additions on top
    # as `containerd.service.d/overrides.conf`:
    #
    #   * `after = [ "local-fs.target" ]` — needs `/var/lib/containerd`
    #     mounted before start (upstream only orders after
    #     `network.target dbus.service`)
    #   * `ExecReload = kill -HUP $MAINPID` — reload on config change;
    #     upstream doesn't declare one
    #   * `LimitNOFILE = 1048576` — file-descriptor bump for busy
    #     kubelets; upstream leaves the default
    #
    # `--config` is NOT passed because containerd's default config
    # path is already `/etc/containerd/config.toml` (which is where we
    # write via `environment.etc."containerd/config.toml"` above), and
    # omitting the flag lets upstream's ExecStart pass through
    # unchanged.
    systemd.packages = [pkgs.containerd];

    systemd.services."containerd" = {
      overrideStrategy = "asDropin";
      wantedBy = ["multi-user.target"];
      after = ["local-fs.target"];
      serviceConfig = {
        ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        LimitNOFILE = "1048576";
      };
    };

    # Ensure containerd directories exist.
    environment.etc."tmpfiles.d/aos-containerd.conf" = {
      text = ''
        # containerd state directories.
        d /var/lib/containerd 0711 root root -
        d /run/containerd 0755 root root -
        d /opt/cni/bin 0755 root root -
        d /etc/cni/net.d 0755 root root -
      '';
    };

    # CNI loopback configuration — required for pod networking.
    environment.etc."cni/net.d/99-loopback.conf" = {
      text = builtins.toJSON {
        cniVersion = "1.0.0";
        name = "lo";
        type = "loopback";
      };
    };
  };
}
