##! modules/kubernetes/edgecore.nix — KubeEdge EdgeCore service module
##!
##! Configures the KubeEdge EdgeCore agent, which connects edge nodes to a
##! cloud-side CloudCore controller. EdgeCore is a lightweight alternative
##! to the full kubelet for resource-constrained devices.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.aos.kubernetes.edgecore;

  edgecoreConfig = ''
    # /etc/kubeedge/config/edgecore.yaml — generated by modules/kubernetes/edgecore.nix
    apiVersion: edgecore.config.kubeedge.io/v1alpha2
    kind: EdgeCore
    modules:
      edgeHub:
        enable: true
        heartbeat: ${toString cfg.heartbeat}
        websocket:
          enable: true
          server: "${cfg.cloudCoreAddress}"
      edged:
        enable: true
        cgroupDriver: systemd
        clusterDNS: "${cfg.clusterDNS}"
        clusterDomain: "${cfg.clusterDomain}"
        containerRuntime: remote
        remoteRuntimeEndpoint: unix:///run/containerd/containerd.sock
        remoteImageEndpoint: unix:///run/containerd/containerd.sock
      eventBus:
        enable: ${if cfg.mqtt.enable then "true" else "false"}
        mqttMode: ${toString cfg.mqtt.mode}
      metaManager:
        enable: true
      serviceBus:
        enable: false
      deviceTwin:
        enable: true
  '';
in
{
  options.aos.kubernetes.edgecore = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the KubeEdge EdgeCore agent. Connects this edge node to
        a cloud-side CloudCore controller for lightweight Kubernetes
        workload management.
      '';
    };

    cloudCoreAddress = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = ''
        WebSocket address of the CloudCore controller
        (e.g. "wss://cloudcore.example.com:10000"). Typically set via
        cloud-init userdata at boot time.
      '';
    };

    clusterDNS = lib.mkOption {
      type = lib.types.str;
      default = "10.96.0.10";
      description = "Cluster DNS service IP for edge pods.";
    };

    clusterDomain = lib.mkOption {
      type = lib.types.str;
      default = "cluster.local";
      description = "Cluster DNS domain for edge pods.";
    };

    heartbeat = lib.mkOption {
      type = lib.types.int;
      default = 15;
      description = "Heartbeat interval in seconds to CloudCore.";
    };

    mqtt = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Enable MQTT event bus for device communication.";
      };

      mode = lib.mkOption {
        type = lib.types.int;
        default = 2;
        description = ''
          MQTT mode: 0 = internal only, 1 = internal and external,
          2 = external only.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs.edgecore ];

    # EdgeCore configuration
    environment.etc."kubeedge/config/edgecore.yaml" = {
      text = edgecoreConfig;
    };

    # Firewall: edgecore websocket (10000), edgehub (10350)
    aos.firewall.allowedTCP = [ 10000 10350 ];

    # edgecore.service — KubeEdge edge agent
    systemd.services."edgecore" = {
      description = "KubeEdge EdgeCore Agent";
      wantedBy = [ "multi-user.target" ];
      after = [
        "network-online.target"
        "containerd.service"
      ];
      wants = [
        "network-online.target"
        "containerd.service"
      ];
      serviceConfig = {
        Type = "simple";
        ExecStart = "${pkgs.edgecore}/bin/edgecore --config /etc/kubeedge/config/edgecore.yaml";
        Restart = "always";
        RestartSec = "10s";
        LimitNOFILE = "1048576";
        LimitNPROC = "infinity";
      };
    };

    # Ensure config directories exist
    environment.etc."tmpfiles.d/aos-edgecore.conf" = {
      text = ''
        d /etc/kubeedge 0755 root root -
        d /etc/kubeedge/config 0755 root root -
        d /var/lib/kubeedge 0755 root root -
      '';
    };
  };
}
