# modules/kubernetes/kubelet.nix — Kubernetes node agent module
#
# Configures the kubelet, the primary Kubernetes agent that runs on every
# node. Generates /var/lib/kubelet/config.yaml (KubeletConfiguration) and
# the kubelet systemd service with appropriate flags.
#
# Absorbed TOML config values:
#   [kubernetes.kubelet] enable, cluster_dns, cluster_domain, cgroup_driver
#   [kubernetes.kubelet] container_runtime, container_runtime_endpoint
#   [kubernetes.kubelet] max_pods, serialize_image_pulls
#   [kubernetes.kubelet] node_labels, node_taints

{ config, pkgs, lib, ... }:

let
  cfg = config.aos.kubernetes.kubelet;

  # Build the KubeletConfiguration YAML.
  # This is the typed configuration file that kubelet reads on startup.
  kubeletConfigYaml = ''
    # /var/lib/kubelet/config.yaml — generated by modules/kubernetes/kubelet.nix
    # KubeletConfiguration API object.
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    cgroupDriver: "${cfg.cgroupDriver}"
    clusterDNS:
    ${builtins.concatStringsSep "\n" (builtins.map (dns: "  - \"${dns}\"") cfg.clusterDNS)}
    clusterDomain: "${cfg.clusterDomain}"
    containerRuntimeEndpoint: "${cfg.containerRuntimeEndpoint}"
    maxPods: ${toString cfg.maxPods}
    serializeImagePulls: ${if cfg.serializeImagePulls then "true" else "false"}
    authentication:
      anonymous:
        enabled: false
      webhook:
        enabled: true
        cacheTTL: "2m0s"
      x509:
        clientCAFile: "/etc/kubernetes/pki/ca.crt"
    authorization:
      mode: Webhook
      webhook:
        cacheAuthorizedTTL: "5m0s"
        cacheUnauthorizedTTL: "30s"
    tlsCertFile: "/var/lib/kubelet/pki/kubelet.crt"
    tlsPrivateKeyFile: "/var/lib/kubelet/pki/kubelet.key"
    rotateCertificates: true
    serverTLSBootstrap: true
    readOnlyPort: 0
    protectKernelDefaults: true
    eventRecordQPS: 5
    shutdownGracePeriod: "30s"
    shutdownGracePeriodCriticalPods: "10s"
  '';

  # Build kubelet command-line flags.
  nodeLabelsFlag =
    if cfg.nodeLabels == {} then ""
    else "--node-labels=${builtins.concatStringsSep "," (lib.mapAttrsToList (k: v: "${k}=${v}") cfg.nodeLabels)}";

  nodeTaintsFlag =
    if cfg.nodeTaints == [] then ""
    else "--register-with-taints=${builtins.concatStringsSep "," cfg.nodeTaints}";

  kubeletFlags = builtins.concatStringsSep " " (builtins.filter (s: s != "") [
    "--config=/var/lib/kubelet/config.yaml"
    "--kubeconfig=/etc/kubernetes/kubelet.conf"
    "--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf"
    "--container-runtime-endpoint=${cfg.containerRuntimeEndpoint}"
    "--hostname-override=${config.aos.networking.hostName}"
    "--v=2"
    nodeLabelsFlag
    nodeTaintsFlag
  ]);

in
{
  options.aos.kubernetes.kubelet = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the kubelet Kubernetes node agent. Required on both worker
        and control plane nodes.
      '';
    };

    clusterDNS = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "10.96.0.10" ];
      description = ''
        Cluster DNS server IP addresses. This is typically the CoreDNS
        service ClusterIP, which must fall within the service CIDR.
      '';
    };

    clusterDomain = lib.mkOption {
      type = lib.types.str;
      default = "cluster.local";
      description = "DNS domain for cluster-internal service resolution.";
    };

    cgroupDriver = lib.mkOption {
      type = lib.types.str;
      default = "systemd";
      description = ''
        Cgroup driver. Must match containerd's cgroup driver. "systemd"
        is required for cgroup v2 (which AOS uses exclusively).
      '';
    };

    containerRuntime = lib.mkOption {
      type = lib.types.str;
      default = "remote";
      description = ''
        Container runtime type. "remote" means kubelet communicates with
        the runtime via CRI over a Unix socket.
      '';
    };

    containerRuntimeEndpoint = lib.mkOption {
      type = lib.types.str;
      default = "unix:///run/containerd/containerd.sock";
      description = "CRI endpoint socket path for the container runtime.";
    };

    maxPods = lib.mkOption {
      type = lib.types.int;
      default = 110;
      description = "Maximum number of pods that can run on this node.";
    };

    serializeImagePulls = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to pull images one at a time. Disabled by default to allow
        parallel image pulls, which speeds up pod startup.
      '';
    };

    nodeLabels = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {};
      description = ''
        Labels to apply to this node on registration. Example:
        { "topology.kubernetes.io/zone" = "us-east-1a"; }
      '';
    };

    nodeTaints = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = ''
        Taints to apply to this node on registration. Format:
        "key=value:effect" (e.g. "node-role.kubernetes.io/control-plane:NoSchedule").
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # /var/lib/kubelet/config.yaml — KubeletConfiguration.
    environment.etc."kubernetes/kubelet-config.yaml" = {
      text = kubeletConfigYaml;
    };

    # kubelet.service — Kubernetes node agent.
    systemd.services."kubelet" = {
      description = "Kubernetes Kubelet";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" "containerd.service" ];
      wants = [ "network-online.target" ];
      requires = [ "containerd.service" ];
      serviceConfig = {
        Type = "notify";
        ExecStart = "/usr/bin/kubelet ${kubeletFlags}";
        Restart = "always";
        RestartSec = "10s";
        # kubelet needs broad privileges for pod management.
        LimitNOFILE = "1048576";
        LimitNPROC = "infinity";
        LimitCORE = "infinity";
        TasksMax = "infinity";
        OOMScoreAdjust = -999;
        Delegate = true;
        CPUAccounting = true;
        MemoryAccounting = true;
      };
    };

    # Ensure kubelet directories exist.
    environment.etc."tmpfiles.d/aos-kubelet.conf" = {
      text = ''
        # kubelet state directories.
        d /var/lib/kubelet 0750 root root -
        d /var/lib/kubelet/pki 0700 root root -
        d /etc/kubernetes 0755 root root -
        d /etc/kubernetes/pki 0700 root root -
        d /etc/kubernetes/manifests 0700 root root -
      '';
    };

    # Ensure containerd is enabled when kubelet is enabled.
    aos.kubernetes.containerd.enable = true;

    # Open kubelet API port in the firewall.
    aos.firewall.allowedTCP = [ 22 10250 ];
  };
}
