##! modules/kubernetes/kubelet.nix — Kubernetes node agent module
##!
##! Configures the kubelet, the primary Kubernetes agent that runs on every
##! node. Generates /var/lib/kubelet/config.yaml (KubeletConfiguration) and
##! the kubelet systemd service with appropriate flags.
##!
##! Absorbed TOML config values:
##!   [kubernetes.kubelet] enable, cluster_dns, cluster_domain, cgroup_driver
##!   [kubernetes.kubelet] container_runtime, container_runtime_endpoint
##!   [kubernetes.kubelet] max_pods, serialize_image_pulls
##!   [kubernetes.kubelet] node_labels, node_taints
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.aos.kubernetes.kubelet;

  # Build the KubeletConfiguration YAML.
  # This is the typed configuration file that kubelet reads on startup.
  kubeletConfigYaml = ''
    # /var/lib/kubelet/config.yaml — generated by modules/kubernetes/kubelet.nix
    # KubeletConfiguration API object.
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    cgroupDriver: "${cfg.cgroupDriver}"
    clusterDNS:
    ${builtins.concatStringsSep "\n" (builtins.map (dns: "  - \"${dns}\"") cfg.clusterDNS)}
    clusterDomain: "${cfg.clusterDomain}"
    containerRuntimeEndpoint: "${cfg.containerRuntimeEndpoint}"
    maxPods: ${toString cfg.maxPods}
    serializeImagePulls: ${if cfg.serializeImagePulls then "true" else "false"}
    authentication:
      anonymous:
        enabled: false
      webhook:
        enabled: true
        cacheTTL: "2m0s"
      x509:
        clientCAFile: "/etc/kubernetes/pki/ca.crt"
    authorization:
      mode: Webhook
      webhook:
        cacheAuthorizedTTL: "5m0s"
        cacheUnauthorizedTTL: "30s"
    tlsCertFile: "/var/lib/kubelet/pki/kubelet.crt"
    tlsPrivateKeyFile: "/var/lib/kubelet/pki/kubelet.key"
    rotateCertificates: true
    serverTLSBootstrap: true
    readOnlyPort: 0
    protectKernelDefaults: true
    eventRecordQPS: 5
    shutdownGracePeriod: "30s"
    shutdownGracePeriodCriticalPods: "10s"
    systemReserved:
      cpu: "${cfg.systemReserved.cpu}"
      memory: "${cfg.systemReserved.memory}"
      ephemeral-storage: "${cfg.systemReserved.ephemeralStorage}"
    kubeReserved:
      cpu: "${cfg.kubeReserved.cpu}"
      memory: "${cfg.kubeReserved.memory}"
      ephemeral-storage: "${cfg.kubeReserved.ephemeralStorage}"
    evictionHard:
      memory.available: "${cfg.evictionHard.memoryAvailable}"
      nodefs.available: "${cfg.evictionHard.nodefsAvailable}"
      imagefs.available: "${cfg.evictionHard.imagefsAvailable}"
    evictionSoft:
      memory.available: "${cfg.evictionSoft.memoryAvailable}"
      nodefs.available: "${cfg.evictionSoft.nodefsAvailable}"
    evictionSoftGracePeriod:
      memory.available: "1m30s"
      nodefs.available: "1m30s"
    imageGCHighThresholdPercent: ${toString cfg.imageGCHighThreshold}
    imageGCLowThresholdPercent: ${toString cfg.imageGCLowThreshold}
    containerLogMaxSize: "${cfg.containerLogMaxSize}"
    containerLogMaxFiles: ${toString cfg.containerLogMaxFiles}
    topologyManagerPolicy: "${cfg.topologyManagerPolicy}"
    ${lib.optionalString (cfg.featureGates != { }) ''
      featureGates:
      ${builtins.concatStringsSep "\n" (
        lib.mapAttrsToList (k: v: "  ${k}: ${if v then "true" else "false"}") cfg.featureGates
      )}
    ''}
  '';

  # Build kubelet command-line flags.
  nodeLabelsFlag =
    if cfg.nodeLabels == { } then
      ""
    else
      "--node-labels=${
        builtins.concatStringsSep "," (lib.mapAttrsToList (k: v: "${k}=${v}") cfg.nodeLabels)
      }";

  nodeTaintsFlag =
    if cfg.nodeTaints == [ ] then
      ""
    else
      "--register-with-taints=${builtins.concatStringsSep "," cfg.nodeTaints}";

  kubeletFlags = builtins.concatStringsSep " " (
    builtins.filter (s: s != "") [
      "--config=/var/lib/kubelet/config.yaml"
      "--kubeconfig=/etc/kubernetes/kubelet.conf"
      "--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf"
      "--container-runtime-endpoint=${cfg.containerRuntimeEndpoint}"
      "--hostname-override=${config.aos.networking.hostName}"
      "--v=2"
      nodeLabelsFlag
      nodeTaintsFlag
    ]
  );
in
{
  options.aos.kubernetes.kubelet = {
    ## Enable the kubelet Kubernetes node agent.
    ##
    ## # See Also
    ## - `aos.kubernetes.containerd`, `aos.kubernetes.network`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the kubelet Kubernetes node agent. Required on both worker
        and control plane nodes.
      '';
    };

    ## Cluster DNS server IP addresses (typically CoreDNS).
    clusterDNS = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "10.96.0.10" ];
      description = ''
        Cluster DNS server IP addresses. This is typically the CoreDNS
        service ClusterIP, which must fall within the service CIDR.
      '';
    };

    ## DNS domain for cluster-internal service resolution.
    clusterDomain = lib.mkOption {
      type = lib.types.str;
      default = "cluster.local";
      description = "DNS domain for cluster-internal service resolution.";
    };

    ## Cgroup driver (must match containerd). "systemd" required for cgroup v2.
    cgroupDriver = lib.mkOption {
      type = lib.types.str;
      default = "systemd";
      description = ''
        Cgroup driver. Must match containerd's cgroup driver. "systemd"
        is required for cgroup v2 (which AOS uses exclusively).
      '';
    };

    ## Container runtime type ("remote" for CRI over Unix socket).
    containerRuntime = lib.mkOption {
      type = lib.types.str;
      default = "remote";
      description = ''
        Container runtime type. "remote" means kubelet communicates with
        the runtime via CRI over a Unix socket.
      '';
    };

    ## CRI endpoint socket path for the container runtime.
    containerRuntimeEndpoint = lib.mkOption {
      type = lib.types.str;
      default = "unix:///run/containerd/containerd.sock";
      description = "CRI endpoint socket path for the container runtime.";
    };

    ## Maximum number of pods that can run on this node.
    maxPods = lib.mkOption {
      type = lib.types.int;
      default = 110;
      description = "Maximum number of pods that can run on this node.";
    };

    ## Whether to pull images one at a time.
    serializeImagePulls = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to pull images one at a time. Disabled by default to allow
        parallel image pulls, which speeds up pod startup.
      '';
    };

    ## Labels to apply to this node on registration.
    ##
    ## # Examples
    ## ```nix
    ## aos.kubernetes.kubelet.nodeLabels = {
    ##   "topology.kubernetes.io/zone" = "us-east-1a";
    ## };
    ## ```
    nodeLabels = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = ''
        Labels to apply to this node on registration. Example:
        { "topology.kubernetes.io/zone" = "us-east-1a"; }
      '';
    };

    ## Taints to apply to this node on registration.
    nodeTaints = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = ''
        Taints to apply to this node on registration. Format:
        "key=value:effect" (e.g. "node-role.kubernetes.io/control-plane:NoSchedule").
      '';
    };

    systemReserved = {
      ## CPU reserved for system daemons (e.g. systemd, journald).
      cpu = lib.mkOption {
        type = lib.types.str;
        default = "100m";
        description = "CPU reserved for system daemons (e.g. systemd, journald).";
      };
      ## Memory reserved for system daemons.
      memory = lib.mkOption {
        type = lib.types.str;
        default = "256Mi";
        description = "Memory reserved for system daemons.";
      };
      ## Ephemeral storage reserved for system daemons.
      ephemeralStorage = lib.mkOption {
        type = lib.types.str;
        default = "1Gi";
        description = "Ephemeral storage reserved for system daemons.";
      };
    };

    kubeReserved = {
      ## CPU reserved for Kubernetes components (kubelet, container runtime).
      cpu = lib.mkOption {
        type = lib.types.str;
        default = "100m";
        description = "CPU reserved for Kubernetes components (kubelet, container runtime).";
      };
      ## Memory reserved for Kubernetes components.
      memory = lib.mkOption {
        type = lib.types.str;
        default = "256Mi";
        description = "Memory reserved for Kubernetes components.";
      };
      ## Ephemeral storage reserved for Kubernetes components.
      ephemeralStorage = lib.mkOption {
        type = lib.types.str;
        default = "1Gi";
        description = "Ephemeral storage reserved for Kubernetes components.";
      };
    };

    evictionHard = {
      ## Hard eviction threshold for available memory.
      memoryAvailable = lib.mkOption {
        type = lib.types.str;
        default = "100Mi";
        description = "Hard eviction threshold for available memory.";
      };
      ## Hard eviction threshold for node filesystem available space.
      nodefsAvailable = lib.mkOption {
        type = lib.types.str;
        default = "10%";
        description = "Hard eviction threshold for node filesystem available space.";
      };
      ## Hard eviction threshold for image filesystem available space.
      imagefsAvailable = lib.mkOption {
        type = lib.types.str;
        default = "15%";
        description = "Hard eviction threshold for image filesystem available space.";
      };
    };

    evictionSoft = {
      ## Soft eviction threshold for available memory.
      memoryAvailable = lib.mkOption {
        type = lib.types.str;
        default = "200Mi";
        description = "Soft eviction threshold for available memory.";
      };
      ## Soft eviction threshold for node filesystem available space.
      nodefsAvailable = lib.mkOption {
        type = lib.types.str;
        default = "15%";
        description = "Soft eviction threshold for node filesystem available space.";
      };
    };

    ## Image GC is triggered when disk usage exceeds this percentage.
    imageGCHighThreshold = lib.mkOption {
      type = lib.types.int;
      default = 85;
      description = "Image GC is triggered when disk usage exceeds this percentage.";
    };

    ## Image GC frees disk until usage drops below this percentage.
    imageGCLowThreshold = lib.mkOption {
      type = lib.types.int;
      default = 80;
      description = "Image GC attempts to free disk until usage drops below this percentage.";
    };

    ## Maximum size of a container log file before rotation.
    containerLogMaxSize = lib.mkOption {
      type = lib.types.str;
      default = "10Mi";
      description = "Maximum size of a container log file before rotation.";
    };

    ## Maximum number of rotated container log files to retain.
    containerLogMaxFiles = lib.mkOption {
      type = lib.types.int;
      default = 5;
      description = "Maximum number of rotated container log files to retain.";
    };

    ## Topology Manager policy for NUMA-aware resource alignment.
    topologyManagerPolicy = lib.mkOption {
      type = lib.types.str;
      default = "none";
      description = ''
        Topology Manager policy for NUMA-aware resource alignment.
        Options: "none", "best-effort", "restricted", "single-numa-node".
      '';
    };

    ## Kubernetes feature gates to enable or disable.
    featureGates = lib.mkOption {
      type = lib.types.attrsOf lib.types.bool;
      default = { };
      description = ''
        Kubernetes feature gates to enable or disable. Example:
        { "GracefulNodeShutdown" = true; "TopologyManager" = true; }
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    system.checks.kubelet = lib.mkCheckGroup {
      name = "kubelet";
      description = "Kubelet and CNI checks";
      checks = [
        (lib.mkCheck {
          name = "kubelet-enabled";
          description = "kubelet service is enabled";
          script = ''
            assert_success "systemctl is-enabled kubelet" \
              "kubelet service is enabled"
          '';
        })
        (lib.mkCheck {
          name = "kubelet-config";
          description = "kubelet config.yaml exists";
          script = ''
            assert_success "test -f /var/lib/kubelet/config.yaml" \
              "kubelet config.yaml exists"
          '';
        })
        (lib.mkCheck {
          name = "cni-dir";
          description = "CNI config directory exists";
          script = ''
            assert_success "test -d /etc/cni/net.d" \
              "CNI config directory exists"
          '';
        })
      ];
    };

    environment.systemPackages = [
      pkgs.kubelet
      pkgs.crictl
    ];

    # /var/lib/kubelet/config.yaml — KubeletConfiguration.
    environment.etc."kubernetes/kubelet-config.yaml" = {
      text = kubeletConfigYaml;
    };

    # kubelet.service — Kubernetes node agent.
    systemd.services."kubelet" = {
      description = "Kubernetes Kubelet";
      wantedBy = [ "multi-user.target" ];
      after = [
        "network-online.target"
        "containerd.service"
      ];
      wants = [ "network-online.target" ];
      requires = [ "containerd.service" ];
      serviceConfig = {
        Type = "notify";
        ExecStart = "${pkgs.kubelet}/bin/kubelet ${kubeletFlags}";
        Restart = "always";
        RestartSec = "10s";
        # kubelet needs broad privileges for pod management.
        LimitNOFILE = "1048576";
        LimitNPROC = "infinity";
        LimitCORE = "infinity";
        TasksMax = "infinity";
        OOMScoreAdjust = -999;
        Delegate = true;
        CPUAccounting = true;
        MemoryAccounting = true;
      };
    };

    # Ensure kubelet directories exist.
    environment.etc."tmpfiles.d/aos-kubelet.conf" = {
      text = ''
        # kubelet state directories.
        d /var/lib/kubelet 0750 root root -
        d /var/lib/kubelet/pki 0700 root root -
        d /etc/kubernetes 0755 root root -
        d /etc/kubernetes/pki 0700 root root -
        d /etc/kubernetes/manifests 0700 root root -
      '';
    };

    # Ensure containerd is enabled when kubelet is enabled.
    aos.kubernetes.containerd.enable = true;

    # Open kubelet API port in the firewall.
    aos.firewall.allowedTCP = [
      22
      10250
    ];
  };
}
