##! modules/kubernetes/network.nix — Kubernetes networking prerequisites module
##!
##! Configures the kernel modules, sysctl parameters, and firewall rules
##! required for Kubernetes pod networking. This module handles the
##! prerequisites — the actual CNI plugin (Cilium, Flannel, etc.) is deployed
##! as a DaemonSet and not part of the OS image.
##!
##! Absorbed TOML config values:
##!   [kubernetes.network] enable, pod_cidr, service_cidr
##!   [kubernetes.network] kernel_modules, sysctl
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.kubernetes.network;

  # Format sysctl entries for the drop-in file.
  sysctlText = builtins.concatStringsSep "\n" (
    lib.mapAttrsToList (key: value: "${key} = ${value}") cfg.sysctl
  );
in {
  options.aos.kubernetes.network = {
    ## Enable Kubernetes networking prerequisites.
    ##
    ## # See Also
    ## - `aos.kubernetes.network.podCIDR`, `aos.kubernetes.network.serviceCIDR`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable Kubernetes networking prerequisites. Loads required kernel
        modules, sets sysctl parameters for bridge traffic and IP forwarding,
        and configures firewall rules for pod-to-pod communication.
      '';
    };

    ## CIDR range for Kubernetes pod IP addresses.
    podCIDR = lib.mkOption {
      type = lib.types.str;
      default = "10.244.0.0/16";
      description = ''
        CIDR range for Kubernetes pod IP addresses. Must not overlap with
        the service CIDR or the host network. The CNI plugin allocates
        pod IPs from this range.
      '';
    };

    ## CIDR range for Kubernetes service ClusterIPs.
    serviceCIDR = lib.mkOption {
      type = lib.types.str;
      default = "10.96.0.0/12";
      description = ''
        CIDR range for Kubernetes service ClusterIPs. Must not overlap
        with the pod CIDR or the host network.
      '';
    };

    ## Kernel modules required for Kubernetes networking.
    kernelModules = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "br_netfilter"
        "overlay"
        "ip_vs"
        "ip_vs_rr"
        "ip_vs_wrr"
        "ip_vs_sh"
        "nf_conntrack"
      ];
      description = ''
        Kernel modules required for Kubernetes networking:
        - br_netfilter: allows iptables to see bridged traffic
        - overlay: required for containerd's overlayfs snapshotter
        - ip_vs*: IPVS load balancing for kube-proxy
        - nf_conntrack: connection tracking for NAT and services
      '';
    };

    ## Sysctl parameters required for Kubernetes networking.
    sysctl = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        "net.bridge.bridge-nf-call-iptables" = "1";
        "net.bridge.bridge-nf-call-ip6tables" = "1";
        "net.ipv4.ip_forward" = "1";
      };
      description = ''
        Sysctl parameters required for Kubernetes networking. Bridge
        netfilter settings allow iptables rules to apply to bridged
        traffic (required for kube-proxy and most CNI plugins).
        IP forwarding is required for pod-to-pod traffic across nodes.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    system.checks.k8s-networking = {
      description = "Kubernetes network prerequisites checks";
      checks = [
        {
          name = "ip-forward";
          description = "IP forwarding is enabled";
          script = ''
            assert_output_contains "cat /proc/sys/net/ipv4/ip_forward" "1" \
              "IP forwarding is enabled"
          '';
        }
        {
          name = "bridge-nf-call";
          description = "Bridge netfilter call is enabled";
          script = ''
            assert_output_contains "cat /proc/sys/net/bridge/bridge-nf-call-iptables" "1" \
              "Bridge netfilter call is enabled"
          '';
        }
      ];
    };

    environment.systemPackages = [pkgs.cni-plugins];

    # /etc/modules-load.d/k8s.conf — kernel modules to load at boot.
    environment.etc."modules-load.d/k8s.conf" = {
      text = ''
        # Kubernetes networking kernel modules.
        # Generated by modules/kubernetes/network.nix
        ${builtins.concatStringsSep "\n" cfg.kernelModules}
      '';
    };

    # /etc/sysctl.d/90-k8s-networking.conf — Kubernetes sysctl parameters.
    environment.etc."sysctl.d/90-k8s-networking.conf" = {
      text = ''
        # Kubernetes networking sysctl parameters.
        # Generated by modules/kubernetes/network.nix

        ${sysctlText}
      '';
    };

    # systemd service to load kernel modules at boot.
    systemd.services."k8s-modules-load" = {
      description = "Load Kubernetes Networking Kernel Modules";
      wantedBy = ["multi-user.target"];
      before = [
        "containerd.service"
        "kubelet.service"
      ];
      after = ["systemd-modules-load.service"];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = builtins.map (mod: "${pkgs.kmod}/sbin/modprobe ${mod}") cfg.kernelModules;
      };
    };

    # Apply bridge sysctls after br_netfilter is loaded. The
    # net.bridge.bridge-nf-call-* parameters only exist in /proc once
    # br_netfilter is present, so systemd-sysctl.service (which runs
    # during sysinit) cannot apply them. This unit re-applies just the
    # k8s sysctl file after the modules are in place.
    systemd.services."k8s-sysctl" = {
      description = "Apply Kubernetes Network Sysctls";
      wantedBy = ["multi-user.target"];
      after = ["k8s-modules-load.service"];
      before = [
        "containerd.service"
        "kubelet.service"
      ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.systemd}/lib/systemd/systemd-sysctl /etc/sysctl.d/90-k8s-networking.conf";
      };
    };

    # Set the firewall forward policy to "accept" for Kubernetes nodes.
    # Pod-to-pod traffic traverses the forward chain and must be allowed.
    aos.firewall.forwardPolicy = "accept";

    # Add pod and service CIDRs to trusted networks in nftables.
    # This ensures pod traffic is not dropped by the input chain.
    aos.firewall.trustedInterfaces = [
      "lo"
      "cni0"
      "flannel.1"
      "cilium_host"
      "cilium_net"
      "lxc*"
      "veth*"
    ];

    # Cilium CNI ports.
    aos.firewall.allowedTCP = [
      4240 # Cilium health checks
      4244 # Hubble relay
    ];

    # VXLAN overlay network (Flannel/Cilium).
    aos.firewall.allowedUDP = [
      8472
    ];
  };
}
