##! Exercises additional A-G command tools with generated and malformed data.
{testing}: {
  acpica = testing.mkQualificationPackageProbe {
    name = "acpica";
    spec = {
      schema_version = "aos.release.package-probe/v1";
      package = "acpica";
      primary = {
        input = "An ACPI secondary-system-description table containing an integer name.";
        operation = "Compile the ASL table to AML, then disassemble the generated bytecode.";
        expected = "Iasl accepts both source and generated AML representations.";
        files."probe.asl" = ''
          DefinitionBlock ("", "SSDT", 2, "AOS", "PROBE", 1)
          {
              Name (ANSR, 42)
          }
        '';
        steps = [
          {
            argv = ["@out@/bin/iasl" "-p" "probe" "probe.asl"];
            exit_code = 0;
          }
          {
            argv = ["@out@/bin/iasl" "-d" "probe.aml"];
            exit_code = 0;
          }
        ];
        artifacts = [];
      };
      bad_input = {
        input = "An ASL table containing an unterminated Name declaration.";
        operation = "Compile the malformed ASL source with iasl.";
        expected = "Iasl rejects the syntax error with a failure status and diagnostic.";
        files."invalid.asl" = ''
          DefinitionBlock ("", "SSDT", 2, "AOS", "BAD", 1)
          {
              Name (ANSR,
          }
        '';
        steps = [
          {
            argv = ["@out@/bin/iasl" "-p" "invalid" "invalid.asl"];
            exit_code = 255;
            observes_rejection = true;
          }
        ];
        artifacts = [];
      };
    };
  };

  cpio = testing.mkQualificationPackageProbe {
    name = "cpio";
    spec = {
      schema_version = "aos.release.package-probe/v1";
      package = "cpio";
      primary = {
        input = "A file name and payload to store in a newc archive.";
        operation = "Create the archive from the name list, then list its stored member.";
        expected = "Cpio emits the exact archived path when reading its own archive.";
        files."payload.txt" = "cpio payload\n";
        steps = [
          {
            argv = ["@out@/bin/cpio" "--create" "--format=newc" "--file=archive.cpio"];
            stdin = "payload.txt\n";
            exit_code = 0;
          }
          {
            argv = ["@out@/bin/cpio" "--list" "--file=archive.cpio"];
            exit_code = 0;
            stdout.exact = "payload.txt\n";
          }
        ];
        artifacts = [];
      };
      bad_input = {
        input = "A text file that is not any supported cpio archive format.";
        operation = "List members from the malformed archive.";
        expected = "Cpio rejects the invalid archive with status 2.";
        files."invalid.cpio" = "not a cpio archive\n";
        steps = [
          {
            argv = ["@out@/bin/cpio" "--list" "--file=invalid.cpio"];
            exit_code = 2;
            stdout.exact = "";
            observes_rejection = true;
          }
        ];
        artifacts = [];
      };
    };
  };

  dnsmasq = testing.mkQualificationPackageProbe {
    name = "dnsmasq";
    spec = {
      schema_version = "aos.release.package-probe/v1";
      package = "dnsmasq";
      primary = {
        input = "A self-contained dnsmasq configuration with DNS and DHCP disabled.";
        operation = "Parse and validate the configuration with dnsmasq's test mode.";
        expected = "Dnsmasq accepts the configuration without starting a daemon.";
        files."dnsmasq.conf" = ''
          port=0
          no-dhcp-interface=*
          log-facility=-
        '';
        steps = [
          {
            argv = ["@out@/sbin/dnsmasq" "--test" "--conf-file=dnsmasq.conf"];
            exit_code = 0;
          }
        ];
        artifacts = [];
      };
      bad_input = {
        input = "A dnsmasq configuration containing an unknown directive.";
        operation = "Parse the malformed configuration in test mode.";
        expected = "Dnsmasq rejects the unknown directive with status 1.";
        files."invalid.conf" = "aos-not-a-dnsmasq-option=42\n";
        steps = [
          {
            argv = ["@out@/sbin/dnsmasq" "--test" "--conf-file=invalid.conf"];
            exit_code = 1;
            observes_rejection = true;
          }
        ];
        artifacts = [];
      };
    };
  };

  dosfstools = testing.mkQualificationPackageProbe {
    name = "dosfstools";
    spec = {
      schema_version = "aos.release.package-probe/v1";
      package = "dosfstools";
      primary = {
        input = "A request for a sparse 1 MiB FAT filesystem image.";
        operation = "Create the image with mkfs.fat and validate it read-only with fsck.fat.";
        expected = "Both filesystem construction and consistency checking succeed.";
        files = {};
        steps = [
          {
            argv = ["@out@/sbin/mkfs.fat" "-C" "filesystem.img" "1024"];
            exit_code = 0;
          }
          {
            argv = ["@out@/sbin/fsck.fat" "-n" "filesystem.img"];
            exit_code = 0;
          }
        ];
        artifacts = [];
      };
      bad_input = {
        input = "A request for a one-block image, below the minimum FAT filesystem size.";
        operation = "Attempt to construct the undersized filesystem.";
        expected = "Mkfs.fat rejects the size with status 1.";
        files = {};
        steps = [
          {
            argv = ["@out@/sbin/mkfs.fat" "-C" "undersized.img" "1"];
            exit_code = 1;
            observes_rejection = true;
          }
        ];
        artifacts = [];
      };
    };
  };

  fastjar = testing.mkQualificationPackageProbe {
    name = "fastjar";
    spec = {
      schema_version = "aos.release.package-probe/v1";
      package = "fastjar";
      primary = {
        input = "A named text entry to package in a Java archive.";
        operation = "Create a JAR with fastjar and list the archive directory.";
        expected = "Fastjar reports the manifest and exact payload member.";
        files."entry.txt" = "jar payload\n";
        steps = [
          {
            argv = ["@out@/bin/fastjar" "cf" "archive.jar" "entry.txt"];
            exit_code = 0;
            stdout.exact = "";
            stderr.exact = "";
          }
          {
            argv = ["@out@/bin/fastjar" "tf" "archive.jar"];
            exit_code = 0;
            stdout.exact = "META-INF/\nMETA-INF/MANIFEST.MF\nentry.txt\n";
            stderr.exact = "";
          }
        ];
        artifacts = [];
      };
      bad_input = {
        input = "A text file that is not a ZIP/JAR archive.";
        operation = "List the malformed archive with fastjar.";
        expected = "Fastjar rejects the invalid archive with status 1.";
        files."invalid.jar" = "not a jar archive\n";
        steps = [
          {
            argv = ["@out@/bin/fastjar" "tf" "invalid.jar"];
            exit_code = 1;
            stdout.exact = "";
            observes_rejection = true;
          }
        ];
        artifacts = [];
      };
    };
  };

  git-lfs = testing.mkQualificationPackageProbe {
    name = "git-lfs";
    spec = {
      schema_version = "aos.release.package-probe/v1";
      package = "git-lfs";
      primary = {
        input = "A fixed 17-byte object to encode as a Git LFS pointer.";
        operation = "Generate the pointer with git-lfs pointer --file.";
        expected = "Git LFS emits the exact canonical pointer document.";
        files."object.bin" = "AOS large object\n";
        steps = [
          {
            argv = ["@out@/bin/git-lfs" "pointer" "--file=object.bin"];
            exit_code = 0;
            stdout.exact = ''
              version https://git-lfs.github.com/spec/v1
              oid sha256:87adda3b1671602f7e758e5ed8c1dfa5f1dffe89e9bcfbd7540b6c4ffb6d94a4
              size 17
            '';
            stderr.exact = "Git LFS pointer for object.bin\n\n";
          }
        ];
        artifacts = [];
      };
      bad_input = {
        input = "A pointer document with a nonnumeric size.";
        operation = "Validate the malformed document in strict pointer-check mode.";
        expected = "Git LFS rejects the malformed pointer with status 1.";
        files."invalid.pointer" = ''
          version https://git-lfs.github.com/spec/v1
          oid sha256:87adda3b1671602f7e758e5ed8c1dfa5f1dffe89e9bcfbd7540b6c4ffb6d94a4
          size seventeen
        '';
        steps = [
          {
            argv = ["@out@/bin/git-lfs" "pointer" "--check" "--strict" "--file=invalid.pointer"];
            exit_code = 1;
            stdout.exact = "";
            observes_rejection = true;
          }
        ];
        artifacts = [];
      };
    };
  };

  gperf = testing.mkQualificationPackageProbe {
    name = "gperf";
    spec = {
      schema_version = "aos.release.package-probe/v1";
      package = "gperf";
      primary = {
        input = "Two distinct keywords with associated integer values.";
        operation = "Generate a C lookup table, compile a consumer, and query both keywords.";
        expected = "The generated perfect hash maps each keyword to its declared value.";
        files."keywords.gperf" = ''
          %{
          #include <string.h>
          %}
          struct keyword { const char *name; int value; };
          %%
          alpha, 19
          beta, 23
          %%
        '';
        files."consumer.c" = ''
          #include <stdio.h>
          #include <string.h>
          #include "keywords.c"

          int main(void) {
              const struct keyword *alpha = lookup("alpha", 5);
              const struct keyword *beta = lookup("beta", 4);
              if (alpha == NULL || beta == NULL || alpha->value + beta->value != 42) {
                  return 2;
              }
              return puts("gperf lookup passed") == EOF;
          }
        '';
        steps = [
          {
            argv = ["@out@/bin/gperf" "--language=C" "--struct-type" "--lookup-function-name=lookup" "--output-file=keywords.c" "keywords.gperf"];
            exit_code = 0;
            stdout.exact = "";
            stderr.exact = "";
          }
          {
            argv = ["@cc@" "consumer.c" "-o" "consumer"];
            exit_code = 0;
            stdout.exact = "";
            stderr.exact = "";
          }
          {
            argv = ["@work@/primary/consumer"];
            exit_code = 0;
            stdout.exact = "gperf lookup passed\n";
            stderr.exact = "";
          }
        ];
        artifacts = [];
      };
      bad_input = {
        input = "Two records declaring the same keyword.";
        operation = "Generate a perfect hash without duplicate-key support.";
        expected = "Gperf rejects the duplicate keyword with status 1.";
        files."duplicates.gperf" = "%%\nalpha\nalpha\n%%\n";
        steps = [
          {
            argv = ["@out@/bin/gperf" "--output-file=duplicates.c" "duplicates.gperf"];
            exit_code = 1;
            stdout.exact = "";
            observes_rejection = true;
          }
        ];
        artifacts = [];
      };
    };
  };
}
