[package]
name = "crucible-shmem"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
blake3 = { workspace = true }
libc = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
