[package]
name = "terrane"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
terrane-core.workspace = true
async-trait.workspace = true
serde.workspace = true
toml.workspace = true
zstd.workspace = true
blake3.workspace = true
xattr = { version = "=1.6.1", optional = true }
libc = { workspace = true, optional = true }

reqwest = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["dep:xattr", "dep:libc"]
surface-sdk = ["std"]
send = []
tokio = ["std", "send", "dep:tokio", "dep:reqwest"]
wasm = []

[lints]
workspace = true
