# stdenv/toolchains/gcc14/glibc.nix - glibc 2.39 (RHEL 10)
#
# Modern glibc built with THIS tier's GCC 14.3.0 + binutils 2.41 +
# linux-headers 6.12. Production C library for all downstream packages.
{
  prev,
  gcc,
  binutils,
  linuxHeaders,
  buildPlatform,
  hostPlatform,
}: let
  # Control-flow Enforcement Technology is x86-only in glibc 2.39. Plain
  # --enable-cet (not permissive): a CET-enabled AOS process loading a
  # non-CET AOS DSO is a bug to fix, not a compatibility case to preserve.
  cetFlag =
    if hostPlatform.isx86_64
    then "--enable-cet"
    else "";
in
  import ../lib/mk-glibc.nix {
    inherit
      prev
      gcc
      binutils
      linuxHeaders
      buildPlatform
      hostPlatform
      ;
  } {
    version = "2.39";
    url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.39.tar.xz";
    sha256 = "0zr0lk75rvkxp0xplfsggaj4fcv1xjpsvg5qrvp6yifim77q2mn0";
    outputs = ["out" "bin" "dev" "static" "getent"];
    useCxx = true;
    cflags = "-O2";
    cc = "$TMPDIR/ccwrap/gcc";
    cxx = "$TMPDIR/ccwrap/g++";
    withHeaders = "${linuxHeaders}";
    linuxHeadersSource = "${linuxHeaders}";
    copyLinuxHeaders = false;
    extraPathDeps = [
      prev.bison
      prev.m4
      prev.python3
    ];
    configureFlags =
      [
        "--disable-profile"
        "--disable-nscd"
        "--disable-timezone-tools"
        "--disable-werror"
        "--enable-static-nss"
        "--without-gd"
        "--without-selinux"
      ]
      ++ (
        if cetFlag != ""
        then [cetFlag]
        else []
      );
    configureCacheVars = [
      "libc_cv_forced_unwind=yes"
      "libc_cv_c_cleanup=yes"
    ];
    preConfigure = ''
      # CC wrapper: supplies the include paths that gccRaw's specs file used
      # to embed (scrubbed to keep gccRaw's $out off the pre-tier chain).
      mkdir -p "$TMPDIR/ccwrap"
      cat > "$TMPDIR/ccwrap/gcc" <<AOS_GLIBC_CC
      #!${prev.bash}/bin/bash
      exec ${gcc}/bin/gcc -idirafter ${prev.glibc}/include -idirafter ${prev.linuxHeaders} "\$@"
      AOS_GLIBC_CC
      cat > "$TMPDIR/ccwrap/g++" <<AOS_GLIBC_CXX
      #!${prev.bash}/bin/bash
      exec ${gcc}/bin/g++ -idirafter ${prev.glibc}/include -idirafter ${prev.linuxHeaders} "\$@"
      AOS_GLIBC_CXX
      chmod +x "$TMPDIR/ccwrap/gcc" "$TMPDIR/ccwrap/g++"
    '';
    splitOutputs = ''
      # The default install lands everything under $out. Move headers, static
      # archives, programs, and locale source data into separate outputs.

      # 1. Headers -> $dev
      mkdir -p "$dev"
      mv "$out/include" "$dev/include"

      # Copy linux headers into glibc's $dev/include for downstream use.
      cp -r "${linuxHeaders}/linux" "$dev/include/" 2>/dev/null || true
      cp -r "${linuxHeaders}/asm" "$dev/include/" 2>/dev/null || true
      cp -r "${linuxHeaders}/asm-generic" "$dev/include/" 2>/dev/null || true

      # 2. Static archives -> $static (except *_nonshared.a)
      mkdir -p "$static/lib"
      mv "$out"/lib/*.a "$static/lib/"

      # libc_nonshared.a (and libpthread_nonshared.a on glibcs older than
      # 2.34) are required at link time even for dynamically-linked binaries.
      mv "$static/lib/libc_nonshared.a" "$out/lib/libc_nonshared.a"
      if [ -f "$static/lib/libpthread_nonshared.a" ]; then
        mv "$static/lib/libpthread_nonshared.a" "$out/lib/libpthread_nonshared.a"
      fi

      # 3. Linker-script .a fixup.
      ${prev.sed}/bin/sed "/^GROUP/s|$out/lib/lib|$static/lib/lib|g" -i "$static/lib"/*.a

      # 4. Locale source data -> $bin (consumed by localedef)
      mkdir -p "$bin/share"
      if [ -d "$out/share/i18n" ]; then
        mv "$out/share/i18n" "$bin/share/i18n"
      fi

      # 5. Programs -> $bin, getent -> $getent
      mkdir -p "$bin/bin" "$bin/sbin" "$getent/bin"
      if [ -d "$out/bin" ]; then
        if [ -f "$out/bin/getent" ]; then
          mv "$out/bin/getent" "$getent/bin/getent"
        fi
        for f in "$out/bin"/*; do
          [ -e "$f" ] && mv "$f" "$bin/bin/"
        done
        rmdir "$out/bin"
      fi
      if [ -d "$out/sbin" ]; then
        for f in "$out/sbin"/*; do
          [ -e "$f" ] && mv "$f" "$bin/sbin/"
        done
        rmdir "$out/sbin"
      fi

      # 6. Drop sln (statically-linked ln replacement, about 50 KB).
      rm -f "$bin/bin/sln"

      # 7. Drop $out/var stub and ld.so.cache (regenerated by ldconfig).
      test -f "$out/etc/ld.so.cache" && rm "$out/etc/ld.so.cache"
      rm -rf "$out/var"
    '';
    finalMessage = "glibc 2.39 installed to $out (+ $bin $dev $static $getent)";
    meta = {
      description = "GNU C Library 2.39 - production C library";
      homepage = "https://www.gnu.org/software/libc/";
      license = "LGPL-2.1-or-later";
      build = {
        os = "linux";
      };
      execute = {
        os = "linux";
      };
    };
  }
