//! Bound, substitution-resistant accumulation of immutable list pages.
//!
//! Every request and response retains one [`QueryBindingV1`]. Continuation
//! tokens additionally retain the immutable revision that issued them, so a
//! byte-identical token cannot be replayed under another query, principal,
//! authorization revision, visibility, sort, filter, or schema.

use std::collections::BTreeSet;

use aos_proto::aos::sandbox::v1::PageInfo;

use crate::controller_query::model::{
    ClientStateItem, InvalidQueryModel, OpaqueResponseBytesV1, OpaqueResponseKindV1,
    QueryBindingV1, checked_item_cost,
};

/// Maximum resources in one response page.
pub const MAXIMUM_PAGE_ITEMS: usize = 1_024;
/// Maximum protobuf bytes in one response page.
pub const MAXIMUM_PAGE_BYTES: usize = 16 * 1024 * 1024;
/// Maximum resources accumulated by one list operation.
pub const MAXIMUM_COLLECTED_ITEMS: usize = 65_536;
/// Maximum protobuf bytes accumulated by one list operation.
pub const MAXIMUM_COLLECTED_BYTES: usize = 64 * 1024 * 1024;
/// Maximum continuation pages accepted by one list operation.
pub const MAXIMUM_LIST_PAGES: usize = 4_096;

/// Reports invalid or non-contiguous paginated state.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum PaginationError {
    /// A caller-selected item or byte bound is zero or above its ceiling.
    #[error("pagination accumulation bound is invalid")]
    InvalidBound,
    /// A response contains invalid opaque fields or an oversized item.
    #[error("pagination response is invalid")]
    InvalidResponse,
    /// A response was produced under another normalized query binding.
    #[error("pagination response query binding changed")]
    BindingSubstitution,
    /// A response does not name the exact outstanding request token.
    #[error("pagination response does not match the outstanding token")]
    TokenSubstitution,
    /// The immutable list revision changed and a fresh list is required.
    #[error("immutable list revision changed; relist is required")]
    RevisionSubstitution,
    /// A continuation token repeats and would create an ABA cycle.
    #[error("pagination continuation token cycle detected")]
    TokenCycle,
    /// The item, byte, or page accumulation bound was reached.
    #[error("pagination accumulation bound exceeded")]
    CapacityExceeded,
    /// A page was supplied after completion.
    #[error("pagination is already complete")]
    AlreadyComplete,
}

impl From<InvalidQueryModel> for PaginationError {
    fn from(_: InvalidQueryModel) -> Self {
        Self::InvalidResponse
    }
}

/// Stores an immutable list revision bound to one normalized query.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ImmutableListRevisionV1 {
    binding: QueryBindingV1,
    bytes: OpaqueResponseBytesV1,
}

impl ImmutableListRevisionV1 {
    /// Returns the complete local query binding.
    #[must_use]
    pub const fn binding(&self) -> QueryBindingV1 {
        self.binding
    }

    /// Returns server-issued revision bytes for the matching transport field.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes.as_bytes()
    }
}

/// Stores a continuation token bound to its normalized query and list revision.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PageTokenV1 {
    binding: QueryBindingV1,
    revision: ImmutableListRevisionV1,
    bytes: OpaqueResponseBytesV1,
}

impl PageTokenV1 {
    /// Returns the complete local query binding.
    #[must_use]
    pub const fn binding(&self) -> QueryBindingV1 {
        self.binding
    }

    /// Returns the exact immutable revision that issued this token.
    #[must_use]
    pub const fn revision(&self) -> &ImmutableListRevisionV1 {
        &self.revision
    }

    /// Returns server-issued token bytes for the matching request field.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes.as_bytes()
    }
}

/// Stores one exact page request generated by a reducer.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PageRequestV1 {
    binding: QueryBindingV1,
    token: Option<PageTokenV1>,
}

impl PageRequestV1 {
    /// Returns the complete normalized query binding.
    #[must_use]
    pub const fn binding(&self) -> QueryBindingV1 {
        self.binding
    }

    /// Returns the continuation bytes, or `None` for page one.
    #[must_use]
    pub fn token_bytes(&self) -> Option<&[u8]> {
        self.token.as_ref().map(PageTokenV1::as_bytes)
    }
}

/// Stores one checked immutable-revision response page.
#[derive(Clone, Debug, PartialEq)]
pub struct ImmutableListPageV1<T> {
    request: PageRequestV1,
    revision: ImmutableListRevisionV1,
    items: Vec<T>,
    item_bytes: usize,
    next_token: Option<PageTokenV1>,
}

impl<T: ClientStateItem> ImmutableListPageV1<T> {
    /// Checks one established public `PageInfo` and its resource items.
    ///
    /// # Errors
    ///
    /// Returns [`PaginationError`] for invalid opaque fields, response bounds,
    /// revision substitution, or a continuation that makes no progress.
    pub fn from_response(
        request: PageRequestV1,
        page: PageInfo,
        items: Vec<T>,
    ) -> Result<Self, PaginationError> {
        if items.len() > MAXIMUM_PAGE_ITEMS
            || (items.is_empty() && !page.next_page_token.is_empty())
        {
            return Err(PaginationError::InvalidResponse);
        }
        let item_bytes = items.iter().try_fold(0_usize, |total, item| {
            total
                .checked_add(checked_item_cost(item)?)
                .ok_or(InvalidQueryModel::ResourceTooLarge)
        })?;
        if item_bytes > MAXIMUM_PAGE_BYTES {
            return Err(PaginationError::InvalidResponse);
        }
        let revision = ImmutableListRevisionV1 {
            binding: request.binding,
            bytes: OpaqueResponseBytesV1::from_response(
                page.immutable_list_revision,
                OpaqueResponseKindV1::ImmutableListRevision,
            )?,
        };
        if request
            .token
            .as_ref()
            .is_some_and(|token| token.revision != revision)
        {
            return Err(PaginationError::RevisionSubstitution);
        }
        let next_token = if page.next_page_token.is_empty() {
            None
        } else {
            let bytes = OpaqueResponseBytesV1::from_response(
                page.next_page_token,
                OpaqueResponseKindV1::PageToken,
            )?;
            if request
                .token
                .as_ref()
                .is_some_and(|token| token.bytes == bytes)
            {
                return Err(PaginationError::TokenCycle);
            }
            Some(PageTokenV1 {
                binding: request.binding,
                revision: revision.clone(),
                bytes,
            })
        };
        Ok(Self {
            request,
            revision,
            items,
            item_bytes,
            next_token,
        })
    }

    /// Returns the request binding carried by this response.
    #[must_use]
    pub const fn binding(&self) -> QueryBindingV1 {
        self.request.binding
    }

    /// Returns the immutable response revision.
    #[must_use]
    pub const fn revision(&self) -> &ImmutableListRevisionV1 {
        &self.revision
    }

    /// Returns checked resources carried by this page.
    #[must_use]
    pub fn items(&self) -> &[T] {
        &self.items
    }

    /// Returns the checked aggregate encoded byte cost.
    #[must_use]
    pub const fn item_bytes(&self) -> usize {
        self.item_bytes
    }
}

/// Reports a successful immutable-page reduction.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PageApplyOutcomeV1 {
    /// Another request is available from [`PaginationReducerV1::request`].
    Continue,
    /// The complete immutable list is now available.
    Complete,
}

/// Accumulates one bounded immutable list without transport effects.
#[derive(Clone, Debug, PartialEq)]
pub struct PaginationReducerV1<T> {
    binding: QueryBindingV1,
    maximum_items: usize,
    maximum_bytes: usize,
    revision: Option<ImmutableListRevisionV1>,
    expected_token: Option<PageTokenV1>,
    seen_tokens: BTreeSet<OpaqueResponseBytesV1>,
    items: Vec<T>,
    item_bytes: usize,
    pages: usize,
    complete: bool,
}

impl<T> PaginationReducerV1<T> {
    /// Creates an empty reducer for one complete normalized query binding.
    ///
    /// # Errors
    ///
    /// Returns [`PaginationError::InvalidBound`] for zero or excessive item
    /// and byte bounds.
    pub fn new(
        binding: QueryBindingV1,
        maximum_items: usize,
        maximum_bytes: usize,
    ) -> Result<Self, PaginationError> {
        if maximum_items == 0
            || maximum_items > MAXIMUM_COLLECTED_ITEMS
            || maximum_bytes == 0
            || maximum_bytes > MAXIMUM_COLLECTED_BYTES
        {
            return Err(PaginationError::InvalidBound);
        }
        Ok(Self {
            binding,
            maximum_items,
            maximum_bytes,
            revision: None,
            expected_token: None,
            seen_tokens: BTreeSet::new(),
            items: Vec::new(),
            item_bytes: 0,
            pages: 0,
            complete: false,
        })
    }

    /// Resumes from a CLI-retained binding, immutable revision, and token.
    ///
    /// These values are continuation metadata, not authority. The next
    /// authenticated response must carry the same complete binding and exact
    /// immutable revision, while the server independently authenticates the
    /// opaque token before returning any page.
    ///
    /// # Errors
    ///
    /// Returns [`PaginationError`] for invalid bounds, empty or oversized
    /// opaque values, or a malformed retained continuation.
    pub fn resume(
        binding: QueryBindingV1,
        immutable_revision: Vec<u8>,
        page_token: Vec<u8>,
        maximum_items: usize,
        maximum_bytes: usize,
    ) -> Result<Self, PaginationError> {
        let mut reducer = Self::new(binding, maximum_items, maximum_bytes)?;
        let revision = ImmutableListRevisionV1 {
            binding,
            bytes: OpaqueResponseBytesV1::from_response(
                immutable_revision,
                OpaqueResponseKindV1::ImmutableListRevision,
            )?,
        };
        let token_bytes =
            OpaqueResponseBytesV1::from_response(page_token, OpaqueResponseKindV1::PageToken)?;
        let token = PageTokenV1 {
            binding,
            revision: revision.clone(),
            bytes: token_bytes.clone(),
        };
        reducer.revision = Some(revision);
        reducer.expected_token = Some(token);
        reducer.seen_tokens.insert(token_bytes);
        Ok(reducer)
    }

    /// Returns the only valid request for the next response page.
    #[must_use]
    pub fn request(&self) -> Option<PageRequestV1> {
        (!self.complete).then(|| PageRequestV1 {
            binding: self.binding,
            token: self.expected_token.clone(),
        })
    }

    /// Returns the pinned immutable revision after page one.
    #[must_use]
    pub const fn revision(&self) -> Option<&ImmutableListRevisionV1> {
        self.revision.as_ref()
    }

    /// Returns the checked accumulated protobuf byte cost.
    #[must_use]
    pub const fn item_bytes(&self) -> usize {
        self.item_bytes
    }

    /// Returns resources only after the terminal page was accepted.
    #[must_use]
    pub fn complete_items(&self) -> Option<&[T]> {
        self.complete.then_some(self.items.as_slice())
    }

    /// Consumes and returns the complete immutable list.
    ///
    /// # Errors
    ///
    /// Returns [`PaginationError::InvalidResponse`] before completion.
    pub fn into_complete_items(self) -> Result<Vec<T>, PaginationError> {
        if self.complete {
            Ok(self.items)
        } else {
            Err(PaginationError::InvalidResponse)
        }
    }

    /// Applies exactly the response to [`Self::request`].
    ///
    /// Binding and token conflicts take precedence over revision and capacity
    /// conflicts so an attacker cannot use aggregate errors to probe state from
    /// another authorization scope.
    ///
    /// # Errors
    ///
    /// Returns [`PaginationError`] without mutating state for any substitution,
    /// cycle, capacity exhaustion, or post-completion input.
    pub fn apply(
        &mut self,
        page: ImmutableListPageV1<T>,
    ) -> Result<PageApplyOutcomeV1, PaginationError> {
        if self.complete {
            return Err(PaginationError::AlreadyComplete);
        }
        if page.request.binding != self.binding {
            return Err(PaginationError::BindingSubstitution);
        }
        if page.request.token != self.expected_token {
            return Err(PaginationError::TokenSubstitution);
        }
        if self
            .revision
            .as_ref()
            .is_some_and(|revision| revision != &page.revision)
        {
            return Err(PaginationError::RevisionSubstitution);
        }
        if page
            .next_token
            .as_ref()
            .is_some_and(|token| self.seen_tokens.contains(&token.bytes))
        {
            return Err(PaginationError::TokenCycle);
        }
        let resulting_items = self
            .items
            .len()
            .checked_add(page.items.len())
            .ok_or(PaginationError::CapacityExceeded)?;
        let resulting_bytes = self
            .item_bytes
            .checked_add(page.item_bytes)
            .ok_or(PaginationError::CapacityExceeded)?;
        if self.pages >= MAXIMUM_LIST_PAGES
            || resulting_items > self.maximum_items
            || resulting_bytes > self.maximum_bytes
        {
            return Err(PaginationError::CapacityExceeded);
        }

        if self.revision.is_none() {
            self.revision = Some(page.revision);
        }
        self.items.extend(page.items);
        self.item_bytes = resulting_bytes;
        self.pages += 1;
        match page.next_token {
            Some(token) => {
                self.seen_tokens.insert(token.bytes.clone());
                self.expected_token = Some(token);
                Ok(PageApplyOutcomeV1::Continue)
            }
            None => {
                self.expected_token = None;
                self.complete = true;
                Ok(PageApplyOutcomeV1::Complete)
            }
        }
    }
}
