[package]
name = "crucible-cas"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "crucible-fleet-store"
path = "src/bin/crucible-fleet-store.rs"

[dependencies]
aes-gcm = { workspace = true, features = ["zeroize"] }
blake3 = { workspace = true }
rustix = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
