##! Package-owned polkit authorization service.
{
  abilitySelection ? null,
  config,
  lib,
  ...
}: let
  cfg = config.aos.security.polkit;
  availabilityAlias = "authorization-service-availability";
  availabilitySelected =
    abilitySelection
    != null
    && abilitySelection.isImplementationSelected availabilityAlias;
  active = cfg.enable || availabilitySelected;
  abilityTypes = lib.abilities.types;
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  serviceTypes = serviceManagement.types;
  interfaces = serviceManagement.interfaces;
  resultOf = lib.abilities.resultOf;
  consumerInstance = "polkit";
  producer = key: interface: parameters:
    serviceManagement.forProducer {
      inherit consumerInstance key interface parameters;
    };
  group = producer "service-group" interfaces.groupResolution {
    name = "polkitd";
    allocation = "managed";
    requested_id = 27;
  };
  principal = producer "service-principal" interfaces.principalResolution {
    name = "polkitd";
    allocation = "managed";
    requested_id = 27;
    description = "PolicyKit daemon";
    home_directory = "/var/lib/polkit-1";
    login_access = "disabled";
    primary_group = resultOf "service-group" "group-name";
    supplementary_groups = [];
  };
  localFilesystems = producer "local-filesystems" interfaces.filesystemReadiness {
    scope = "local-filesystems";
  };
  systemBusAvailability = {
    requirementTemplates.system-bus-availability =
      lib.abilities.interfaceSelector {
        name = "aos.dbus.system-bus-availability";
        abi = 1;
      }
      // {
        description = "Requires the configured system message bus.";
        methods = ["observe"];
        guarantees = [];
        strength = "required";
        fallback = null;
      };
    requests.system-bus-availability = {
      requirement = "system-bus-availability";
      consumer = consumerInstance;
      scope = ["system-bus"];
      parameters.scope = "system-bus";
    };
  };
  rulesConfiguration = serviceManagement.forConfiguration {
    inherit serviceTypes consumerInstance;
    declaration = {
      name = "local-rules-source";
      source = {
        kind = "inline-text";
        content = ''
          // Generated by the package-owned polkit ability module.
          ${lib.concatStringsSep "\n\n" cfg.extraRules}
        '';
      };
      mode = "0640";
    };
  };
  configurationFiles = serviceManagement.forProducers {
    inherit consumerInstance;
    interface = interfaces.filesystemEntry;
    methods = ["materialize" "observe" "release"];
    producers = [
      {
        key = "local-rules-file";
        parameters = {
          name = "polkit-local-rules";
          entry = {
            kind = "copied-file";
            source = {
              kind = "execution-path";
              resource = resultOf "local-rules-source" "resource";
              path = resultOf "local-rules-source" "planned-path";
            };
            maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
          };
          destination = "/etc/polkit-1/rules.d/10-aos.rules";
          owner = "root";
          group = resultOf "service-group" "group-name";
          mode = "0640";
          prerequisites = [
            (resultOf "local-rules-source" "resource")
            (resultOf "local-filesystems" "resource")
          ];
        };
      }
      {
        key = "packaged-actions-file";
        parameters = {
          name = "polkit-packaged-actions";
          entry = {
            kind = "copied-file";
            source = {
              kind = "artifact-file";
              reference = {
                artifact = lib.abilities.packageOutput {};
                path = "share/polkit-1/actions/org.freedesktop.policykit.policy";
              };
            };
            maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
          };
          destination = "/etc/polkit-1/actions/org.freedesktop.policykit.policy";
          owner = "root";
          group = "root";
          mode = "0444";
          prerequisites = [(resultOf "local-filesystems" "resource")];
        };
      }
    ];
  };
  privilegedWrappers = serviceManagement.forProducers {
    inherit consumerInstance;
    interface = interfaces.privilegedExecutable;
    methods = ["observe"];
    producers =
      builtins.map (wrapper: {
        key = "wrapper-${wrapper.name}";
        parameters = {
          inherit (wrapper) name;
          source = {
            artifact = lib.abilities.packageOutput {};
            path = wrapper.path;
          };
          owner = "root";
          group = "root";
          mode = "4755";
          maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
        };
      }) [
        {
          name = "pkexec";
          path = "bin/pkexec";
        }
        {
          name = "polkit-agent-helper-1";
          path = "lib/polkit-1/polkit-agent-helper-1";
        }
      ];
  };
  service = serviceManagement.forService {
    featureContributions = [
      (serviceManagement.featureContribution {
        key = "device_policy";
        requirementAlias = "service-device-policy";
        description = "Requires the selected service-management provider to enforce the declared device access policy.";
        interface = "aos.service.device-policy";
        abi = 1;
        parameters = {
          baseline_access = "declared-devices-only";
          rules = [
            {
              selector = {
                kind = "number";
                device_type = "character";
                major = 1;
                minor = 3;
              };
              read = true;
              write = true;
              create = false;
            }
          ];
        };
      })
      (serviceManagement.featureContribution {
        key = "hardening";
        requirementAlias = "service-hardening";
        description = "Requires the selected service-management provider to enforce the declared service hardening policy.";
        interface = "aos.service.hardening";
        abi = 1;
        parameters = {
          allow_privilege_escalation = false;
          ambient_privileges = [];
          privilege_bounds = {
            kind = "restricted";
            privileges = ["change-user-identity" "change-group-identity"];
          };
          resource_control_delegation = false;
          resource_control_access = "read-only";
          device_access_scope = "private";
          host_clock_mutation = false;
          host_name_mutation = false;
          operating_system_log_access = false;
          operating_system_extension_access = false;
          operating_system_tunable_access = false;
          lock_execution_personality = true;
          writable_executable_memory = false;
          remove_interprocess_communication = true;
          isolation_domains = ["filesystem" "network"];
          network_families = ["local"];
          memory_pressure_adjustment = 0;
          permit_realtime = false;
          permit_elevated_file_identity = false;
          process_visibility = "self";
          operation_architectures = ["native"];
          operation_allow = [];
          operation_deny = [];
          operation_profile = "system-service";
          isolated_identity_mapping = "none";
        };
      })
    ];
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "polkit";
      enabled = true;
      lifecycle = {
        description = "Authorization Manager";
        execution_model = "foreground";
        environment_files = [];
        condition = [];
        pre_start = [];
        start = [
          {
            executable = {
              artifact = lib.abilities.packageOutput {};
              entry_point = "lib/polkit-1/polkitd";
              arguments = ["--no-debug" "--log-level=notice"];
            };
            ignore_failure = false;
          }
        ];
        post_start = [];
        stop = [];
        post_stop = [];
        restart = "on-failure";
        restart_delay_millis = 100;
        configuration_change_action = "reload";
        remain_after_exit = false;
        start_timeout_millis = 90000;
        stop_timeout_millis = 90000;
      };
      dependencies = {
        after = [
          (resultOf "system-bus-availability" "resource")
        ];
        before = [];
        requires = [(resultOf "system-bus-availability" "resource")];
        wants = [];
        prerequisites = [
          (resultOf "local-rules-file" "resource")
          (resultOf "packaged-actions-file" "resource")
        ];
      };
      supervision = {
        startup_protocol = "notification";
        notification_access = "main-process";
      };
      reload = {
        strategy = "signal";
        commands = [];
        signal = "HUP";
        completion = "command-exit";
      };
      directories.managed = [
        {
          path = "polkit-1";
          purpose = "state";
          mode = "0700";
          retention = "persistent";
          owner = resultOf "service-principal" "principal-name";
          group = resultOf "service-group" "group-name";
        }
        {
          path = "polkit-1";
          purpose = "runtime";
          mode = "0750";
          retention = "restart";
          owner = resultOf "service-principal" "principal-name";
          group = resultOf "service-group" "group-name";
        }
      ];
      identity = {
        principal = resultOf "service-principal" "principal-name";
        primary_group = resultOf "service-group" "group-name";
        supplementary_groups = [];
        ephemeral = false;
        file_creation_mask = "0077";
      };
      isolation = {
        privilege = "unprivileged";
        filesystem = "read-only-system";
        home_access = "inaccessible";
        network = "none";
        process_visibility = "private";
        termination_scope = "all-processes";
        temporary_directory = "private";
        devices = [];
        host_paths = [];
        permit_core_dumps = false;
      };
      resources = {
        locked_memory_bytes = {
          kind = "maximum";
          value = 0;
        };
        memory_max_bytes = {
          kind = "maximum";
          value = 33554432;
        };
        memory_swap_max_bytes = {
          kind = "maximum";
          value = 33554432;
        };
        oom_policy = "stop";
      };
    };
  };
  fragments = [
    group
    principal
    localFilesystems
    systemBusAvailability
    rulesConfiguration
    configurationFiles
    privilegedWrappers
    service
  ];
  contributions = builtins.map serviceManagement.splitContribution fragments;
in {
  imports = [
    ./availability-interface.nix
    ./dbus-registration.nix
  ];

  options.aos.security.polkit = {
    enable = lib.mkOption {
      type = abilityTypes.boolean;
      default = false;
      description = "Run polkit and install its authorization tools.";
    };
    extraRules = lib.mkOption {
      type = abilityTypes.list {
        element = abilityTypes.string {
          maxLength = abilityTypes.limits.maxStringLength;
          syntax = null;
        };
        maxItems = abilityTypes.limits.maxCollectionItems;
      };
      default = [];
      description = "JavaScript authorization rules loaded after packaged policy.";
    };
  };

  config = lib.mkMerge [
    {aos.abilities = lib.mkMerge (builtins.map (entry: entry.declarations) contributions);}
    (lib.mkIf active {
      aos.contributions = {
        pamServices."polkit-1" = {
          unixAuth = true;
          startSession = false;
          setLoginUid = false;
        };
      };
      aos.abilities = lib.mkMerge (
        [
          {
            instances = {
              ${availabilityAlias} = {};
              ${consumerInstance} = {};
            };
          }
          {
            runtimeChecks.polkit = {
              description = "polkit policy and privilege checks";
              checks = [
                {
                  name = "polkit-policy";
                  description = "polkit answers through D-Bus with packaged actions and local rules";
                  script = ''
                    vm.wait_until_succeeds(
                        "pkaction | grep -Fx org.freedesktop.policykit.exec", timeout=30
                    )
                    vm.succeed("grep -Fq 'Generated by the package-owned polkit ability module' /etc/polkit-1/rules.d/10-aos.rules")
                    vm.succeed("grep -q pam_unix.so /etc/pam.d/polkit-1")
                  '';
                }
                {
                  name = "polkit-wrappers";
                  description = "polkit privileged entry points are root-owned setuid wrappers";
                  script = ''
                    vm.wait_until_succeeds("test -u /run/wrappers/bin/pkexec", timeout=30)
                    vm.succeed("test -u /run/wrappers/bin/polkit-agent-helper-1")
                    vm.succeed("test $(stat -c %u:%g /run/wrappers/bin/pkexec) = 0:0")
                  '';
                }
              ];
            };
          }
        ]
        ++ builtins.map (entry: entry.configured) contributions
      );
    })
  ];
}
