##! Package-owned polkit authorization service.
{
  config,
  lib,
  ...
}: let
  cfg = config.aos.security.polkit;
  abilityTypes = lib.abilities.types;
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  serviceTypes = serviceManagement.types;
  interfaces = serviceManagement.interfaces;
  resultOf = lib.abilities.resultOf;
  consumerInstance = "polkit";
  producer = key: interface: parameters:
    serviceManagement.forProducer {
      inherit consumerInstance key interface parameters;
    };
  group = producer "service-group" interfaces.groupResolution {
    name = "polkitd";
    allocation = "managed";
    requested_id = 27;
  };
  principal = producer "service-principal" interfaces.principalResolution {
    name = "polkitd";
    allocation = "managed";
    requested_id = 27;
    description = "PolicyKit daemon";
    home_directory = "/var/lib/polkit-1";
    login_access = "disabled";
    primary_group = resultOf "service-group" "group-name";
    supplementary_groups = [];
  };
  localFilesystems = producer "local-filesystems" interfaces.filesystemReadiness {
    scope = "local-filesystems";
  };
  rulesConfiguration = serviceManagement.forConfiguration {
    inherit serviceTypes consumerInstance;
    declaration = {
      name = "local-rules-source";
      source = {
        kind = "inline-text";
        content = ''
          // Generated by the package-owned polkit ability module.
          ${lib.concatStringsSep "\n\n" cfg.extraRules}
        '';
      };
      mode = "0640";
    };
  };
  configurationFiles = serviceManagement.forProducers {
    inherit consumerInstance;
    interface = interfaces.filesystemEntry;
    methods = ["materialize" "observe" "release"];
    producers = [
      {
        key = "local-rules-file";
        parameters = {
          name = "polkit-local-rules";
          entry = {
            kind = "copied-file";
            source = {
              kind = "execution-path";
              resource = resultOf "local-rules-source" "retained-resource";
              path = resultOf "local-rules-source" "execution-path";
            };
            maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
          };
          destination = "/etc/polkit-1/rules.d/10-aos.rules";
          owner = "root";
          group = resultOf "service-group" "group-name";
          mode = "0640";
          prerequisites = [
            (resultOf "local-rules-source" "retained-resource")
            (resultOf "local-filesystems" "readiness-resource")
          ];
        };
      }
      {
        key = "packaged-actions-file";
        parameters = {
          name = "polkit-packaged-actions";
          entry = {
            kind = "copied-file";
            source = {
              kind = "artifact-file";
              reference = {
                artifact = lib.abilities.packageOutput {};
                path = "share/polkit-1/actions/org.freedesktop.policykit.policy";
              };
            };
            maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
          };
          destination = "/etc/polkit-1/actions/org.freedesktop.policykit.policy";
          owner = "root";
          group = "root";
          mode = "0444";
          prerequisites = [(resultOf "local-filesystems" "readiness-resource")];
        };
      }
    ];
  };
  packagedUnits = {
    requirementTemplates.systemd-packaged-unit =
      lib.abilities.interfaceSelector {
        name = "aos.systemd.packaged-unit";
        abi = 1;
      }
      // {
        description = "References message-bus and login-manager units required by polkit.";
        methods = ["observe"];
        guarantees = [];
        strength = "required";
        fallback = null;
      };
    requests = builtins.listToAttrs (builtins.map (unit: {
        name = unit.key;
        value = {
          requirement = "systemd-packaged-unit";
          consumer = consumerInstance;
          scope = [unit.key];
          parameters = {
            source = {
              artifact = lib.abilities.packageOutput {package = unit.package;};
              unit_file = "lib/systemd/system/${unit.name}";
              unit_name = unit.name;
            };
            activation = "reference";
            prerequisites = [];
            dependencies = {
              after = [];
              before = [];
              requires = [];
              wants = [];
            };
            drop_in = {
              accepted_exit_statuses = [];
              reload_triggers = [];
              search_path = [];
            };
          };
        };
      }) [
        {
          key = "dbus-socket";
          package = "dbus";
          name = "dbus.socket";
        }
        {
          key = "login-manager";
          package = "systemd";
          name = "systemd-logind.service";
        }
      ]);
  };
  service = serviceManagement.forService {
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "polkit";
      enabled = true;
      lifecycle = {
        description = "Authorization Manager";
        execution_model = "foreground";
        environment_files = [];
        condition = [];
        pre_start = [];
        start = [
          {
            executable = {
              artifact = lib.abilities.packageOutput {};
              entry_point = "lib/polkit-1/polkitd";
              arguments = ["--no-debug" "--log-level=notice"];
            };
            ignore_failure = false;
          }
        ];
        post_start = [];
        stop = [];
        post_stop = [];
        restart = "on-failure";
        restart_delay_millis = 100;
        configuration_change_action = "reload";
        remain_after_exit = false;
        start_timeout_millis = 90000;
        stop_timeout_millis = 90000;
      };
      dependencies = {
        after = [
          (resultOf "dbus-socket" "unit-resource")
          (resultOf "login-manager" "unit-resource")
        ];
        before = [];
        requires = [(resultOf "dbus-socket" "unit-resource")];
        wants = [(resultOf "login-manager" "unit-resource")];
        prerequisites = [
          (resultOf "local-rules-file" "retained-resource")
          (resultOf "packaged-actions-file" "retained-resource")
        ];
      };
      supervision = {
        startup_protocol = "notification";
        notification_access = "main-process";
      };
      reload = {
        strategy = "signal";
        commands = [];
        signal = "HUP";
        completion = "command-exit";
      };
      directories.managed = [
        {
          path = "polkit-1";
          purpose = "state";
          mode = "0700";
          retention = "persistent";
          owner = resultOf "service-principal" "principal-name";
          group = resultOf "service-group" "group-name";
        }
        {
          path = "polkit-1";
          purpose = "runtime";
          mode = "0750";
          retention = "restart";
          owner = resultOf "service-principal" "principal-name";
          group = resultOf "service-group" "group-name";
        }
      ];
      identity = {
        principal = resultOf "service-principal" "principal-name";
        primary_group = resultOf "service-group" "group-name";
        supplementary_groups = [];
        ephemeral = false;
        file_creation_mask = "0077";
      };
      isolation = {
        privilege = "unprivileged";
        filesystem = "read-only-system";
        home_access = "inaccessible";
        network = "none";
        process_visibility = "private";
        termination_scope = "all-processes";
        temporary_directory = "private";
        devices = [];
        host_paths = [];
        permit_core_dumps = false;
      };
      linux_isolation = {
        allow_privilege_escalation = false;
        ambient_capabilities = [];
        capability_bounds = {
          kind = "restricted";
          capabilities = ["CAP_SETUID" "CAP_SETGID"];
        };
        control_group_delegation = false;
        control_group_access = "read-only";
        device_namespace = "private";
        kernel_clock_mutation = false;
        kernel_hostname_mutation = false;
        kernel_log_access = false;
        kernel_module_access = false;
        kernel_tunable_access = false;
        lock_personality = true;
        memory_write_execute = false;
        remove_ipc = true;
        namespace_isolation = ["mount" "network"];
        network_address_families = ["unix"];
        oom_score_adjust = 0;
        permit_realtime = false;
        permit_suid_sgid = false;
        process_visibility = "self";
        syscall_architectures = ["native"];
        syscall_allow = [];
        syscall_deny = [];
        syscall_profile = "system-service";
        user_namespace_ownership = "none";
      };
      linux_device_policy = {
        baseline_access = "declared-devices-only";
        rules = [
          {
            selector = {
              kind = "number";
              device_type = "character";
              major = 1;
              minor = 3;
            };
            read = true;
            write = true;
            create_node = false;
          }
        ];
      };
      resources = {
        locked_memory_bytes = {
          kind = "maximum";
          value = 0;
        };
        memory_max_bytes = {
          kind = "maximum";
          value = 33554432;
        };
        memory_swap_max_bytes = {
          kind = "maximum";
          value = 33554432;
        };
        oom_policy = "stop";
      };
    };
  };
  fragments = [
    group
    principal
    localFilesystems
    rulesConfiguration
    configurationFiles
    packagedUnits
    service
  ];
  contributions = builtins.map serviceManagement.splitContribution fragments;
in {
  options.aos.security.polkit = {
    enable = lib.mkOption {
      type = abilityTypes.boolean;
      default = false;
      description = "Run polkit and install its authorization tools.";
    };
    extraRules = lib.mkOption {
      type = abilityTypes.list {
        element = abilityTypes.string {
          maxLength = abilityTypes.limits.maxStringLength;
          syntax = null;
        };
        maxItems = abilityTypes.limits.maxCollectionItems;
      };
      default = [];
      description = "JavaScript authorization rules loaded after packaged policy.";
    };
  };

  config = lib.mkMerge [
    {aos.abilities = lib.mkMerge (builtins.map (entry: entry.declarations) contributions);}
    (lib.mkIf cfg.enable {
      aos.abilities = lib.mkMerge (
        [{instances.${consumerInstance} = {};}]
        ++ builtins.map (entry: entry.configured) contributions
      );
    })
  ];
}
