[package]
name = "aos-nix-harness"
version = "0.1.0"
edition = "2024"

[features]
default = []
native-eval = ["aos-core/native-eval"]

[dependencies]
anyhow = { workspace = true }
aos-core = { workspace = true }
aos-nix-compat = { workspace = true }
base64 = { workspace = true }
nix-compat = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
ratchet-cache = { workspace = true }
ratchet-oracle = { workspace = true }
tempfile = { workspace = true }
