//! Generated C declarations for memory-mutation batches.

use super::*;

pub(crate) fn emit_memory_batch_c_header(out: &mut String) {
    macro_rules! define {
        ($name:literal, $value:expr) => {
            let _ = writeln!(out, "#define {} {}", $name, $value);
        };
    }
    out.push_str("\n/* Atomic ordered QEMU memory-mutation batch ABI. */\n");
    out.push_str("#define CRUCIBLE_MEMORY_MUTATION_BATCH_MAGIC_V1 \"CRUMBAT1\"\n");
    out.push_str("#define CRUCIBLE_MEMORY_MUTATION_BATCH_PRECONDITION_SHA256_DOMAIN_V1 \"crucible.memory-mutation-batch-precondition.v1\\0\"\n");
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_PRECONDITION_SHA256_DOMAIN_V1_BYTES",
        MEMORY_MUTATION_BATCH_PRECONDITION_SHA256_DOMAIN_V1.len()
    );
    out.push_str("#define CRUCIBLE_MEMORY_MUTATION_BATCH_BEFORE_SHA256_DOMAIN_V1 \"crucible.memory-mutation-batch-before.v1\\0\"\n");
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_BEFORE_SHA256_DOMAIN_V1_BYTES",
        MEMORY_MUTATION_BATCH_BEFORE_SHA256_DOMAIN_V1.len()
    );
    out.push_str("#define CRUCIBLE_MEMORY_MUTATION_BATCH_AFTER_SHA256_DOMAIN_V1 \"crucible.memory-mutation-batch-after.v1\\0\"\n");
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_AFTER_SHA256_DOMAIN_V1_BYTES",
        MEMORY_MUTATION_BATCH_AFTER_SHA256_DOMAIN_V1.len()
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_VERSION_V1",
        MEMORY_MUTATION_BATCH_VERSION_V1
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_HEADER_V1_BYTES",
        MEMORY_MUTATION_BATCH_HEADER_V1_BYTES
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_RECORD_V1_BYTES",
        MEMORY_MUTATION_BATCH_RECORD_V1_BYTES
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_MAX_ACTIONS",
        MEMORY_MUTATION_BATCH_MAX_ACTIONS
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_MAX_CHANGED_BYTES",
        MEMORY_MUTATION_BATCH_MAX_CHANGED_BYTES
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_VERSION_OFFSET",
        MEMORY_MUTATION_BATCH_VERSION_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_COUNT_OFFSET",
        MEMORY_MUTATION_BATCH_COUNT_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_PRECONDITION_OFFSET",
        MEMORY_MUTATION_BATCH_PRECONDITION_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_RECORDS_LENGTH_OFFSET",
        MEMORY_MUTATION_BATCH_RECORDS_LENGTH_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_RESERVED_OFFSET",
        MEMORY_MUTATION_BATCH_RESERVED_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_BODY_OFFSET",
        MEMORY_MUTATION_BATCH_BODY_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_RECORD_ACTION_HASH_OFFSET",
        MEMORY_MUTATION_BATCH_RECORD_ACTION_HASH_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_RECORD_LENGTH_OFFSET",
        MEMORY_MUTATION_BATCH_RECORD_LENGTH_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_RECORD_RESERVED_OFFSET",
        MEMORY_MUTATION_BATCH_RECORD_RESERVED_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_RECORD_BODY_OFFSET",
        MEMORY_MUTATION_BATCH_RECORD_BODY_OFFSET
    );
    out.push_str("#define CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_MAGIC_V1 \"CRUMBAV1\"\n");
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_VERSION_V1",
        MEMORY_MUTATION_BATCH_EVIDENCE_VERSION_V1
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_HEADER_V1_BYTES",
        MEMORY_MUTATION_BATCH_EVIDENCE_HEADER_V1_BYTES
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_RECORD_V1_BYTES",
        MEMORY_MUTATION_BATCH_EVIDENCE_RECORD_V1_BYTES
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_VERSION_OFFSET",
        MEMORY_MUTATION_BATCH_EVIDENCE_VERSION_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_COUNT_OFFSET",
        MEMORY_MUTATION_BATCH_EVIDENCE_COUNT_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_PRECONDITION_OFFSET",
        MEMORY_MUTATION_BATCH_EVIDENCE_PRECONDITION_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_RECORDS_LENGTH_OFFSET",
        MEMORY_MUTATION_BATCH_EVIDENCE_RECORDS_LENGTH_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_RESERVED_OFFSET",
        MEMORY_MUTATION_BATCH_EVIDENCE_RESERVED_OFFSET
    );
    define!(
        "CRUCIBLE_MEMORY_MUTATION_BATCH_EVIDENCE_BODY_OFFSET",
        MEMORY_MUTATION_BATCH_EVIDENCE_BODY_OFFSET
    );
}
