# stdenv/toolchains/gcc4_1/coreutils.nix — GNU Coreutils 5.97 (RHEL 5)
#
# Built with THIS tier's GCC 4.1.2 + binutils 2.17 + glibc 2.5.
#
{
  prev,
  gcc,
  binutils,
  glibc,
  perl,
  texinfo,
  help2man,
  buildPlatform,
  hostPlatform,
}:
let
  inherit (import ../../../lib/derivations.nix { system = builtins.currentSystem; }) fetchTarball;

  src = fetchTarball {
    url = "https://mirrors.kernel.org/gnu/coreutils/coreutils-5.97.tar.bz2";
    hash = "0xq92cfg0dgd2d4bj1fc8p6ymapbfaavwcl1vhl6nvrqbxfmbkp5";
  };
in
builtins.derivation {
  name = "coreutils-5.97";
  system = buildPlatform.system;
  builder = "${prev.bash}/bin/bash";
  args = [
    "-c"
    ''
      set -eu

      export PATH="${texinfo}/bin:${help2man}/bin:${prev.coreutils}/bin:${gcc}/bin:${binutils}/bin:${prev.gnumake}/bin:${prev.sed}/bin:${prev.grep}/bin:${prev.gawk}/bin:${prev.findutils}/bin:${prev.tar}/bin:${prev.gzip}/bin:${prev.diffutils}/bin:${prev.bash}/bin:${prev.patch}/bin:${perl}/bin"
      export CONFIG_SHELL="${prev.bash}/bin/bash"

      # Stub autotools — prevents Makefiles from re-running real autoconf/automake
      mkdir -p "$TMPDIR/fakebin"
      for tool in autoconf autoheader aclocal automake autoreconf autom4te; do
        printf '#!${prev.bash}/bin/bash\nexit 0\n' > "$TMPDIR/fakebin/$tool"
        chmod +x "$TMPDIR/fakebin/$tool"
      done
      export PATH="$TMPDIR/fakebin:$PATH"

      cd "$TMPDIR"
      cp -r ${src} coreutils-5.97
      cd coreutils-5.97
      chmod -R u+w .
      find . -type f -exec touch {} + 2>/dev/null || true

      # Replace wheel-gen.pl (Perl) with awk implementation
      # Outputs just the raw gap values (factor.c wraps them in its own declaration)
      cat > src/wheel-gen.pl << 'WHEELEOF'
#!/bin/sh
N=$1
gawk -v n="$N" '
BEGIN {
  split("2 3 5 7 11 13 17 19 23 29 31", p)
  prod = 1
  for (i = 1; i <= n; i++) prod *= p[i]
  nc = 0
  for (k = 1; k <= prod; k++) {
    coprime = 1
    for (i = 1; i <= n; i++)
      if (k % p[i] == 0) { coprime = 0; break }
    if (coprime) { nc++; c[nc] = k }
  }
  for (i = 1; i < nc; i++) {
    d = c[i+1] - c[i]
    if (i > 1) printf ","
    if ((i-1) % 16 == 0) printf "\n  "
    else printf " "
    printf "%d", d
  }
  d = c[1] + prod - c[nc]
  printf ", %d,\n", d
}'
WHEELEOF
      ${prev.sed}/bin/sed -i "s|#!/bin/sh|#!${prev.bash}/bin/bash|" src/wheel-gen.pl
      chmod +x src/wheel-gen.pl

      # Replace extract-magic (Perl) with awk implementation
      cat > src/extract-magic << 'EMEOF'
#!/bin/sh
gawk '
/S_MAGIC_[A-Z0-9_]+/ && /0x[0-9a-fA-F]+/ {
  match($0, /S_MAGIC_[A-Z0-9_]+/)
  name = substr($0, RSTART, RLENGTH)
  match($0, /0x[0-9a-fA-F]+/)
  val = substr($0, RSTART, RLENGTH)
  if (!(name in seen)) {
    printf "#define %s %s\n", name, val
    seen[name] = 1
  }
}' "$@"
EMEOF
      ${prev.sed}/bin/sed -i "s|#!/bin/sh|#!${prev.bash}/bin/bash|" src/extract-magic
      chmod +x src/extract-magic

      # Replace help2man (Perl) with a dummy that creates the output file
      cp ${builtins.toFile "help2man-dummy" ''
#!/bin/sh
out=""
next_is_out=""
for arg; do
  if test -n "$next_is_out"; then
    out="$arg"
    next_is_out=""
    continue
  fi
  case "$arg" in
    -o) next_is_out=1 ;;
  esac
done
if test -n "$out"; then
  dir="''${out%/*}"
  if test "$dir" != "$out"; then
    mkdir -p "$dir"
  fi
  printf '.TH DUMMY 1\n' > "$out"
fi
exit 0
''} man/help2man
      ${prev.sed}/bin/sed -i "s|#!/bin/sh|#!${prev.bash}/bin/bash|" man/help2man
      chmod +x man/help2man

      # Replace Makefile.in for man/tests BEFORE configure so config.status
      # produces dummy Makefiles (post-configure overrides get regenerated by make)
      for d in man tests; do
        if test -d "$d"; then
          printf 'all install install-data install-exec uninstall:\n\t@true\n' > "$d/Makefile.in"
        fi
      done

      CC="${gcc}/bin/gcc -static" \
      CFLAGS="-O2 -I${glibc}/include" \
      LDFLAGS="-L${glibc}/lib -static -Wl,--whole-archive ${glibc}/lib/libnss_files.a ${glibc}/lib/libnss_dns.a ${glibc}/lib/libresolv.a -Wl,--no-whole-archive -Wl,--defsym=__res_iclose=0 -Wl,-u,dl_iterate_phdr" \
      ./configure \
        --prefix="$out" \
        --build=${hostPlatform.config} --host=${hostPlatform.config} --target=${hostPlatform.config} \
        --disable-nls

      # Touch pre-generated files AFTER configure so they're newer than
      # their sources. Prevents make from regenerating them with perl/bison.
      touch src/dircolors.h src/fs.h src/wheel.h
      touch lib/getdate.c lib/getdate.h

      # Strip prerequisites from autotools regeneration rules
      find . -name Makefile | while read f; do
        sed -i 's/^Makefile:.*/Makefile:/; s/^config\.status:.*/config.status:/; s/^configure:.*/configure:/' "$f"
      done

      make -j"$NIX_BUILD_CORES" \
        AUTOCONF=true AUTOHEADER=true ACLOCAL=true AUTOMAKE=true
      make install \
        AUTOCONF=true AUTOHEADER=true ACLOCAL=true AUTOMAKE=true

      echo "Coreutils 5.97 installed to $out"
    ''
  ];
}
// {
  meta = {
    build = {
      os = "linux";
      cpu = [
        "x86_64"
        "i686"
      ];
    };
    execute = {
      os = "linux";
      cpu = [
        "x86_64"
        "i686"
      ];
    };
  };
}
