##! Package-owned OpenPubkey SSH authentication configuration.
{
  config,
  lib,
  packageName,
  ...
}: let
  cfg = config.aos.services.opkssh;
  abilityTypes = lib.abilities.types;
  boundedString = maxLength:
    abilityTypes.string {
      inherit maxLength;
      syntax = null;
    };
  strings = maxItems:
    abilityTypes.list {
      element = boundedString 4096;
      inherit maxItems;
    };
  provider = abilityTypes.record {
    fields = {
      issuer = boundedString 4096;
      clientId = boundedString 4096;
      expirationPolicy = {
        type = boundedString 128;
        default = "24h";
      };
    };
  };
  authRule = abilityTypes.record {
    fields = {
      principal = abilityTypes.principalName;
      identity = boundedString 4096;
      issuer = boundedString 4096;
    };
  };

  providersText = builtins.concatStringsSep "\n" (
    builtins.map (
      entry: "${entry.issuer} ${entry.clientId} ${entry.expirationPolicy}"
    )
    cfg.providers
  );
  authIdText = builtins.concatStringsSep "\n" (
    builtins.map (
      entry: "${entry.identity} ${entry.principal} ${entry.issuer}"
    )
    cfg.authRules
  );
  configYaml =
    ''
      # /etc/opk/config.yml - generated by the opkssh package module.
      # Do not edit manually.
    ''
    + lib.optionalString (cfg.denyEmails != []) ''
      deny_emails:
      ${builtins.concatStringsSep "\n" (builtins.map (email: "  - ${email}") cfg.denyEmails)}
    ''
    + lib.optionalString (cfg.denyUsers != []) ''
      deny_users:
      ${builtins.concatStringsSep "\n" (builtins.map (user: "  - ${user}") cfg.denyUsers)}
    '';
in {
  options.aos.services = lib.mkOption {
    type = lib.types.lazyAttrsOf (lib.types.submodule ({name, ...}: {
      options = lib.optionalAttrs (name == "opkssh") {
        enable = lib.mkOption {
          type = abilityTypes.boolean;
          default = false;
          description = "Enable OpenID Connect authentication for OpenSSH through opkssh.";
        };

        providers = lib.mkOption {
          type = abilityTypes.list {
            element = provider;
            maxItems = 256;
          };
          default = [];
          description = "OIDC providers allowed to authenticate.";
          example = [
            {
              issuer = "https://accounts.google.com";
              clientId = "client.apps.googleusercontent.com";
              expirationPolicy = "24h";
            }
          ];
        };

        authRules = lib.mkOption {
          type = abilityTypes.list {
            element = authRule;
            maxItems = 4096;
          };
          default = [];
          description = "OIDC identity-to-principal mappings.";
          example = [
            {
              principal = "root";
              identity = "alice@example.com";
              issuer = "https://accounts.google.com";
            }
          ];
        };

        denyEmails = lib.mkOption {
          type = strings 4096;
          default = [];
          description = "Email addresses denied authentication.";
        };

        denyUsers = lib.mkOption {
          type = strings 4096;
          default = [];
          description = "Runtime principals denied authentication.";
        };
      };
    }));
    default = {};
  };

  config = lib.mkMerge [
    {aos.services.opkssh = {};}
    (lib.mkIf (cfg.enable && config.aos.abilities.environment != null) {
      aos.services.ssh.authorizedKeysCommand = {
        executable = {
          artifact = lib.abilities.packageOutput {package = packageName;};
          path = "bin/opkssh";
        };
        arguments = ["verify" "%u" "%k" "%t"];
        user = "opksshuser";
      };

      environment.etc = {
        "opk/providers".text = providersText + "\n";
        "opk/auth_id".text = authIdText + "\n";
        "opk/config.yml".text = configYaml;
      };

      aos.users.users.opksshuser = {
        uid = 993;
        group = "opksshuser";
        home = "/";
        shell = "/sbin/nologin";
        description = "opkssh AuthorizedKeysCommand user";
        extraGroups = [];
      };

      aos.users.groups.opksshuser = {
        gid = 993;
        members = ["opksshuser"];
      };
    })
  ];
}
