##! Configures the OpenPubkey SSH authentication plugin and its fixed identity.
{
  config,
  lib,
  package,
  ...
}: let
  cfg = config.aos.security.opkssh;
  field = type: description: lib.mkOption {inherit type description;};
  providersText = lib.concatStringsSep "\n" (builtins.map
    (entry: "${entry.issuer} ${entry.clientId} ${entry.expirationPolicy}")
    cfg.providers);
  authIdText = lib.concatStringsSep "\n" (builtins.map
    (entry: "${entry.identity} ${entry.principal} ${entry.issuer}")
    cfg.authRules);
  configYaml =
    "# Generated by the opkssh package module.\n"
    + lib.optionalString (cfg.denyEmails != [])
    "deny_emails:\n${lib.concatStringsSep "\n" (builtins.map (email: "  - ${email}") cfg.denyEmails)}\n"
    + lib.optionalString (cfg.denyUsers != [])
    "deny_users:\n${lib.concatStringsSep "\n" (builtins.map (user: "  - ${user}") cfg.denyUsers)}\n";
  group = config.aos.abilities.identity.operations.group.effects.opkssh;
  principal = config.aos.abilities.identity.operations.principal.effects.opkssh;
  files = config.aos.abilities.configuration.operations.file.effects;
  file = path: content: {
    input = {
      inherit path content;
      mode = "0444";
    };
  };
in {
  options.aos.security.opkssh = {
    enable = lib.mkEnableOption "OpenID Connect SSH authentication";
    providers = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
        options = {
          issuer = field lib.types.str "Allowed OIDC issuer URL.";
          clientId = field lib.types.str "Allowed OIDC client identity.";
          expirationPolicy = lib.mkOption {
            type = lib.types.str;
            default = "24h";
            description = "Maximum accepted identity lifetime.";
          };
        };
      });
      default = [];
      description = "OIDC providers allowed to authenticate.";
    };
    authRules = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
        options = {
          principal = field lib.types.str "Runtime principal granted SSH access.";
          identity = field lib.types.str "OIDC identity granted access.";
          issuer = field lib.types.str "OIDC issuer authorized for this mapping.";
        };
      });
      default = [];
      description = "OIDC identity-to-principal mappings.";
    };
    denyEmails = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Email addresses denied authentication.";
    };
    denyUsers = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Runtime principals denied authentication.";
    };
  };

  config = lib.mkIf cfg.enable {
    aos.services.ssh.authorizedKeysCommand = {
      executable = {
        path = "${package}/bin/opkssh";
        arguments = ["verify" "%u" "%k" "%t"];
      };
      user = "opksshuser";
    };
    aos.services.ssh.dependencies.prerequisites = builtins.sort (left: right: builtins.toJSON left < builtins.toJSON right) [
      principal.outputs.resource
      config.aos.abilities.filesystem.operations.entry.effects.opkssh-log.outputs.resource
      files.opkssh-providers.outputs.resource
      files.opkssh-auth-id.outputs.resource
      files.opkssh-config.outputs.resource
    ];
    aos.abilities = {
      filesystem.operations.entry.effects.opkssh-log = {
        lifetime = "persistent";
        input = {
          path = "/var/log/opkssh.log";
          kind = "empty-file";
          mode = "0660";
          owner = "root";
          group = group.outputs.name;
        };
      };
      identity.operations = {
        group.effects.opkssh.input = {
          name = "opksshuser";
          requested_id = 993;
        };
        principal.effects.opkssh.input = {
          name = "opksshuser";
          requested_id = 993;
          home_directory = "/";
          description = "opkssh AuthorizedKeysCommand user";
          primary_group = group.outputs.name;
        };
      };
      configuration.operations.file.effects = {
        opkssh-providers = file "/etc/opk/providers" (providersText + "\n");
        opkssh-auth-id = file "/etc/opk/auth_id" (authIdText + "\n");
        opkssh-config = file "/etc/opk/config.yml" configYaml;
      };
    };
  };
}
