[package]
name = "ratchet-jit"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
bincode = { workspace = true }
cranelift-codegen = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
ratchet-core = { workspace = true }
ratchet-value = { workspace = true }
serde = { workspace = true }
target-lexicon = { workspace = true }
thiserror = { workspace = true }
