[package]
name = "aos-configuration-provider"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
rustix = { workspace = true, features = ["fs", "process"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
toml.workspace = true
