[package]
name = "ratchet-oracle"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
anyhow = { workspace = true }
aos-nix-compat = { workspace = true }
aos-nix-syntax = { workspace = true }
ratchet-core = { workspace = true }
ratchet-cache = { workspace = true }
aos-nix-dialect = { workspace = true }
ratchet-value = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
bzip2 = { workspace = true }
crossbeam-deque = { workspace = true }
flate2 = { workspace = true }
git2 = { workspace = true }
md-5 = { workspace = true }
miette = { workspace = true }
nix-compat = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
ring = { workspace = true }
rusqlite = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
xxhash-rust = { workspace = true }
xz2 = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
loom = { workspace = true }
proptest = { workspace = true }
ratchet-core = { workspace = true, features = ["test-util"] }
