[package]
name = "crucible-guest"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
crucible-protocol = { path = "../crucible-protocol" }
libc = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
crucible-campaign = { path = "../crucible-campaign" }

[[bin]]
name = "crucible-guest"
path = "src/main.rs"
