[package]
name = "aos-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
default = []
native-eval = ["dep:aos-nix", "aos-nix/candidate_c_value"]

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
regex = { workspace = true }
glob = { workspace = true }
ignore = { workspace = true }
hex = { workspace = true }
ed25519-dalek = { workspace = true }
indicatif = { workspace = true }
console = { workspace = true }
humantime = { workspace = true }
alejandra = { workspace = true }
tokio = { workspace = true }
atty = { workspace = true }
aos-nix = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
