//! Bounded transport-neutral ownership transaction semantics.
//!
//! V1 has three methods: `Begin` durably admits an exact canonical claim,
//! `CompleteOrResume` explicitly drives or resumes issuance for that intent,
//! and `Query` observes only the exact request binding. A pending result may
//! include the crash window after external issuance but before local commit;
//! it therefore carries no evidence that issuance has not occurred. A
//! completed result returns exact canonical artifacts but does not establish
//! present lease liveness.
//!
//! This module deliberately does not choose a byte carrier. A local
//! `SOCK_SEQPACKET` adapter and a future authenticated remote adapter must both
//! validate into these types. Neither local credentials nor paths,
//! descriptors, monotonic deadlines, or backend journal details belong here.
//!
//! The session binding is SHA-256 over the domain string, selected version,
//! length-prefixed stable authority key ID, exact authority generation and
//! fingerprint, ownership-key usage code, canonical method codes, and the
//! three negotiated bounds, all integers big-endian. The all-zero hash alone
//! maps to the value one to reserve the zero sentinel. It correlates messages but does not replace
//! authentication by the eventual carrier. The client and server nonces must
//! be independently generated by a CSPRNG for every connection.

use aos_sandbox_core::model::{KeyReference, KeyUsage};
use aos_sandbox_core::{ObjectDigest, ProtocolId, ProtocolVersion, negotiate_protocol};
use sha2::{Digest as _, Sha256};

use crate::{
    MAXIMUM_REQUESTED_DURATION_SECONDS, OwnershipClaimV1, UnverifiedOwnershipLeaseResponse,
};

/// Maximum semantic request bytes a V1 carrier may admit.
pub const MAXIMUM_OWNERSHIP_REQUEST_BYTES: u32 = 4 * 1024;
/// Maximum semantic response bytes a V1 carrier may admit.
pub const MAXIMUM_OWNERSHIP_RESPONSE_BYTES: u32 = 256 * 1024;
/// Minimum response budget accepted during negotiation.
///
/// The ceiling always reserves both maximum canonical artifacts and bounded
/// envelope overhead, so a completed transaction can never become
/// unreturnable after it is durably admitted.
pub const MINIMUM_OWNERSHIP_RESPONSE_BYTES: u32 = 196 * 1024;
const MAXIMUM_METHODS: usize = 3;
const SESSION_BINDING_DOMAIN: &[u8] = b"aos-ownership-authority-session-v1\0";

/// Identifies one closed V1 ownership-authority method.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum OwnershipMethodV1 {
    /// Durably admits an unsigned canonical ownership claim.
    Begin,
    /// Explicitly completes or resumes one previously admitted claim.
    CompleteOrResume,
    /// Queries one exact request-ID and claim-digest binding.
    Query,
}

impl OwnershipMethodV1 {
    const fn code(self) -> u8 {
        match self {
            Self::Begin => 1,
            Self::CompleteOrResume => 2,
            Self::Query => 3,
        }
    }
}

/// Binds follow-up operations and results to one immutable claim.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OwnershipTransactionReferenceV1 {
    request_id: [u8; 16],
    claim_digest: ObjectDigest,
}

impl OwnershipTransactionReferenceV1 {
    /// Constructs a non-sentinel request and claim binding.
    ///
    /// # Errors
    ///
    /// Returns [`OwnershipProtocolValidationError::InvalidTransactionReference`]
    /// when either field is its all-zero sentinel.
    pub fn new(
        request_id: [u8; 16],
        claim_digest: ObjectDigest,
    ) -> Result<Self, OwnershipProtocolValidationError> {
        if request_id == [0; 16] || claim_digest.as_bytes() == &[0; 32] {
            return Err(OwnershipProtocolValidationError::InvalidTransactionReference);
        }
        Ok(Self {
            request_id,
            claim_digest,
        })
    }

    /// Derives the exact transaction binding from a validated canonical claim.
    #[must_use]
    pub fn from_claim(claim: &OwnershipClaimV1) -> Self {
        Self {
            request_id: *claim.request_id(),
            claim_digest: claim.digest(),
        }
    }

    /// Returns the stable idempotency request identity.
    #[must_use]
    pub const fn request_id(&self) -> &[u8; 16] {
        &self.request_id
    }

    /// Returns the domain-separated digest of the complete canonical claim.
    #[must_use]
    pub const fn claim_digest(&self) -> ObjectDigest {
        self.claim_digest
    }
}

/// Carries a method-specific request after hostile-input validation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OwnershipRequestBodyV1 {
    /// Carries the sole complete claim accepted from a client.
    Begin(Box<OwnershipClaimV1>),
    /// Names a durable intent without accepting replacement claim bytes.
    CompleteOrResume(OwnershipTransactionReferenceV1),
    /// Names the sole durable transaction that may be observed.
    Query(OwnershipTransactionReferenceV1),
}

impl OwnershipRequestBodyV1 {
    fn method(&self) -> OwnershipMethodV1 {
        match self {
            Self::Begin(_) => OwnershipMethodV1::Begin,
            Self::CompleteOrResume(_) => OwnershipMethodV1::CompleteOrResume,
            Self::Query(_) => OwnershipMethodV1::Query,
        }
    }

    fn transaction(&self) -> OwnershipTransactionReferenceV1 {
        match self {
            Self::Begin(claim) => OwnershipTransactionReferenceV1::from_claim(claim),
            Self::CompleteOrResume(reference) | Self::Query(reference) => *reference,
        }
    }
}

/// Owns an exact method/body/request binding independent of its carrier.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnershipRequestEnvelopeV1 {
    session_binding: [u8; 32],
    method: OwnershipMethodV1,
    transaction: OwnershipTransactionReferenceV1,
    body: OwnershipRequestBodyV1,
}

impl OwnershipRequestEnvelopeV1 {
    /// Validates an independently decoded method tag and body.
    ///
    /// # Errors
    ///
    /// Returns [`OwnershipProtocolValidationError::MethodMismatch`] when the
    /// outer method tag does not exactly select the supplied body.
    fn from_parts(
        session_binding: [u8; 32],
        method: OwnershipMethodV1,
        body: OwnershipRequestBodyV1,
    ) -> Result<Self, OwnershipProtocolValidationError> {
        if method != body.method() {
            return Err(OwnershipProtocolValidationError::MethodMismatch);
        }
        Ok(Self {
            session_binding,
            method,
            transaction: body.transaction(),
            body,
        })
    }

    /// Returns the negotiated correlation transcript echoed by this request.
    #[must_use]
    pub const fn session_binding(&self) -> &[u8; 32] {
        &self.session_binding
    }

    /// Returns the closed method selected by this request.
    #[must_use]
    pub const fn method(&self) -> OwnershipMethodV1 {
        self.method
    }

    /// Returns the exact request-ID and claim-digest binding.
    #[must_use]
    pub const fn transaction(&self) -> OwnershipTransactionReferenceV1 {
        self.transaction
    }

    /// Returns the validated method-specific request.
    #[must_use]
    pub const fn body(&self) -> &OwnershipRequestBodyV1 {
        &self.body
    }
}

/// Describes durable transaction state without claiming live authority.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OwnershipTransactionStatusV1 {
    /// No durable request binding existed at the query linearization point.
    Absent,
    /// An intent exists; external issuance may already have happened.
    Pending,
    /// Exact response artifacts were committed for the immutable request.
    Completed(UnverifiedOwnershipLeaseResponse),
}

/// Classifies portable protocol failures without backend diagnostics.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OwnershipProtocolErrorCodeV1 {
    /// The message is malformed, non-canonical, or semantically invalid.
    InvalidRequest,
    /// The authenticated transport did not establish a caller identity.
    Unauthenticated,
    /// The established identity cannot perform the requested operation.
    PermissionDenied,
    /// No compatible ownership protocol version exists.
    IncompatibleProtocol,
    /// A mandatory semantic capability is unavailable.
    RequiredCapabilityUnavailable,
    /// The service's active authority key generation differs from the pin.
    WrongAuthorityEpoch,
    /// A request identity is already bound to different claim bytes.
    IdempotencyConflict,
    /// Expected absence failed because an owner already exists.
    AlreadyOwned,
    /// A renewal does not name the exact current lease fence.
    StaleExpectedPrior,
    /// Completion or query names no durable request binding.
    NotFound,
    /// The fixed authority epoch cannot admit another transaction.
    ResourceExhausted,
    /// The carrier deadline elapsed with an indeterminate transaction result.
    DeadlineExceeded,
    /// Linearizable authority state is temporarily unavailable.
    Unavailable,
    /// Protected state or a returned authority artifact failed authentication.
    IntegrityFailure,
    /// The implementation failed without safe backend detail.
    Internal,
}

/// Gives the normative recovery action for a stable error code.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OwnershipErrorRecoveryV1 {
    /// Correct identity, configuration, or request bytes before another call.
    CorrectRequest,
    /// Observe the exact transaction, then retry only the identical operation.
    QueryThenRetryExact,
    /// Wait for an explicit authority-state or capacity transition.
    AwaitStateChange,
    /// Refresh authoritative state and create a newly planned request.
    RefreshAndReplan,
    /// Quarantine the service until protected integrity is restored.
    Quarantine,
}

impl OwnershipProtocolErrorCodeV1 {
    /// Returns the fixed recovery rule for this error class.
    #[must_use]
    pub const fn recovery(self) -> OwnershipErrorRecoveryV1 {
        match self {
            Self::DeadlineExceeded | Self::Unavailable | Self::Internal => {
                OwnershipErrorRecoveryV1::QueryThenRetryExact
            }
            Self::AlreadyOwned | Self::StaleExpectedPrior => {
                OwnershipErrorRecoveryV1::RefreshAndReplan
            }
            Self::ResourceExhausted => OwnershipErrorRecoveryV1::AwaitStateChange,
            Self::IntegrityFailure => OwnershipErrorRecoveryV1::Quarantine,
            Self::InvalidRequest
            | Self::Unauthenticated
            | Self::PermissionDenied
            | Self::IncompatibleProtocol
            | Self::RequiredCapabilityUnavailable
            | Self::WrongAuthorityEpoch
            | Self::IdempotencyConflict
            | Self::NotFound => OwnershipErrorRecoveryV1::CorrectRequest,
        }
    }
}

/// Carries either one bound transaction status or one stable error.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OwnershipResponseOutcomeV1 {
    /// Reports a non-authorizing durable state observation.
    Status(OwnershipTransactionStatusV1),
    /// Reports a closed stable error code without backend-specific text.
    Error(OwnershipProtocolErrorCodeV1),
}

/// Binds every response to the exact request method and transaction identity.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnershipResponseEnvelopeV1 {
    session_binding: [u8; 32],
    method: OwnershipMethodV1,
    transaction: OwnershipTransactionReferenceV1,
    outcome: OwnershipResponseOutcomeV1,
}

impl OwnershipResponseEnvelopeV1 {
    /// Validates a response under the V1 method/status state machine.
    ///
    /// `Absent` is query-only. Begin and completion may return only pending or
    /// completed status. Errors remain method-bound and carry no artifacts.
    ///
    /// # Errors
    ///
    /// Returns [`OwnershipProtocolValidationError::InvalidResponseStatus`]
    /// when a non-query response claims absence.
    fn new(
        session_binding: [u8; 32],
        method: OwnershipMethodV1,
        transaction: OwnershipTransactionReferenceV1,
        begin_action: Option<crate::OwnershipClaimAction>,
        outcome: OwnershipResponseOutcomeV1,
    ) -> Result<Self, OwnershipProtocolValidationError> {
        validate_outcome(method, begin_action, &outcome)?;
        Ok(Self {
            session_binding,
            method,
            transaction,
            outcome,
        })
    }

    /// Returns the negotiated correlation transcript echoed by this response.
    #[must_use]
    pub const fn session_binding(&self) -> &[u8; 32] {
        &self.session_binding
    }

    /// Returns the exact request method echoed by the response.
    #[must_use]
    pub const fn method(&self) -> OwnershipMethodV1 {
        self.method
    }

    /// Returns the exact request and claim binding echoed by the response.
    #[must_use]
    pub const fn transaction(&self) -> OwnershipTransactionReferenceV1 {
        self.transaction
    }

    /// Returns the stable response outcome.
    #[must_use]
    pub const fn outcome(&self) -> &OwnershipResponseOutcomeV1 {
        &self.outcome
    }
}

/// Checks that a response belongs to the exact originating request.
///
/// This check is mandatory even on an authenticated ordered carrier: it
/// prevents cross-method, cross-request, and cross-claim response substitution
/// by multiplexers and reconnect logic.
///
/// # Errors
///
/// Returns [`OwnershipProtocolValidationError::SessionBindingMismatch`] for a
/// request or response from another negotiation, and
/// [`OwnershipProtocolValidationError::ResponseBindingMismatch`] when the
/// method or immutable transaction reference differs.
pub fn validate_response_binding(
    session: &NegotiatedOwnershipSessionV1,
    request: &OwnershipRequestEnvelopeV1,
    response: &OwnershipResponseEnvelopeV1,
) -> Result<(), OwnershipProtocolValidationError> {
    if request.session_binding() != session.binding()
        || response.session_binding() != session.binding()
    {
        return Err(OwnershipProtocolValidationError::SessionBindingMismatch);
    }
    if request.method() != response.method() || request.transaction() != response.transaction() {
        return Err(OwnershipProtocolValidationError::ResponseBindingMismatch);
    }
    Ok(())
}

/// Carries the client's exact compatibility and authority-generation pin.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnershipClientHelloV1 {
    client_nonce: [u8; 32],
    version: ProtocolVersion,
    expected_authority: KeyReference,
    required_methods: Vec<OwnershipMethodV1>,
    maximum_response_bytes: u32,
}

impl OwnershipClientHelloV1 {
    /// Constructs a bounded canonical client offer.
    ///
    /// Methods must be strictly ordered and unique. The authority reference
    /// must name a nonzero ownership-lease signing generation and fingerprint.
    /// The caller must generate `client_nonce` independently with a CSPRNG for
    /// this connection; this type can reject only the zero sentinel.
    ///
    /// # Errors
    ///
    /// Returns [`OwnershipProtocolValidationError`] for an incompatible
    /// version, zero nonce, invalid authority pin, non-canonical method set,
    /// or invalid response ceiling.
    pub fn new(
        client_nonce: [u8; 32],
        version: ProtocolVersion,
        expected_authority: KeyReference,
        required_methods: Vec<OwnershipMethodV1>,
        maximum_response_bytes: u32,
    ) -> Result<Self, OwnershipProtocolValidationError> {
        if client_nonce == [0; 32] {
            return Err(OwnershipProtocolValidationError::InvalidNonce);
        }
        negotiate_protocol(ProtocolId::OwnershipAuthority, version)
            .map_err(|_| OwnershipProtocolValidationError::IncompatibleProtocol)?;
        validate_authority(&expected_authority)?;
        validate_methods(&required_methods)?;
        if !(MINIMUM_OWNERSHIP_RESPONSE_BYTES..=MAXIMUM_OWNERSHIP_RESPONSE_BYTES)
            .contains(&maximum_response_bytes)
        {
            return Err(OwnershipProtocolValidationError::InvalidResponseBound);
        }
        Ok(Self {
            client_nonce,
            version,
            expected_authority,
            required_methods,
            maximum_response_bytes,
        })
    }

    /// Returns the client's per-connection CSPRNG nonce.
    #[must_use]
    pub const fn client_nonce(&self) -> &[u8; 32] {
        &self.client_nonce
    }

    /// Returns the exact offered semantic protocol version.
    #[must_use]
    pub const fn version(&self) -> ProtocolVersion {
        self.version
    }

    /// Returns the protected client configuration's authority-generation pin.
    #[must_use]
    pub const fn expected_authority(&self) -> &KeyReference {
        &self.expected_authority
    }

    /// Returns the canonical required method set.
    #[must_use]
    pub fn required_methods(&self) -> &[OwnershipMethodV1] {
        &self.required_methods
    }

    /// Returns the maximum complete response the client accepts.
    #[must_use]
    pub const fn maximum_response_bytes(&self) -> u32 {
        self.maximum_response_bytes
    }
}

/// Records one successfully negotiated V1 ownership session contract.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NegotiatedOwnershipSessionV1 {
    version: ProtocolVersion,
    authority: KeyReference,
    methods: Vec<OwnershipMethodV1>,
    maximum_request_bytes: u32,
    maximum_response_bytes: u32,
    maximum_requested_lease_seconds: u64,
    binding: [u8; 32],
}

impl NegotiatedOwnershipSessionV1 {
    /// Negotiates an exact key epoch and closed method set.
    ///
    /// The authority key is never selected by fallback: it must exactly match
    /// the client's protected pin. Server methods must be strictly ordered and
    /// unique before subset validation. The server must generate
    /// `server_nonce` independently with a CSPRNG for this connection.
    ///
    /// # Errors
    ///
    /// Returns [`OwnershipProtocolValidationError`] for a zero server nonce,
    /// invalid server key, wrong authority epoch, non-canonical server methods,
    /// or a missing required method.
    pub fn negotiate(
        hello: &OwnershipClientHelloV1,
        server_nonce: [u8; 32],
        authority: KeyReference,
        methods: Vec<OwnershipMethodV1>,
    ) -> Result<Self, OwnershipProtocolValidationError> {
        if server_nonce == [0; 32] {
            return Err(OwnershipProtocolValidationError::InvalidNonce);
        }
        validate_authority(&authority)?;
        if authority != *hello.expected_authority() {
            return Err(OwnershipProtocolValidationError::WrongAuthorityEpoch);
        }
        validate_methods(&methods)?;
        if hello
            .required_methods()
            .iter()
            .any(|method| !methods.contains(method))
        {
            return Err(OwnershipProtocolValidationError::RequiredMethodUnavailable);
        }
        let maximum_request_bytes = MAXIMUM_OWNERSHIP_REQUEST_BYTES;
        let maximum_response_bytes = hello.maximum_response_bytes();
        let maximum_requested_lease_seconds = MAXIMUM_REQUESTED_DURATION_SECONDS;
        let binding = session_binding(
            hello,
            server_nonce,
            &authority,
            &methods,
            maximum_request_bytes,
            maximum_requested_lease_seconds,
        );
        Ok(Self {
            version: hello.version(),
            authority,
            methods,
            maximum_request_bytes,
            maximum_response_bytes,
            maximum_requested_lease_seconds,
            binding,
        })
    }

    /// Returns the exact selected semantic protocol version.
    #[must_use]
    pub const fn version(&self) -> ProtocolVersion {
        self.version
    }

    /// Returns the exact active ownership signing-key generation.
    #[must_use]
    pub const fn authority(&self) -> &KeyReference {
        &self.authority
    }

    /// Returns the closed supported method set.
    #[must_use]
    pub fn methods(&self) -> &[OwnershipMethodV1] {
        &self.methods
    }

    /// Returns the server's semantic request ceiling.
    #[must_use]
    pub const fn maximum_request_bytes(&self) -> u32 {
        self.maximum_request_bytes
    }

    /// Returns the selected complete response ceiling.
    #[must_use]
    pub const fn maximum_response_bytes(&self) -> u32 {
        self.maximum_response_bytes
    }

    /// Returns the largest duration any V1 claim may request.
    #[must_use]
    pub const fn maximum_requested_lease_seconds(&self) -> u64 {
        self.maximum_requested_lease_seconds
    }

    /// Returns the nonzero domain-separated negotiated correlation transcript.
    #[must_use]
    pub const fn binding(&self) -> &[u8; 32] {
        &self.binding
    }

    /// Constructs a request bound to this negotiated session.
    ///
    /// # Errors
    ///
    /// Returns [`OwnershipProtocolValidationError::MethodUnavailable`] when
    /// the body selects a method outside the negotiated set.
    pub fn request(
        &self,
        body: OwnershipRequestBodyV1,
    ) -> Result<OwnershipRequestEnvelopeV1, OwnershipProtocolValidationError> {
        let method = body.method();
        if !self.methods.contains(&method) {
            return Err(OwnershipProtocolValidationError::MethodUnavailable);
        }
        OwnershipRequestEnvelopeV1::from_parts(self.binding, method, body)
    }

    /// Validates independently decoded request fields against this session.
    ///
    /// # Errors
    ///
    /// Rejects a wrong transcript, unnegotiated method, or method/body mismatch.
    pub fn validate_request_parts(
        &self,
        binding: [u8; 32],
        method: OwnershipMethodV1,
        body: OwnershipRequestBodyV1,
    ) -> Result<OwnershipRequestEnvelopeV1, OwnershipProtocolValidationError> {
        if binding != self.binding || binding == [0; 32] {
            return Err(OwnershipProtocolValidationError::SessionBindingMismatch);
        }
        if !self.methods.contains(&method) {
            return Err(OwnershipProtocolValidationError::MethodUnavailable);
        }
        OwnershipRequestEnvelopeV1::from_parts(binding, method, body)
    }

    /// Constructs a trusted server-side response bound to this negotiated session.
    ///
    /// This builder derives metadata from `request`. Carrier decoders must use
    /// [`Self::validate_response_parts`] so hostile echoed fields are checked
    /// rather than normalized.
    ///
    /// # Errors
    ///
    /// Rejects an unnegotiated method or invalid method/outcome combination.
    pub fn response(
        &self,
        request: &OwnershipRequestEnvelopeV1,
        outcome: OwnershipResponseOutcomeV1,
    ) -> Result<OwnershipResponseEnvelopeV1, OwnershipProtocolValidationError> {
        if request.session_binding != self.binding {
            return Err(OwnershipProtocolValidationError::SessionBindingMismatch);
        }
        if !self.methods.contains(&request.method) {
            return Err(OwnershipProtocolValidationError::MethodUnavailable);
        }
        let begin_action = match request.body() {
            OwnershipRequestBodyV1::Begin(claim) => Some(claim.action()),
            OwnershipRequestBodyV1::CompleteOrResume(_) | OwnershipRequestBodyV1::Query(_) => None,
        };
        OwnershipResponseEnvelopeV1::new(
            self.binding,
            request.method,
            request.transaction,
            begin_action,
            outcome,
        )
    }

    /// Validates independently decoded response metadata before construction.
    ///
    /// This is the mandatory client-side carrier adapter boundary. It checks
    /// the exact transcript, negotiated method, echoed method and transaction,
    /// and the action-aware method/outcome matrix without replacing hostile
    /// values with locally derived ones.
    ///
    /// # Errors
    ///
    /// Returns [`OwnershipProtocolValidationError`] for a foreign transcript,
    /// unnegotiated or substituted method, substituted request ID or claim
    /// digest, or an invalid status/error combination.
    pub fn validate_response_parts(
        &self,
        request: &OwnershipRequestEnvelopeV1,
        binding: [u8; 32],
        method: OwnershipMethodV1,
        transaction: OwnershipTransactionReferenceV1,
        outcome: OwnershipResponseOutcomeV1,
    ) -> Result<OwnershipResponseEnvelopeV1, OwnershipProtocolValidationError> {
        if request.session_binding != self.binding || binding != self.binding || binding == [0; 32]
        {
            return Err(OwnershipProtocolValidationError::SessionBindingMismatch);
        }
        if !self.methods.contains(&method) {
            return Err(OwnershipProtocolValidationError::MethodUnavailable);
        }
        if method != request.method || transaction != request.transaction {
            return Err(OwnershipProtocolValidationError::ResponseBindingMismatch);
        }
        let begin_action = match request.body() {
            OwnershipRequestBodyV1::Begin(claim) => Some(claim.action()),
            OwnershipRequestBodyV1::CompleteOrResume(_) | OwnershipRequestBodyV1::Query(_) => None,
        };
        OwnershipResponseEnvelopeV1::new(binding, method, transaction, begin_action, outcome)
    }
}

/// Reports invalid hostile or independently decoded protocol semantics.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum OwnershipProtocolValidationError {
    /// The protocol major/minor offer is not supported.
    #[error("ownership authority protocol version is incompatible")]
    IncompatibleProtocol,
    /// The request ID or claim digest is an all-zero sentinel.
    #[error("ownership transaction reference is invalid")]
    InvalidTransactionReference,
    /// A client or server connection nonce is the all-zero sentinel.
    #[error("ownership authority connection nonce is invalid")]
    InvalidNonce,
    /// The outer method tag does not match the decoded body.
    #[error("ownership authority method does not match its body")]
    MethodMismatch,
    /// A non-query response claimed that the transaction is absent.
    #[error("ownership authority response status is invalid for its method")]
    InvalidResponseStatus,
    /// An error code is invalid for the selected method.
    #[error("ownership authority error is invalid for its method")]
    InvalidResponseError,
    /// A response method, request ID, or claim digest differs from its request.
    #[error("ownership authority response is not bound to its request")]
    ResponseBindingMismatch,
    /// A request or response does not echo the negotiated transcript.
    #[error("ownership authority session binding does not match")]
    SessionBindingMismatch,
    /// The selected method was not negotiated.
    #[error("ownership authority method was not negotiated")]
    MethodUnavailable,
    /// The authority key is not an exact usable ownership-lease generation.
    #[error("ownership authority key reference is invalid")]
    InvalidAuthority,
    /// The client pin and active authority key generation differ.
    #[error("ownership authority key generation does not match the client pin")]
    WrongAuthorityEpoch,
    /// A method list is empty, oversized, unsorted, or contains duplicates.
    #[error("ownership authority method set is not canonical")]
    InvalidMethodSet,
    /// The server does not implement one of the client's required methods.
    #[error("ownership authority required method is unavailable")]
    RequiredMethodUnavailable,
    /// The requested response budget is outside the fixed V1 range.
    #[error("ownership authority response bound is invalid")]
    InvalidResponseBound,
}

fn validate_authority(authority: &KeyReference) -> Result<(), OwnershipProtocolValidationError> {
    if authority.generation() == 0
        || authority.public_key_sha256().as_bytes() == &[0; 32]
        || authority.usage() != KeyUsage::OwnershipLease
    {
        return Err(OwnershipProtocolValidationError::InvalidAuthority);
    }
    Ok(())
}

fn validate_methods(methods: &[OwnershipMethodV1]) -> Result<(), OwnershipProtocolValidationError> {
    if methods.is_empty()
        || methods.len() > MAXIMUM_METHODS
        || methods.windows(2).any(|pair| pair[0] >= pair[1])
    {
        return Err(OwnershipProtocolValidationError::InvalidMethodSet);
    }
    Ok(())
}

fn validate_outcome(
    method: OwnershipMethodV1,
    begin_action: Option<crate::OwnershipClaimAction>,
    outcome: &OwnershipResponseOutcomeV1,
) -> Result<(), OwnershipProtocolValidationError> {
    match outcome {
        OwnershipResponseOutcomeV1::Status(status) => {
            let valid = match method {
                OwnershipMethodV1::Begin | OwnershipMethodV1::CompleteOrResume => {
                    !matches!(status, OwnershipTransactionStatusV1::Absent)
                }
                OwnershipMethodV1::Query => true,
            };
            if !valid {
                return Err(OwnershipProtocolValidationError::InvalidResponseStatus);
            }
        }
        OwnershipResponseOutcomeV1::Error(error) => {
            let common = matches!(
                error,
                OwnershipProtocolErrorCodeV1::InvalidRequest
                    | OwnershipProtocolErrorCodeV1::Unauthenticated
                    | OwnershipProtocolErrorCodeV1::PermissionDenied
                    | OwnershipProtocolErrorCodeV1::IncompatibleProtocol
                    | OwnershipProtocolErrorCodeV1::RequiredCapabilityUnavailable
                    | OwnershipProtocolErrorCodeV1::WrongAuthorityEpoch
                    | OwnershipProtocolErrorCodeV1::IdempotencyConflict
                    | OwnershipProtocolErrorCodeV1::DeadlineExceeded
                    | OwnershipProtocolErrorCodeV1::Unavailable
                    | OwnershipProtocolErrorCodeV1::IntegrityFailure
                    | OwnershipProtocolErrorCodeV1::Internal
            );
            let valid = common
                || match method {
                    OwnershipMethodV1::Begin => match begin_action {
                        Some(crate::OwnershipClaimAction::Acquire) => matches!(
                            error,
                            OwnershipProtocolErrorCodeV1::AlreadyOwned
                                | OwnershipProtocolErrorCodeV1::ResourceExhausted
                        ),
                        Some(crate::OwnershipClaimAction::Renew) => matches!(
                            error,
                            OwnershipProtocolErrorCodeV1::StaleExpectedPrior
                                | OwnershipProtocolErrorCodeV1::ResourceExhausted
                        ),
                        None => false,
                    },
                    OwnershipMethodV1::CompleteOrResume => matches!(
                        error,
                        OwnershipProtocolErrorCodeV1::AlreadyOwned
                            | OwnershipProtocolErrorCodeV1::StaleExpectedPrior
                            | OwnershipProtocolErrorCodeV1::NotFound
                    ),
                    OwnershipMethodV1::Query => false,
                };
            if !valid {
                return Err(OwnershipProtocolValidationError::InvalidResponseError);
            }
        }
    }
    Ok(())
}

fn session_binding(
    hello: &OwnershipClientHelloV1,
    server_nonce: [u8; 32],
    authority: &KeyReference,
    methods: &[OwnershipMethodV1],
    maximum_request_bytes: u32,
    maximum_requested_lease_seconds: u64,
) -> [u8; 32] {
    let mut digest = Sha256::new();
    digest.update(SESSION_BINDING_DOMAIN);
    digest.update(hello.client_nonce);
    digest.update(server_nonce);
    digest.update(hello.version.major().to_be_bytes());
    digest.update(hello.version.minor().to_be_bytes());
    let key_id = authority.stable_key_id().as_str().as_bytes();
    digest.update((key_id.len() as u16).to_be_bytes());
    digest.update(key_id);
    digest.update(authority.generation().to_be_bytes());
    digest.update(authority.public_key_sha256().as_bytes());
    digest.update([5]); // KeyUsage::OwnershipLease canonical trust-codec value.
    digest.update([methods.len() as u8]);
    for method in methods {
        digest.update([method.code()]);
    }
    digest.update(maximum_request_bytes.to_be_bytes());
    digest.update(hello.maximum_response_bytes.to_be_bytes());
    digest.update(maximum_requested_lease_seconds.to_be_bytes());
    let mut binding: [u8; 32] = digest.finalize().into();
    if binding == [0; 32] {
        binding[31] = 1;
    }
    binding
}

#[cfg(test)]
mod tests {
    use aos_sandbox_core::model::{KeyUsage, StableKeyId};
    use aos_sandbox_core::{
        AssignmentEpoch, DesiredGeneration, IncarnationId, LeaseAssignment, NodeId, SandboxId,
    };

    use super::*;

    fn authority(byte: u8, generation: u64) -> KeyReference {
        KeyReference::new(
            StableKeyId::new(format!("ownership-authority-{byte}"))
                .unwrap_or_else(|error| panic!("test key ID failed: {error}")),
            generation,
            ObjectDigest::from_bytes([byte; 32]),
            KeyUsage::OwnershipLease,
        )
    }

    fn claim() -> OwnershipClaimV1 {
        let assignment = LeaseAssignment::new(
            SandboxId::from_bytes([1; 16]),
            IncarnationId::from_bytes([2; 16]),
            AssignmentEpoch::new(3),
            ObjectDigest::from_bytes([4; 32]),
        )
        .unwrap_or_else(|error| panic!("test assignment failed: {error}"));
        OwnershipClaimV1::acquire(
            [5; 16],
            assignment,
            DesiredGeneration::new(6),
            NodeId::from_bytes([7; 16]),
            60,
        )
        .unwrap_or_else(|error| panic!("test claim failed: {error}"))
    }

    fn methods() -> Vec<OwnershipMethodV1> {
        vec![
            OwnershipMethodV1::Begin,
            OwnershipMethodV1::CompleteOrResume,
            OwnershipMethodV1::Query,
        ]
    }

    fn session() -> NegotiatedOwnershipSessionV1 {
        let pinned = authority(9, 4);
        let hello = OwnershipClientHelloV1::new(
            [11; 32],
            ProtocolVersion::new(1, 0),
            pinned.clone(),
            methods(),
            MINIMUM_OWNERSHIP_RESPONSE_BYTES,
        )
        .unwrap_or_else(|error| panic!("test hello failed: {error}"));
        NegotiatedOwnershipSessionV1::negotiate(&hello, [12; 32], pinned, methods())
            .unwrap_or_else(|error| panic!("test session failed: {error}"))
    }

    fn request(method: OwnershipMethodV1) -> OwnershipRequestEnvelopeV1 {
        let claim = claim();
        let reference = OwnershipTransactionReferenceV1::from_claim(&claim);
        let body = match method {
            OwnershipMethodV1::Begin => OwnershipRequestBodyV1::Begin(Box::new(claim)),
            OwnershipMethodV1::CompleteOrResume => {
                OwnershipRequestBodyV1::CompleteOrResume(reference)
            }
            OwnershipMethodV1::Query => OwnershipRequestBodyV1::Query(reference),
        };
        session()
            .request(body)
            .unwrap_or_else(|error| panic!("test request failed: {error}"))
    }

    #[test]
    fn claim_has_stable_golden_bytes_and_digest() {
        let claim = claim();
        assert_eq!(claim.canonical_bytes().len(), 176);
        assert_eq!(
            &claim.canonical_bytes()[..16],
            b"AOSOCLM1\0\x01\x01\0\0\0\0\0"
        );
        assert_eq!(
            claim.digest(),
            ObjectDigest::from_bytes([
                0xaf, 0x42, 0x3b, 0xd1, 0x54, 0x0a, 0xd5, 0x60, 0xf8, 0x9f, 0x71, 0xbd, 0x35, 0x63,
                0xa9, 0xac, 0x3c, 0x7b, 0xf2, 0x46, 0x26, 0x31, 0x5f, 0x22, 0xd2, 0x84, 0xae, 0x9a,
                0x3a, 0xdb, 0x90, 0x23,
            ])
        );
    }

    #[test]
    fn receipt_is_canonical_and_binds_request_claim_and_lease() {
        let claim = claim();
        let receipt =
            crate::OwnershipTransactionReceiptV1::new(authority(9, 4), &claim, b"canonical lease")
                .unwrap_or_else(|error| panic!("test receipt failed: {error}"));
        let decoded =
            crate::OwnershipTransactionReceiptV1::from_canonical_bytes(receipt.canonical_bytes())
                .unwrap_or_else(|error| panic!("test receipt decode failed: {error}"));
        assert_eq!(decoded, receipt);
        assert!(
            decoded
                .verify_context(&authority(9, 4), &claim, b"canonical lease")
                .is_ok()
        );
        assert!(
            decoded
                .verify_context(&authority(9, 4), &claim, b"different lease")
                .is_err()
        );

        let rebound = OwnershipClaimV1::acquire(
            [8; 16],
            claim.assignment(),
            DesiredGeneration::new(claim.desired_generation().get() + 1),
            claim.node(),
            claim.requested_maximum_seconds(),
        )
        .unwrap_or_else(|error| panic!("test rebound claim failed: {error}"));
        assert!(
            decoded
                .verify_context(&authority(9, 4), &rebound, b"canonical lease")
                .is_err()
        );
        assert!(
            crate::OwnershipTransactionReceiptV1::from_canonical_bytes(
                &receipt.canonical_bytes()[..receipt.canonical_bytes().len() - 1]
            )
            .is_err()
        );
        for offset in [16_usize, 17, 55, 88, 104, 136, 144] {
            let mut mutated = receipt.canonical_bytes().to_vec();
            mutated[offset] ^= 1;
            let rejected = crate::OwnershipTransactionReceiptV1::from_canonical_bytes(&mutated)
                .and_then(|candidate| {
                    candidate.verify_context(&authority(9, 4), &claim, b"canonical lease")?;
                    Ok(candidate)
                });
            assert!(
                rejected.is_err(),
                "mutated receipt field at {offset} was accepted"
            );
        }
    }

    #[test]
    fn request_envelope_rejects_method_confusion() {
        let body = OwnershipRequestBodyV1::Begin(Box::new(claim()));
        assert_eq!(
            session().validate_request_parts(*session().binding(), OwnershipMethodV1::Query, body),
            Err(OwnershipProtocolValidationError::MethodMismatch)
        );
    }

    #[test]
    fn transaction_reference_rejects_sentinels() {
        assert_eq!(
            OwnershipTransactionReferenceV1::new([0; 16], ObjectDigest::from_bytes([1; 32])),
            Err(OwnershipProtocolValidationError::InvalidTransactionReference)
        );
        assert_eq!(
            OwnershipTransactionReferenceV1::new([1; 16], ObjectDigest::from_bytes([0; 32])),
            Err(OwnershipProtocolValidationError::InvalidTransactionReference)
        );
    }

    #[test]
    fn absent_is_query_only() {
        for method in [
            OwnershipMethodV1::Begin,
            OwnershipMethodV1::CompleteOrResume,
        ] {
            let outcome = OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Absent);
            assert_eq!(
                session().response(&request(method), outcome),
                Err(OwnershipProtocolValidationError::InvalidResponseStatus)
            );
        }
    }

    #[test]
    fn status_matrix_allows_exact_replay_and_query_observation() {
        let response =
            UnverifiedOwnershipLeaseResponse::from_transport(vec![1], vec![2], vec![3], vec![4])
                .unwrap_or_else(|error| panic!("test response failed: {error}"));
        for method in [
            OwnershipMethodV1::Begin,
            OwnershipMethodV1::CompleteOrResume,
        ] {
            for status in [
                OwnershipTransactionStatusV1::Pending,
                OwnershipTransactionStatusV1::Completed(response.clone()),
            ] {
                assert!(
                    session()
                        .response(&request(method), OwnershipResponseOutcomeV1::Status(status),)
                        .is_ok()
                );
            }
        }
        for status in [
            OwnershipTransactionStatusV1::Absent,
            OwnershipTransactionStatusV1::Pending,
            OwnershipTransactionStatusV1::Completed(response),
        ] {
            assert!(
                session()
                    .response(
                        &request(OwnershipMethodV1::Query),
                        OwnershipResponseOutcomeV1::Status(status),
                    )
                    .is_ok()
            );
        }
    }

    #[test]
    fn negotiation_pins_exact_authority_epoch_and_canonical_methods() {
        let pinned = authority(9, 4);
        let hello = OwnershipClientHelloV1::new(
            [11; 32],
            ProtocolVersion::new(1, 0),
            pinned.clone(),
            methods(),
            MINIMUM_OWNERSHIP_RESPONSE_BYTES,
        )
        .unwrap_or_else(|error| panic!("test hello failed: {error}"));
        let session =
            NegotiatedOwnershipSessionV1::negotiate(&hello, [12; 32], pinned.clone(), methods())
                .unwrap_or_else(|error| panic!("test negotiation failed: {error}"));
        assert_eq!(session.authority(), &pinned);
        assert_eq!(session.methods(), methods());
        assert_eq!(
            session.binding(),
            &[
                80, 92, 48, 129, 187, 10, 41, 182, 133, 140, 55, 52, 22, 35, 28, 65, 208, 122, 81,
                183, 154, 54, 254, 54, 127, 78, 116, 89, 193, 215, 79, 196,
            ]
        );
        assert_eq!(
            session.maximum_response_bytes(),
            MINIMUM_OWNERSHIP_RESPONSE_BYTES
        );

        assert_eq!(
            NegotiatedOwnershipSessionV1::negotiate(&hello, [12; 32], authority(9, 5), methods()),
            Err(OwnershipProtocolValidationError::WrongAuthorityEpoch)
        );
        assert_eq!(
            NegotiatedOwnershipSessionV1::negotiate(
                &hello,
                [12; 32],
                pinned,
                vec![OwnershipMethodV1::Query, OwnershipMethodV1::Begin],
            ),
            Err(OwnershipProtocolValidationError::InvalidMethodSet)
        );
    }

    #[test]
    fn negotiation_rejects_wrong_usage_zero_generation_and_bounds() {
        let wrong_usage = KeyReference::new(
            StableKeyId::new("broker".to_owned())
                .unwrap_or_else(|error| panic!("test key ID failed: {error}")),
            1,
            ObjectDigest::from_bytes([1; 32]),
            KeyUsage::BrokerAuthorization,
        );
        assert_eq!(
            OwnershipClientHelloV1::new(
                [11; 32],
                ProtocolVersion::new(1, 0),
                wrong_usage,
                methods(),
                MINIMUM_OWNERSHIP_RESPONSE_BYTES,
            ),
            Err(OwnershipProtocolValidationError::InvalidAuthority)
        );
        assert_eq!(
            OwnershipClientHelloV1::new(
                [11; 32],
                ProtocolVersion::new(1, 0),
                authority(1, 0),
                methods(),
                MINIMUM_OWNERSHIP_RESPONSE_BYTES,
            ),
            Err(OwnershipProtocolValidationError::InvalidAuthority)
        );
        assert_eq!(
            OwnershipClientHelloV1::new(
                [11; 32],
                ProtocolVersion::new(1, 0),
                authority(1, 1),
                methods(),
                MINIMUM_OWNERSHIP_RESPONSE_BYTES - 1,
            ),
            Err(OwnershipProtocolValidationError::InvalidResponseBound)
        );
    }

    #[test]
    fn errors_have_fixed_recovery_semantics() {
        assert_eq!(
            OwnershipProtocolErrorCodeV1::Unavailable.recovery(),
            OwnershipErrorRecoveryV1::QueryThenRetryExact
        );
        assert_eq!(
            OwnershipProtocolErrorCodeV1::StaleExpectedPrior.recovery(),
            OwnershipErrorRecoveryV1::RefreshAndReplan
        );
        assert_eq!(
            OwnershipProtocolErrorCodeV1::IntegrityFailure.recovery(),
            OwnershipErrorRecoveryV1::Quarantine
        );
    }

    #[test]
    fn response_binding_rejects_method_request_and_claim_substitution() {
        let session = session();
        let request = session
            .request(OwnershipRequestBodyV1::Begin(Box::new(claim())))
            .unwrap_or_else(|error| panic!("test request failed: {error}"));
        let reference = request.transaction();
        let correct = session
            .response(
                &request,
                OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
            )
            .unwrap_or_else(|error| panic!("test response failed: {error}"));
        assert_eq!(
            validate_response_binding(&session, &request, &correct),
            Ok(())
        );
        assert!(
            session
                .validate_response_parts(
                    &request,
                    *session.binding(),
                    request.method(),
                    reference,
                    OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
                )
                .is_ok()
        );

        assert_eq!(
            session.validate_response_parts(
                &request,
                *session.binding(),
                OwnershipMethodV1::Query,
                reference,
                OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
            ),
            Err(OwnershipProtocolValidationError::ResponseBindingMismatch)
        );
        for substituted in [
            OwnershipTransactionReferenceV1::new([8; 16], reference.claim_digest()),
            OwnershipTransactionReferenceV1::new(
                *reference.request_id(),
                ObjectDigest::from_bytes([9; 32]),
            ),
        ] {
            assert_eq!(
                session.validate_response_parts(
                    &request,
                    *session.binding(),
                    OwnershipMethodV1::Begin,
                    substituted.unwrap_or_else(|error| panic!("test reference failed: {error}")),
                    OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
                ),
                Err(OwnershipProtocolValidationError::ResponseBindingMismatch)
            );
        }
    }

    #[test]
    fn negotiation_rejects_newer_version_and_missing_method() {
        assert_eq!(
            OwnershipClientHelloV1::new(
                [11; 32],
                ProtocolVersion::new(1, 1),
                authority(1, 1),
                methods(),
                MINIMUM_OWNERSHIP_RESPONSE_BYTES,
            ),
            Err(OwnershipProtocolValidationError::IncompatibleProtocol)
        );
        let pinned = authority(2, 1);
        let hello = OwnershipClientHelloV1::new(
            [11; 32],
            ProtocolVersion::new(1, 0),
            pinned.clone(),
            methods(),
            MINIMUM_OWNERSHIP_RESPONSE_BYTES,
        )
        .unwrap_or_else(|error| panic!("test hello failed: {error}"));
        assert_eq!(
            NegotiatedOwnershipSessionV1::negotiate(
                &hello,
                [12; 32],
                pinned,
                vec![OwnershipMethodV1::Begin, OwnershipMethodV1::Query],
            ),
            Err(OwnershipProtocolValidationError::RequiredMethodUnavailable)
        );
    }

    #[test]
    fn session_rejects_unnegotiated_method_and_old_epoch_binding() {
        let pinned = authority(10, 4);
        let hello = OwnershipClientHelloV1::new(
            [13; 32],
            ProtocolVersion::new(1, 0),
            pinned.clone(),
            vec![OwnershipMethodV1::Query],
            MINIMUM_OWNERSHIP_RESPONSE_BYTES,
        )
        .unwrap_or_else(|error| panic!("test hello failed: {error}"));
        let query_only = NegotiatedOwnershipSessionV1::negotiate(
            &hello,
            [14; 32],
            pinned,
            vec![OwnershipMethodV1::Query],
        )
        .unwrap_or_else(|error| panic!("test session failed: {error}"));
        assert_ne!(query_only.binding(), &[0; 32]);
        assert_eq!(
            query_only.request(OwnershipRequestBodyV1::Begin(Box::new(claim()))),
            Err(OwnershipProtocolValidationError::MethodUnavailable)
        );
        let query_request = query_only
            .request(OwnershipRequestBodyV1::Query(
                OwnershipTransactionReferenceV1::from_claim(&claim()),
            ))
            .unwrap_or_else(|error| panic!("test query request failed: {error}"));
        assert_eq!(
            query_only.validate_response_parts(
                &query_request,
                *query_only.binding(),
                OwnershipMethodV1::Begin,
                query_request.transaction(),
                OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
            ),
            Err(OwnershipProtocolValidationError::MethodUnavailable),
        );

        let current = session();
        let request = current
            .request(OwnershipRequestBodyV1::Begin(Box::new(claim())))
            .unwrap_or_else(|error| panic!("test request failed: {error}"));
        let response = current
            .response(
                &request,
                OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
            )
            .unwrap_or_else(|error| panic!("test response failed: {error}"));
        assert_eq!(
            validate_response_binding(&query_only, &request, &response),
            Err(OwnershipProtocolValidationError::SessionBindingMismatch)
        );
    }

    #[test]
    fn reconnect_nonces_produce_distinct_bindings_and_reject_old_responses() {
        let pinned = authority(9, 4);
        let hello = OwnershipClientHelloV1::new(
            [21; 32],
            ProtocolVersion::new(1, 0),
            pinned.clone(),
            methods(),
            MINIMUM_OWNERSHIP_RESPONSE_BYTES,
        )
        .unwrap_or_else(|error| panic!("test hello failed: {error}"));
        let first =
            NegotiatedOwnershipSessionV1::negotiate(&hello, [22; 32], pinned.clone(), methods())
                .unwrap_or_else(|error| panic!("test first session failed: {error}"));
        let second = NegotiatedOwnershipSessionV1::negotiate(&hello, [23; 32], pinned, methods())
            .unwrap_or_else(|error| panic!("test second session failed: {error}"));
        assert_ne!(first.binding(), second.binding());
        let next_hello = OwnershipClientHelloV1::new(
            [24; 32],
            ProtocolVersion::new(1, 0),
            authority(9, 4),
            methods(),
            MINIMUM_OWNERSHIP_RESPONSE_BYTES,
        )
        .unwrap_or_else(|error| panic!("test reconnect hello failed: {error}"));
        let third = NegotiatedOwnershipSessionV1::negotiate(
            &next_hello,
            [22; 32],
            authority(9, 4),
            methods(),
        )
        .unwrap_or_else(|error| panic!("test third session failed: {error}"));
        assert_ne!(first.binding(), third.binding());
        let request = first
            .request(OwnershipRequestBodyV1::Begin(Box::new(claim())))
            .unwrap_or_else(|error| panic!("test request failed: {error}"));
        let response = first
            .response(
                &request,
                OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
            )
            .unwrap_or_else(|error| panic!("test response failed: {error}"));
        assert_eq!(
            validate_response_binding(&second, &request, &response),
            Err(OwnershipProtocolValidationError::SessionBindingMismatch),
        );
        assert_eq!(
            second.validate_response_parts(
                &request,
                *first.binding(),
                request.method(),
                request.transaction(),
                OwnershipResponseOutcomeV1::Status(OwnershipTransactionStatusV1::Pending),
            ),
            Err(OwnershipProtocolValidationError::SessionBindingMismatch),
        );

        assert_eq!(
            OwnershipClientHelloV1::new(
                [0; 32],
                ProtocolVersion::new(1, 0),
                authority(9, 4),
                methods(),
                MINIMUM_OWNERSHIP_RESPONSE_BYTES,
            ),
            Err(OwnershipProtocolValidationError::InvalidNonce),
        );
        assert_eq!(
            NegotiatedOwnershipSessionV1::negotiate(&hello, [0; 32], authority(9, 4), methods(),),
            Err(OwnershipProtocolValidationError::InvalidNonce),
        );
    }

    #[test]
    fn method_error_matrix_is_closed() {
        let session = session();
        let errors = [
            OwnershipProtocolErrorCodeV1::InvalidRequest,
            OwnershipProtocolErrorCodeV1::Unauthenticated,
            OwnershipProtocolErrorCodeV1::PermissionDenied,
            OwnershipProtocolErrorCodeV1::IncompatibleProtocol,
            OwnershipProtocolErrorCodeV1::RequiredCapabilityUnavailable,
            OwnershipProtocolErrorCodeV1::WrongAuthorityEpoch,
            OwnershipProtocolErrorCodeV1::IdempotencyConflict,
            OwnershipProtocolErrorCodeV1::AlreadyOwned,
            OwnershipProtocolErrorCodeV1::StaleExpectedPrior,
            OwnershipProtocolErrorCodeV1::NotFound,
            OwnershipProtocolErrorCodeV1::ResourceExhausted,
            OwnershipProtocolErrorCodeV1::DeadlineExceeded,
            OwnershipProtocolErrorCodeV1::Unavailable,
            OwnershipProtocolErrorCodeV1::IntegrityFailure,
            OwnershipProtocolErrorCodeV1::Internal,
        ];
        for method in methods() {
            for error in errors {
                let expected = match method {
                    OwnershipMethodV1::Begin => !matches!(
                        error,
                        OwnershipProtocolErrorCodeV1::StaleExpectedPrior
                            | OwnershipProtocolErrorCodeV1::NotFound
                    ),
                    OwnershipMethodV1::CompleteOrResume => {
                        !matches!(error, OwnershipProtocolErrorCodeV1::ResourceExhausted)
                    }
                    OwnershipMethodV1::Query => !matches!(
                        error,
                        OwnershipProtocolErrorCodeV1::AlreadyOwned
                            | OwnershipProtocolErrorCodeV1::StaleExpectedPrior
                            | OwnershipProtocolErrorCodeV1::NotFound
                            | OwnershipProtocolErrorCodeV1::ResourceExhausted
                    ),
                };
                assert_eq!(
                    session
                        .response(&request(method), OwnershipResponseOutcomeV1::Error(error))
                        .is_ok(),
                    expected,
                    "unexpected matrix result for {method:?}/{error:?}",
                );
            }
        }

        let acquired = claim();
        let renew = OwnershipClaimV1::renew(
            [11; 16],
            acquired.assignment(),
            DesiredGeneration::new(7),
            acquired.node(),
            crate::ExpectedOwnershipLease::new(6, ObjectDigest::from_bytes([12; 32]))
                .unwrap_or_else(|error| panic!("test fence failed: {error}")),
            60,
        )
        .unwrap_or_else(|error| panic!("test renewal failed: {error}"));
        let renew_request = session
            .request(OwnershipRequestBodyV1::Begin(Box::new(renew)))
            .unwrap_or_else(|error| panic!("test request failed: {error}"));
        assert!(
            session
                .response(
                    &renew_request,
                    OwnershipResponseOutcomeV1::Error(
                        OwnershipProtocolErrorCodeV1::StaleExpectedPrior
                    )
                )
                .is_ok()
        );
        assert_eq!(
            session.response(
                &renew_request,
                OwnershipResponseOutcomeV1::Error(OwnershipProtocolErrorCodeV1::AlreadyOwned)
            ),
            Err(OwnershipProtocolValidationError::InvalidResponseError),
        );
    }
}
