[package]
name = "crucible-cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "crucible"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
crucible-api = { path = "../crucible-api" }
crucible-session = { path = "../crucible-session" }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
crucible = { path = "../crucible", features = ["test-double"] }
crucible-harness = { path = "../crucible-harness" }
crucible-protocol = { path = "../crucible-protocol" }
libc = { workspace = true }
serde_json = { workspace = true }
