[package]
name = "crucible-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[features]
default = []
test-double = ["crucible-session/test-double"]

[[bin]]
name = "crucible"
path = "src/main.rs"

[[test]]
name = "machine_readable"
path = "tests/machine_readable.rs"
required-features = ["test-double"]

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
crucible-api = { path = "../crucible-api" }
crucible-campaign = { path = "../crucible-campaign" }
crucible-daemon = { path = "../crucible-daemon" }
crucible-session = { path = "../crucible-session" }
rustix = { workspace = true, features = ["process", "termios"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
toml = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
crucible-cas = { path = "../crucible-cas" }
crucible-harness = { path = "../crucible-harness" }
libc = { workspace = true }
