[package]
name = "crucible-linux-resource"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[lints]
workspace = true

[features]
default = ["cas"]
cas = ["dep:crucible-cas"]

[dependencies]
crucible-cas = { workspace = true, optional = true }
libc = { workspace = true }
rustix = { workspace = true }
thiserror = { workspace = true }
