[package]
name = "crucible-linux-resource"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
libc = { workspace = true }
rustix = { workspace = true, features = ["time"] }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
