##! X11 headers and stub libraries for headless builds
##!
##! Provides X11 protocol headers, Xlib headers, and empty stub shared
##! libraries.  This is NOT a full X11 stack — it exists only so that
##! headless-only packages (e.g. OpenJDK) can compile their AWT code
##! without pulling in a real X server or libxcb.
{
  mkDerivation,
  fetchurl,
  gnumake,
}:
let
  # ── sources ──────────────────────────────────────────────────────────
  xorgprotoSrc = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/proto/xorgproto-2024.1.tar.xz"
    ];
    hash = "sha256-NyIl/UCBW4QjVH9diQxd68cuiLkQiPv7ExWMIElcy1k=";
  };

  libX11Src = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/lib/libX11-1.8.10.tar.xz"
    ];
    hash = "sha256-Kzs9rZNH20HcpWvrfbWHjyg73hFC8E2fjkeK9DXf3FM=";
  };

  libXextSrc = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/lib/libXext-1.3.6.tar.xz"
    ];
    hash = "sha256-7bWfojmU5AX9xbQAr99YIK5hYLlPNePcPaRFehbol1M=";
  };

  libXrenderSrc = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/lib/libXrender-0.9.12.tar.xz"
    ];
    hash = "sha256-uDISjaSLOcjWCCJEgXQ0A60Wkb9OVU5L6cF03xcdG5c=";
  };

  libXtstSrc = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/lib/libXtst-1.2.5.tar.xz"
    ];
    hash = "sha256-tQ1MJblwCadEcGwQOcWY9NjmSRDJ/eOBmU4criNdkkI=";
  };

  libXiSrc = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/lib/libXi-1.8.2.tar.xz"
    ];
    hash = "sha256-0OBVXlPW4hFOq/pEImuhYtJwhQGiXhjZnPs1wJTGwQQ=";
  };

  libXtSrc = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/lib/libXt-1.3.1.tar.xz"
    ];
    hash = "sha256-4Kd0szMk9NTAWxmepFBQ+HIGWG2BZV+L7026Q02TEog=";
  };

  libXrandrSrc = fetchurl {
    urls = [
      "https://xorg.freedesktop.org/archive/individual/lib/libXrandr-1.5.4.tar.xz"
    ];
    hash = "sha256-GtWwZTdfSoWRWqYGEcxkB8BgSSohTX+dryFL51LDtNM=";
  };
in
mkDerivation {
  pname = "xorg-stubs";
  version = "2024.1";

  # Dummy src — we use the fetchurl results directly in phases
  src = xorgprotoSrc;

  buildDeps = [ gnumake ];
  runtimeDeps = [ ];
  propagatedDeps = [ ];

  phases = [
    {
      name = "install";
      script = ''
        mkdir -p $out/include/X11/extensions $out/lib

        # ── 1. xorgproto headers (X11 protocol) ──────────────────────
        mkdir -p /tmp/xorg-work
        cd /tmp/xorg-work
        tar xf ${xorgprotoSrc}
        cp -a xorgproto-*/include/X11/* $out/include/X11/

        # ── 2. libX11 headers (Xlib) ─────────────────────────────────
        tar xf ${libX11Src}
        cp -a libX11-*/include/X11/*.h $out/include/X11/
        # Create XlibConf.h (normally generated by configure)
        cat > $out/include/X11/XlibConf.h << 'XLIBCONF'
        #ifndef _XLIBCONF_H_
        #define _XLIBCONF_H_
        #define XTHREADS 1
        #define XUSE_MTSAFE_API 1
        #endif
        XLIBCONF

        # ── 3. libXext headers ────────────────────────────────────────
        tar xf ${libXextSrc}
        cp -a libXext-*/include/X11/extensions/*.h $out/include/X11/extensions/

        # ── 4. libXrender headers ─────────────────────────────────────
        tar xf ${libXrenderSrc}
        cp -a libXrender-*/include/X11/extensions/*.h $out/include/X11/extensions/

        # ── 5. libXtst headers ────────────────────────────────────────
        tar xf ${libXtstSrc}
        cp -a libXtst-*/include/X11/extensions/*.h $out/include/X11/extensions/

        # ── 6. libXi headers ─────────────────────────────────────────
        tar xf ${libXiSrc}
        cp -a libXi-*/include/X11/extensions/*.h $out/include/X11/extensions/

        # ── 7. libXt headers ─────────────────────────────────────────
        tar xf ${libXtSrc}
        cp -a libXt-*/include/X11/*.h $out/include/X11/

        # ── 8. libXrandr headers ────────────────────────────────────
        tar xf ${libXrandrSrc}
        cp -a libXrandr-*/include/X11/extensions/*.h $out/include/X11/extensions/

        # ── 9. Stub shared libraries for linking ─────────────────────
        # OpenJDK links against these but never calls them in headless mode.
        for lib in X11 Xext Xrender Xtst Xi Xt Xrandr; do
          echo "void _xorg_stub_''${lib}(void){}" | \
            gcc -shared -o $out/lib/lib''${lib}.so -x c - -Wl,-soname,lib''${lib}.so
        done
      '';
    }
  ];

  meta = {
    description = "X11 headers and stub libraries for headless builds";
    homepage = "https://www.x.org";
    license = "MIT";
  };
}
