##! Package-owned SELinux policy configuration and lifecycle services.
{
  config,
  lib,
  packageName,
  ...
}: let
  cfg = config.aos.security.selinux;
  abilityTypes = lib.abilities.types;
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  serviceTypes = serviceManagement.types;
  interfaces = serviceManagement.interfaces;
  resultOf = lib.abilities.resultOf;
  consumerInstance = "selinux";

  command = artifact: entryPoint: arguments: {
    executable = {
      inherit artifact arguments;
      entry_point = entryPoint;
    };
    ignore_failure = false;
  };
  producer = key: interface: parameters:
    serviceManagement.forProducer {
      inherit consumerInstance key interface parameters;
    };
  localFilesystems = producer "local-filesystems" interfaces.filesystemReadiness {
    scope = "local-filesystems";
  };
  policyState = producer "policy-state" interfaces.persistentStorageAllocation {
    name = "selinux-policy-state";
    purpose = "state";
    mode = "0700";
    requested_path = "/var/lib/selinux";
    owner = "root";
    group = "root";
  };
  earlySystem = producer "early-system" interfaces.activationMilestone {
    milestone = "early-system";
  };
  runtimeEntryPopulation = producer "runtime-entry-population" interfaces.runtimeEntryPopulation {
    entries = [];
  };

  selinuxConfiguration = serviceManagement.forConfiguration {
    inherit serviceTypes consumerInstance;
    declaration = {
      name = "selinux-config-source";
      source = {
        kind = "inline-text";
        content = ''
          # Generated by the refpolicy package ability module.
          SELINUX=${cfg.mode}
          SELINUXTYPE=${cfg.policy}
        '';
      };
      mode = "0444";
    };
  };
  semanageConfiguration = serviceManagement.forConfiguration {
    inherit serviceTypes consumerInstance;
    declaration = {
      name = "semanage-config-source";
      source = {
        kind = "interpolated-text";
        maximum_size_bytes = abilityTypes.limits.maxDocumentBytes;
        fragments = [
          {
            kind = "literal";
            text = ''
              # Generated by the refpolicy package ability module.
              module-store = direct
              handle-unknown = allow
              compiler-directory =
            '';
          }
          {
            kind = "artifact-directory-path";
            reference = {
              artifact = lib.abilities.packageOutput {package = "policycoreutils";};
              path = "libexec/selinux/hll";
            };
          }
          {
            kind = "literal";
            text = ''

              [load_policy]
              path =
            '';
          }
          {
            kind = "artifact-file-path";
            reference = {
              artifact = lib.abilities.packageOutput {package = "policycoreutils";};
              path = "sbin/load_policy";
            };
          }
          {
            kind = "literal";
            text = ''

              args =
              [end]

              [setfiles]
              path =
            '';
          }
          {
            kind = "artifact-file-path";
            reference = {
              artifact = lib.abilities.packageOutput {package = "policycoreutils";};
              path = "sbin/setfiles";
            };
          }
          {
            kind = "literal";
            text = ''

              args = -q -c $@ $<
              [end]

              [sefcontext_compile]
              path =
            '';
          }
          {
            kind = "artifact-file-path";
            reference = {
              artifact = lib.abilities.packageOutput {package = "libselinux";};
              path = "sbin/sefcontext_compile";
            };
          }
          {
            kind = "literal";
            text = ''

              args = $@
              [end]
            '';
          }
        ];
      };
      mode = "0444";
    };
  };
  configurationFiles = serviceManagement.forProducers {
    inherit consumerInstance;
    interface = interfaces.filesystemEntry;
    methods = ["materialize" "observe" "release"];
    producers = [
      {
        key = "selinux-config";
        parameters = {
          name = "selinux-config";
          entry = {
            kind = "copied-file";
            source = {
              kind = "execution-path";
              resource = resultOf "selinux-config-source" "resource";
              path = resultOf "selinux-config-source" "planned-path";
            };
            maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
          };
          destination = "/etc/selinux/config";
          owner = "root";
          group = "root";
          mode = "0444";
          prerequisites = [
            (resultOf "selinux-config-source" "resource")
            (resultOf "local-filesystems" "resource")
          ];
        };
      }
      {
        key = "semanage-config";
        parameters = {
          name = "semanage-config";
          entry = {
            kind = "copied-file";
            source = {
              kind = "execution-path";
              resource = resultOf "semanage-config-source" "resource";
              path = resultOf "semanage-config-source" "planned-path";
            };
            maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
          };
          destination = "/etc/selinux/semanage.conf";
          owner = "root";
          group = "root";
          mode = "0444";
          prerequisites = [
            (resultOf "semanage-config-source" "resource")
            (resultOf "local-filesystems" "resource")
          ];
        };
      }
    ];
  };

  policyLoad = serviceManagement.forService {
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "selinux-policy-load";
      enabled = true;
      lifecycle = {
        description = "Load SELinux policy";
        execution_model = "oneshot";
        environment_files = [];
        condition = [];
        pre_start = [];
        start = [
          (command
            (lib.abilities.packageOutput {})
            "libexec/aos-selinux-load-policy"
            [cfg.policy cfg.mode])
        ];
        post_start = [];
        stop = [];
        post_stop = [];
        restart = "never";
        restart_delay_millis = 0;
        configuration_change_action = "restart";
        remain_after_exit = true;
        start_timeout_millis = 90000;
        stop_timeout_millis = 90000;
      };
      conditions.all = [
        {
          kind = "mandatory-access-control";
          state = "available";
          negated = false;
        }
      ];
      dependencies = {
        after = [
          (resultOf "local-filesystems" "resource")
          (resultOf "policy-state" "resource")
        ];
        before = [
          (resultOf "early-system" "resource")
          (resultOf "runtime-entry-population" "resource")
        ];
        requires = [
          (resultOf "policy-state" "resource")
          (resultOf "selinux-config" "resource")
          (resultOf "semanage-config" "resource")
        ];
        wants = [];
        wanted_by = [(resultOf "early-system" "resource")];
      };
      readiness = {
        mechanism = "successful-exit";
        signal_scope = "none";
        timeout_millis = 90000;
      };
    };
  };
  autorelabel = serviceManagement.forService {
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "selinux-autorelabel";
      enabled = cfg.autorelabel;
      lifecycle = {
        description = "SELinux filesystem relabeling";
        execution_model = "oneshot";
        environment_files = [];
        condition = [
          (command
            (lib.abilities.packageOutput {package = "coreutils";})
            "bin/test"
            ["-f" "/.autorelabel"])
        ];
        pre_start = [];
        start = [
          (command
            (lib.abilities.packageOutput {package = "policycoreutils";})
            "sbin/fixfiles"
            ["-f" "-F" "relabel"])
        ];
        post_start = [
          (command
            (lib.abilities.packageOutput {package = "coreutils";})
            "bin/rm"
            ["-f" "/.autorelabel"])
        ];
        stop = [];
        post_stop = [];
        restart = "never";
        restart_delay_millis = 0;
        configuration_change_action = "restart";
        remain_after_exit = true;
        start_timeout_millis = 90000;
        stop_timeout_millis = 90000;
      };
      dependencies = {
        after = [
          (resultOf "selinux-policy-load-lifecycle" "resource")
          (resultOf "local-filesystems" "resource")
        ];
        before = [(resultOf "early-system" "resource")];
        requires = [(resultOf "selinux-policy-load-lifecycle" "resource")];
        wants = [];
        wanted_by = [(resultOf "early-system" "resource")];
      };
      readiness = {
        mechanism = "successful-exit";
        signal_scope = "none";
        timeout_millis = 90000;
      };
    };
  };

  fragments = [
    localFilesystems
    policyState
    earlySystem
    runtimeEntryPopulation
    selinuxConfiguration
    semanageConfiguration
    configurationFiles
    policyLoad
    autorelabel
  ];
  contributions = builtins.map serviceManagement.splitContribution fragments;
in {
  options.aos.security.selinux = {
    enable = lib.mkOption {
      type = abilityTypes.boolean;
      default = false;
      description = "Enable SELinux mandatory access control.";
    };
    mode = lib.mkOption {
      type = abilityTypes.enum ["enforcing" "permissive" "disabled"];
      default = "enforcing";
      description = "SELinux operating mode.";
    };
    policy = lib.mkOption {
      type = abilityTypes.localKey;
      default = "refpolicy";
      description = "SELinux policy store name to load.";
    };
    autorelabel = lib.mkOption {
      type = abilityTypes.boolean;
      default = true;
      description = "Relabel the root filesystem when /.autorelabel exists.";
    };
  };

  config = lib.mkMerge [
    {aos.abilities = lib.mkMerge (builtins.map (entry: entry.declarations) contributions);}
    (lib.mkIf cfg.enable {
      aos.contributions = {
        kernelParameters.refpolicy = [
          "enforcing=0"
          "security=selinux"
          "selinux=1"
        ];
        filesystemTrees = [
          {
            target = "selinux/${cfg.policy}/contexts";
            source = {
              artifact = lib.abilities.packageOutput {package = packageName;};
              path = "etc/selinux/refpolicy/contexts";
            };
          }
        ];
        runtimeChecks.selinux = {
          description = "SELinux checks";
          checks = [
            {
              name = "selinuxfs";
              description = "/sys/fs/selinux is present";
              script = ''
                vm.succeed("test -d /sys/fs/selinux")
              '';
            }
            {
              name = "enforce-file";
              description = "SELinux enforce file exists";
              script = ''
                vm.succeed("test -f /sys/fs/selinux/enforce")
              '';
            }
          ];
        };
      };
      aos.abilities = lib.mkMerge (
        [{instances.${consumerInstance} = {};}]
        ++ builtins.map (entry: entry.configured) contributions
      );
    })
  ];
}
