##! modules/monitoring/alloy.nix — Grafana Alloy observability agent module
##!
##! Configures Grafana Alloy (formerly Grafana Agent) as a unified
##! observability pipeline. Alloy collects metrics, logs, and traces
##! and ships them to Grafana Cloud, Prometheus, Loki, Tempo, or other
##! compatible backends. It uses the River configuration language for
##! defining pipelines, components, and destinations.
##!
##! Options:
##!   [monitoring.alloy] enable, configFile, extraArgs
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.monitoring.alloy;

  # Build the complete command-line flags.
  alloyFlags = builtins.concatStringsSep " " (
    ["--config.file=/etc/alloy/config.alloy"] ++ cfg.extraArgs
  );
in {
  options.aos.monitoring.alloy = {
    ## Enable the Grafana Alloy observability agent.
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable the Grafana Alloy observability agent. Alloy provides a
        unified pipeline for collecting and shipping metrics, logs, and
        traces to Grafana Cloud or compatible backends.
      '';
    };

    ## Grafana Alloy configuration in River format.
    configFile = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = ''
        Grafana Alloy configuration in River format. This defines the
        complete observability pipeline including sources, processors,
        and exporters. See the Alloy documentation for River syntax.
      '';
    };

    ## Additional command-line arguments for the Alloy binary.
    extraArgs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = ''
        Additional command-line arguments passed to the Alloy binary.
        Example: [ "--server.http.listen-addr=0.0.0.0:12345" ]
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [pkgs.alloy];

    # /etc/alloy/config.alloy — Grafana Alloy pipeline configuration.
    environment.etc."alloy/config.alloy" = {
      text =
        if cfg.configFile != ""
        then cfg.configFile
        else ''
          // /etc/alloy/config.alloy — generated by modules/monitoring/alloy.nix
          // Do not edit manually.
          //
          // No pipeline configured. Add components via aos.monitoring.alloy.configFile.
        '';
    };

    # alloy.service — Grafana Alloy observability agent.
    systemd.services."alloy" = {
      description = "Grafana Alloy Observability Agent";
      wantedBy = ["multi-user.target"];
      after = ["network-online.target"];
      wants = ["network-online.target"];
      serviceConfig = {
        Type = "simple";
        ExecStart = "${pkgs.alloy}/bin/alloy run ${alloyFlags}";
        ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        Restart = "on-failure";
        RestartSec = "5s";
        # Run as a dedicated user.
        DynamicUser = true;
        User = "alloy";
        Group = "alloy";
        # Security hardening.
        ProtectSystem = "full";
        ProtectHome = true;
        NoNewPrivileges = true;
        PrivateTmp = true;
        RuntimeDirectory = "alloy";
        RuntimeDirectoryMode = "0750";
        # Alloy may need to read /proc and /sys for host metrics.
        ProtectKernelTunables = false;
        ProtectControlGroups = false;
        # Resource limits.
        MemoryMax = "512M";
      };
    };

    # Ensure Alloy state directories exist.
    environment.etc."tmpfiles.d/aos-alloy.conf" = {
      text = ''
        # Alloy state directories.
        d /var/lib/alloy 0750 alloy alloy -
      '';
    };
  };
}
