##! modules/monitoring/hardware.nix — Hardware monitoring module
##!
##! Configures hardware health monitoring including systemd watchdog
##! timers, S.M.A.R.T. disk health checks (via smartd), and thermal
##! throttling detection. The watchdog ensures the system reboots if
##! the kernel or systemd becomes unresponsive. SMART monitoring
##! provides early warning of disk failures.
##!
##! Options:
##!   [monitoring.hardware] enable, watchdog, watchdogTimeout, smartd
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.monitoring.hardware;

  # Watchdog configuration for systemd's system.conf.d drop-in.
  watchdogConf = ''
    # /etc/systemd/system.conf.d/watchdog.conf — generated by modules/monitoring/hardware.nix
    # Do not edit manually.

    [Manager]
    RuntimeWatchdogSec=${toString cfg.watchdogTimeout}
    RebootWatchdogSec=${toString (cfg.watchdogTimeout * 2)}
    KExecWatchdogSec=${toString (cfg.watchdogTimeout * 2)}
  '';
in {
  options.aos.monitoring.hardware = {
    ## Enable the systemd hardware watchdog.
    ##
    ## # See Also
    ## - `aos.monitoring.hardware.watchdogTimeout`
    watchdog = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Enable the systemd hardware watchdog. If the kernel or systemd
        becomes unresponsive for longer than watchdogTimeout, the system
        will be automatically rebooted. Requires a hardware watchdog
        device (/dev/watchdog).
      '';
    };

    ## Watchdog timeout in seconds before triggering a reboot.
    watchdogTimeout = lib.mkOption {
      type = lib.types.int;
      default = 30;
      description = ''
        Watchdog timeout in seconds. If systemd does not pet the watchdog
        within this interval, the hardware watchdog triggers a reboot.
        The reboot watchdog is set to 2x this value.
      '';
    };

    # `thermalThrottling` was removed in the systemd refactor
    # (spec v3.1 §6.10). The previous implementation declared
    # `systemd.services."thermal-check.timer"` — a misuse pattern
    # that stuffed `[Timer]` directives into a `[Service]` section
    # of a file named `thermal-check.timer.service`, which systemd
    # silently ignored. Re-add when actually needed, declaring a
    # proper `systemd.services.thermal-check` + `systemd.timers.
    # thermal-check` pair.
  };

  config = lib.mkMerge [
    {
      environment.systemPackages = [pkgs.smartmontools];
    }
    (lib.mkIf cfg.enable {
      # Watchdog configuration drop-in for systemd.
      environment.etc."systemd/system.conf.d/watchdog.conf" = lib.mkIf cfg.watchdog {
        text = watchdogConf;
      };
    })
  ];
}
