//! Checks the shared-memory ABI against frozen cross-language vectors.

#![forbid(unsafe_code)]

use std::panic::{AssertUnwindSafe, catch_unwind};

use crucible_shmem::{
    ABI_VERSION, ACCELERATOR_ENTRY_CLASS_OFFSET, ACCELERATOR_ENTRY_DATA_LEN_OFFSET,
    ACCELERATOR_ENTRY_DATA_OFFSET, ACCELERATOR_ENTRY_DEVICE_ID_OFFSET,
    ACCELERATOR_ENTRY_GENERATION_OFFSET, ACCELERATOR_ENTRY_JOB_KIND_OFFSET,
    ACCELERATOR_ENTRY_PROTOCOL_VERSION_OFFSET, ACCELERATOR_ENTRY_QUEUE_ID_OFFSET,
    ACCELERATOR_ENTRY_SEQUENCE_OFFSET, ACCELERATOR_ENTRY_SERVICE_UNITS_OFFSET,
    ACCELERATOR_ENTRY_SIZE, COVERAGE_ENTRY_BLOCK_LEN_OFFSET, COVERAGE_ENTRY_CURRENT_ICOUNT_OFFSET,
    COVERAGE_ENTRY_GUEST_PC_OFFSET, COVERAGE_ENTRY_MAP_INDEX_OFFSET, COVERAGE_ENTRY_SIZE,
    COVERAGE_ENTRY_VCPU_INDEX_OFFSET, FRAME_ENTRY_DATA_OFFSET, FRAME_ENTRY_DELIVERY_ICOUNT_OFFSET,
    FRAME_ENTRY_LEN_OFFSET, FRAME_ENTRY_SEQ_OFFSET, FRAME_ENTRY_SIZE, FRAME_ENTRY_SRC_NODE_OFFSET,
    FrameEntry, GUEST_INTROSPECTION_ENTRY_DATA_OFFSET, GUEST_INTROSPECTION_ENTRY_LEN_OFFSET,
    GUEST_INTROSPECTION_ENTRY_SEQUENCE_OFFSET, GUEST_INTROSPECTION_ENTRY_SIZE, MAX_FRAME_DATA,
    NODE_SLOT_CONTROL_BOUNDARY_ACK_OFFSET, NODE_SLOT_CURRENT_ICOUNT_OFFSET,
    NODE_SLOT_CURRENT_NS_OFFSET, NODE_SLOT_DEVICE_IO_ACTIVE_OFFSET,
    NODE_SLOT_IDLE_WAKE_ICOUNT_OFFSET, NODE_SLOT_KIND_OFFSET,
    NODE_SLOT_LOGICAL_TIME_RAW_ICOUNT_OFFSET, NODE_SLOT_LOGICAL_TIME_RESTORE_ACK_OFFSET,
    NODE_SLOT_LOGICAL_TIME_RESTORE_REQUEST_OFFSET, NODE_SLOT_LOGICAL_TIME_RESTORE_TARGET_OFFSET,
    NODE_SLOT_MAX_ADVANCE_ICOUNT_OFFSET, NODE_SLOT_PREEMPTION_ARG0_OFFSET,
    NODE_SLOT_PREEMPTION_ARG1_OFFSET, NODE_SLOT_PREEMPTION_AT_ICOUNT_OFFSET,
    NODE_SLOT_PREEMPTION_CEILING_ICOUNT_OFFSET, NODE_SLOT_PREEMPTION_CONSUMED_SEQUENCE_OFFSET,
    NODE_SLOT_PREEMPTION_DEADLINE_ICOUNT_OFFSET, NODE_SLOT_PREEMPTION_KIND_OFFSET,
    NODE_SLOT_PREEMPTION_PUBLISHED_SEQUENCE_OFFSET, NODE_SLOT_PUBLISH_GEN_OFFSET, NODE_SLOT_SIZE,
    NODE_SLOT_STATUS_OFFSET, NODE_SLOT_WAKE_SIGNAL_OFFSET, PREEMPTION_KIND_VCPU_SWITCH,
    REGION_HEADER_ABI_VERSION_OFFSET, REGION_HEADER_ENTRY_STRIDE_OFFSET,
    REGION_HEADER_FAULT_PAYLOAD_ARENA_BYTES_OFFSET, REGION_HEADER_ICOUNT_SHIFT_OFFSET,
    REGION_HEADER_MAGIC_OFFSET, REGION_HEADER_NODE_COUNT_OFFSET,
    REGION_HEADER_PAUSE_REQUESTED_OFFSET, REGION_HEADER_QUEUE_CAPACITY_OFFSET,
    REGION_HEADER_REGION_SIZE_OFFSET, REGION_HEADER_RING_COUNT_OFFSET,
    REGION_HEADER_RING_DATA_OFF_OFFSET, REGION_HEADER_RING_HDR_OFF_OFFSET,
    REGION_HEADER_SHUTDOWN_REQUESTED_OFFSET, REGION_HEADER_SIZE, REGION_MAGIC,
    RING_HEADER_READ_IDX_OFFSET, RING_HEADER_SIZE, RING_HEADER_WRITE_IDX_OFFSET, RegionConfig,
    RegionLayout, STATUS_IDLE, SpscRingSnapshot, WHITEBOX_MARKER_ENTRY_CURRENT_ICOUNT_OFFSET,
    WHITEBOX_MARKER_ENTRY_KIND_OFFSET, WHITEBOX_MARKER_ENTRY_PAYLOAD_LEN_OFFSET,
    WHITEBOX_MARKER_ENTRY_PAYLOAD_OFFSET, WHITEBOX_MARKER_ENTRY_SIZE,
    WHITEBOX_MARKER_ENTRY_VCPU_INDEX_OFFSET, generated_c_header,
};

const COMMITTED_HEADER: &str = include_str!("../include/crucible_shmem_abi.h");
const GOLDEN_VECTOR_FIXTURE: &str = include_str!("fixtures/shmem_abi_golden.fixture");

const GOLDEN_VM_NODE_COUNT: u32 = 2;
const GOLDEN_QUEUE_CAPACITY: u32 = 8;
const GOLDEN_ICOUNT_SHIFT: u32 = 4;
const GOLDEN_NODE_SLOT_BASE: usize = REGION_HEADER_SIZE;
const GOLDEN_RING_HEADER_BASE: usize = GOLDEN_NODE_SLOT_BASE + NODE_SLOT_SIZE;
const GOLDEN_FRAME_ENTRY_BASE: usize = GOLDEN_RING_HEADER_BASE + RING_HEADER_SIZE;
const GOLDEN_COVERAGE_ENTRY_BASE: usize = GOLDEN_FRAME_ENTRY_BASE + FRAME_ENTRY_SIZE;
const GOLDEN_WHITEBOX_MARKER_ENTRY_BASE: usize = GOLDEN_COVERAGE_ENTRY_BASE + COVERAGE_ENTRY_SIZE;
const GOLDEN_GUEST_INTROSPECTION_ENTRY_BASE: usize =
    GOLDEN_WHITEBOX_MARKER_ENTRY_BASE + WHITEBOX_MARKER_ENTRY_SIZE;
const GOLDEN_ACCELERATOR_ENTRY_BASE: usize =
    GOLDEN_GUEST_INTROSPECTION_ENTRY_BASE + GUEST_INTROSPECTION_ENTRY_SIZE;
const GOLDEN_TOTAL_LEN: usize = GOLDEN_ACCELERATOR_ENTRY_BASE + ACCELERATOR_ENTRY_SIZE;
const GOLDEN_GUEST_INTROSPECTION_RECORD: &[u8] =
    b"CRGI\x01\x00\x07\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00";

#[path = "gate_abi_conformance/gate_cases.rs"]
mod gate_cases;

#[path = "gate_abi_conformance/decode.rs"]
mod decode;
#[path = "gate_abi_conformance/encode.rs"]
mod encode;
#[path = "gate_abi_conformance/fixture_parser.rs"]
mod fixture_parser;
#[path = "gate_abi_conformance/golden_bytes.rs"]
mod golden_bytes;
#[path = "gate_abi_conformance/snapshot.rs"]
mod snapshot;
#[path = "gate_abi_conformance/types.rs"]
mod types;

use decode::*;
use encode::*;
use fixture_parser::*;
use golden_bytes::*;
use snapshot::*;
use types::*;
