//! The systemd unit-graph compiler for configuration manifests.
//!
//! `aos-eval.service` produces two read-only inputs — `/run/aos/manifest.json`
//! (the resolved package set + config) and `/run/aos/graph.json` (the
//! cross-package read/write DAG) — and never activates. This module is the
//! `aos-graph-compile.service` body that turns those inputs into a runtime
//! systemd graph so that systemd's own ordering, parallelism, and failure
//! isolation drive provisioning, rather than a monolithic `apm install`.
//!
//! # What it writes
//!
//! Everything heavyweight (the `aos-pkg-fetch@.service` / `aos-pkg-install@.service`
//! template bodies, sandboxing, the three targets) is image-baked into gen-0
//! (`modules/systemd/graph.nix`). At runtime the compiler writes only a small,
//! deterministic surface under `/run/systemd/system/` (tmpfs, outranks `/etc`
//! and `/usr`, outside the composefs `/etc` overlay — invariant **I1**):
//!
//! - one per-instance dropin per package, `aos-pkg-install@<p>.service.d/10-edges.conf`,
//!   mirroring the config DAG;
//! - `.wants/` symlinks pulling each instance from its target;
//!
//! then it calls `daemon-reload` once and `start --no-block aos-config.target`
//! through the [`SystemdControl`] seam (invariant **I2** — the compiler drives
//! systemd through nothing else). The on-disk surface is a pure function of the
//! two inputs (invariant **I3**): re-running over identical inputs is a
//! byte-identical no-op.
//!
//! # The dropin format
//!
//! ```ini
//! # Generated by aos-graph-compile from /run/aos/{manifest,graph}.json.
//! # Do not edit; regenerated on every `apm switch`/`upgrade`.
//! [Unit]
//! After=aos-pkg-fetch@nginx.service
//! After=aos-pkg-install@firewall.service
//! Wants=aos-pkg-install@firewall.service
//! ```
//!
//! The fetch self-edge is `After=` only (an unmet fetch leaves render *inactive*,
//! not failed — the package degrades); config edges are `After=`+`Wants=` (soft,
//! so a dependency's failure isolates). The compiler emits **no**
//! `Requires=`/`BindsTo=`/`Requisite=` anywhere — that is the lever that turns a
//! one-bad-package failure into degraded-not-failed boot (build-spec §3).
//!
//! # Module map
//!
//! - [`reproject`] — the degraded re-projected-manifest commit (build-spec §5):
//!   restrict the full manifest to the packages that materialized, close under
//!   the config graph, re-hash into a content-addressed generation, record the
//!   drop-set.
//! - [`subverbs`] — the `apm fetch <pkg>` / `apm render-one <pkg>` handlers that
//!   back the template `ExecStart=`s (build-spec §4).

pub mod reproject;
pub mod subverbs;

#[cfg(test)]
mod tests;

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use serde_json::Value;

use crate::types::validate_package_name;

/// Default tmpfs root systemd reads runtime units from.
pub const RUN_SYSTEMD_SYSTEM: &str = "/run/systemd/system";

/// Default path of the eval-produced data contract.
pub const DEFAULT_MANIFEST_PATH: &str = "/run/aos/manifest.json";

/// Default path of the eval-produced cross-package DAG.
pub const DEFAULT_GRAPH_PATH: &str = "/run/aos/graph.json";

/// Fixed dropin filename carrying each install instance's ordering edges.
const EDGES_DROPIN: &str = "10-edges.conf";

/// The static fetch template baked into gen-0.
const FETCH_TEMPLATE: &str = "aos-pkg-fetch@.service";
/// The static install/render template baked into gen-0.
const INSTALL_TEMPLATE: &str = "aos-pkg-install@.service";
/// The fetch wing target.
const FETCH_TARGET: &str = "aos-fetch.target";
/// The render wing target.
const RENDER_TARGET: &str = "aos-config-render.target";
/// The umbrella target the compiler starts.
const CONFIG_TARGET: &str = "aos-config.target";

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

/// The cross-package config DAG emitted as `/run/aos/graph.json`.
///
/// `edges[p]` is the set of packages `p` reads config from (its out-neighbors):
/// the edge `nginx → firewall` is `edges["nginx"] = ["firewall"]`. Only
/// install/activate honor this ordering; fetch carries no config edges
/// (downloads are order-independent — build-spec §3).
///
/// ```text
/// { "edges": { "nginx": ["firewall"], "firewall": [] } }
/// ```
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigGraph {
    /// Adjacency map `package → out-neighbors`. A package with no dependencies
    /// may be present with an empty list or absent entirely.
    #[serde(default)]
    pub edges: BTreeMap<String, Vec<String>>,
}

impl ConfigGraph {
    /// Parse a `graph.json` document.
    ///
    /// # Errors
    ///
    /// Returns an error if `text` is not the expected JSON shape.
    pub fn from_json(text: &str) -> Result<Self> {
        serde_json::from_str(text).context("parsing graph.json")
    }

    /// Out-neighbors of `pkg` (the packages it reads config from), or an empty
    /// slice when `pkg` declares no dependencies.
    fn deps_of(&self, pkg: &str) -> &[String] {
        self.edges.get(pkg).map(Vec::as_slice).unwrap_or(&[])
    }
}

// ---------------------------------------------------------------------------
// Plan
// ---------------------------------------------------------------------------

/// The validated, cycle-free package graph the compiler renders to disk.
///
/// Built by [`plan`] from the manifest's package set intersected with the graph
/// edges. Package names are validated against the apm `packageNameRegex` so they
/// are safe to interpolate into systemd instance names and `/run` paths.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompilePlan {
    /// Every package that gets a fetch + install instance, sorted.
    packages: BTreeSet<String>,
    /// `package → its install-ordering dependencies` (config out-neighbors that
    /// are themselves in `packages`), each set sorted for determinism.
    edges: BTreeMap<String, BTreeSet<String>>,
}

impl CompilePlan {
    /// The packages this plan materializes instances for.
    pub fn packages(&self) -> &BTreeSet<String> {
        &self.packages
    }

    /// The install-ordering dependencies of `pkg` (may be empty).
    pub fn dependencies(&self, pkg: &str) -> BTreeSet<String> {
        self.edges.get(pkg).cloned().unwrap_or_default()
    }
}

/// Build a [`CompilePlan`] from the eval outputs.
///
/// The package set is read from `manifest.packages` when present (the resolved
/// working set); otherwise it falls back to the union of the graph's nodes, so
/// the compiler is robust to either manifest shape. Edges are restricted to
/// endpoints in the package set, every name is validated, and the graph is
/// checked for cycles (defensively — a non-converging eval fails `aos-eval`
/// before any graph exists, build-spec §3).
///
/// # Errors
///
/// Returns an error if a package name is invalid, if an edge names a package
/// outside the manifest set, or if the graph contains a cycle (with the cycle
/// path in the message).
pub fn plan(manifest: &Value, graph: &ConfigGraph) -> Result<CompilePlan> {
    let packages = read_packages(manifest, graph);
    for pkg in &packages {
        validate_package_name(pkg)
            .with_context(|| format!("manifest package '{pkg}' is not a valid apm package name"))?;
    }

    let mut edges: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for pkg in &packages {
        let mut deps = BTreeSet::new();
        for dep in graph.deps_of(pkg) {
            validate_package_name(dep)
                .with_context(|| format!("graph dependency '{dep}' is not a valid package name"))?;
            if dep == pkg {
                // A self-loop in graph.json is meaningless (a package does not
                // order against itself); drop it rather than emit a systemd
                // ordering cycle.
                continue;
            }
            if !packages.contains(dep) {
                bail!(
                    "graph.json edge '{pkg}' -> '{dep}' names a package not in the manifest set"
                );
            }
            deps.insert(dep.clone());
        }
        edges.insert(pkg.clone(), deps);
    }

    detect_cycle(&edges)?;

    Ok(CompilePlan { packages, edges })
}

/// Read the package set: `manifest.packages` if present, else the graph nodes.
fn read_packages(manifest: &Value, graph: &ConfigGraph) -> BTreeSet<String> {
    if let Some(names) = manifest.get("packages").and_then(package_names) {
        return names;
    }
    // Fallback: every node mentioned by the graph (keys and out-neighbors).
    let mut set = BTreeSet::new();
    for (pkg, deps) in &graph.edges {
        set.insert(pkg.clone());
        set.extend(deps.iter().cloned());
    }
    set
}

/// Extract package names from a `manifest.packages` value, accepting either a
/// `["nginx", …]` array of strings or a `[{ "name": "nginx" }, …]` array of
/// objects (with `name` or `package` keys).
fn package_names(v: &Value) -> Option<BTreeSet<String>> {
    let arr = v.as_array()?;
    let mut set = BTreeSet::new();
    for item in arr {
        if let Some(s) = item.as_str() {
            set.insert(s.to_string());
        } else if let Some(obj) = item.as_object() {
            let name = obj
                .get("name")
                .or_else(|| obj.get("package"))
                .and_then(Value::as_str)?;
            set.insert(name.to_string());
        } else {
            return None;
        }
    }
    Some(set)
}

/// Detect an ordering cycle via DFS, reporting the offending path.
///
/// # Errors
///
/// Returns an error naming the cycle (e.g. `a -> b -> a`) when one is found.
fn detect_cycle(edges: &BTreeMap<String, BTreeSet<String>>) -> Result<()> {
    /// DFS coloring: `White` unvisited, `Gray` on the active stack, `Black` done.
    #[derive(Clone, Copy, PartialEq, Eq)]
    enum Color {
        Gray,
        Black,
    }

    let mut color: BTreeMap<&str, Color> = BTreeMap::new();
    // Iterative DFS so a pathological graph cannot blow the stack. Each stack
    // frame carries the node and the index of the next neighbor to visit.
    for root in edges.keys() {
        if color.contains_key(root.as_str()) {
            continue;
        }
        let mut stack: Vec<(&str, std::collections::btree_set::Iter<'_, String>)> =
            vec![(root.as_str(), edges[root].iter())];
        color.insert(root.as_str(), Color::Gray);
        while let Some((node, iter)) = stack.last_mut() {
            let node = *node;
            match iter.next() {
                Some(next) => match color.get(next.as_str()) {
                    Some(Color::Gray) => {
                        // Back-edge: reconstruct the cycle from the active stack.
                        let mut path: Vec<&str> =
                            stack.iter().map(|(n, _)| *n).collect();
                        if let Some(pos) = path.iter().position(|n| *n == next.as_str()) {
                            path = path[pos..].to_vec();
                        }
                        path.push(next.as_str());
                        bail!("graph.json contains an ordering cycle: {}", path.join(" -> "));
                    }
                    Some(Color::Black) => {}
                    None => {
                        color.insert(next.as_str(), Color::Gray);
                        stack.push((next.as_str(), edges[next.as_str()].iter()));
                    }
                },
                None => {
                    color.insert(node, Color::Black);
                    stack.pop();
                }
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Rendered artifacts (pure)
// ---------------------------------------------------------------------------

/// The exact `/run/systemd/system` surface a [`CompilePlan`] maps to.
///
/// Produced by [`GraphCompiler::render`] without touching disk, so the format
/// contract is unit-testable. Paths are absolute under the compiler's run root.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlannedArtifacts {
    /// `dropin path → file contents`.
    pub dropins: BTreeMap<PathBuf, String>,
    /// `symlink path → link target`.
    pub symlinks: BTreeMap<PathBuf, PathBuf>,
}

/// Render the verbatim `10-edges.conf` body for `pkg` and its `deps`.
///
/// Always emits the `After=aos-pkg-fetch@<pkg>.service` self-edge; emits the
/// `After=`/`Wants=` config-edge lines only when `deps` is non-empty (an empty
/// `[Unit]` section is never produced — build-spec §2.1). `deps` is a sorted set
/// so the output is deterministic.
fn dropin_contents(pkg: &str, deps: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("# Generated by aos-graph-compile from /run/aos/{manifest,graph}.json.\n");
    out.push_str("# Do not edit; regenerated on every `apm switch`/`upgrade`.\n");
    out.push_str("[Unit]\n");
    out.push_str(&format!("After=aos-pkg-fetch@{pkg}.service\n"));
    if !deps.is_empty() {
        let instances: Vec<String> = deps
            .iter()
            .map(|d| format!("aos-pkg-install@{d}.service"))
            .collect();
        let joined = instances.join(" ");
        out.push_str(&format!("After={joined}\n"));
        out.push_str(&format!("Wants={joined}\n"));
    }
    out
}

// ---------------------------------------------------------------------------
// The systemd control seam
// ---------------------------------------------------------------------------

/// The minimal systemd control surface the compiler is permitted to use
/// (invariant **I2**).
///
/// Exactly the four operations build-spec §2 names — `daemon-reload`,
/// `start --no-block`, `reset-failed <unit>` — modeled as a trait so the
/// compiler is unit-testable on a host without a system bus (a `FakeSystemd`
/// records calls). The production implementation is for
/// [`aos_systemd::SystemdClient`].
#[async_trait::async_trait]
pub trait SystemdControl {
    /// `Manager.Reload()` — equivalent to `systemctl daemon-reload`.
    ///
    /// # Errors
    ///
    /// Returns an error if the reload request fails.
    async fn daemon_reload(&self) -> Result<()>;

    /// Queue a start job for `name` without awaiting it (`systemctl start
    /// --no-block`).
    ///
    /// # Errors
    ///
    /// Returns an error if systemd rejects the unit name or cannot queue the job.
    async fn start_unit_no_wait(&self, name: &str) -> Result<()>;

    /// Clear the failed state of a single unit (`systemctl reset-failed <name>`).
    ///
    /// # Errors
    ///
    /// Returns an error if the request fails for a reason other than the unit
    /// being absent.
    async fn reset_failed_unit(&self, name: &str) -> Result<()>;
}

#[async_trait::async_trait]
impl SystemdControl for aos_systemd::SystemdClient {
    async fn daemon_reload(&self) -> Result<()> {
        aos_systemd::SystemdClient::daemon_reload(self)
            .await
            .map_err(|e| anyhow::anyhow!("daemon-reload failed: {e}"))
    }

    async fn start_unit_no_wait(&self, name: &str) -> Result<()> {
        aos_systemd::SystemdClient::start_unit_no_wait(self, name)
            .await
            .map_err(|e| anyhow::anyhow!("start {name} failed: {e}"))
    }

    async fn reset_failed_unit(&self, name: &str) -> Result<()> {
        aos_systemd::SystemdClient::reset_failed_unit(self, name)
            .await
            .map_err(|e| anyhow::anyhow!("reset-failed {name} failed: {e}"))
    }
}

// ---------------------------------------------------------------------------
// The compiler
// ---------------------------------------------------------------------------

/// What a reconcile changed on disk, returned by
/// [`GraphCompiler::reconcile_filesystem`] so the caller can `reset-failed` the
/// removed instances (build-spec §6).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ReconcileReport {
    /// Packages whose instances were newly written or rewritten.
    pub written: BTreeSet<String>,
    /// Packages whose stale `/run` units were deleted (removed from the
    /// manifest since the previous compile).
    pub removed: BTreeSet<String>,
}

/// The graph compiler, parameterized by its `/run/systemd/system` root so it can
/// be driven against a tempdir in unit tests.
#[derive(Debug, Clone)]
pub struct GraphCompiler {
    run_root: PathBuf,
}

impl Default for GraphCompiler {
    fn default() -> Self {
        Self::new()
    }
}

impl GraphCompiler {
    /// A compiler writing to the production `/run/systemd/system` root.
    pub fn new() -> Self {
        Self {
            run_root: PathBuf::from(RUN_SYSTEMD_SYSTEM),
        }
    }

    /// A compiler writing under `run_root` (used by tests + `--run-root`).
    pub fn with_run_root(run_root: impl Into<PathBuf>) -> Self {
        Self {
            run_root: run_root.into(),
        }
    }

    /// Render the plan to its on-disk artifact set without touching disk.
    pub fn render(&self, plan: &CompilePlan) -> PlannedArtifacts {
        let mut dropins = BTreeMap::new();
        let mut symlinks = BTreeMap::new();
        for pkg in &plan.packages {
            let deps = plan.edges.get(pkg).cloned().unwrap_or_default();
            // Install dropin (fetch instances get no dropin — they have no edges).
            let dropin = self
                .run_root
                .join(format!("aos-pkg-install@{pkg}.service.d"))
                .join(EDGES_DROPIN);
            dropins.insert(dropin, dropin_contents(pkg, &deps));

            // `.wants/` symlinks: target.wants/<instance> -> ../<template>.
            let fetch_link = self
                .run_root
                .join(format!("{FETCH_TARGET}.wants"))
                .join(format!("aos-pkg-fetch@{pkg}.service"));
            symlinks.insert(fetch_link, PathBuf::from(format!("../{FETCH_TEMPLATE}")));

            let install_link = self
                .run_root
                .join(format!("{RENDER_TARGET}.wants"))
                .join(format!("aos-pkg-install@{pkg}.service"));
            symlinks.insert(install_link, PathBuf::from(format!("../{INSTALL_TEMPLATE}")));
        }
        PlannedArtifacts { dropins, symlinks }
    }

    /// Reconcile `/run/systemd/system` to exactly match `plan` (build-spec §2.5,
    /// §6).
    ///
    /// Writes every desired dropin (dir `0755`, file `0644`) then every desired
    /// `.wants/` symlink (atomic temp+rename), then deletes any stale
    /// `aos-pkg-*@<p>` artifacts for packages no longer in the plan. The result
    /// is a pure function of `plan` (invariant **I3**): re-running is idempotent.
    /// This performs no `daemon-reload` — the caller sequences that and the
    /// `reset-failed` of [`ReconcileReport::removed`].
    ///
    /// # Errors
    ///
    /// Returns an error if any directory, file, or symlink operation fails.
    pub fn reconcile_filesystem(&self, plan: &CompilePlan) -> Result<ReconcileReport> {
        std::fs::create_dir_all(&self.run_root)
            .with_context(|| format!("creating {}", self.run_root.display()))?;

        let artifacts = self.render(plan);

        // (1) dropins.
        for (path, contents) in &artifacts.dropins {
            write_dropin(path, contents)?;
        }
        // (2) symlinks.
        for (path, target) in &artifacts.symlinks {
            write_symlink(path, target)?;
        }
        // (3) prune stragglers (packages removed since the last compile).
        let on_disk = self.scan_existing_packages()?;
        let removed: BTreeSet<String> =
            on_disk.difference(&plan.packages).cloned().collect();
        for pkg in &removed {
            self.remove_package_artifacts(pkg)?;
        }

        Ok(ReconcileReport {
            written: plan.packages.clone(),
            removed,
        })
    }

    /// Full compile: reconcile the filesystem, then drive systemd (build-spec
    /// §2.3–2.4, §6) — `reset-failed` every removed instance, one `daemon-reload`,
    /// then `start --no-block aos-config.target`.
    ///
    /// # Errors
    ///
    /// Returns an error if the filesystem reconcile fails or any systemd call
    /// fails. A failure here exits `aos-graph-compile.service` non-zero and the
    /// box stays on the gen-0 seed (recovery ladder rung 4).
    pub async fn compile<C>(
        &self,
        manifest: &Value,
        graph: &ConfigGraph,
        client: &C,
    ) -> Result<ReconcileReport>
    where
        C: SystemdControl + ?Sized,
    {
        let plan = plan(manifest, graph)?;
        let report = self.reconcile_filesystem(&plan)?;

        // reset-failed each removed instance so a previously-failed unit does
        // not linger (build-spec §6). Both planes (fetch + install) are cleared.
        for pkg in &report.removed {
            client
                .reset_failed_unit(&format!("aos-pkg-fetch@{pkg}.service"))
                .await?;
            client
                .reset_failed_unit(&format!("aos-pkg-install@{pkg}.service"))
                .await?;
        }

        // Exactly one daemon-reload after all files are on disk (build-spec §2.3).
        client.daemon_reload().await?;

        // Start the umbrella target and return immediately; systemd schedules
        // the whole wing asynchronously (build-spec §2.4).
        client.start_unit_no_wait(CONFIG_TARGET).await?;

        Ok(report)
    }

    /// Scan the run root for the packages that currently have `aos-pkg-*@<p>`
    /// instance artifacts (dropin dirs or `.wants` symlinks).
    fn scan_existing_packages(&self) -> Result<BTreeSet<String>> {
        let mut found = BTreeSet::new();

        // Install dropin directories: aos-pkg-install@<p>.service.d
        if let Ok(entries) = std::fs::read_dir(&self.run_root) {
            for entry in entries.flatten() {
                let name = entry.file_name();
                let name = name.to_string_lossy();
                if let Some(pkg) = name
                    .strip_prefix("aos-pkg-install@")
                    .and_then(|rest| rest.strip_suffix(".service.d"))
                    .or_else(|| {
                        name.strip_prefix("aos-pkg-fetch@")
                            .and_then(|rest| rest.strip_suffix(".service.d"))
                    })
                {
                    found.insert(pkg.to_string());
                }
            }
        }

        // `.wants` symlinks under each target.wants directory.
        for (target, prefix) in [
            (FETCH_TARGET, "aos-pkg-fetch@"),
            (RENDER_TARGET, "aos-pkg-install@"),
        ] {
            let dir = self.run_root.join(format!("{target}.wants"));
            if let Ok(entries) = std::fs::read_dir(&dir) {
                for entry in entries.flatten() {
                    let name = entry.file_name();
                    let name = name.to_string_lossy();
                    if let Some(pkg) = name
                        .strip_prefix(prefix)
                        .and_then(|rest| rest.strip_suffix(".service"))
                    {
                        found.insert(pkg.to_string());
                    }
                }
            }
        }

        Ok(found)
    }

    /// Delete every `/run` artifact belonging to `pkg`.
    fn remove_package_artifacts(&self, pkg: &str) -> Result<()> {
        let install_dropin_dir = self
            .run_root
            .join(format!("aos-pkg-install@{pkg}.service.d"));
        remove_dir_if_present(&install_dropin_dir)?;
        // Defensive: a fetch dropin dir is never written, but clean it if a
        // prior version left one.
        let fetch_dropin_dir = self.run_root.join(format!("aos-pkg-fetch@{pkg}.service.d"));
        remove_dir_if_present(&fetch_dropin_dir)?;

        let fetch_link = self
            .run_root
            .join(format!("{FETCH_TARGET}.wants"))
            .join(format!("aos-pkg-fetch@{pkg}.service"));
        remove_file_if_present(&fetch_link)?;
        let install_link = self
            .run_root
            .join(format!("{RENDER_TARGET}.wants"))
            .join(format!("aos-pkg-install@{pkg}.service"));
        remove_file_if_present(&install_link)?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Filesystem helpers
// ---------------------------------------------------------------------------

/// Write a dropin file, creating its `…service.d/` parent (`0755`), with mode
/// `0644`.
fn write_dropin(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
        set_mode(parent, 0o755)?;
    }
    // Atomic write (temp + rename) so a crash mid-write never leaves a truncated
    // dropin that a later daemon-reload could load — matching write_symlink.
    let tmp = path.with_extension("conf.tmp");
    std::fs::write(&tmp, contents).with_context(|| format!("writing {}", tmp.display()))?;
    set_mode(&tmp, 0o644)?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// Create (or atomically replace) a relative symlink `path -> target`.
fn write_symlink(path: &Path, target: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
        set_mode(parent, 0o755)?;
    }
    // If an identical symlink already exists, leave it (idempotent, I3).
    if let Ok(existing) = std::fs::read_link(path)
        && existing == target
    {
        return Ok(());
    }
    // Atomic replace via temp + rename so a wanted unit never momentarily lacks
    // its symlink (build-spec §2.5).
    let tmp = path.with_extension("tmp-aos-graph");
    let _ = std::fs::remove_file(&tmp);
    std::os::unix::fs::symlink(target, &tmp)
        .with_context(|| format!("symlinking {} -> {}", tmp.display(), target.display()))?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// `chmod` a path, ignoring the operation on platforms without unix perms in a
/// test sandbox (always present on the AOS target).
fn set_mode(path: &Path, mode: u32) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let perms = std::fs::Permissions::from_mode(mode);
    std::fs::set_permissions(path, perms)
        .with_context(|| format!("chmod {mode:o} {}", path.display()))
}

/// Remove a directory tree if it exists, treating absence as success.
fn remove_dir_if_present(path: &Path) -> Result<()> {
    match std::fs::remove_dir_all(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e).with_context(|| format!("removing {}", path.display())),
    }
}

/// Remove a file/symlink if it exists, treating absence as success.
fn remove_file_if_present(path: &Path) -> Result<()> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e).with_context(|| format!("removing {}", path.display())),
    }
}

// ---------------------------------------------------------------------------
// Service entrypoint
// ---------------------------------------------------------------------------

/// Run the compiler as `aos-graph-compile.service`: read the two inputs, open a
/// real [`aos_systemd::SystemdClient`], and drive the compile.
///
/// `ConditionPathExists=/run/aos/manifest.json` on the unit guarantees the
/// manifest is present before this runs; a missing graph.json is treated as an
/// empty graph (independent packages, no ordering).
///
/// # Errors
///
/// Returns an error if the manifest cannot be read or parsed, if the plan is
/// invalid (bad name, cycle), or if any systemd call fails. The service then
/// exits non-zero and the box stays on the gen-0 seed.
pub async fn run_graph_compile_command(
    manifest_path: &Path,
    graph_path: &Path,
    run_root: Option<&Path>,
) -> Result<()> {
    let manifest_text = std::fs::read_to_string(manifest_path)
        .with_context(|| format!("reading manifest {}", manifest_path.display()))?;
    let manifest: Value = serde_json::from_str(&manifest_text)
        .with_context(|| format!("parsing manifest {}", manifest_path.display()))?;

    let graph = if graph_path.exists() {
        let graph_text = std::fs::read_to_string(graph_path)
            .with_context(|| format!("reading graph {}", graph_path.display()))?;
        ConfigGraph::from_json(&graph_text)?
    } else {
        ConfigGraph::default()
    };

    let compiler = match run_root {
        Some(root) => GraphCompiler::with_run_root(root),
        None => GraphCompiler::new(),
    };

    let client = aos_systemd::SystemdClient::connect()
        .await
        .context("connecting to systemd")?;
    let report = compiler.compile(&manifest, &graph, &client).await?;
    eprintln!(
        "aos-graph-compile: {} package instance(s) wired, {} removed; started {CONFIG_TARGET}",
        report.written.len(),
        report.removed.len(),
    );
    Ok(())
}
