//! The systemd unit-graph compiler for configuration manifests.
//!
//! `aos-eval.service` produces two read-only inputs — `/run/aos/manifest.json`
//! (the resolved package set + config) and `/run/aos/graph.json` (the
//! cross-package read/write DAG) — and never activates. This module is the
//! `aos-graph-compile.service` body that turns those inputs into a runtime
//! systemd graph so that systemd's own ordering, parallelism, and failure
//! isolation drive provisioning, rather than a monolithic `apm install`.
//!
//! # What it writes
//!
//! Everything heavyweight (the `aos-pkg-fetch@.service` / `aos-pkg-install@.service`
//! template bodies, sandboxing, the three targets) is image-baked into gen-0
//! (`modules/systemd/graph.nix`). At runtime the compiler writes only a small,
//! deterministic surface under `/run/systemd/system/` (tmpfs, outranks `/etc`
//! and `/usr`, outside the composefs `/etc` overlay — invariant **I1**):
//!
//! - one per-instance dropin per package, `aos-pkg-install@<p>.service.d/10-edges.conf`,
//!   mirroring the config DAG;
//! - `.wants/` symlinks pulling each instance from its target;
//!
//! then it calls `daemon-reload` once and awaits `aos-config.target` through the
//! [`SystemdControl`] seam. A changed manifest first stops the old
//! `RemainAfterExit` transaction so every required oneshot runs again. The
//! on-disk surface is a pure function of the two inputs (invariant **I3**):
//! re-running over identical inputs is a byte-identical no-op.
//!
//! # The dropin format
//!
//! ```ini
//! # Generated by aos-graph-compile from /run/aos/{manifest,graph}.json.
//! # Do not edit; regenerated on every `apm switch`/`upgrade`.
//! [Unit]
//! After=aos-pkg-fetch@nginx.service
//! After=aos-pkg-install@firewall.service
//! Wants=aos-pkg-install@firewall.service
//! ```
//!
//! The fetch self-edge is `After=` only (an unmet fetch leaves render *inactive*,
//! not failed — the package degrades); config edges are `After=`+`Wants=` (soft,
//! so a dependency's failure isolates). The compiler emits **no**
//! `Requires=`/`BindsTo=`/`Requisite=` anywhere — that is the lever that turns a
//! one-bad-package failure into degraded-not-failed boot (build-spec §3).
//!
//! # Module map
//!
//! - [`reproject`] — the degraded re-projected-manifest commit (build-spec §5):
//!   restrict the full manifest to the packages that materialized, close under
//!   the config graph, re-hash into a content-addressed generation, record the
//!   drop-set.
//! - [`subverbs`] — the `apm fetch <pkg>` / `apm render-one <pkg>` handlers that
//!   back the template `ExecStart=`s (build-spec §4).

pub mod reproject;
pub mod subverbs;

#[cfg(test)]
mod tests;

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::config_eval::materialize::ConfigManifest;
use crate::types::validate_package_name;

/// Default tmpfs root systemd reads runtime units from.
pub const RUN_SYSTEMD_SYSTEM: &str = "/run/systemd/system";

/// Default path of the eval-produced data contract.
pub const DEFAULT_MANIFEST_PATH: &str = "/run/aos/manifest.json";

/// Default path of the eval-produced cross-package DAG.
pub const DEFAULT_GRAPH_PATH: &str = "/run/aos/graph.json";

/// Runtime state shared by graph compilation, package subverbs, and activation.
pub const GRAPH_TRANSACTION_STATE: &str = "graph-transaction.json";

/// Runtime proof published only after configuration activation commits.
const ACTIVATION_RECORD: &str = "activation.json";

/// Fixed dropin filename carrying each install instance's ordering edges.
const EDGES_DROPIN: &str = "10-edges.conf";
/// Fixed dropin filename making each wing target wait for all of its instances.
const INSTANCES_DROPIN: &str = "10-instances.conf";

/// The static fetch template baked into gen-0.
const FETCH_TEMPLATE: &str = "aos-pkg-fetch@.service";
/// The static install/render template baked into gen-0.
const INSTALL_TEMPLATE: &str = "aos-pkg-install@.service";
/// The fetch wing target.
const FETCH_TARGET: &str = "aos-fetch.target";
/// The render wing target.
const RENDER_TARGET: &str = "aos-config-render.target";
/// The umbrella target the compiler starts.
const CONFIG_TARGET: &str = "aos-config.target";

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

/// The cross-package config DAG emitted as `/run/aos/graph.json`.
///
/// `edges[p]` is the set of packages `p` reads config from (its out-neighbors):
/// the edge `nginx → firewall` is `edges["nginx"] = ["firewall"]`. Only
/// install/activate honor this ordering; fetch carries no config edges
/// (downloads are order-independent — build-spec §3).
///
/// ```text
/// { "edges": { "nginx": ["firewall"], "firewall": [] } }
/// ```
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConfigGraph {
    /// Adjacency map `package → out-neighbors`. A package with no dependencies
    /// may be present with an empty list or absent entirely.
    #[serde(default)]
    pub edges: BTreeMap<String, Vec<String>>,
}

impl ConfigGraph {
    /// Parse a `graph.json` document.
    ///
    /// # Errors
    ///
    /// Returns an error if `text` is not the expected JSON shape.
    pub fn from_json(text: &str) -> Result<Self> {
        serde_json::from_str(text).context("parsing graph.json")
    }

    /// Out-neighbors of `pkg` (the packages it reads config from), or an empty
    /// slice when `pkg` declares no dependencies.
    fn deps_of(&self, pkg: &str) -> &[String] {
        self.edges.get(pkg).map(Vec::as_slice).unwrap_or(&[])
    }
}

// ---------------------------------------------------------------------------
// Plan
// ---------------------------------------------------------------------------

/// The validated, cycle-free package graph the compiler renders to disk.
///
/// Built by [`plan`] from a strict manifest and its identical companion graph.
/// Package names are validated against the apm `packageNameRegex` so they are
/// safe to interpolate into systemd instance names and `/run` paths.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompilePlan {
    /// Every package that gets a fetch + install instance, sorted.
    packages: BTreeSet<String>,
    /// `package → its install-ordering dependencies` (config out-neighbors that
    /// are themselves in `packages`), each set sorted for determinism.
    edges: BTreeMap<String, BTreeSet<String>>,
}

impl CompilePlan {
    /// The packages this plan materializes instances for.
    pub fn packages(&self) -> &BTreeSet<String> {
        &self.packages
    }

    /// The install-ordering dependencies of `pkg` (may be empty).
    pub fn dependencies(&self, pkg: &str) -> BTreeSet<String> {
        self.edges.get(pkg).cloned().unwrap_or_default()
    }
}

/// Build a [`CompilePlan`] from the eval outputs.
///
/// The manifest is validated in full and `graph.json` must exactly equal its
/// embedded graph. Every package name and edge endpoint is validated, and the
/// graph is checked for cycles defensively.
///
/// # Errors
///
/// Returns an error if the manifest is invalid, the companion graph disagrees,
/// a package name or edge is invalid, or the graph contains a cycle.
pub fn plan(manifest: &ConfigManifest, graph: &ConfigGraph) -> Result<CompilePlan> {
    manifest.validate().context("validating config manifest")?;
    if graph.edges != manifest.graph.edges {
        bail!("graph.json disagrees with the dependency graph embedded in manifest.json");
    }
    let packages: BTreeSet<String> = manifest.packages.iter().cloned().collect();
    for pkg in &packages {
        validate_package_name(pkg)
            .with_context(|| format!("manifest package '{pkg}' is not a valid apm package name"))?;
    }

    let mut edges: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for pkg in &packages {
        let mut deps = BTreeSet::new();
        for dep in graph.deps_of(pkg) {
            validate_package_name(dep)
                .with_context(|| format!("graph dependency '{dep}' is not a valid package name"))?;
            if dep == pkg {
                // A self-loop in graph.json is meaningless (a package does not
                // order against itself); drop it rather than emit a systemd
                // ordering cycle.
                continue;
            }
            if !packages.contains(dep) {
                bail!("graph.json edge '{pkg}' -> '{dep}' names a package not in the manifest set");
            }
            deps.insert(dep.clone());
        }
        edges.insert(pkg.clone(), deps);
    }

    detect_cycle(&edges)?;

    Ok(CompilePlan { packages, edges })
}

/// Detect an ordering cycle via DFS, reporting the offending path.
///
/// # Errors
///
/// Returns an error naming the cycle (e.g. `a -> b -> a`) when one is found.
fn detect_cycle(edges: &BTreeMap<String, BTreeSet<String>>) -> Result<()> {
    /// DFS coloring: `White` unvisited, `Gray` on the active stack, `Black` done.
    #[derive(Clone, Copy, PartialEq, Eq)]
    enum Color {
        Gray,
        Black,
    }

    let mut color: BTreeMap<&str, Color> = BTreeMap::new();
    // Iterative DFS so a pathological graph cannot blow the stack. Each stack
    // frame carries the node and the index of the next neighbor to visit.
    for root in edges.keys() {
        if color.contains_key(root.as_str()) {
            continue;
        }
        let mut stack: Vec<(&str, std::collections::btree_set::Iter<'_, String>)> =
            vec![(root.as_str(), edges[root].iter())];
        color.insert(root.as_str(), Color::Gray);
        while let Some((node, iter)) = stack.last_mut() {
            let node = *node;
            match iter.next() {
                Some(next) => match color.get(next.as_str()) {
                    Some(Color::Gray) => {
                        // Back-edge: reconstruct the cycle from the active stack.
                        let mut path: Vec<&str> = stack.iter().map(|(n, _)| *n).collect();
                        if let Some(pos) = path.iter().position(|n| *n == next.as_str()) {
                            path = path[pos..].to_vec();
                        }
                        path.push(next.as_str());
                        bail!(
                            "graph.json contains an ordering cycle: {}",
                            path.join(" -> ")
                        );
                    }
                    Some(Color::Black) => {}
                    None => {
                        color.insert(next.as_str(), Color::Gray);
                        stack.push((next.as_str(), edges[next.as_str()].iter()));
                    }
                },
                None => {
                    color.insert(node, Color::Black);
                    stack.pop();
                }
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Rendered artifacts (pure)
// ---------------------------------------------------------------------------

/// The exact `/run/systemd/system` surface a [`CompilePlan`] maps to.
///
/// Produced by [`GraphCompiler::render`] without touching disk, so the format
/// contract is unit-testable. Paths are absolute under the compiler's run root.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlannedArtifacts {
    /// `dropin path → file contents`.
    pub dropins: BTreeMap<PathBuf, String>,
    /// `symlink path → link target`.
    pub symlinks: BTreeMap<PathBuf, PathBuf>,
}

/// Render the verbatim `10-edges.conf` body for `pkg` and its `deps`.
///
/// Always emits the `After=aos-pkg-fetch@<pkg>.service` self-edge; emits the
/// `After=`/`Wants=` config-edge lines only when `deps` is non-empty (an empty
/// `[Unit]` section is never produced — build-spec §2.1). `deps` is a sorted set
/// so the output is deterministic.
fn dropin_contents(pkg: &str, deps: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("# Generated by aos-graph-compile from /run/aos/{manifest,graph}.json.\n");
    out.push_str("# Do not edit; regenerated on every `apm switch`/`upgrade`.\n");
    out.push_str("[Unit]\n");
    out.push_str(&format!("After=aos-pkg-fetch@{pkg}.service\n"));
    if !deps.is_empty() {
        let instances: Vec<String> = deps
            .iter()
            .map(|d| format!("aos-pkg-install@{d}.service"))
            .collect();
        let joined = instances.join(" ");
        out.push_str(&format!("After={joined}\n"));
        out.push_str(&format!("Wants={joined}\n"));
    }
    out
}

/// Render the target ordering barrier for one package wing.
///
/// A `.wants/` symlink alone does not order a target after the wanted unit;
/// without this drop-in the target could become active while its oneshots were
/// still running. The file is emitted even for an empty plan so a recompile
/// overwrites stale instance ordering with an inert `[Unit]` section.
fn target_dropin_contents(template: &str, packages: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("# Generated by aos-graph-compile from /run/aos/manifest.json.\n");
    out.push_str("# Do not edit; regenerated on every `apm switch`/`upgrade`.\n");
    out.push_str("[Unit]\n");
    if !packages.is_empty() {
        let units = packages
            .iter()
            .map(|package| template.replace("@.", &format!("@{package}.")))
            .collect::<Vec<_>>()
            .join(" ");
        out.push_str(&format!("After={units}\n"));
    }
    out
}

// ---------------------------------------------------------------------------
// The systemd control seam
// ---------------------------------------------------------------------------

/// The minimal systemd control surface the compiler is permitted to use
/// (invariant **I2**).
///
/// Exactly the operations build-spec §2 names — `daemon-reload`, a target
/// start, and `reset-failed <unit>` — modeled as a trait so the
/// compiler is unit-testable on a host without a system bus (a `FakeSystemd`
/// records calls). The production implementation is for
/// [`aos_systemd::SystemdClient`].
#[async_trait::async_trait]
pub trait SystemdControl {
    /// `Manager.Reload()` — equivalent to `systemctl daemon-reload`.
    ///
    /// # Errors
    ///
    /// Returns an error if the reload request fails.
    async fn daemon_reload(&self) -> Result<()>;

    /// Start `name` and await its systemd job.
    ///
    /// # Errors
    ///
    /// Returns an error if systemd rejects the unit, loses the job, or reports
    /// a terminal result other than `done`.
    async fn start_unit(&self, name: &str) -> Result<()>;

    /// Stop `name` and await its systemd job.
    ///
    /// # Errors
    ///
    /// Returns an error if systemd rejects the unit or the job does not finish.
    async fn stop_unit(&self, name: &str) -> Result<()>;

    /// Clear the failed state of a single unit (`systemctl reset-failed <name>`).
    ///
    /// # Errors
    ///
    /// Returns an error if the request fails for a reason other than the unit
    /// being absent.
    async fn reset_failed_unit(&self, name: &str) -> Result<()>;
}

#[async_trait::async_trait]
impl SystemdControl for aos_systemd::SystemdClient {
    async fn daemon_reload(&self) -> Result<()> {
        aos_systemd::SystemdClient::daemon_reload(self)
            .await
            .map_err(|e| anyhow::anyhow!("daemon-reload failed: {e}"))
    }

    async fn start_unit(&self, name: &str) -> Result<()> {
        let outcome = aos_systemd::SystemdClient::start_unit(self, name)
            .await
            .map_err(|e| anyhow::anyhow!("start {name} failed: {e}"))?;
        if !outcome.result.is_done() {
            anyhow::bail!(
                "start {name} completed with systemd job result '{}'",
                outcome.result.label()
            );
        }
        Ok(())
    }

    async fn stop_unit(&self, name: &str) -> Result<()> {
        let outcome = aos_systemd::SystemdClient::stop_unit(self, name)
            .await
            .map_err(|e| anyhow::anyhow!("stop {name} failed: {e}"))?;
        if !outcome.result.is_done() {
            anyhow::bail!(
                "stop {name} completed with systemd job result '{}'",
                outcome.result.label()
            );
        }
        Ok(())
    }

    async fn reset_failed_unit(&self, name: &str) -> Result<()> {
        aos_systemd::SystemdClient::reset_failed_unit(self, name)
            .await
            .map_err(|e| anyhow::anyhow!("reset-failed {name} failed: {e}"))
    }
}

// ---------------------------------------------------------------------------
// The compiler
// ---------------------------------------------------------------------------

/// What a reconcile changed on disk, returned by
/// [`GraphCompiler::reconcile_filesystem`] so the caller can `reset-failed` the
/// removed instances (build-spec §6).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ReconcileReport {
    /// Packages whose instances were newly written or rewritten.
    pub written: BTreeSet<String>,
    /// Packages whose stale `/run` units were deleted (removed from the
    /// manifest since the previous compile).
    pub removed: BTreeSet<String>,
}

/// Identity of one graph transaction and each package input pin.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct GraphTransaction {
    /// Hash of the complete validated manifest.
    pub manifest: String,
    /// Package-specific hashes of closure, config, and credential inputs.
    pub packages: BTreeMap<String, String>,
    /// Whether the umbrella target completed successfully.
    #[serde(default)]
    pub completed: bool,
}

/// Proof that the activation service committed one graph transaction.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
struct ActivationProof {
    schema: String,
    generation: u32,
    generation_id: String,
    transaction_manifest: String,
    dropped_packages: Vec<String>,
    status: String,
    activation_exit: i32,
}

impl ActivationProof {
    /// Whether immutable activation identity fields are structurally valid.
    fn is_well_formed(&self) -> bool {
        self.schema == "aos.config-activation/v1"
            && self.generation > 0
            && is_sha256_id(&self.generation_id)
    }

    /// Whether this proof authorizes the completed-transaction fast path.
    fn completes(&self, transaction: &GraphTransaction) -> bool {
        self.is_well_formed()
            && self.transaction_manifest == transaction.manifest
            && self.dropped_packages.is_empty()
            && self.status == "complete"
            && matches!(self.activation_exit, 0 | 5)
    }

    /// Whether this proof records a valid, retryable degraded transaction.
    fn degrades(&self, transaction: &GraphTransaction) -> bool {
        self.is_well_formed()
            && self.transaction_manifest == transaction.manifest
            && self.status == "degraded"
            && (self.activation_exit == 6 || !self.dropped_packages.is_empty())
    }
}

/// Checks the `sha256:<64 lowercase hexadecimal digits>` identity syntax.
fn is_sha256_id(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|digest| {
        digest.len() == 64
            && digest
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
    })
}

/// Computes the stable transaction and package pin identities for a manifest.
pub(crate) fn graph_transaction(manifest: &ConfigManifest) -> Result<GraphTransaction> {
    manifest.validate().context("validating config manifest")?;
    let value = serde_json::to_value(manifest).context("serializing config manifest")?;
    let manifest_hash = hash_json(&value)?;
    let mut packages = BTreeMap::new();
    for package in &manifest.packages {
        let output = manifest
            .package_outputs
            .get(package)
            .with_context(|| format!("manifest has no runtime output pin for {package:?}"))?;
        let pin = serde_json::json!({
            "package": package,
            "output": output,
            "config": manifest.config.get(package),
            "credentials": manifest.credentials.get(package),
        });
        packages.insert(package.clone(), hash_json(&pin)?);
    }
    Ok(GraphTransaction {
        manifest: manifest_hash,
        packages,
        completed: false,
    })
}

/// Serializes JSON before hashing it with SHA-256.
fn hash_json(value: &serde_json::Value) -> Result<String> {
    let bytes = serde_json::to_vec(value).context("serializing graph transaction identity")?;
    Ok(format!("sha256:{:x}", Sha256::digest(bytes)))
}

/// Returns the state-file path below a marker/state root.
pub(crate) fn transaction_state_path(root: &Path) -> PathBuf {
    root.join(GRAPH_TRANSACTION_STATE)
}

/// Reads a transaction state, returning `None` when it is absent.
pub(crate) fn read_transaction(root: &Path) -> Result<Option<GraphTransaction>> {
    let path = transaction_state_path(root);
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error).with_context(|| format!("reading {}", path.display())),
    };
    serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}

/// Atomically publishes transaction state for the package subverbs.
fn write_transaction(root: &Path, state: &GraphTransaction) -> Result<()> {
    std::fs::create_dir_all(root).with_context(|| format!("creating {}", root.display()))?;
    let path = transaction_state_path(root);
    let temporary = root.join(format!(".{GRAPH_TRANSACTION_STATE}.tmp"));
    let mut bytes = serde_json::to_vec(state).context("serializing graph transaction state")?;
    bytes.push(b'\n');
    std::fs::write(&temporary, bytes)
        .with_context(|| format!("writing {}", temporary.display()))?;
    std::fs::rename(&temporary, &path)
        .with_context(|| format!("renaming {} to {}", temporary.display(), path.display()))
}

/// Reads the activation proof. Absence means activation has not committed.
fn read_activation_proof(root: &Path) -> Result<Option<ActivationProof>> {
    let path = root.join(ACTIVATION_RECORD);
    let text = match std::fs::read_to_string(&path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error).with_context(|| format!("reading {}", path.display())),
    };
    serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}

/// Removes the prior attempt's proof before systemd starts a new transaction.
fn clear_activation_proof(root: &Path) -> Result<()> {
    let path = root.join(ACTIVATION_RECORD);
    match std::fs::remove_file(&path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("removing {}", path.display())),
    }
}

/// The graph compiler, parameterized by its `/run/systemd/system` root so it can
/// be driven against a tempdir in unit tests.
#[derive(Debug, Clone)]
pub struct GraphCompiler {
    run_root: PathBuf,
    state_root: PathBuf,
}

impl Default for GraphCompiler {
    fn default() -> Self {
        Self::new()
    }
}

impl GraphCompiler {
    /// A compiler writing to the production `/run/systemd/system` root.
    pub fn new() -> Self {
        Self {
            run_root: PathBuf::from(RUN_SYSTEMD_SYSTEM),
            state_root: PathBuf::from(subverbs::MARKER_ROOT),
        }
    }

    /// A compiler writing under `run_root` (used by tests + `--run-root`).
    pub fn with_run_root(run_root: impl Into<PathBuf>) -> Self {
        let run_root = run_root.into();
        Self {
            state_root: run_root.clone(),
            run_root,
        }
    }

    /// A compiler with independent unit and transaction-state roots.
    pub fn with_roots(run_root: impl Into<PathBuf>, state_root: impl Into<PathBuf>) -> Self {
        Self {
            run_root: run_root.into(),
            state_root: state_root.into(),
        }
    }

    /// Render the plan to its on-disk artifact set without touching disk.
    pub fn render(&self, plan: &CompilePlan) -> PlannedArtifacts {
        let mut dropins = BTreeMap::new();
        let mut symlinks = BTreeMap::new();
        for (target, template) in [
            (FETCH_TARGET, FETCH_TEMPLATE),
            (RENDER_TARGET, INSTALL_TEMPLATE),
        ] {
            dropins.insert(
                self.run_root
                    .join(format!("{target}.d"))
                    .join(INSTANCES_DROPIN),
                target_dropin_contents(template, &plan.packages),
            );
        }
        for pkg in &plan.packages {
            let deps = plan.edges.get(pkg).cloned().unwrap_or_default();
            // Install dropin (fetch instances get no dropin — they have no edges).
            let dropin = self
                .run_root
                .join(format!("aos-pkg-install@{pkg}.service.d"))
                .join(EDGES_DROPIN);
            dropins.insert(dropin, dropin_contents(pkg, &deps));

            // `.wants/` symlinks: target.wants/<instance> -> ../<template>.
            let fetch_link = self
                .run_root
                .join(format!("{FETCH_TARGET}.wants"))
                .join(format!("aos-pkg-fetch@{pkg}.service"));
            symlinks.insert(fetch_link, PathBuf::from(format!("../{FETCH_TEMPLATE}")));

            let install_link = self
                .run_root
                .join(format!("{RENDER_TARGET}.wants"))
                .join(format!("aos-pkg-install@{pkg}.service"));
            symlinks.insert(
                install_link,
                PathBuf::from(format!("../{INSTALL_TEMPLATE}")),
            );
        }
        PlannedArtifacts { dropins, symlinks }
    }

    /// Reconcile `/run/systemd/system` to exactly match `plan` (build-spec §2.5,
    /// §6).
    ///
    /// Writes every desired dropin (dir `0755`, file `0644`) then every desired
    /// `.wants/` symlink (atomic temp+rename), then deletes any stale
    /// `aos-pkg-*@<p>` artifacts for packages no longer in the plan. The result
    /// is a pure function of `plan` (invariant **I3**): re-running is idempotent.
    /// This performs no `daemon-reload` — the caller sequences that and the
    /// `reset-failed` of [`ReconcileReport::removed`].
    ///
    /// # Errors
    ///
    /// Returns an error if any directory, file, or symlink operation fails.
    pub fn reconcile_filesystem(&self, plan: &CompilePlan) -> Result<ReconcileReport> {
        std::fs::create_dir_all(&self.run_root)
            .with_context(|| format!("creating {}", self.run_root.display()))?;

        let artifacts = self.render(plan);

        // (1) dropins.
        for (path, contents) in &artifacts.dropins {
            write_dropin(path, contents)?;
        }
        // (2) symlinks.
        for (path, target) in &artifacts.symlinks {
            write_symlink(path, target)?;
        }
        for (target, prefix) in [
            (FETCH_TARGET, "aos-pkg-fetch@"),
            (RENDER_TARGET, "aos-pkg-install@"),
        ] {
            let expected = plan
                .packages
                .iter()
                .map(|package| format!("{prefix}{package}.service"))
                .collect();
            prune_managed_directory(&self.run_root.join(format!("{target}.wants")), &expected)?;
        }
        // These runtime drop-in directories are compiler-owned. Leaving an
        // obsolete second drop-in beside the generated file can silently add
        // hard systemd edges and makes the effective graph differ from the
        // authenticated manifest.
        for pkg in &plan.packages {
            prune_dropin_directory(
                &self
                    .run_root
                    .join(format!("aos-pkg-install@{pkg}.service.d")),
                EDGES_DROPIN,
            )?;
            remove_dir_if_present(&self.run_root.join(format!("aos-pkg-fetch@{pkg}.service.d")))?;
        }
        for target in [FETCH_TARGET, RENDER_TARGET] {
            prune_dropin_directory(&self.run_root.join(format!("{target}.d")), INSTANCES_DROPIN)?;
        }
        // (3) prune stragglers (packages removed since the last compile).
        let on_disk = self.scan_existing_packages()?;
        let removed: BTreeSet<String> = on_disk.difference(&plan.packages).cloned().collect();
        for pkg in &removed {
            self.remove_package_artifacts(pkg)?;
        }

        Ok(ReconcileReport {
            written: plan.packages.clone(),
            removed,
        })
    }

    /// Full compile: reconcile the filesystem, then drive systemd (build-spec
    /// §2.3–2.4, §6) — `reset-failed` every removed instance, one `daemon-reload`,
    /// then await `aos-config.target`. Waiting is what makes the activation
    /// service a boot-ordering barrier before presets and `multi-user.target`.
    ///
    /// # Errors
    ///
    /// Returns an error if the filesystem reconcile fails or any systemd call
    /// fails. A failure here exits `aos-graph-compile.service` non-zero and the
    /// box stays on the gen-0 seed (recovery ladder rung 4).
    pub async fn compile<C>(
        &self,
        manifest: &ConfigManifest,
        graph: &ConfigGraph,
        client: &C,
    ) -> Result<ReconcileReport>
    where
        C: SystemdControl + ?Sized,
    {
        let plan = plan(manifest, graph)?;
        let desired_state = graph_transaction(manifest)?;
        let previous_state = read_transaction(&self.state_root)?;
        if let Some(previous) = previous_state
            .as_ref()
            .filter(|state| state.completed && state.manifest == desired_state.manifest)
        {
            if read_activation_proof(&self.state_root)
                .ok()
                .flatten()
                .is_some_and(|proof| proof.completes(previous))
                && self.runtime_artifacts_match(&plan)?
            {
                return Ok(ReconcileReport {
                    written: plan.packages.clone(),
                    removed: BTreeSet::new(),
                });
            }
        }

        let mut affected = plan.packages.clone();
        if let Some(previous) = &previous_state {
            affected.extend(previous.packages.keys().cloned());
        }

        // RemainAfterExit oneshots and their targets retain active state. Stop
        // the complete old transaction explicitly so the new transaction is
        // guaranteed to execute rather than being treated as already active.
        for unit in [CONFIG_TARGET, "aos-activate.service", RENDER_TARGET] {
            client.stop_unit(unit).await?;
        }
        for package in affected.iter().rev() {
            client
                .stop_unit(&format!("aos-pkg-install@{package}.service"))
                .await?;
        }
        client.stop_unit(FETCH_TARGET).await?;
        for package in affected.iter().rev() {
            client
                .stop_unit(&format!("aos-pkg-fetch@{package}.service"))
                .await?;
        }

        let report = self.reconcile_filesystem(&plan)?;

        // Clear failures and start-limit accounting for every affected unit.
        for pkg in &affected {
            client
                .reset_failed_unit(&format!("aos-pkg-fetch@{pkg}.service"))
                .await?;
            client
                .reset_failed_unit(&format!("aos-pkg-install@{pkg}.service"))
                .await?;
        }
        for unit in [
            FETCH_TARGET,
            RENDER_TARGET,
            "aos-activate.service",
            CONFIG_TARGET,
        ] {
            client.reset_failed_unit(unit).await?;
        }

        // Exactly one daemon-reload after all files are on disk (build-spec §2.3).
        client.daemon_reload().await?;

        // Publish incomplete state before starting the graph so fetch, render,
        // and activation all validate markers against this exact transaction.
        write_transaction(&self.state_root, &desired_state)?;
        // A proof from an earlier attempt must never authorize this start. The
        // activation service publishes a replacement only after pointer commit.
        clear_activation_proof(&self.state_root)?;

        // Start the umbrella target and wait for its After= chain. Fetch and
        // render failures remain soft Wants= failures, while the target itself
        // does not become active until aos-activate.service has settled.
        client.start_unit(CONFIG_TARGET).await?;

        let proof = read_activation_proof(&self.state_root)?.with_context(|| {
            format!(
                "{} completed without publishing {}",
                CONFIG_TARGET, ACTIVATION_RECORD
            )
        })?;
        if proof.completes(&desired_state) {
            let mut completed_state = desired_state;
            completed_state.completed = true;
            write_transaction(&self.state_root, &completed_state)?;
        } else if proof.transaction_manifest != desired_state.manifest {
            bail!(
                "activation proof transaction {} does not match requested transaction {}",
                proof.transaction_manifest,
                desired_state.manifest
            );
        } else if !proof.degrades(&desired_state) {
            bail!(
                "activation proof did not establish a complete or degraded transaction: status={:?}, exit={}",
                proof.status,
                proof.activation_exit
            );
        }

        Ok(report)
    }

    /// Scan the run root for the packages that currently have `aos-pkg-*@<p>`
    /// instance artifacts (dropin dirs or `.wants` symlinks).
    fn scan_existing_packages(&self) -> Result<BTreeSet<String>> {
        let mut found = BTreeSet::new();

        // Install dropin directories: aos-pkg-install@<p>.service.d
        if let Some(entries) = read_dir_if_present(&self.run_root)? {
            for entry in entries {
                let entry = entry.with_context(|| {
                    format!("reading directory entry below {}", self.run_root.display())
                })?;
                let name = entry.file_name();
                let name = name.to_string_lossy();
                if let Some(pkg) = name
                    .strip_prefix("aos-pkg-install@")
                    .and_then(|rest| rest.strip_suffix(".service.d"))
                    .or_else(|| {
                        name.strip_prefix("aos-pkg-fetch@")
                            .and_then(|rest| rest.strip_suffix(".service.d"))
                    })
                {
                    found.insert(pkg.to_string());
                }
            }
        }

        // `.wants` symlinks under each target.wants directory.
        for (target, prefix) in [
            (FETCH_TARGET, "aos-pkg-fetch@"),
            (RENDER_TARGET, "aos-pkg-install@"),
        ] {
            let dir = self.run_root.join(format!("{target}.wants"));
            if let Some(entries) = read_dir_if_present(&dir)? {
                for entry in entries {
                    let entry = entry.with_context(|| {
                        format!("reading directory entry below {}", dir.display())
                    })?;
                    let name = entry.file_name();
                    let name = name.to_string_lossy();
                    if let Some(pkg) = name
                        .strip_prefix(prefix)
                        .and_then(|rest| rest.strip_suffix(".service"))
                    {
                        found.insert(pkg.to_string());
                    }
                }
            }
        }

        Ok(found)
    }

    /// Whether the loaded runtime graph is byte-for-byte the desired graph.
    ///
    /// A completed activation proof cannot authorize a no-reload fast path if
    /// `/run/systemd/system` was lost or altered: repairing files without a
    /// daemon reload would leave systemd executing its stale in-memory graph.
    fn runtime_artifacts_match(&self, plan: &CompilePlan) -> Result<bool> {
        let artifacts = self.render(plan);
        for (path, expected) in artifacts.dropins {
            if std::fs::read_to_string(&path).ok().as_deref() != Some(expected.as_str()) {
                return Ok(false);
            }
            if !dropin_directory_has_only(
                path.parent().context("generated drop-in has no parent")?,
                path.file_name()
                    .and_then(|name| name.to_str())
                    .context("generated drop-in has a non-UTF-8 filename")?,
            )? {
                return Ok(false);
            }
        }
        for (path, expected) in artifacts.symlinks {
            if std::fs::read_link(path).ok().as_ref() != Some(&expected) {
                return Ok(false);
            }
        }
        for (target, prefix) in [
            (FETCH_TARGET, "aos-pkg-fetch@"),
            (RENDER_TARGET, "aos-pkg-install@"),
        ] {
            let expected = plan
                .packages
                .iter()
                .map(|package| format!("{prefix}{package}.service"))
                .collect();
            if !directory_names_equal(&self.run_root.join(format!("{target}.wants")), &expected)? {
                return Ok(false);
            }
        }
        if self.scan_existing_packages()? != plan.packages {
            return Ok(false);
        }
        for package in &plan.packages {
            if self
                .run_root
                .join(format!("aos-pkg-fetch@{package}.service.d"))
                .exists()
            {
                return Ok(false);
            }
        }
        Ok(true)
    }

    /// Delete every `/run` artifact belonging to `pkg`.
    fn remove_package_artifacts(&self, pkg: &str) -> Result<()> {
        let install_dropin_dir = self
            .run_root
            .join(format!("aos-pkg-install@{pkg}.service.d"));
        remove_dir_if_present(&install_dropin_dir)?;
        // Defensive: a fetch dropin dir is never written, but clean it if a
        // prior version left one.
        let fetch_dropin_dir = self.run_root.join(format!("aos-pkg-fetch@{pkg}.service.d"));
        remove_dir_if_present(&fetch_dropin_dir)?;

        let fetch_link = self
            .run_root
            .join(format!("{FETCH_TARGET}.wants"))
            .join(format!("aos-pkg-fetch@{pkg}.service"));
        remove_file_if_present(&fetch_link)?;
        let install_link = self
            .run_root
            .join(format!("{RENDER_TARGET}.wants"))
            .join(format!("aos-pkg-install@{pkg}.service"));
        remove_file_if_present(&install_link)?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Filesystem helpers
// ---------------------------------------------------------------------------

/// Opens a directory, treating absence as an empty optional directory.
fn read_dir_if_present(path: &Path) -> Result<Option<std::fs::ReadDir>> {
    match std::fs::read_dir(path) {
        Ok(entries) => Ok(Some(entries)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error).with_context(|| format!("reading {}", path.display())),
    }
}

/// Whether a compiler-owned drop-in directory contains exactly one file.
fn dropin_directory_has_only(path: &Path, expected: &str) -> Result<bool> {
    directory_names_equal(path, &BTreeSet::from([expected.to_string()]))
}

/// Whether a managed directory contains exactly the expected entry names.
fn directory_names_equal(path: &Path, expected: &BTreeSet<String>) -> Result<bool> {
    let Some(entries) = read_dir_if_present(path)? else {
        return Ok(false);
    };
    let mut actual = BTreeSet::new();
    for entry in entries {
        let entry =
            entry.with_context(|| format!("reading directory entry below {}", path.display()))?;
        let name = entry
            .file_name()
            .into_string()
            .map_err(|_| anyhow::anyhow!("non-UTF-8 entry below {}", path.display()))?;
        actual.insert(name);
    }
    Ok(&actual == expected)
}

/// Removes obsolete entries from one compiler-owned drop-in directory.
fn prune_dropin_directory(path: &Path, expected: &str) -> Result<()> {
    prune_managed_directory(path, &BTreeSet::from([expected.to_string()]))
}

/// Removes every entry not named in `expected` from a compiler-owned directory.
fn prune_managed_directory(path: &Path, expected: &BTreeSet<String>) -> Result<()> {
    let Some(entries) = read_dir_if_present(path)? else {
        return Ok(());
    };
    for entry in entries {
        let entry =
            entry.with_context(|| format!("reading directory entry below {}", path.display()))?;
        if entry
            .file_name()
            .to_str()
            .is_some_and(|name| expected.contains(name))
        {
            continue;
        }
        let entry_path = entry.path();
        let metadata = std::fs::symlink_metadata(&entry_path)
            .with_context(|| format!("inspecting {}", entry_path.display()))?;
        if metadata.file_type().is_dir() {
            std::fs::remove_dir_all(&entry_path)
                .with_context(|| format!("removing stale {}", entry_path.display()))?;
        } else {
            std::fs::remove_file(&entry_path)
                .with_context(|| format!("removing stale {}", entry_path.display()))?;
        }
    }
    Ok(())
}

/// Write a dropin file, creating its `…service.d/` parent (`0755`), with mode
/// `0644`.
fn write_dropin(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
        set_mode(parent, 0o755)?;
    }
    // Atomic write (temp + rename) so a crash mid-write never leaves a truncated
    // dropin that a later daemon-reload could load — matching write_symlink.
    let tmp = path.with_extension("conf.tmp");
    std::fs::write(&tmp, contents).with_context(|| format!("writing {}", tmp.display()))?;
    set_mode(&tmp, 0o644)?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// Create (or atomically replace) a relative symlink `path -> target`.
fn write_symlink(path: &Path, target: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
        set_mode(parent, 0o755)?;
    }
    // If an identical symlink already exists, leave it (idempotent, I3).
    if let Ok(existing) = std::fs::read_link(path)
        && existing == target
    {
        return Ok(());
    }
    // Atomic replace via temp + rename so a wanted unit never momentarily lacks
    // its symlink (build-spec §2.5).
    let tmp = path.with_extension("tmp-aos-graph");
    let _ = std::fs::remove_file(&tmp);
    std::os::unix::fs::symlink(target, &tmp)
        .with_context(|| format!("symlinking {} -> {}", tmp.display(), target.display()))?;
    std::fs::rename(&tmp, path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// `chmod` a path, ignoring the operation on platforms without unix perms in a
/// test sandbox (always present on the AOS target).
fn set_mode(path: &Path, mode: u32) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let perms = std::fs::Permissions::from_mode(mode);
    std::fs::set_permissions(path, perms)
        .with_context(|| format!("chmod {mode:o} {}", path.display()))
}

/// Remove a directory tree if it exists, treating absence as success.
fn remove_dir_if_present(path: &Path) -> Result<()> {
    match std::fs::remove_dir_all(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e).with_context(|| format!("removing {}", path.display())),
    }
}

/// Remove a file/symlink if it exists, treating absence as success.
fn remove_file_if_present(path: &Path) -> Result<()> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e).with_context(|| format!("removing {}", path.display())),
    }
}

// ---------------------------------------------------------------------------
// Service entrypoint
// ---------------------------------------------------------------------------

/// Run the compiler as `aos-graph-compile.service`: read the two inputs, open a
/// real [`aos_systemd::SystemdClient`], and drive the compile.
///
/// `ConditionPathExists=/run/aos/manifest.json` on the unit guarantees the
/// manifest is present before this runs. The companion graph is mandatory and
/// must exactly match the graph embedded in the validated manifest.
///
/// # Errors
///
/// Returns an error if the manifest cannot be read or parsed, if the plan is
/// invalid (bad name, cycle), or if any systemd call fails. The service then
/// exits non-zero and the box stays on the gen-0 seed.
pub async fn run_graph_compile_command(
    manifest_path: &Path,
    graph_path: &Path,
    run_root: Option<&Path>,
) -> Result<()> {
    let manifest_text = std::fs::read_to_string(manifest_path)
        .with_context(|| format!("reading manifest {}", manifest_path.display()))?;
    let manifest: ConfigManifest = serde_json::from_str(&manifest_text)
        .with_context(|| format!("parsing manifest {}", manifest_path.display()))?;
    manifest
        .validate()
        .with_context(|| format!("validating manifest {}", manifest_path.display()))?;

    let graph_text = std::fs::read_to_string(graph_path)
        .with_context(|| format!("reading graph {}", graph_path.display()))?;
    let graph = ConfigGraph::from_json(&graph_text)?;
    if graph.edges != manifest.graph.edges {
        bail!(
            "{} disagrees with the dependency graph embedded in {}",
            graph_path.display(),
            manifest_path.display()
        );
    }

    let compiler = match run_root {
        Some(root) => GraphCompiler::with_roots(
            root,
            manifest_path.parent().unwrap_or_else(|| Path::new(".")),
        ),
        None => GraphCompiler::new(),
    };

    let client = aos_systemd::SystemdClient::connect()
        .await
        .context("connecting to systemd")?;
    let report = compiler.compile(&manifest, &graph, &client).await?;
    eprintln!(
        "aos-graph-compile: {} package instance(s) wired, {} removed; started {CONFIG_TARGET}",
        report.written.len(),
        report.removed.len(),
    );
    Ok(())
}
