##! Package-owned sudo policy and privileged runtime resources.
{
  config,
  lib,
  ...
}: let
  cfg = config.aos.security.sudo;
  abilityTypes = lib.abilities.types;
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  runtimeEntries = serviceManagement.forProducer {
    consumerInstance = "runtime";
    key = "runtime-entries";
    interface = serviceManagement.interfaces.runtimeEntryPopulation;
    methods = ["observe"];
    parameters.entries = [
      {
        kind = "directory";
        path = "/run/sudo";
        mode = "0755";
        owner = "root";
        group = "root";
      }
      {
        kind = "directory";
        path = "/var/db/sudo";
        mode = "0700";
        owner = "root";
        group = "root";
      }
      {
        kind = "directory";
        path = "/var/log/sudo-io";
        mode = "0700";
        owner = "root";
        group = "root";
      }
    ];
  };
  wrapper = name: path: {
    key = "wrapper-${name}";
    parameters = {
      inherit name;
      entry = {
        kind = "copied-file";
        source = {
          kind = "artifact-file";
          reference = {
            artifact = lib.abilities.packageOutput {};
            inherit path;
          };
        };
        maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
      };
      destination = "/run/wrappers/bin/${name}";
      owner = "root";
      group = "root";
      mode = "4755";
      prerequisites = [(lib.abilities.resultOf "aos:wrapper-bin" "resource")];
    };
  };
  wrappers = serviceManagement.forProducers {
    consumerInstance = "runtime";
    interface = serviceManagement.interfaces.filesystemEntry;
    methods = ["materialize" "observe" "release"];
    producers = [
      (wrapper "sudo" "bin/sudo")
      (wrapper "sudoedit" "bin/sudo")
    ];
  };
  contributions = builtins.map serviceManagement.splitContribution [runtimeEntries wrappers];
  passwordTag =
    if cfg.wheelNeedsPassword
    then "PASSWD"
    else "NOPASSWD";
  sudoersText = ''
    # Generated by the sudo package module.
    Defaults env_reset
    Defaults use_pty
    Defaults secure_path="${config.system.build.systemPath}"

    root ALL=(ALL:ALL) ALL
    %wheel ALL=(ALL:ALL) ${passwordTag}: ALL
    ${lib.concatStringsSep "\n" cfg.extraRules}
  '';
in {
  options.aos.security.sudo = {
    enable = lib.mkOption {
      type = abilityTypes.boolean;
      default = false;
      description = "Install sudo with policy for the wheel group.";
    };

    wheelNeedsPassword = lib.mkOption {
      type = abilityTypes.boolean;
      default = true;
      description = "Require wheel members to authenticate before using sudo.";
    };

    extraRules = lib.mkOption {
      type = abilityTypes.list {
        element = abilityTypes.string {
          maxLength = 4096;
          syntax = null;
        };
        maxItems = 4096;
      };
      default = [];
      description = "Additional complete sudoers policy lines.";
    };
  };

  config = lib.mkMerge [
    {aos.abilities = lib.mkMerge (builtins.map (entry: entry.declarations) contributions);}
    (lib.mkIf (cfg.enable && config.aos.abilities.environment != null) {
      aos.abilities = lib.mkMerge (
        [{instances.runtime = {};}]
        ++ builtins.map (entry: entry.configured) contributions
      );

      aos.contributions.pamServices.sudo = {
        unixAuth = true;
        startSession = true;
        setLoginUid = true;
      };

      environment.etc."sudoers" = {
        mode = "0440";
        text = sudoersText;
      };
    })
  ];
}
