##! Package-owned sudo policy and privileged runtime resources.
{
  config,
  lib,
  ...
}: let
  cfg = config.aos.security.sudo;
  wheelMembers = config.aos.users.groups.wheel.members;
  abilityTypes = lib.abilities.types;
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  runtimeEntries = serviceManagement.forProducer {
    consumerInstance = "runtime";
    key = "runtime-entries";
    interface = serviceManagement.interfaces.runtimeEntryPopulation;
    methods = ["observe"];
    parameters.entries = [
      {
        kind = "directory";
        path = "/run/sudo";
        mode = "0755";
        owner = "root";
        group = "root";
      }
      {
        kind = "directory";
        path = "/var/db/sudo";
        mode = "0700";
        owner = "root";
        group = "root";
      }
      {
        kind = "directory";
        path = "/var/log/sudo-io";
        mode = "0700";
        owner = "root";
        group = "root";
      }
    ];
  };
  wrapper = name: path: {
    key = "wrapper-${name}";
    parameters = {
      inherit name;
      source = {
        artifact = lib.abilities.packageOutput {};
        inherit path;
      };
      owner = "root";
      group = "root";
      mode = "4755";
      maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
    };
  };
  wrappers = serviceManagement.forProducers {
    consumerInstance = "runtime";
    interface = serviceManagement.interfaces.privilegedExecutable;
    methods = ["observe"];
    producers = [
      (wrapper "sudo" "bin/sudo")
      (wrapper "sudoedit" "bin/sudo")
    ];
  };
  contributions = builtins.map serviceManagement.splitContribution [runtimeEntries wrappers];
  passwordTag =
    if cfg.wheelNeedsPassword
    then "PASSWD"
    else "NOPASSWD";
  sudoersText = ''
    # Generated by the sudo package module.
    Defaults env_reset
    Defaults use_pty
    Defaults secure_path="${config.system.build.systemPath}"

    root ALL=(ALL:ALL) ALL
    %wheel ALL=(ALL:ALL) ${passwordTag}: ALL
    ${lib.concatStringsSep "\n" cfg.extraRules}
  '';
in {
  options.aos.security.sudo = {
    enable = lib.mkOption {
      type = abilityTypes.boolean;
      default = false;
      description = "Install sudo with policy for the wheel group.";
    };

    wheelNeedsPassword = lib.mkOption {
      type = abilityTypes.boolean;
      default = true;
      description = "Require wheel members to authenticate before using sudo.";
    };

    extraRules = lib.mkOption {
      type = abilityTypes.list {
        element = abilityTypes.string {
          maxLength = 4096;
          syntax = null;
        };
        maxItems = 4096;
      };
      default = [];
      description = "Additional complete sudoers policy lines.";
    };
  };

  config = lib.mkMerge [
    {aos.abilities = lib.mkMerge (builtins.map (entry: entry.declarations) contributions);}
    (lib.mkIf (cfg.enable && config.aos.abilities.environment != null) {
      aos.abilities = lib.mkMerge (
        [{instances.runtime = {};}]
        ++ builtins.map (entry: entry.configured) contributions
      );

      aos.contributions.pamServices.sudo = {
        unixAuth = true;
        startSession = true;
        setLoginUid = true;
      };

      environment.etc."sudoers" = {
        mode = "0440";
        text = sudoersText;
      };
    })
    (lib.mkIf (cfg.enable && config.aos.abilities.environment != null) {
      aos.abilities.runtimeChecks.sudo = {
        description = "sudo policy and privilege checks";
        checks =
          [
            {
              name = "sudo-policy";
              description = "sudoers and PAM configuration are valid";
              script = ''
                vm.succeed("visudo -cf /etc/sudoers")
                vm.succeed("grep -q pam_unix.so /etc/pam.d/sudo")
              '';
            }
            {
              name = "sudo-wrapper";
              description = "sudo is materialized as a root-owned setuid wrapper";
              script = ''
                vm.wait_until_succeeds("test -u /run/wrappers/bin/sudo", timeout=30)
                vm.succeed("test $(stat -c %u:%g /run/wrappers/bin/sudo) = 0:0")
                vm.succeed("sudo -n true")
              '';
            }
            {
              name = "sudo-unauthorized";
              description = "a user outside wheel cannot run sudo";
              script = ''
                vm.fail("setpriv --reuid=65534 --regid=65534 --clear-groups sudo -n true")
              '';
            }
          ]
          ++ lib.optionals (!cfg.wheelNeedsPassword && wheelMembers != []) [
            (let
              userName = builtins.head wheelMembers;
              user = config.aos.users.users.${userName};
              group = config.aos.users.groups.${user.group};
            in {
              name = "sudo-wheel-authorized";
              description = "a configured wheel member can run an authorized command";
              script = ''
                vm.succeed(
                    "setpriv --reuid=${toString user.uid} --regid=${toString group.gid} "
                    "--groups=${toString config.aos.users.groups.wheel.gid} "
                    "sudo -n id -u | grep -Fx 0"
                )
              '';
            })
          ];
      };
    })
  ];
}
