##! modules/security/firewall.nix — nftables-based firewall module
##!
##! Generates a complete nftables ruleset with input filtering and forward
##! chain (for Kubernetes pod traffic). Services declare their own port
##! requirements by appending to aos.firewall.allowedTCP / allowedUDP.
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.firewall;
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  serviceTypes = serviceManagement.types;
  resultOf = lib.abilities.resultOf;
  producer = key: interface: parameters:
    serviceManagement.forProducer {
      consumerInstance = "system:firewall";
      inherit key interface parameters;
    };
  command = arguments: {
    executable = {
      artifact = lib.abilities.packageOutput {package = "nftables";};
      entry_point = "sbin/nft";
      inherit arguments;
    };
    ignore_failure = false;
  };

  # Render a named set's `elements = { 22, 80, 443 }` line. Omitted
  # entirely when the port list is empty — a declared-but-empty set
  # is fine (referencing it simply never matches).
  setElements = ports:
    if ports == []
    then ""
    else "\n      elements = { ${builtins.concatStringsSep ", " (builtins.map toString ports)} }";

  # Trusted interface rules — accept all traffic on lo, etc.
  trustedIfaceRules = builtins.concatStringsSep "\n" (
    builtins.map (iface: "    iifname \"${iface}\" accept") cfg.trustedInterfaces
  );

  # Full nftables ruleset.
  nftablesConf = ''
    #!${pkgs.nftables}/sbin/nft -f
    # /etc/nftables.conf — generated by modules/security/firewall.nix
    # Do not edit manually.

    # Flush existing rules.
    flush ruleset

    table inet filter {
      # Named sets for the inbound port allow-list. Package firewall
      # services mutate these sets at activation time. An empty set is
      # harmless — referencing it from a rule simply never matches.
      set allowed_tcp {
        type inet_service${setElements cfg.allowedTCP}
      }
      set allowed_udp {
        type inet_service${setElements cfg.allowedUDP}
      }

      chain input {
        type filter hook input priority 0; policy ${cfg.defaultPolicy};

        # Accept established and related connections.
        ct state established,related accept

        # Drop invalid packets.
        ct state invalid drop

        # Trusted interfaces (loopback, etc).
    ${trustedIfaceRules}

        # Accept ICMP (ping) and ICMPv6 for diagnostics.
        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        # Allowed inbound ports — base config plus any active package
        # firewall service that `add element`s to the sets above.
        tcp dport @allowed_tcp accept
        udp dport @allowed_udp accept

        # Log and drop everything else.
        log prefix "nft-drop: " flags all counter drop
      }

      chain forward {
        type filter hook forward priority 0; policy ${cfg.forwardPolicy};

        # Accept established and related forwarded traffic.
        ct state established,related accept

        # Drop invalid forwarded packets.
        ct state invalid drop
      }

      chain output {
        type filter hook output priority 0; policy accept;
      }
    }
  '';
  abilityFragments = [
    (producer "firewall-filesystems" serviceManagement.interfaces.filesystemReadiness {
      scope = "local-filesystems";
    })
    (producer "firewall-network-stack" serviceManagement.interfaces.networkReadiness {
      scope = "stack-prepared";
      address_families = ["ipv4" "ipv6"];
    })
    (serviceManagement.forConfiguration {
      inherit serviceTypes;
      consumerInstance = "system:firewall";
      declaration = {
        name = "firewall-ruleset";
        source = {
          kind = "inline-text";
          content = nftablesConf;
        };
        mode = "0444";
      };
    })
    (serviceManagement.forService {
      inherit serviceTypes;
      consumerInstance = "system:firewall";
      declaration = {
        service = "nftables";
        enabled = true;
        lifecycle = {
          description = "nftables Firewall";
          execution_model = "oneshot";
          environment_files = [];
          condition = [];
          pre_start = [];
          start = [(command ["-f" (resultOf "firewall-ruleset" "planned-path")])];
          post_start = [];
          stop = [(command ["flush" "ruleset"])];
          post_stop = [];
          restart = "never";
          restart_delay_millis = 100;
          configuration_change_action = "reload";
          remain_after_exit = true;
          start_timeout_millis = 90000;
          stop_timeout_millis = 90000;
        };
        dependencies = {
          after = [(resultOf "firewall-filesystems" "readiness-resource")];
          before = [(resultOf "firewall-network-stack" "readiness-resource")];
          requires = [];
          wants = [(resultOf "firewall-network-stack" "readiness-resource")];
        };
        reload = {
          strategy = "command";
          commands = [(command ["-f" (resultOf "firewall-ruleset" "planned-path")])];
          completion = "command-exit";
        };
        configuration.views = [{
          name = "ruleset";
          source = resultOf "firewall-ruleset" "planned-path";
          optional = false;
        }];
      };
    })
  ];
in {
  options.aos.firewall = {
    ## Enable the nftables-based firewall.
    ##
    ## # See Also
    ## - `aos.firewall.allowedTCP`, `aos.firewall.allowedUDP`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the nftables-based firewall.";
    };

    ## Default policy for the input chain.
    ##
    ## # Examples
    ## ```nix
    ## aos.firewall.defaultPolicy = "drop";
    ## ```
    defaultPolicy = lib.mkOption {
      type = lib.types.str;
      default = "drop";
      description = ''
        Default policy for the input chain. Should be "drop" for security.
        Only explicitly allowed ports will accept traffic.
      '';
    };

    ## TCP ports to allow inbound.
    ##
    ## Services append their ports here (e.g. SSH adds port 22,
    ## kubelet adds 10250, etc).
    ##
    ## # Examples
    ## ```nix
    ## aos.firewall.allowedTCP = [ 22 80 443 ];
    ## ```
    allowedTCP = lib.mkOption {
      type = lib.types.listOf lib.types.port;
      default = [];
      description = "TCP ports to allow inbound. Services append their ports here.";
    };

    ## UDP ports to allow inbound.
    ##
    ## Services append their ports here (e.g. Cilium VXLAN adds 8472).
    allowedUDP = lib.mkOption {
      type = lib.types.listOf lib.types.port;
      default = [];
      description = "UDP ports to allow inbound. Services append their ports here.";
    };

    ## Default policy for the forward chain.
    ##
    ## Set to "accept" on Kubernetes nodes for pod-to-pod traffic.
    forwardPolicy = lib.mkOption {
      type = lib.types.uniqEnum ["accept" "drop"];
      default = "drop";
      description = ''
        Default policy for the forward chain. Set to "accept" on Kubernetes
        nodes where pod-to-pod traffic traverses the forward chain.
      '';
    };

    ## Network interfaces where all traffic is accepted unconditionally.
    trustedInterfaces = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = ["lo"];
      description = ''
        Network interfaces where all traffic is accepted unconditionally.
        The loopback interface (lo) should always be trusted.
      '';
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge ([
    {
      system.checks.firewall = {
        description = "nftables firewall checks";
        checks = [
          {
            name = "nftables-active";
            description = "nftables service is active";
            script = ''
              vm.succeed("systemctl is-active nftables")
            '';
          }
          {
            name = "ruleset-loaded";
            description = "nftables ruleset is loaded";
            # `nft` by absolute store path: image slimming keeps nftables off the
            # system PATH (it is in the closure via this module's own units), so
            # the bare command is not available in-guest.
            script = ''
              vm.succeed("${pkgs.nftables}/sbin/nft list ruleset")
            '';
          }
        ];
      };

      aos.abilities.instances."system:firewall" = {};
    }
  ] ++ builtins.map (fragment: {aos.abilities = fragment;}) abilityFragments));
}
