##! modules/security/firewall.nix — nftables-based firewall module
##!
##! Generates a complete nftables ruleset with input filtering and forward
##! chain (for Kubernetes pod traffic). Services declare their own port
##! requirements by appending to aos.firewall.allowedTCP / allowedUDP.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.aos.firewall;

  # Format a list of ports as an nftables set expression: { 22, 80, 443 }
  portSet =
    ports:
    if ports == [ ] then "" else "{ ${builtins.concatStringsSep ", " (builtins.map toString ports)} }";

  # Build nftables rules for allowed TCP ports.
  tcpInputRules =
    if cfg.allowedTCP == [ ] then "" else "    tcp dport ${portSet cfg.allowedTCP} accept\n";

  # Build nftables rules for allowed UDP ports.
  udpInputRules =
    if cfg.allowedUDP == [ ] then "" else "    udp dport ${portSet cfg.allowedUDP} accept\n";

  # Trusted interface rules — accept all traffic on lo, etc.
  trustedIfaceRules = builtins.concatStringsSep "\n" (
    builtins.map (iface: "    iifname \"${iface}\" accept") cfg.trustedInterfaces
  );

  # Full nftables ruleset.
  nftablesConf = ''
    #!${pkgs.nftables}/sbin/nft -f
    # /etc/nftables.conf — generated by modules/security/firewall.nix
    # Do not edit manually.

    # Flush existing rules.
    flush ruleset

    table inet filter {
      chain input {
        type filter hook input priority 0; policy ${cfg.defaultPolicy};

        # Accept established and related connections.
        ct state established,related accept

        # Drop invalid packets.
        ct state invalid drop

        # Trusted interfaces (loopback, etc).
    ${trustedIfaceRules}

        # Accept ICMP (ping) and ICMPv6 for diagnostics.
        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        # Allowed TCP ports.
    ${tcpInputRules}
        # Allowed UDP ports.
    ${udpInputRules}
        # Log and drop everything else.
        log prefix "nft-drop: " flags all counter drop
      }

      chain forward {
        type filter hook forward priority 0; policy ${cfg.forwardPolicy};

        # Accept established and related forwarded traffic.
        ct state established,related accept

        # Drop invalid forwarded packets.
        ct state invalid drop
      }

      chain output {
        type filter hook output priority 0; policy accept;
      }
    }
  '';
in
{
  options.aos.firewall = {
    ## Enable the nftables-based firewall.
    ##
    ## # See Also
    ## - `aos.firewall.allowedTCP`, `aos.firewall.allowedUDP`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the nftables-based firewall.";
    };

    ## Default policy for the input chain.
    ##
    ## # Examples
    ## ```nix
    ## aos.firewall.defaultPolicy = "drop";
    ## ```
    defaultPolicy = lib.mkOption {
      type = lib.types.str;
      default = "drop";
      description = ''
        Default policy for the input chain. Should be "drop" for security.
        Only explicitly allowed ports will accept traffic.
      '';
    };

    ## TCP ports to allow inbound.
    ##
    ## Services append their ports here (e.g. SSH adds port 22,
    ## kubelet adds 10250, etc).
    ##
    ## # Examples
    ## ```nix
    ## aos.firewall.allowedTCP = [ 22 80 443 ];
    ## ```
    allowedTCP = lib.mkOption {
      type = lib.types.listOf lib.types.port;
      default = [ ];
      description = "TCP ports to allow inbound. Services append their ports here.";
    };

    ## UDP ports to allow inbound.
    ##
    ## Services append their ports here (e.g. Cilium VXLAN adds 8472).
    allowedUDP = lib.mkOption {
      type = lib.types.listOf lib.types.port;
      default = [ ];
      description = "UDP ports to allow inbound. Services append their ports here.";
    };

    ## Default policy for the forward chain.
    ##
    ## Set to "accept" on Kubernetes nodes for pod-to-pod traffic.
    ##
    ## # See Also
    ## - `aos.kubernetes.network.enable`
    forwardPolicy = lib.mkOption {
      type = lib.types.str;
      default = "drop";
      description = ''
        Default policy for the forward chain. Set to "accept" on Kubernetes
        nodes where pod-to-pod traffic traverses the forward chain.
      '';
    };

    ## Network interfaces where all traffic is accepted unconditionally.
    trustedInterfaces = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "lo" ];
      description = ''
        Network interfaces where all traffic is accepted unconditionally.
        The loopback interface (lo) should always be trusted.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    system.checks.firewall = lib.mkCheckGroup {
      name = "firewall";
      description = "nftables firewall checks";
      checks = [
        (lib.mkCheck {
          name = "nftables-active";
          description = "nftables service is active";
          script = ''
            assert_success "systemctl is-active nftables" \
              "nftables service is active"
          '';
        })
        (lib.mkCheck {
          name = "ruleset-loaded";
          description = "nftables ruleset is loaded";
          script = ''
            assert_success "nft list ruleset" \
              "nftables ruleset is loaded"
          '';
        })
      ];
    };

    environment.systemPackages = [
      pkgs.nftables
      pkgs.iptables
    ];

    # /etc/nftables.conf — complete nftables ruleset.
    environment.etc."nftables.conf" = {
      text = nftablesConf;
    };

    # nftables.service — load the firewall rules at boot.
    systemd.services."nftables" = {
      description = "nftables Firewall";
      wantedBy = [ "multi-user.target" ];
      before = [ "network-pre.target" ];
      wants = [ "network-pre.target" ];
      after = [ "local-fs.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.nftables}/sbin/nft -f /etc/nftables.conf";
        ExecReload = "${pkgs.nftables}/sbin/nft -f /etc/nftables.conf";
        ExecStop = "${pkgs.nftables}/sbin/nft flush ruleset";
      };
    };
  };
}
