# modules/security/firewall.nix — nftables-based firewall module
#
# Generates a complete nftables ruleset with input filtering, forward
# chain (for Kubernetes pod traffic), and pre-configured port sets for
# SSH, Kubernetes worker nodes, control plane components, and Cilium.
#
# Absorbed TOML config values:
#   [firewall] enable, default_policy, allowed_tcp, allowed_udp
#   [firewall] forward_policy, trusted_interfaces
#   [firewall.kubernetes] worker_tcp, worker_udp, control_plane_tcp, cilium_tcp

{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.aos.firewall;

  # Format a list of ports as an nftables set expression: { 22, 80, 443 }
  portSet =
    ports:
    if ports == [ ] then "" else "{ ${builtins.concatStringsSep ", " (builtins.map toString ports)} }";

  # Build nftables rules for allowed TCP ports.
  tcpInputRules =
    if cfg.allowedTCP == [ ] then "" else "    tcp dport ${portSet cfg.allowedTCP} accept\n";

  # Build nftables rules for allowed UDP ports.
  udpInputRules =
    if cfg.allowedUDP == [ ] then "" else "    udp dport ${portSet cfg.allowedUDP} accept\n";

  # Trusted interface rules — accept all traffic on lo, etc.
  trustedIfaceRules = builtins.concatStringsSep "\n" (
    builtins.map (iface: "    iifname \"${iface}\" accept") cfg.trustedInterfaces
  );

  # Kubernetes-specific rules (only included when K8s ports are defined).
  k8sWorkerTcpRules =
    if cfg.kubernetes.workerTCP == [ ] then
      ""
    else
      "    tcp dport ${portSet cfg.kubernetes.workerTCP} accept comment \"K8s worker ports\"\n";

  k8sWorkerUdpRules =
    if cfg.kubernetes.workerUDP == [ ] then
      ""
    else
      "    udp dport ${portSet cfg.kubernetes.workerUDP} accept comment \"K8s overlay (VXLAN)\"\n";

  k8sControlPlaneTcpRules =
    if cfg.kubernetes.controlPlaneTCP == [ ] then
      ""
    else
      "    tcp dport ${portSet cfg.kubernetes.controlPlaneTCP} accept comment \"K8s control plane\"\n";

  k8sCiliumTcpRules =
    if cfg.kubernetes.ciliumTCP == [ ] then
      ""
    else
      "    tcp dport ${portSet cfg.kubernetes.ciliumTCP} accept comment \"Cilium health/Hubble\"\n";

  # Full nftables ruleset.
  nftablesConf = ''
    #!/usr/sbin/nft -f
    # /etc/nftables.conf — generated by modules/security/firewall.nix
    # Do not edit manually.

    # Flush existing rules.
    flush ruleset

    table inet filter {
      chain input {
        type filter hook input priority 0; policy ${cfg.defaultPolicy};

        # Accept established and related connections.
        ct state established,related accept

        # Drop invalid packets.
        ct state invalid drop

        # Trusted interfaces (loopback, etc).
    ${trustedIfaceRules}

        # Accept ICMP (ping) and ICMPv6 for diagnostics.
        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        # Allowed TCP ports.
    ${tcpInputRules}
        # Allowed UDP ports.
    ${udpInputRules}
        # Kubernetes worker node ports.
    ${k8sWorkerTcpRules}${k8sWorkerUdpRules}
        # Kubernetes control plane ports.
    ${k8sControlPlaneTcpRules}
        # Cilium CNI ports.
    ${k8sCiliumTcpRules}
        # Log and drop everything else.
        log prefix "nft-drop: " flags all counter drop
      }

      chain forward {
        type filter hook forward priority 0; policy ${cfg.forwardPolicy};

        # Accept established and related forwarded traffic.
        ct state established,related accept

        # Drop invalid forwarded packets.
        ct state invalid drop
      }

      chain output {
        type filter hook output priority 0; policy accept;
      }
    }
  '';

in
{
  options.aos.firewall = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the nftables-based firewall.";
    };

    defaultPolicy = lib.mkOption {
      type = lib.types.str;
      default = "drop";
      description = ''
        Default policy for the input chain. Should be "drop" for security.
        Only explicitly allowed ports will accept traffic.
      '';
    };

    allowedTCP = lib.mkOption {
      type = lib.types.listOf lib.types.port;
      default = [ 22 ];
      description = "TCP ports to allow inbound. Default: SSH only.";
    };

    allowedUDP = lib.mkOption {
      type = lib.types.listOf lib.types.port;
      default = [ ];
      description = "UDP ports to allow inbound.";
    };

    forwardPolicy = lib.mkOption {
      type = lib.types.str;
      default = "drop";
      description = ''
        Default policy for the forward chain. Set to "accept" on Kubernetes
        nodes where pod-to-pod traffic traverses the forward chain.
      '';
    };

    trustedInterfaces = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "lo" ];
      description = ''
        Network interfaces where all traffic is accepted unconditionally.
        The loopback interface (lo) should always be trusted.
      '';
    };

    kubernetes = {
      workerTCP = lib.mkOption {
        type = lib.types.listOf lib.types.port;
        default = [
          10250
          10256
          30000
        ];
        description = ''
          TCP ports for Kubernetes worker nodes:
          - 10250: kubelet API
          - 10256: kube-proxy health check
          - 30000: NodePort range start (30000-32767 handled separately)
        '';
      };

      workerUDP = lib.mkOption {
        type = lib.types.listOf lib.types.port;
        default = [ 8472 ];
        description = ''
          UDP ports for Kubernetes worker nodes:
          - 8472: VXLAN overlay network (Flannel/Cilium)
        '';
      };

      controlPlaneTCP = lib.mkOption {
        type = lib.types.listOf lib.types.port;
        default = [
          6443
          2379
          2380
          10257
          10259
        ];
        description = ''
          TCP ports for Kubernetes control plane:
          - 6443: kube-apiserver
          - 2379-2380: etcd client and peer
          - 10257: kube-controller-manager
          - 10259: kube-scheduler
        '';
      };

      ciliumTCP = lib.mkOption {
        type = lib.types.listOf lib.types.port;
        default = [
          4240
          4244
        ];
        description = ''
          TCP ports for Cilium CNI:
          - 4240: Cilium health checks
          - 4244: Hubble relay
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      pkgs.nftables
      pkgs.iptables
    ];

    # /etc/nftables.conf — complete nftables ruleset.
    environment.etc."nftables.conf" = {
      text = nftablesConf;
    };

    # nftables.service — load the firewall rules at boot.
    systemd.services."nftables" = {
      description = "nftables Firewall";
      wantedBy = [ "multi-user.target" ];
      before = [ "network-pre.target" ];
      wants = [ "network-pre.target" ];
      after = [ "local-fs.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "/usr/sbin/nft -f /etc/nftables.conf";
        ExecReload = "/usr/sbin/nft -f /etc/nftables.conf";
        ExecStop = "/usr/sbin/nft flush ruleset";
      };
    };
  };
}
