##! modules/security/hardening.nix — System hardening via sysctl and kernel params
##!
##! Applies security-focused sysctl settings and kernel parameters. The defaults
##! follow CIS benchmarks and DISA STIG guidance: ASLR, pointer restriction,
##! dmesg access control, network hardening, and filesystem protections.
##!
##! Absorbed TOML config values:
##!   [security.hardening] enable, sysctl, kernel_lockdown, core_dump
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.security.hardening;

  # Format sysctl settings as a sysctl.d(5) drop-in file.
  sysctlText = builtins.concatStringsSep "\n" (
    lib.mapAttrsToList (key: value: "${key} = ${value}") cfg.sysctl
  );
in {
  options.aos.security.hardening = {
    ## Enable system hardening (sysctl, lockdown, core dump restrictions).
    ##
    ## # See Also
    ## - `aos.security.hardening.sysctl`, `aos.security.hardening.kernelLockdown`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Enable system hardening. Applies security-focused sysctl settings,
        kernel lockdown mode, and core dump restrictions. Enabled by default
        because AOS is a server OS where security is paramount.
      '';
    };

    ## Security-focused sysctl parameters (CIS benchmarks).
    ##
    ## # Examples
    ## ```nix
    ## aos.security.hardening.sysctl."kernel.kptr_restrict" = "2";
    ## ```
    sysctl = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        # -- Address space layout randomization --
        "kernel.randomize_va_space" = "2";

        # -- Kernel pointer and debug restrictions --
        "kernel.kptr_restrict" = "2";
        "kernel.dmesg_restrict" = "1";
        "kernel.perf_event_paranoid" = "3";
        "kernel.yama.ptrace_scope" = "2";

        # -- Network hardening: IPv4 --
        "net.ipv4.conf.all.rp_filter" = "1";
        "net.ipv4.conf.all.accept_redirects" = "0";
        "net.ipv4.conf.all.send_redirects" = "0";
        "net.ipv4.conf.all.accept_source_route" = "0";
        "net.ipv4.conf.all.log_martians" = "1";
        "net.ipv4.icmp_echo_ignore_broadcasts" = "1";
        "net.ipv4.tcp_syncookies" = "1";

        # -- Network hardening: IPv6 --
        "net.ipv6.conf.all.accept_redirects" = "0";

        # -- Filesystem protections --
        "fs.protected_hardlinks" = "1";
        "fs.protected_symlinks" = "1";
        "fs.suid_dumpable" = "0";
      };
      description = ''
        Kernel sysctl parameters for security hardening. Written to
        /etc/sysctl.d/80-aos-hardening.conf and applied at boot by
        systemd-sysctl.service. The defaults follow CIS benchmark
        recommendations for Linux servers.
      '';
    };

    ## Kernel lockdown mode (none, integrity, confidentiality).
    ##
    ## # Examples
    ## ```nix
    ## aos.security.hardening.kernelLockdown = "confidentiality";
    ## ```
    kernelLockdown = lib.mkOption {
      type = lib.types.enum [
        "none"
        "integrity"
        "confidentiality"
      ];
      default = "integrity";
      description = ''
        Kernel lockdown mode:
        - none: no restrictions
        - integrity: prevents modification of the running kernel
          (blocks kexec, module signature bypass, /dev/mem writes)
        - confidentiality: integrity + prevents reading kernel memory
          (blocks /proc/kcore, eBPF, perf)
      '';
    };

    coreDump = {
      ## Allow core dumps (disabled by default for security).
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Allow core dumps. Disabled by default on AOS because core dumps
          can leak sensitive data (cryptographic keys, credentials) from
          process memory.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # /etc/sysctl.d/80-aos-hardening.conf — security sysctl settings.
    # Applied by systemd-sysctl.service during early boot.
    environment.etc."sysctl.d/80-aos-hardening.conf" = {
      text = ''
        # /etc/sysctl.d/80-aos-hardening.conf
        # Generated by modules/security/hardening.nix
        # Security-focused kernel parameters per CIS benchmarks.

        ${sysctlText}
      '';
    };

    # Core dump configuration.
    environment.etc."sysctl.d/81-aos-coredump.conf" = {
      text = ''
        # Core dump control — generated by modules/security/hardening.nix
        ${
          if cfg.coreDump.enable
          then ''
            kernel.core_pattern=|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e
          ''
          else ''
            kernel.core_pattern=|/bin/false
            fs.suid_dumpable = 0
          ''
        }
      '';
    };

    # systemd core dump configuration.
    environment.etc."systemd/coredump.conf" = {
      text = ''
        # /etc/systemd/coredump.conf — generated by modules/security/hardening.nix
        [Coredump]
        ${
          if cfg.coreDump.enable
          then ''
            Storage=journal
            Compress=yes
            MaxUse=1G
          ''
          else ''
            Storage=none
            ProcessSizeMax=0
          ''
        }
      '';
    };

    # Kernel lockdown parameter — added to boot command line.
    # Only add the parameter if lockdown is not "none".
    aos.boot.kernelParams = let
      baseCmdline = [
        "console=ttyS0,115200"
        "console=tty0"
        "systemd.unified_cgroup_hierarchy=1"
        "selinux=1"
        "security=selinux"
      ];
      lockdownParam =
        if cfg.kernelLockdown != "none"
        then ["lockdown=${cfg.kernelLockdown}"]
        else [];
    in
      baseCmdline ++ lockdownParam;

    # Resource limits to prevent core dumps at the process level.
    environment.etc."security/limits.d/aos-hardening.conf" = lib.mkIf (!cfg.coreDump.enable) {
      text = ''
        # Disable core dumps for all users.
        # Generated by modules/security/hardening.nix
        *  hard  core  0
        *  soft  core  0
      '';
    };
  };
}
