##! modules/security/opkssh.nix — OpenPubkey SSH authentication module
##!
##! Configures opkssh for SSH authentication using OpenID Connect (OIDC)
##! identities. Users authenticate via their identity provider (Google,
##! Azure, GitLab) and receive ephemeral SSH keys containing PK Tokens.
##! The SSH daemon verifies these tokens via an AuthorizedKeysCommand.
##!
##! When enabled, this module:
##!   - Installs the opkssh binary
##!   - Creates the opksshuser service account
##!   - Generates /etc/opk/providers and /etc/opk/auth_id
##!   - Generates /etc/opk/config.yml (deny lists, env vars)
##!   - Configures sshd AuthorizedKeysCommand integration
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.services.opkssh;

  # Generate /etc/opk/providers — space-delimited provider list.
  # Format: <issuer> <client_id> <expiration_policy>
  providersText = builtins.concatStringsSep "\n" (
    builtins.map (p: "${p.issuer} ${p.clientId} ${p.expirationPolicy}") cfg.providers
  );

  # Generate /etc/opk/auth_id — identity-to-principal mapping.
  # Format: <identity> <principal> <issuer>
  authIdText = builtins.concatStringsSep "\n" (
    builtins.map (r: "${r.identity} ${r.principal} ${r.issuer}") cfg.authRules
  );

  # Generate /etc/opk/config.yml — server YAML config.
  configYaml =
    ''
      # /etc/opk/config.yml — generated by modules/security/opkssh.nix
      # Do not edit manually.
    ''
    + (
      if cfg.denyEmails != []
      then ''
        deny_emails:
        ${builtins.concatStringsSep "\n" (builtins.map (e: "  - ${e}") cfg.denyEmails)}
      ''
      else ""
    )
    + (
      if cfg.denyUsers != []
      then ''
        deny_users:
        ${builtins.concatStringsSep "\n" (builtins.map (u: "  - ${u}") cfg.denyUsers)}
      ''
      else ""
    );
in {
  options.aos.services.opkssh = {
    ## Enable opkssh OIDC SSH authentication.
    ##
    ## When enabled, sshd is configured to use opkssh as the
    ## AuthorizedKeysCommand, allowing users to authenticate with
    ## OIDC identity tokens instead of long-lived SSH keys.
    ##
    ## # Examples
    ## ```nix
    ## aos.services.opkssh.enable = true;
    ## aos.services.opkssh.providers = [{
    ##   issuer = "https://accounts.google.com";
    ##   clientId = "your-client-id.apps.googleusercontent.com";
    ## }];
    ## ```
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable opkssh OIDC SSH authentication.";
    };

    ## OIDC providers allowed to authenticate.
    ##
    ## Each provider specifies an issuer URL, OAuth client ID, and
    ## token expiration policy.
    ##
    ## # Examples
    ## ```nix
    ## aos.services.opkssh.providers = [{
    ##   issuer = "https://accounts.google.com";
    ##   clientId = "your-client-id.apps.googleusercontent.com";
    ##   expirationPolicy = "24h";
    ## }];
    ## ```
    providers = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            ## OIDC issuer URL (e.g. "https://accounts.google.com").
            issuer = lib.mkOption {
              type = lib.types.str;
              description = "OIDC issuer URL.";
            };
            ## OAuth client ID for this provider.
            clientId = lib.mkOption {
              type = lib.types.str;
              description = "OAuth client ID.";
            };
            ## Token expiration policy.
            expirationPolicy = lib.mkOption {
              type = lib.types.str;
              default = "24h";
              description = "Token expiration policy (e.g. 12h, 24h, 48h, oidc).";
            };
          };
        }
      );
      default = [];
      description = "OIDC providers allowed to authenticate.";
    };

    ## Identity-to-principal mappings.
    ##
    ## Maps OIDC identities (email, sub, group) to Linux usernames,
    ## controlling which identities can log in as which users.
    ##
    ## # Examples
    ## ```nix
    ## aos.services.opkssh.authRules = [{
    ##   principal = "root";
    ##   identity = "alice@example.com";
    ##   issuer = "https://accounts.google.com";
    ## }];
    ## ```
    authRules = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            ## Linux username this identity maps to.
            principal = lib.mkOption {
              type = lib.types.str;
              description = "Linux username.";
            };
            ## Email, sub, or group identifier.
            identity = lib.mkOption {
              type = lib.types.str;
              description = "Email, sub, or group identifier.";
            };
            ## OIDC issuer URL for this identity.
            issuer = lib.mkOption {
              type = lib.types.str;
              description = "OIDC issuer URL for this identity.";
            };
          };
        }
      );
      default = [];
      description = "Identity-to-principal mappings.";
    };

    ## Email addresses to deny authentication.
    denyEmails = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Email addresses to deny authentication.";
    };

    ## Linux users to deny authentication.
    denyUsers = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Linux users to deny authentication.";
    };

    ## Path to the server config file.
    serverConfigPath = lib.mkOption {
      type = lib.types.str;
      default = "/etc/opk/config.yml";
      description = "Path to the opkssh server config file.";
    };
  };

  config = lib.mkIf cfg.enable {
    # Wire opkssh into sshd via AuthorizedKeysCommand.
    aos.services.ssh.authorizedKeysCommand = "${pkgs.opkssh}/bin/opkssh verify %u %k %t";
    aos.services.ssh.authorizedKeysCommandUser = "opksshuser";

    # /etc/opk/providers — OIDC provider list.
    environment.etc."opk/providers" = {
      text = providersText + "\n";
    };

    # /etc/opk/auth_id — identity-to-principal mapping.
    environment.etc."opk/auth_id" = {
      text = authIdText + "\n";
    };

    # /etc/opk/config.yml — server config.
    environment.etc."opk/config.yml" = {
      text = configYaml;
    };

    # Ensure /etc/opk/ directory and log file exist.
    environment.etc."tmpfiles.d/aos-opkssh.conf" = {
      text = ''
        # opkssh directories and log files.
        d /etc/opk 0755 root root -
        f /var/log/opkssh.log 0660 root opksshuser -
      '';
    };

    # Create the opksshuser service account.
    aos.users.users.opksshuser = {
      uid = 993;
      group = "opksshuser";
      home = "/";
      shell = "/sbin/nologin";
      description = "opkssh AuthorizedKeysCommand user";
      extraGroups = [];
    };

    aos.users.groups.opksshuser = {
      gid = 993;
      members = ["opksshuser"];
    };
  };
}
