##! modules/security/polkit.nix — System authorization policy service
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.aos.security.polkit;
  localRules = ''
    // Generated by modules/security/polkit.nix.
    ${lib.concatStringsSep "\n\n" cfg.extraRules}
  '';
in {
  options.aos.security.polkit = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Run polkit and install its authorization tools.";
    };

    extraRules = lib.mkOption {
      type = lib.types.listOf lib.types.lines;
      default = [];
      description = "JavaScript authorization rules loaded after packaged policy.";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [pkgs.polkit];
    environment.etc."polkit-1/rules.d/10-aos.rules" = {
      mode = "0640";
      text = localRules;
    };
    environment.etc."polkit-1/actions/org.freedesktop.policykit.policy".source = "${pkgs.polkit}/share/polkit-1/actions/org.freedesktop.policykit.policy";

    aos.services.dbus.packages = [pkgs.polkit];

    aos.users.users.polkitd = {
      uid = 27;
      group = "polkitd";
      home = "/var/lib/polkit-1";
      shell = "/sbin/nologin";
      description = "PolicyKit daemon";
      extraGroups = [];
    };
    aos.users.groups.polkitd = {
      gid = 27;
      members = [];
    };

    aos.security.wrappers = {
      pkexec = {
        source = "${pkgs.polkit}/bin/pkexec";
        owner = "root";
        group = "root";
        mode = "4755";
      };
      polkit-agent-helper-1 = {
        source = "${pkgs.polkit}/lib/polkit-1/polkit-agent-helper-1";
        owner = "root";
        group = "root";
        mode = "4755";
      };
    };

    aos.pam.services."polkit-1" = {
      unixAuth = true;
      startSession = false;
      setLoginUid = false;
    };

    environment.etc."tmpfiles.d/aos-polkit.conf".text = ''
      d /etc/polkit-1/rules.d 0750 root polkitd -
      d /run/polkit-1/rules.d 0750 root polkitd -
      d /var/lib/polkit-1 0700 polkitd polkitd -
    '';

    systemd.services.polkit = {
      description = "Authorization Manager";
      wantedBy = ["multi-user.target"];
      after = ["dbus.socket" "systemd-logind.service"];
      requires = ["dbus.socket"];
      wants = ["systemd-logind.service"];
      serviceConfig = {
        Type = "notify-reload";
        BusName = "org.freedesktop.PolicyKit1";
        ExecStart = "${pkgs.polkit}/lib/polkit-1/polkitd --no-debug --log-level=notice";
        User = "polkitd";
        Group = "polkitd";
        CapabilityBoundingSet = ["CAP_SETUID" "CAP_SETGID"];
        DeviceAllow = "/dev/null rw";
        DevicePolicy = "strict";
        LimitMEMLOCK = 0;
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        NoNewPrivileges = true;
        PrivateDevices = true;
        PrivateNetwork = true;
        PrivateTmp = true;
        ProtectClock = true;
        ProtectControlGroups = true;
        ProtectHome = true;
        ProtectHostname = true;
        ProtectKernelLogs = true;
        ProtectKernelModules = true;
        ProtectKernelTunables = true;
        ProtectSystem = "strict";
        RemoveIPC = true;
        RestrictAddressFamilies = ["AF_UNIX"];
        RestrictNamespaces = true;
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        SystemCallArchitectures = "native";
        SystemCallFilter = "@system-service";
        UMask = "0077";
        MemoryMax = "32M";
        MemorySwapMax = "32M";
        OOMPolicy = "stop";
        Restart = "on-failure";
      };
    };

    system.checks.polkit = {
      description = "polkit service and privilege checks";
      checks = [
        {
          name = "polkit-active";
          description = "polkit owns its D-Bus name under the dedicated account";
          script = ''
            vm.wait_until_succeeds(
                "systemctl is-active --quiet polkit.service", timeout=30
            )
            vm.succeed("test $(systemctl show -p MainPID --value polkit.service) != 0")
            vm.succeed(
                "grep -Eq '^Uid:[[:space:]]+27[[:space:]]+27[[:space:]]+27[[:space:]]+27$' /proc/$(systemctl show -p MainPID --value polkit.service)/status"
            )
          '';
        }
        {
          name = "polkit-policy";
          description = "packaged actions and local rules are visible";
          script = ''
            vm.succeed("pkaction | grep -Fx org.freedesktop.policykit.exec")
            vm.succeed("grep -Fq 'Generated by modules/security/polkit.nix' /etc/polkit-1/rules.d/10-aos.rules")
            vm.succeed("grep -q pam_unix.so /etc/pam.d/polkit-1")
          '';
        }
        {
          name = "polkit-wrappers";
          description = "polkit privileged entry points are root-owned setuid wrappers";
          script = ''
            vm.wait_until_succeeds(
                "systemctl is-active --quiet aos-security-wrappers.service",
                timeout=30,
            )
            vm.succeed("test -u /run/wrappers/bin/pkexec")
            vm.succeed("test -u /run/wrappers/bin/polkit-agent-helper-1")
            vm.succeed("test $(stat -c %u:%g /run/wrappers/bin/pkexec) = 0:0")
          '';
        }
      ];
    };
  };
}
