##! modules/security/polkit.nix — System authorization policy service
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.aos.security.polkit or {enable = false;};
  polkitArtifact = lib.abilities.packageOutput {package = "polkit";};
in {
  environment.systemPackages = [pkgs.polkit];

  aos.security.wrappers = lib.mkIf cfg.enable {
    pkexec = {
      source = {
        artifact = polkitArtifact;
        path = "bin/pkexec";
      };
    };
    polkit-agent-helper-1 = {
      source = {
        artifact = polkitArtifact;
        path = "lib/polkit-1/polkit-agent-helper-1";
      };
    };
  };

  aos.pam.services."polkit-1" = lib.mkIf cfg.enable {
    unixAuth = true;
    startSession = false;
    setLoginUid = false;
  };

  system.checks.polkit = lib.mkIf cfg.enable {
    description = "polkit service and privilege checks";
    checks = [
      {
        name = "polkit-active";
        description = "polkit owns its D-Bus name under the dedicated account";
        script = ''
          vm.wait_until_succeeds(
              "systemctl is-active --quiet polkit.service", timeout=30
          )
          vm.succeed("test $(systemctl show -p MainPID --value polkit.service) != 0")
          vm.succeed(
              "grep -Eq '^Uid:[[:space:]]+27[[:space:]]+27[[:space:]]+27[[:space:]]+27$' /proc/$(systemctl show -p MainPID --value polkit.service)/status"
          )
        '';
      }
      {
        name = "polkit-policy";
        description = "packaged actions and local rules are visible";
        script = ''
          vm.succeed("pkaction | grep -Fx org.freedesktop.policykit.exec")
          vm.succeed("grep -Fq 'Generated by the package-owned polkit ability module' /etc/polkit-1/rules.d/10-aos.rules")
          vm.succeed("grep -q pam_unix.so /etc/pam.d/polkit-1")
        '';
      }
      {
        name = "polkit-wrappers";
        description = "polkit privileged entry points are root-owned setuid wrappers";
        script = ''
          vm.wait_until_succeeds("test -u /run/wrappers/bin/pkexec", timeout=30)
          vm.succeed("test -u /run/wrappers/bin/polkit-agent-helper-1")
          vm.succeed("test $(stat -c %u:%g /run/wrappers/bin/pkexec) = 0:0")
        '';
      }
    ];
  };
}
