##! modules/security/selinux.nix — SELinux configuration module
##!
##! Configures SELinux mode, policy, and generates the config file, policy
##! loading service, and optional auto-relabeling service. SELinux is a
##! mandatory access control (MAC) system that confines processes to the
##! minimum privileges they need.
##!
##! Absorbed TOML config values:
##!   [security.selinux] enable, mode, policy, autorelabel
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.security.selinux;
in {
  options.aos.security.selinux = {
    ## Enable SELinux mandatory access control.
    ##
    ## # Examples
    ## ```nix
    ## aos.security.selinux.enable = true;
    ## ```
    ##
    ## # See Also
    ## - `aos.security.selinux.mode`, `aos.security.selinux.policy`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Enable SELinux mandatory access control. When enabled, the kernel
        enforces the configured policy on all processes. Requires kernel
        support (selinux=1 security=selinux in boot parameters).
      '';
    };

    ## SELinux operating mode (enforcing, permissive, disabled).
    ##
    ## # Examples
    ## ```nix
    ## aos.security.selinux.mode = "permissive";
    ## ```
    mode = lib.mkOption {
      type = lib.types.enum [
        "enforcing"
        "permissive"
        "disabled"
      ];
      default = "enforcing";
      description = ''
        SELinux operating mode:
        - enforcing: denies access and logs violations
        - permissive: logs violations but does not deny access
        - disabled: SELinux is completely disabled
      '';
    };

    ## SELinux policy to load ("targeted" or "strict").
    policy = lib.mkOption {
      type = lib.types.str;
      default = "targeted";
      description = ''
        SELinux policy to load. "targeted" confines specific daemons while
        leaving most user processes unconfined. "strict" confines everything.
      '';
    };

    ## Automatically relabel the filesystem on first boot or policy change.
    autorelabel = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Automatically relabel the filesystem on first boot or when the
        /.autorelabel file exists. Required after policy changes to ensure
        all files have correct security contexts.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    system.checks.selinux = lib.mkCheckGroup {
      name = "selinux";
      description = "SELinux checks";
      checks = [
        (lib.mkCheck {
          name = "selinuxfs";
          description = "/sys/fs/selinux is present";
          script = ''
            assert_success "test -d /sys/fs/selinux" \
              "/sys/fs/selinux is present"
          '';
        })
        (lib.mkCheck {
          name = "enforce-file";
          description = "SELinux enforce file exists";
          script = ''
            assert_success "test -f /sys/fs/selinux/enforce" \
              "SELinux enforce file exists"
          '';
        })
      ];
    };

    environment.systemPackages = [
      pkgs.policycoreutils
      pkgs.libselinux
    ];

    # /etc/selinux/config — main SELinux configuration file.
    # Read by libselinux at boot and by selinux-policy-load.service.
    environment.etc."selinux/config" = {
      text = ''
        # /etc/selinux/config — generated by modules/security/selinux.nix
        # SELinux mode: enforcing, permissive, or disabled
        SELINUX=${cfg.mode}

        # SELinux policy name
        SELINUXTYPE=${cfg.policy}
      '';
    };

    systemd.services = {
      # Load the SELinux policy early in boot.
      # This must run before any confined services start.
      "selinux-policy-load" = {
        description = "Load SELinux Policy";
        wantedBy = ["sysinit.target"];
        before = [
          "sysinit.target"
          "systemd-tmpfiles-setup.service"
        ];
        after = ["local-fs.target"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = "${pkgs.policycoreutils}/sbin/load_policy";
        };
      };

      # Filesystem relabeling service.
      # Runs on first boot or when /.autorelabel exists.
      "selinux-autorelabel" = lib.mkIf cfg.autorelabel {
        description = "SELinux Filesystem Relabeling";
        wantedBy = ["sysinit.target"];
        before = ["sysinit.target"];
        after = [
          "selinux-policy-load.service"
          "local-fs.target"
        ];
        requires = ["selinux-policy-load.service"];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          # Only relabel if the marker file exists.
          ExecCondition = "${pkgs.coreutils}/bin/test -f /.autorelabel";
          ExecStart = "${pkgs.policycoreutils}/sbin/fixfiles -f -F relabel";
          ExecStartPost = "${pkgs.coreutils}/bin/rm -f /.autorelabel";
        };
      };
    };

    # Ensure SELinux kernel parameters are present in the boot config.
    # The boot module handles the actual cmdline; we just declare what
    # we need here and the system compositor merges it.
    aos.boot.kernelParams = [
      "console=ttyS0,115200"
      "console=tty0"
      "systemd.unified_cgroup_hierarchy=1"
      "selinux=1"
      "security=selinux"
    ];
  };
}
