##! modules/security/wrappers.nix — Runtime privilege wrappers
##!
##! Materializes explicitly declared privileged executables in the volatile
##! `/run/wrappers/bin` directory. Package outputs remain immutable and never
##! carry setuid bits; ownership and mode are applied by PID 1 at boot and
##! whenever a configuration generation activates.
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.aos.security.wrappers;
  names = builtins.attrNames cfg;
  render = name: let
    wrapper = cfg.${name};
  in "C+ /run/wrappers/bin/${name} ${wrapper.mode} ${wrapper.owner} ${wrapper.group} - ${wrapper.source}";
in {
  options.aos.security.wrappers = lib.mkOption {
    type = lib.types.attrsOf (lib.types.submodule {
      options = {
        source = lib.mkOption {
          type = lib.types.strMatching "/nix/store/[A-Za-z0-9+._?=/-]+";
          description = "Absolute package executable copied into the runtime wrapper directory.";
        };
        owner = lib.mkOption {
          type = lib.types.strMatching "[A-Za-z_][A-Za-z0-9_-]*";
          default = "root";
          description = "Owner of the runtime wrapper.";
        };
        group = lib.mkOption {
          type = lib.types.strMatching "[A-Za-z_][A-Za-z0-9_-]*";
          default = "root";
          description = "Group of the runtime wrapper.";
        };
        mode = lib.mkOption {
          type = lib.types.strMatching "[0-7]{4}";
          default = "4755";
          description = "Four-digit octal mode applied to the runtime wrapper.";
        };
      };
    });
    default = {};
    description = "Privileged executables materialized under /run/wrappers/bin.";
  };

  config = lib.mkIf (names != []) {
    assertions =
      map (name: {
        assertion = builtins.match "[A-Za-z0-9._+-]+" name != null;
        message = "aos.security.wrappers names may contain only letters, digits, '.', '_', '+', and '-'";
      })
      names;

    environment.etc."tmpfiles.d/aos-security-wrappers.conf" = {
      text = ''
        # Generated by modules/security/wrappers.nix.
        d /run/wrappers     0755 root root - -
        d /run/wrappers/bin 0755 root root - -
        ${builtins.concatStringsSep "\n" (map render names)}
      '';
    };

    systemd.services.aos-security-wrappers = {
      description = "Materialize runtime privilege wrappers";
      wantedBy = ["sysinit.target"];
      before = ["systemd-user-sessions.service"];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = "yes";
        ExecStart = "${pkgs.systemd}/bin/systemd-tmpfiles --create /etc/tmpfiles.d/aos-security-wrappers.conf";
      };
    };
  };
}
