##! modules/base/_apm-registry-renderer.nix — Shared apm registry files
{lib}: let
  registryNamePattern = "[A-Za-z0-9_-]+";

  registryType = lib.types.submodule {
    options = {
      url = lib.mkOption {
        type = lib.types.str;
        description = "Registry git/HTTP URL.";
      };
      trustKeys = lib.mkOption {
        type = lib.types.nonEmptyListOf lib.types.str;
        description = ''
          Maintainer public keys in `<name>:Ed25519:<base64>` form.
          The first entry becomes the `[registry.signing]` bootstrap
          anchor; all entries are written to `trusted-keys.d`.
        '';
      };
      required = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Require signature verification on every sync.";
      };
      priority = lib.mkOption {
        type = lib.types.int;
        default = 50;
        description = "Registry priority (higher = preferred).";
      };
      caches = lib.mkOption {
        type = lib.types.listOf (lib.types.submodule {
          options = {
            url = lib.mkOption {
              type = lib.types.str;
              description = "Binary-cache base URL.";
            };
            priority = lib.mkOption {
              type = lib.types.int;
              default = 100;
              description = "Cache priority (higher is tried first).";
            };
          };
        });
        default = [];
        description = ''
          Client-side binary caches available before the registry's committed
          cache stack has been synchronized.
        '';
      };
      sbDbCerts = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = ''
          Secure Boot db certificate(s) in PEM form, used by `apm` to
          re-verify cataloged UKIs against this registry at download
          time (RFC-0006 phase 4). Each entry is a PEM block; they are
          concatenated into `/etc/apm/trusted-sb-certs.d/<name>.pem`.
          Leave empty to skip the download-time UKI re-verification
          step (the signed catalog's active-set and SBAT-floor checks
          still apply).
        '';
      };
    };
  };

  registryCaches = registry:
    if registry.caches == []
    then ""
    else
      "\n"
      + lib.concatMapStringsSep "\n" (cache:
        lib.removeSuffix "\n" ''
          [[registry.caches]]
          url = ${builtins.toJSON cache.url}
          priority = ${builtins.toString cache.priority}
        '')
      registry.caches;

  registryToml = name: registry: ''
    # /etc/apm/registries.d/${name}.toml
    # Generated by modules/base/apm-registries.nix - do not edit manually.
    [registry]
    name = "${name}"
    url = "${registry.url}"
    priority = ${builtins.toString registry.priority}
    enabled = true
    ${registryCaches registry}

    [registry.signing]
    required = ${
      if registry.required
      then "true"
      else "false"
    }
    public_key = "${builtins.head registry.trustKeys}"
  '';

  trustedKeys = registry:
    lib.concatMapStrings (key: key + "\n") registry.trustKeys;

  trustedSbCerts = registry:
    lib.concatMapStrings (cert: cert + "\n") registry.sbDbCerts;

  trustKeyPattern = name: "${lib.escapeRegex name}:Ed25519:[A-Za-z0-9+/]+=*";
in {
  inherit
    registryNamePattern
    registryType
    registryToml
    trustedKeys
    trustedSbCerts
    trustKeyPattern
    ;
}
