##! modules/base/_apm-registry-renderer.nix — Shared apm registry files
{
  lib,
  pkgs,
}: let
  registryNamePattern = "[A-Za-z0-9_-]+";

  toml = lib.formats.toml {inherit lib pkgs;};

  registryType = lib.types.submodule {
    options = {
      url = lib.mkOption {
        type = lib.types.str;
        description = "Registry git/HTTP URL.";
      };
      trustKeys = lib.mkOption {
        type = lib.types.nonEmptyListOf lib.types.str;
        description = ''
          Maintainer public keys in `<name>:Ed25519:<base64>` form.
          The first entry becomes the `[registry.signing]` bootstrap
          anchor; all entries are written to `trusted-keys.d`.
        '';
      };
      required = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Require signature verification on every sync.";
      };
      priority = lib.mkOption {
        type = lib.types.int;
        default = 50;
        description = "Registry priority (higher = preferred).";
      };
      tracking = lib.mkOption {
        type = lib.types.submodule {
          options = {
            mode = lib.mkOption {
              type = lib.types.enum ["default" "commit" "branch" "channel" "tag" "version"];
              default = "default";
              description = ''
                Which revision dimension the registry tracks. `default`
                follows the registry's default-branch HEAD; every other
                mode pins to `value`. The modes are mutually exclusive by
                construction — apm accepts at most one of
                `commit`/`branch`/`channel`/`tag`/`version`, and this
                single option makes that structural.
              '';
            };
            value = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = ''
                The commit hash, branch, channel, tag, or semver
                constraint to track, interpreted per `mode`. Required
                unless `mode` is `default`, in which case it is ignored.
                apm validates the ref format for the selected mode at
                load time.
              '';
            };
          };
        };
        default = {};
        description = ''
          How this registry selects a revision. Renders to the matching
          `[registry]` tracking key (`channel = "..."`, `tag = "..."`,
          and so on); `default` renders no tracking key, leaving apm to
          follow the default-branch HEAD.
        '';
      };
      maxStalenessSeconds = lib.mkOption {
        type = lib.types.nullOr lib.types.int;
        default = null;
        description = ''
          Maximum age, in seconds, of the last successful channel sync
          before a failed refresh is treated as stale. Pairs with
          channel tracking; apm defaults to 14 days when unset.
        '';
      };
      caches = lib.mkOption {
        type = lib.types.listOf (lib.types.submodule {
          options = {
            url = lib.mkOption {
              type = lib.types.str;
              description = "Binary cache base URL.";
            };
            priority = lib.mkOption {
              type = lib.types.int;
              default = 100;
              description = "Cache selection priority (higher is tried first).";
            };
          };
        });
        default = [];
        description = ''
          Client-side binary cache entries, baked as `[[registry.caches]]`.
          Merged with the registry's committed caches and sorted by
          priority at resolution time.
        '';
      };
      sbDbCerts = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = ''
          Secure Boot db certificate(s) in PEM form, used by `apm` to
          re-verify cataloged UKIs against this registry at download
          time (RFC-0006 phase 4). Each entry is a PEM block; they are
          concatenated into `/etc/apm/trusted-sb-certs.d/<name>.pem`.
          Leave empty to skip the download-time UKI re-verification
          step (the signed catalog's active-set and SBAT-floor checks
          still apply).
        '';
      };
    };
  };

  # Assemble the `[registry]` table as a Nix attrset and serialise it with
  # the pure-Nix TOML emitter, which escapes strings and renders arrays of
  # tables that hand-rolled interpolation cannot. The enum member names are
  # the TOML tracking keys, so a mode other than `default` maps straight to
  # its key with no lookup table. Optional keys are added only when set, so
  # an unset tracking mode, absent staleness, or empty cache list emit
  # nothing.
  registryToml = name: registry: let
    header = ''
      # /etc/apm/registries.d/${name}.toml
      # Generated by the AOS apm registries module - do not edit manually.
    '';
    body = toml.toTOML {
      registry =
        {
          name = name;
          url = registry.url;
          priority = registry.priority;
          enabled = true;
          signing = {
            required = registry.required;
            public_key = builtins.head registry.trustKeys;
          };
        }
        // lib.optionalAttrs (registry.tracking.mode != "default") {
          ${registry.tracking.mode} = registry.tracking.value;
        }
        // lib.optionalAttrs (registry.maxStalenessSeconds != null) {
          max_staleness_seconds = registry.maxStalenessSeconds;
        }
        // lib.optionalAttrs (registry.caches != []) {
          caches =
            builtins.map (cache: {inherit (cache) url priority;})
            registry.caches;
        };
    };
  in
    header + body;

  trustedKeys = registry:
    lib.concatMapStrings (key: key + "\n") registry.trustKeys;

  trustedSbCerts = registry:
    lib.concatMapStrings (cert: cert + "\n") registry.sbDbCerts;

  trustKeyPattern = name: "${lib.escapeRegex name}:Ed25519:[A-Za-z0-9+/]+=*";
in {
  inherit
    registryNamePattern
    registryType
    registryToml
    trustedKeys
    trustedSbCerts
    trustKeyPattern
    ;
}
