##! modules/base/boot.nix — Boot configuration module
##!
##! Configures kernel command line parameters and the systemd-based
##! initrd. The image builder composes these into a Unified Kernel
##! Image and drops it onto a 512 MiB ESP alongside sd-boot; no
##! per-generation loader entries, no syslinux/grub fallbacks.
##!
##! The UKI's .cmdline section is baked into a signed binary, so
##! changes to `aos.boot.kernelParams` require an image rebuild (not
##! just a config refresh).
{
  config,
  lib,
  ...
}: {
  options.aos.boot = {
    ## Kernel command line parameters.
    ##
    ## Other modules (SELinux, hardening, network tuning, …) append
    ## to this list. The combined string is baked into the UKI's
    ## .cmdline section at image build time.
    ##
    ## # Examples
    ## ```nix
    ## aos.boot.kernelParams = [ "console=ttyS0,115200" "selinux=1" ];
    ## ```
    kernelParams = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = ''
        Kernel command line parameters. These are baked into the
        UKI's .cmdline section at image build time. Base parameters
        (console, cgroup v2, gpt-auto disable) are set in the config
        section below; other modules append their own.
      '';
    };

    initrd = {
      ## Whether to generate a systemd-based initrd.
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Whether to generate a systemd-based initrd (initial ramdisk).";
      };

      ## Kernel modules to include in the initrd.
      modules = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [
          "virtio_blk"
          "virtio_pci"
          "virtio_net"
          "ext4"
          # isofs is required so aos-platform-detect.service can mount
          # the ISO9660 `aos-metadata` channel — used by VM tests and
          # by bare-metal operators who attach metadata via IPMI
          # virtual media.
          "isofs"
          "overlay"
          "dm-crypt"
          "qemu_fw_cfg"
        ];
        description = ''
          Kernel modules to include in the initrd. These are loaded
          early in boot before the root filesystem is mounted. The
          defaults cover virtio (QEMU/KVM block, PCI, net), ext4
          root, ISO9660 metadata channel, overlayfs for /etc,
          dm-crypt for encrypted swap, and qemu_fw_cfg for ignition's
          QEMU platform reader.
        '';
      };
    };
  };

  config = {
    assertions = [
      {
        assertion =
          !(lib.any
            (p: lib.hasPrefix "ignition.config.url=" p)
            config.aos.boot.kernelParams);
        message = ''
          aos.boot.kernelParams must not contain `ignition.config.url=…`.

          The UKI's .cmdline is baked into a signed binary; hardcoding a
          config URL there would make every boot from the image fetch
          from that URL, overriding platform detection. Provide per-
          deployment ignition configs via the `aos-metadata` ISO9660
          channel instead (see modules/services/ignition.nix).
        '';
      }
    ];

    # Base kernel command line — always present.
    aos.boot.kernelParams = [
      "console=ttyS0,115200"
      "console=tty0"
      "systemd.unified_cgroup_hierarchy=1"
      # Turn off systemd-gpt-auto-generator — it synthesises .swap /
      # .mount units at boot with `ExecStart=/usr/sbin/swapon`, a path
      # AOS's rootfs doesn't populate. AOS owns swap (cryptswap.service)
      # and root (/etc/fstab → systemd-fstab-generator) explicitly, so
      # there's nothing for the auto-generator to contribute that's
      # not already covered. Both `systemd.gpt-auto=` (hyphenated, the
      # documented form) and `systemd.gpt_auto=` (underscored) are
      # accepted by systemd's parameter parser; ship the hyphenated
      # spelling to match the upstream man page.
      "systemd.gpt-auto=0"
    ];

    # systemd-initrd kernel modules configuration.
    # Written to /etc/initrd-modules.conf for the image builder.
    environment.etc."initrd-modules.conf" = lib.mkIf config.aos.boot.initrd.enable {
      text = ''
        # Kernel modules to include in the systemd-based initrd.
        # Generated by modules/base/boot.nix
        ${builtins.concatStringsSep "\n" config.aos.boot.initrd.modules}
      '';
    };
  };
}
