# modules/base/boot.nix — Boot configuration module
#
# Configures the boot loader (systemd-boot), kernel command line parameters,
# initrd generation via dracut, and optional Unified Kernel Image (UKI) and
# Secure Boot support.
#
# Absorbed TOML config values:
#   [boot] loader, kernel_params
#   [boot.initrd] enable, modules
#   [boot.uki] enable
#   [boot.secure_boot] enable

{ config, pkgs, lib, ... }:

let
  cfg = config.aos.boot;

  # Build the complete kernel command line string from the list of parameters.
  kernelCmdline = builtins.concatStringsSep " " cfg.kernelParams;

  # Dracut modules list for initrd generation.
  dracutModules = builtins.concatStringsSep " " (builtins.map (m: ''"${m}"'') cfg.initrd.modules);
in
{
  options.aos.boot = {
    loader = lib.mkOption {
      type = lib.types.str;
      default = "systemd-boot";
      description = ''
        Boot loader to use. Currently only "systemd-boot" is supported.
        Future: "grub", "direct" (direct kernel boot for VMs).
      '';
    };

    kernelParams = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "console=ttyS0,115200"
        "console=tty0"
        "systemd.unified_cgroup_hierarchy=1"
        "selinux=1"
        "security=selinux"
      ];
      description = ''
        Kernel command line parameters. These are written to the boot loader
        entry and passed to the kernel at boot time. The default includes
        serial console output, unified cgroup v2, and SELinux enablement.
      '';
    };

    initrd = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Whether to generate an initrd (initial ramdisk) using dracut.";
      };

      modules = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [
          "virtio_blk"
          "virtio_pci"
          "ext4"
          "overlay"
        ];
        description = ''
          Kernel modules to include in the initrd. These are loaded early
          in boot before the root filesystem is mounted. The defaults cover
          virtio (QEMU/KVM), ext4 root, and overlayfs for /etc.
        '';
      };
    };

    uki = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Build a Unified Kernel Image (UKI) that combines the kernel,
          initrd, and command line into a single signed EFI binary.
          Requires Secure Boot infrastructure.
        '';
      };
    };

    secureBoot = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Enable UEFI Secure Boot support. When enabled, the boot loader
          and kernel are signed with the platform key. Requires UKI to be
          enabled for full chain-of-trust.
        '';
      };
    };
  };

  config = {
    environment.systemPackages = [ pkgs.dracut ];

    # systemd-boot loader entry for the current generation.
    # Written to /boot/loader/entries/aos.conf
    environment.etc."boot/loader/entries/aos.conf" = {
      text = ''
        title   AOS ${config.aos.system.version} (${config.aos.system.variant})
        linux   /vmlinuz
        ${lib.optionalString cfg.initrd.enable "initrd  /initramfs.img"}
        options ${kernelCmdline}
      '';
    };

    # systemd-boot loader configuration.
    # Written to /boot/loader/loader.conf
    environment.etc."boot/loader/loader.conf" = {
      text = ''
        default aos.conf
        timeout 3
        console-mode max
        editor  no
      '';
    };

    # Dracut configuration for initrd generation.
    # Written to /etc/dracut.conf.d/aos.conf
    environment.etc."dracut.conf.d/aos.conf" = lib.mkIf cfg.initrd.enable {
      text = ''
        # AOS initrd configuration — generated by modules/base/boot.nix
        # Do not edit manually.

        # Force-include these kernel modules in the initrd.
        add_drivers+=" ${builtins.concatStringsSep " " cfg.initrd.modules} "

        # Use systemd in the initrd for service-based boot ordering.
        add_dracutmodules+=" systemd systemd-initrd "

        # Compress the initrd with zstd for fast decompression.
        compress="zstd"

        # Do not include the full kernel module tree — only what we specify.
        hostonly="yes"
        hostonly_cmdline="no"
      '';
    };

    # UKI build configuration — tells systemd-ukify how to combine
    # kernel + initrd + cmdline into a single PE binary.
    environment.etc."kernel/uki.conf" = lib.mkIf cfg.uki.enable {
      text = ''
        # UKI configuration — generated by modules/base/boot.nix
        [UKI]
        Linux=/boot/vmlinuz
        Initrd=/boot/initramfs.img
        Cmdline=${kernelCmdline}
        OSRelease=@/etc/os-release
        ${lib.optionalString cfg.secureBoot.enable "SecureBootSigningTool=/usr/bin/sbsign"}
      '';
    };
  };
}
