##! modules/base/filesystems.nix — Immutable filesystem layout module
##!
##! Defines the AOS filesystem hierarchy: read-only root (ext4 or EROFS),
##! FAT32 ESP, overlay /etc, encrypted swap, and tmpfs for /tmp and /run.
##! This is the core of the immutable OS design — the root filesystem is
##! mounted read-only and all mutable state lives elsewhere.
##!
##! This module owns the pool's existence: whether the host uses ZFS, which
##! pool carries its state, and importing that pool at boot. The datasets in
##! it and the memory ZFS may hold are owned by modules/base/zfs-datasets.nix
##! and modules/base/zfs-memory.nix.
##!
##! Absorbed TOML config values:
##!   [filesystems] root_read_only, root_device, root_fstype, esp_device
##!   [filesystems.zfs] enable, pool_name
##!   [filesystems.overlay] etc_overlay
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.filesystems;

  # OpenZFS is an out-of-tree module, so its build is bound to one exact
  # kernel. `aos.boot.storage` overrides this when the immutable image slots
  # live on zvols and the same build has to be in the initrd.
  zfsForRunningKernel = pkgs.zfsForKernel config.system.build.kernel;

  # Build fstab entries from the filesystem configuration.
  #
  # The overlay on /etc is NOT listed here: the initrd service
  # `etc-overlay-setup.service` (in modules/services/boot-substrate.nix)
  # mounts it before `initrd-switch-root`, and the kernel inherits
  # that mount into stage 2. Adding it to fstab would re-trigger the
  # mount in stage 2 after switch_root, which overlayfs handles poorly
  # while the mount is already live.
  fstabEntries = builtins.concatStringsSep "\n" [
    "# /etc/fstab — generated by modules/base/filesystems.nix"
    "# Do not edit manually."
    ""
    "# Root filesystem (${
      if cfg.rootReadOnly
      then "read-only"
      else "read-write"
    })"
    # passno 0 for erofs: it is a read-only, build-time-verified image that
    # needs no boot-time fsck (and `fsck.ext4` would choke on it). ext4 keeps
    # passno 1.
    "${cfg.rootDevice}  /  ${cfg.rootFsType}  ${
      if cfg.rootReadOnly
      then "ro"
      else "rw"
    },relatime  0  ${
      if cfg.rootFsType == "erofs"
      then "0"
      else "1"
    }"
    ""
    "# EFI System Partition — FAT32 so UEFI firmware can read it."
    "${cfg.espDevice}  /boot  vfat  noauto,nofail,ro,noatime,fmask=0077,dmask=0077  0  0"
    ""
    (
      if cfg.zfs.enable && cfg.zfs.systemState
      then ''
        # /var is a declared ZFS dataset; modules/base/zfs-datasets.nix
        # generates the systemd mount unit that mounts it.
      ''
      else ''
        # /var — persistent mutable state (partition created by systemd-repart)
        /dev/disk/by-partlabel/var  /var  ext4  rw,relatime,nosuid,nodev  0  2
      ''
    )
    ""
    "# tmpfs mounts"
    "tmpfs  /tmp  tmpfs  nosuid,nodev,noexec,mode=1777,size=50%  0  0"
    "tmpfs  /run  tmpfs  nosuid,nodev,noexec,mode=755,size=25%  0  0"
  ];
in {
  options.aos.filesystems = {
    ## Mount the root filesystem read-only (immutable OS foundation).
    ##
    ## # See Also
    ## - `aos.filesystems.zfs.enable`
    rootReadOnly = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Mount the root filesystem read-only. This is the foundation of the
        immutable OS design. All mutable state must live on separate mounts
        (/var via ZFS, /etc via overlay, /tmp and /run via tmpfs).
      '';
    };

    ## Block device for the root filesystem.
    ##
    ## Defaults to the GPT partlabel of the root-A slot — the same device the
    ## baked UKI `root=` points at (`modules/base/boot.nix`), so fstab and the
    ## kernel command line agree. `modules/security/verity.nix` overrides this
    ## to `/dev/mapper/root` so both `root=` and the fstab `/` entry follow the
    ## dm-verity-assembled mapper device (F1) without mkForce list surgery.
    rootDevice = lib.mkOption {
      type = lib.types.str;
      default = "/dev/disk/by-partlabel/root-a";
      description = "Block device for the root filesystem.";
    };

    ## Filesystem type for the root partition.
    rootFsType = lib.mkOption {
      type = lib.types.str;
      default = "ext4";
      description = "Filesystem type for the root partition.";
    };

    ## Block device for the EFI System Partition.
    espDevice = lib.mkOption {
      type = lib.types.str;
      default = "/dev/disk/by-partlabel/ESP";
      description = "Stable block-device path for the EFI System Partition.";
    };

    zfs = {
      ## Use ZFS for persistent mutable state under /var.
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Use ZFS for persistent mutable state under /var, providing
          snapshots, compression, checksumming, and per-dataset quotas. When
          disabled, `/var` is an ext4 partition that systemd-repart creates at
          first boot.

          Enabling this also enables the bounded memory policy in
          `modules/base/zfs-memory.nix`, which is what keeps OpenZFS's
          RAM-scaled defaults from growing without regard to pool size.
        '';
      };

      ## Place the system's mutable state (/var) on the pool.
      systemState = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Put `/var` and its children on the pool. When false the pool carries
          only the datasets a configuration declares explicitly, and `/var`
          stays on the partition the image provides. That suits a host with a
          pool for bulk data whose system state should keep the image's own
          provisioning and recovery path.
        '';
      };

      ## Name of the ZFS pool for persistent data.
      poolName = lib.mkOption {
        type = lib.types.strMatching "[A-Za-z][A-Za-z0-9_.:-]*";
        default = "rpool";
        description = ''
          Name of the ZFS pool holding persistent data. Matches the default of
          `aos.boot.storage.zfs.poolName`, which sets this option when the
          immutable image slots live on zvols in the same pool.
        '';
      };

      package = lib.mkOption {
        type = lib.types.package;
        default = pkgs.zfs;
        internal = true;
        description = ''
          OpenZFS userland and kernel module. Defaults to the userland-only
          build so systems with ZFS disabled never build the module; the
          configuration below binds it to the running kernel whenever ZFS is
          actually enabled.
        '';
      };
    };

    # `aos.filesystems.overlayEtc` was removed in spec v12: the
    # composefs-backed /etc overlay is now unconditional. See
    # `modules/services/boot-substrate.nix:etc-overlay-setup.service` for the
    # three-layer mount (system EROFS lower + per-gen config lower +
    # /var/etc + tmpfs upper).
  };

  config = {
    system.checks.filesystem = {
      description = "Filesystem layout checks";
      checks = [
        {
          name = "tmp-tmpfs";
          description = "/tmp is tmpfs";
          script = ''
            assert "/tmp tmpfs" in vm.succeed("cat /proc/mounts")
          '';
        }
        {
          name = "run-tmpfs";
          description = "/run is tmpfs";
          script = ''
            assert "/run tmpfs" in vm.succeed("cat /proc/mounts")
          '';
        }
        {
          name = "nix-store-exists";
          description = "/nix/store directory exists";
          script = ''
            vm.succeed("test -d /nix/store")
          '';
        }
        {
          name = "nix-store-populated";
          description = "/nix/store is populated";
          script = ''
            vm.succeed("ls /nix/store/ | head -1")
          '';
        }
        {
          name = "var-writable";
          description = "/var is writable";
          script = ''
            vm.succeed("touch /var/test-write && rm /var/test-write")
          '';
        }
        {
          name = "etc-os-release";
          description = "/etc/os-release exists";
          script = ''
            vm.succeed("test -f /etc/os-release")
          '';
        }
        {
          name = "etc-passwd";
          description = "/etc/passwd exists";
          script = ''
            vm.succeed("test -f /etc/passwd")
          '';
        }
      ];
    };

    # /etc/fstab — filesystem table read by mount(8) and systemd generators.
    environment.etc."fstab" = {
      text = fstabEntries + "\n";
    };

    # tmpfiles rules to create standard volatile directories.
    # etc-overlay-setup.service creates `/run/etc/upper-<gen>/{dir,work}`
    # at boot time directly (spec v12 §6.1.4).
    environment.etc."tmpfiles.d/aos-filesystems.conf" = {
      text = ''
        # tmpfiles.d rules — generated by modules/base/filesystems.nix
        d /run 0755 root root -
      '';
    };

    # A host whose state lives on ZFS needs the module loadable in stage 2 and
    # the userland present in recovery. Recovery without pool access cannot
    # repair the one thing it exists to repair.
    aos.filesystems.zfs.package = lib.mkIf cfg.zfs.enable (lib.mkDefault zfsForRunningKernel);
    aos.kernel.modulePackages = lib.mkIf cfg.zfs.enable [cfg.zfs.package];
    aos.kernel.modules = lib.mkIf cfg.zfs.enable ["zfs"];
    aos.boot.recovery.extraPackages = lib.mkIf cfg.zfs.enable [cfg.zfs.package];

    systemd.services = lib.mkMerge [
      # Pool import. Declared datasets are created and mounted by
      # modules/base/zfs-datasets.nix, which orders itself after this.
      (lib.mkIf cfg.zfs.enable {
        "zfs-import" = {
          description = "Import ZFS pool ${cfg.zfs.poolName}";
          wantedBy = ["local-fs.target"];
          before = ["local-fs.target"];
          # Importing a pool needs /dev/zfs, which appears only once the
          # module is inserted. Without this the import can run first and
          # fail on a host that is otherwise configured correctly.
          after = ["systemd-udev-settle.service" "systemd-modules-load.service"];
          wants = ["systemd-modules-load.service"];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStart = "${pkgs.bash}/bin/bash -c '${cfg.zfs.package}/sbin/zpool list -H ${cfg.zfs.poolName} >/dev/null 2>&1 || ${cfg.zfs.package}/sbin/zpool import -N -f ${cfg.zfs.poolName}'";
            ExecStop = "${cfg.zfs.package}/sbin/zpool export ${cfg.zfs.poolName}";
          };
        };
      })

      # Encrypted swap — plain dm-crypt keyed from /dev/urandom. The key
      # is discarded on reboot so swap contents are not recoverable.
      # The swap partition itself is created by systemd-repart on first boot.
      {
        "cryptswap" = {
          description = "Set Up Encrypted Swap";
          wantedBy = ["swap.target"];
          before = ["swap.target"];
          requires = ["dev-disk-by\\x2dpartlabel-swap.device"];
          after = [
            "local-fs.target"
            "dev-disk-by\\x2dpartlabel-swap.device"
          ];
          unitConfig = {
            # The partition only exists after systemd-repart's first-boot run.
            # ConditionPathExists makes the first pre-repart boot a
            # no-op instead of a fatal service failure.
            ConditionPathExists = "/dev/disk/by-partlabel/swap";
            DefaultDependencies = "no";
          };
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
          };
          script = ''
            set -euo pipefail
            swap_dev=/dev/disk/by-partlabel/swap
            dm_name=cryptswap

            if [ -e /dev/mapper/$dm_name ]; then
              exit 0
            fi

            ${pkgs.cryptsetup}/sbin/cryptsetup open --type=plain \
              --cipher=aes-xts-plain64 \
              --key-size=256 \
              --key-file=/dev/urandom \
              "$swap_dev" "$dm_name"

            ${pkgs.util-linux}/sbin/mkswap /dev/mapper/$dm_name
            ${pkgs.util-linux}/sbin/swapon /dev/mapper/$dm_name
          '';
          preStop = ''
            set -eu
            if ${pkgs.util-linux}/sbin/swapon --show=NAME --noheadings \
                | grep -qx /dev/mapper/cryptswap; then
              ${pkgs.util-linux}/sbin/swapoff /dev/mapper/cryptswap
            fi
            if [ -e /dev/mapper/cryptswap ]; then
              ${pkgs.cryptsetup}/sbin/cryptsetup close cryptswap
            fi
          '';
        };
      }
    ];
  };
}
