##! modules/base/journald.nix — Journald configuration module
##!
##! Configures systemd-journald logging behavior: storage backend (persistent
##! to disk vs volatile in memory), retention policy, size limits, and rate
##! limiting. Generates /etc/systemd/journald.conf with a [Journal] section
##! containing all configured options.
##!
##! Persistent storage (the default) writes journal files to /var/log/journal,
##! which survives reboots. Volatile storage uses tmpfs at /run/log/journal and
##! is lost on reboot but avoids disk I/O.
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.journald;
in {
  options.aos.journald = {
    ## Journal storage mode (persistent, volatile, auto).
    storage = lib.mkOption {
      type = lib.types.enum [
        "persistent"
        "volatile"
        "auto"
      ];
      default = "persistent";
      description = ''
        Journal storage mode:
        - persistent: write to /var/log/journal (survives reboot)
        - volatile: write to /run/log/journal (lost on reboot)
        - auto: use persistent if /var/log/journal exists, else volatile
      '';
    };

    ## Maximum time to keep journal entries.
    maxRetentionSec = lib.mkOption {
      type = lib.types.str;
      default = "1month";
      description = ''
        Maximum time to keep journal entries. Entries older than this are
        removed during journal rotation. Accepts systemd time span syntax
        (e.g. "1month", "2weeks", "7d").
      '';
    };

    ## Maximum disk space the journal may use.
    maxUse = lib.mkOption {
      type = lib.types.str;
      default = "500M";
      description = ''
        Maximum disk space the journal may use. When this limit is reached,
        the oldest entries are pruned. Accepts size suffixes (K, M, G).
      '';
    };

    ## Maximum size of individual journal files.
    systemMaxFileSize = lib.mkOption {
      type = lib.types.str;
      default = "50M";
      description = ''
        Maximum size of individual journal files. When a file reaches this
        size, journald rotates to a new file. Accepts size suffixes (K, M, G).
      '';
    };

    ## Time interval for rate limiting.
    rateLimitInterval = lib.mkOption {
      type = lib.types.str;
      default = "30s";
      description = ''
        Time interval for rate limiting. If more than rateLimitBurst messages
        are received from a service within this interval, further messages
        are dropped until the interval resets.
      '';
    };

    ## Maximum messages per service within rateLimitInterval.
    rateLimitBurst = lib.mkOption {
      type = lib.types.int;
      default = 10000;
      description = ''
        Maximum number of messages a service may log within rateLimitInterval
        before rate limiting kicks in. The default of 10000 is generous enough
        for most server workloads while still protecting against log floods.
      '';
    };

    ## Forward journal messages to a traditional syslog daemon.
    forwardToSyslog = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Forward journal messages to a traditional syslog daemon. Disabled by
        default because AOS uses journald as the sole logging system. Enable
        this if a syslog-based log aggregator is in use.
      '';
    };
  };

  config = {
    # /etc/systemd/journald.conf — systemd-journald configuration.
    # Applied when systemd-journald.service starts or receives SIGUSR2.
    environment.etc."systemd/journald.conf" = {
      text = ''
        # /etc/systemd/journald.conf
        # Generated by modules/base/journald.nix — do not edit manually.

        [Journal]
        Storage=${cfg.storage}
        MaxRetentionSec=${cfg.maxRetentionSec}
        SystemMaxUse=${cfg.maxUse}
        SystemMaxFileSize=${cfg.systemMaxFileSize}
        RateLimitIntervalSec=${cfg.rateLimitInterval}
        RateLimitBurst=${toString cfg.rateLimitBurst}
        ForwardToSyslog=${
          if cfg.forwardToSyslog
          then "yes"
          else "no"
        }
        Compress=yes
      '';
    };

    # Ensure the persistent journal directory exists when using persistent storage.
    environment.etc."tmpfiles.d/aos-journald.conf" = {
      text = ''
        # Journald state directories — generated by modules/base/journald.nix
        d /var/log/journal 2755 root systemd-journal -
      '';
    };
  };
}
