##! modules/base/kdump.nix — Kernel crash dump module
##!
##! Configures kdump for capturing kernel crash dumps. When the kernel panics,
##! kexec boots a secondary "crash kernel" that has been pre-loaded into a
##! reserved memory region. The crash kernel writes the contents of the
##! panicked kernel's memory to the target directory for later analysis.
##!
##! The crashkernel= boot parameter reserves memory for the crash kernel.
##! The kdump service pre-loads the crash kernel image so it is ready to
##! execute immediately on panic without requiring disk I/O from the
##! panicked system.
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.kdump;
in {
  options.aos.kdump = {
    ## Enable kdump kernel crash dump capture.
    ##
    ## # Examples
    ## ```nix
    ## aos.kdump.enable = true;
    ## ```
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable kdump kernel crash dump capture. When the kernel panics,
        kexec boots a crash kernel from reserved memory that writes the
        crashed kernel's memory to disk. Requires the crashkernel= boot
        parameter and a kexec-capable kernel.
      '';
    };

    ## Memory to reserve for the crash kernel.
    crashKernelSize = lib.mkOption {
      type = lib.types.str;
      default = "256M";
      description = ''
        Amount of memory to reserve for the crash kernel. This memory is
        unavailable to the running system. 256M is sufficient for most
        server configurations; systems with many devices or large IOMMU
        tables may need more.
      '';
    };

    ## Directory where crash dumps are written.
    target = lib.mkOption {
      type = lib.types.str;
      default = "/var/crash";
      description = ''
        Directory where crash dumps are written. Must be on a filesystem
        that is accessible from the crash kernel (typically a simple
        block device mount, not ZFS or network storage).
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Add crashkernel= parameter to the boot command line to reserve
    # memory for the crash kernel.
    aos.boot.kernelParams = [
      "crashkernel=${cfg.crashKernelSize}"
    ];

    # kdump.service — pre-loads the crash kernel into reserved memory.
    # The crash kernel is ready to execute immediately on panic without
    # requiring any disk I/O from the panicked system.
    systemd.services."kdump" = {
      description = "Load kdump crash kernel";
      wantedBy = ["multi-user.target"];
      after = ["local-fs.target"];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.kexec-tools}/sbin/kexec -p /boot/vmlinuz --initrd=/boot/initramfs-kdump.img --append=\"root=${config.aos.filesystems.rootDevice} irqpoll nr_cpus=1 reset_devices panic=10 systemd.unit=kdump-save.target\"";
        ExecStop = "${pkgs.kexec-tools}/sbin/kexec -p -u";
      };
    };

    # kdump-save.service — runs inside the crash kernel to write the dump.
    # This service is activated by kdump-save.target (set via the crash
    # kernel's command line) and copies /proc/vmcore to the target directory.
    systemd.services."kdump-save" = {
      description = "Save kernel crash dump";
      after = ["local-fs.target"];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${pkgs.makedumpfile}/bin/makedumpfile -l --message-level 1 -d 31 /proc/vmcore ${cfg.target}/vmcore-$(date +%Y%m%d-%H%M%S)";
        ExecStartPost = "${pkgs.systemd}/bin/systemctl reboot";
        StandardOutput = "journal+console";
      };
    };

    # Ensure the crash dump target directory exists.
    environment.etc."tmpfiles.d/aos-kdump.conf" = {
      text = ''
        # kdump target directory — generated by modules/base/kdump.nix
        d ${cfg.target} 0700 root root -
      '';
    };

    # kdump configuration file for reference and tooling.
    environment.etc."kdump.conf" = {
      text = ''
        # /etc/kdump.conf
        # Generated by modules/base/kdump.nix — do not edit manually.

        path ${cfg.target}
        core_collector makedumpfile -l --message-level 1 -d 31
        default reboot
      '';
    };
  };
}
