##! modules/base/kernel.nix — Kernel configuration module
##!
##! Configures kernel tunables via sysctl, kernel module loading, and optional
##! TCP BBR congestion control. Generates /etc/sysctl.d/10-aos-kernel.conf for
##! performance-oriented sysctl settings and /etc/modules-load.d/aos-kernel.conf
##! for modules to load at boot. When BBR is enabled, the necessary kernel
##! parameters are appended to the boot command line.
##!
##! These are performance/functionality sysctls — security-focused sysctls
##! belong in modules/security/hardening.nix.
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.kernel;

  # Format sysctl settings as a sysctl.d(5) drop-in file.
  sysctlText = builtins.concatStringsSep "\n" (
    lib.mapAttrsToList (key: value: "${key} = ${value}") cfg.sysctl
  );
in {
  options.aos.kernel = {
    ## Enable TCP BBR congestion control.
    bbr = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Enable TCP BBR congestion control. BBR achieves higher throughput and
        lower latency than CUBIC on lossy or high-BDP paths. When enabled,
        the tcp_bbr module is loaded and the default congestion control
        algorithm and queue discipline are set via kernel boot parameters.
      '';
    };

    ## Enable the kernel hardware watchdog.
    watchdog = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Enable the kernel hardware watchdog. When enabled, the kernel
        configures the watchdog timer to reset the machine if the system
        hangs. Useful for unattended servers where a stuck kernel should
        trigger a reboot rather than hang indefinitely.
      '';
    };

    ## Performance-oriented sysctl parameters.
    ##
    ## # See Also
    ## - `aos.security.hardening.sysctl` (security sysctls)
    sysctl = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        # -- Network performance --
        "net.core.somaxconn" = "32768";
        "net.core.netdev_max_backlog" = "16384";

        # -- Virtual memory --
        "vm.swappiness" = "10";

        # -- Filesystem watches (IDEs, file sync, container runtimes) --
        "fs.inotify.max_user_instances" = "8192";
        "fs.inotify.max_user_watches" = "524288";

        # -- Process limits --
        "kernel.pid_max" = "4194304";
      };
      description = ''
        Kernel sysctl parameters for system performance tuning. Written to
        /etc/sysctl.d/10-aos-kernel.conf and applied at boot by
        systemd-sysctl.service. These are functional/performance settings;
        security hardening sysctls are in modules/security/hardening.nix.
      '';
    };

    ## Kernel modules to load at boot.
    modules = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = ''
        Kernel modules to load at boot. Written to
        /etc/modules-load.d/aos-kernel.conf and loaded by
        systemd-modules-load.service. Example: ["br_netfilter" "overlay"].
      '';
    };
  };

  config = {
    # /etc/sysctl.d/10-aos-kernel.conf — performance sysctl settings.
    # Priority 10 so security settings in 80-aos-hardening.conf take precedence.
    environment.etc."sysctl.d/10-aos-kernel.conf" = {
      text = ''
        # /etc/sysctl.d/10-aos-kernel.conf
        # Generated by modules/base/kernel.nix — do not edit manually.
        # Performance and functionality kernel tunables.

        ${sysctlText}
      '';
    };

    # /etc/modules-load.d/aos-kernel.conf — modules to load at boot.
    environment.etc."modules-load.d/aos-kernel.conf" = {
      text = ''
        # /etc/modules-load.d/aos-kernel.conf
        # Generated by modules/base/kernel.nix — do not edit manually.

        ${lib.optionalString cfg.bbr "tcp_bbr"}
        ${lib.concatStringsSep "\n" cfg.modules}
      '';
    };

    # When BBR is enabled, add kernel parameters to set the default congestion
    # control algorithm and queue discipline.
    aos.boot.kernelParams = lib.mkIf cfg.bbr [
      "net.core.default_qdisc=fq"
      "net.ipv4.tcp_congestion_control=bbr"
    ];

    # Watchdog kernel parameter — enables hardware watchdog if available.
    environment.etc."sysctl.d/11-aos-watchdog.conf" = lib.mkIf cfg.watchdog {
      text = ''
        # Hardware watchdog — generated by modules/base/kernel.nix
        kernel.nmi_watchdog = 1
        kernel.watchdog_thresh = 10
      '';
    };
  };
}
