# modules/base/networking.nix — Network configuration module
#
# Configures networking via systemd-networkd and systemd-resolved.
# Generates .network files for each interface, resolved.conf for DNS,
# and manages the hostname.
#
# Absorbed TOML config values:
#   [network] hostname, use_dhcp, nameservers, search_domains
#   [network.interfaces.*] address, gateway, dns
#   [network.resolved] enable, dnssec

{ config, pkgs, lib, ... }:

let
  cfg = config.aos.networking;

  # Generate a systemd-networkd .network file for a named interface.
  mkNetworkUnit = name: ifCfg:
    let
      hasStaticAddr = ifCfg ? address && ifCfg.address != "";
    in
    ''
      # /etc/systemd/network/10-${name}.network
      # Generated by modules/base/networking.nix

      [Match]
      Name=${name}

      [Network]
      ${if hasStaticAddr then ''
      Address=${ifCfg.address}
      ${lib.optionalString (ifCfg ? gateway && ifCfg.gateway != "") "Gateway=${ifCfg.gateway}"}
      ${lib.optionalString (ifCfg ? dns && ifCfg.dns != "") "DNS=${ifCfg.dns}"}
      '' else ''
      DHCP=yes
      ''}
    '';

  # Build the default DHCP network unit if no interfaces are specified.
  defaultNetworkUnit = ''
    # /etc/systemd/network/80-dhcp.network
    # Generated by modules/base/networking.nix
    # Default: DHCP on all Ethernet interfaces.

    [Match]
    Name=en*
    Type=ether

    [Network]
    DHCP=yes

    [DHCPv4]
    UseDNS=yes
    UseNTP=yes
    UseDomains=yes
  '';

  # Build resolved.conf from DNS settings.
  resolvedConf = ''
    # /etc/systemd/resolved.conf
    # Generated by modules/base/networking.nix

    [Resolve]
    ${lib.optionalString (cfg.nameservers != []) "DNS=${builtins.concatStringsSep " " cfg.nameservers}"}
    ${lib.optionalString (cfg.search != []) "Domains=${builtins.concatStringsSep " " cfg.search}"}
    DNSSEC=${cfg.resolved.dnssec}
    DNSOverTLS=opportunistic
    MulticastDNS=no
    LLMNR=no
  '';

in
{
  options.aos.networking = {
    hostName = lib.mkOption {
      type = lib.types.str;
      default = "aos";
      description = "System hostname. Written to /etc/hostname and set via hostnamectl.";
    };

    useDHCP = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Use DHCP for all Ethernet interfaces by default. When true and no
        static interfaces are defined, a catch-all .network file is generated
        that enables DHCP on all en* interfaces.
      '';
    };

    interfaces = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          address = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "Static IPv4/IPv6 address in CIDR notation (e.g. 10.0.0.5/24).";
          };
          gateway = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "Default gateway for this interface.";
          };
          dns = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "DNS server for this interface.";
          };
        };
      });
      default = {};
      description = ''
        Per-interface network configuration. Each key is the interface name
        (e.g. "eth0", "ens3"). If address is set, static configuration is
        used; otherwise DHCP is used for that interface.
      '';
    };

    nameservers = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "Global DNS servers for systemd-resolved.";
    };

    search = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [];
      description = "DNS search domains.";
    };

    resolved = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Enable systemd-resolved for DNS resolution.";
      };

      dnssec = lib.mkOption {
        type = lib.types.str;
        default = "allow-downgrade";
        description = ''
          DNSSEC validation mode. Valid values: "yes", "no",
          "allow-downgrade". The default allows DNSSEC when available
          but does not fail if the upstream does not support it.
        '';
      };
    };
  };

  config = {
    # Per-interface network files.
    environment.etc = let
      interfaceFiles = lib.mapAttrs' (name: ifCfg:
        lib.nameValuePair "systemd/network/10-${name}.network" {
          text = mkNetworkUnit name ifCfg;
        }
      ) cfg.interfaces;

      # Default DHCP unit when no interfaces are explicitly configured.
      defaultFile = lib.optionalAttrs (cfg.useDHCP && cfg.interfaces == {}) {
        "systemd/network/80-dhcp.network" = {
          text = defaultNetworkUnit;
        };
      };

      # resolved configuration.
      resolvedFile = lib.optionalAttrs cfg.resolved.enable {
        "systemd/resolved.conf" = {
          text = resolvedConf;
        };
      };
    in
      interfaceFiles // defaultFile // resolvedFile;

    # Enable systemd-networkd for network management.
    systemd.services."systemd-networkd" = {
      description = "Network Configuration";
      wantedBy = [ "multi-user.target" ];
      after = [ "systemd-udevd.service" ];
      serviceConfig = {
        Type = "notify";
        Restart = "on-failure";
        RestartSec = "5s";
      };
    };

    # Enable systemd-resolved for DNS.
    systemd.services."systemd-resolved" = lib.mkIf cfg.resolved.enable {
      description = "Network Name Resolution";
      wantedBy = [ "multi-user.target" ];
      after = [ "systemd-networkd.service" ];
      serviceConfig = {
        Type = "notify";
        Restart = "on-failure";
        RestartSec = "5s";
      };
    };
  };
}
