##! modules/base/networking.nix — Network configuration module
##!
##! Declares provider-neutral link, resolver, and hostname policy.
##!
##! Absorbed TOML config values:
##!   [network] hostname, use_dhcp, nameservers, search_domains
##!   [network.interfaces.*] address, gateway, dns
##!   [network.resolved] enable, dnssec
{
  config,
  lib,
  packageModulesAvailable ? false,
  ...
}: let
  cfg = config.aos.networking;
in {
  imports = lib.optionals (!packageModulesAvailable) [../../pkgs/system/_aos-host-policy/networking.nix];

  config = {
    system.checks.networking-base = {
      description = "Base networking checks";
      checks =
        [
          {
            name = "loopback-exists";
            description = "Loopback interface exists";
            script = ''
              vm.succeed("test -d /sys/class/net/lo")
            '';
          }
          {
            name = "loopback-up";
            description = "Loopback interface is up";
            script = ''
              assert "unknown" in vm.succeed("cat /sys/class/net/lo/operstate")
            '';
          }
          {
            name = "proc-net";
            description = "/proc/net is available";
            script = ''
              vm.succeed("test -d /proc/net")
            '';
          }
          {
            name = "hostname-file";
            description = "Configured hostname is active";
            script = ''
              vm.succeed("test -f /etc/hostname")
              vm.succeed("test \"$(cat /etc/hostname)\" = \"$(cat /proc/sys/kernel/hostname)\"")
            '';
          }
        ]
        ++ lib.optionals cfg.resolved.enable [
          {
            name = "resolver-configuration";
            description = "libc resolver configuration is populated";
            script = ''
              vm.succeed("test -s /etc/resolv.conf")
            '';
          }
        ];
    };

    # Minimal /etc/protocols so getprotobyname() works. Network configuration
    # itself is rendered only by the selected package-owned provider above.
    environment.etc.protocols.text = ''
      # /etc/protocols — minimal, generated by modules/base/networking.nix
      ip          0       IP       # internet protocol, pseudo protocol number
      icmp        1       ICMP     # internet control message protocol
      igmp        2       IGMP     # Internet Group Management
      ggp         3       GGP      # gateway-gateway protocol
      ipencap     4       IP-ENCAP # IP encapsulated in IP
      tcp         6       TCP      # transmission control protocol
      egp         8       EGP      # exterior gateway protocol
      udp         17      UDP      # user datagram protocol
      ipv6        41      IPv6     # Internet Protocol, version 6
      ipv6-route  43      IPv6-Route
      ipv6-frag   44      IPv6-Frag
      rsvp        46      RSVP     # Reservation Protocol
      gre         47      GRE      # Generic Routing Encapsulation
      esp         50      ESP      # Encap Security Payload
      ah          51      AH       # Authentication Header
      ipv6-icmp   58      IPv6-ICMP # ICMP for IPv6
      ipv6-nonxt  59      IPv6-NoNxt
      ipv6-opts   60      IPv6-Opts
      eigrp       88      EIGRP    # Cisco EIGRP
      ospf        89      OSPFIGP  # Open Shortest Path First
      pim         103     PIM      # Protocol Independent Multicast
      sctp        132     SCTP     # Stream Control Transmission Protocol
      udplite     136     UDPLite  # UDP-Lite
    '';
  };
}
