##! modules/base/nix-db.nix — Seed the single-user Nix database
##!
##! The image ships its store closure in /nix.lower/store and the initrd mounts
##! it at /nix/store via overlayfs. The native store-database ability registers
##! that closure in Nix's local DB and exposes AOS profile generations as Nix
##! GC roots.
{
  lib,
  pkgs,
  ...
}: let
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  serviceTypes = serviceManagement.types;
  resultOf = lib.abilities.resultOf;
  consumerInstance = "system:nix-db";
  command = arguments: {
    executable = {
      artifact = lib.abilities.packageOutput {package = "bash";};
      entry_point = "bin/bash";
      inherit arguments;
    };
    ignore_failure = false;
  };
  databaseRequest = {
    requirementTemplates."system:nix-store-database" =
      lib.abilities.interfaceSelector {
        name = "aos.nix.store-database";
        abi = 1;
      }
      // {
        description = "Converge the booted image's local Nix store database.";
        methods = ["converge" "observe"];
        guarantees = [];
        strength = "required";
        fallback = null;
      };
    requests."system:nix-store-database" = {
      requirement = "system:nix-store-database";
      consumer = consumerInstance;
      scope = ["database"];
      parameters = {
        scope = "local";
        registration = {
          path = "/aos-registration";
          required = false;
        };
        prerequisites = [];
      };
    };
  };
  filesystemReadiness = serviceManagement.forProducer {
    inherit consumerInstance;
    key = "filesystem-readiness";
    interface = serviceManagement.interfaces.filesystemReadiness;
    parameters.scope = "local-filesystems";
  };
  gcRootBridge = serviceManagement.forService {
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "aos-nix-db";
      enabled = true;
      lifecycle = {
        description = "Expose durable AOS profiles as Nix garbage-collection roots";
        execution_model = "oneshot";
        environment_files = [];
        condition = [];
        pre_start = [];
        start = [
          (command [
            "-euo"
            "pipefail"
            "-c"
            ''
              mkdir -p /var/lib/profiles /nix/var/nix/gcroots
              if [ -L /nix/var/nix/gcroots/aos-profiles ]; then
                rm -f /nix/var/nix/gcroots/aos-profiles
              fi
              mkdir -p /nix/var/nix/gcroots/aos-profiles
              if ! mountpoint -q /nix/var/nix/gcroots/aos-profiles; then
                mount --bind /var/lib/profiles /nix/var/nix/gcroots/aos-profiles
              fi
            ''
          ])
        ];
        post_start = [];
        stop = [];
        post_stop = [];
        restart = "never";
        restart_delay_millis = 0;
        configuration_change_action = "restart";
        remain_after_exit = true;
        start_timeout_millis = 90000;
        stop_timeout_millis = 90000;
      };
      dependencies = {
        after = [
          (resultOf "filesystem-readiness" "readiness-resource")
          (resultOf "nix-store-database" "readiness-resource")
        ];
        before = [];
        requires = [
          (resultOf "filesystem-readiness" "readiness-resource")
          (resultOf "nix-store-database" "readiness-resource")
        ];
        wants = [];
      };
      environment = {
        variables = {};
        search_path =
          builtins.map
          (package: lib.abilities.packageOutput {inherit package;})
          ["coreutils" "util-linux"];
      };
    };
  };
  abilityFragments = [databaseRequest filesystemReadiness gcRootBridge];
in {
  config = lib.mkMerge [
    {
      environment.etc."nix/nix.conf" = {
        text = ''
          # Generated by modules/base/nix-db.nix — do not edit manually.
          build-users-group =
        '';
      };

      aos.abilities.instances.${consumerInstance} = {};

      system.checks.nix-db = {
        description = "Nix store database seed and GC-root bridge";
        checks = [
          {
            name = "service-active";
            description = "the provider-owned aos-nix-db service completed during boot";
            script = ''
              vm.succeed("systemctl is-active aos-nix-db.service")
            '';
          }
          {
            name = "database-created";
            description = "single-user Nix database exists on the writable overlay";
            script = ''
              vm.succeed("${pkgs.coreutils}/bin/test -f /nix/var/nix/db/db.sqlite")
            '';
          }
          {
            name = "single-user-config";
            description = "Nix is configured without a multi-user build group";
            script = ''
              assert "build-users-group =" in vm.succeed("cat /etc/nix/nix.conf")
            '';
          }
          {
            name = "gcroot-bridge";
            description = "AOS profile tree is visible under Nix GC roots";
            script = ''
              vm.succeed(
                  "${pkgs.util-linux}/bin/mountpoint -q "
                  "/nix/var/nix/gcroots/aos-profiles"
              )
              vm.succeed(
                  "${pkgs.coreutils}/bin/test "
                  "$(${pkgs.coreutils}/bin/stat -c %d:%i /var/lib/profiles) = "
                  "$(${pkgs.coreutils}/bin/stat -c %d:%i "
                  "/nix/var/nix/gcroots/aos-profiles)"
              )
            '';
          }
          {
            name = "current-system-valid";
            description = "the booted system toplevel is registered valid";
            script = ''
              vm.succeed(
                  "${pkgs.nix}/bin/nix-store --check-validity "
                  "$(${pkgs.coreutils}/bin/readlink /run/current-system)"
              )
            '';
          }
        ];
      };
    }
    (lib.mkMerge (builtins.map (fragment: {aos.abilities = fragment;}) abilityFragments))
  ];
}
