##! modules/base/nsswitch.nix — Name Service Switch configuration
##!
##! Writes /etc/nsswitch.conf so glibc activates the NSS modules built
##! into systemd (nss-systemd, nss-myhostname, nss-resolve).
##! `nss-mymachines` is deliberately not shipped, so package/container
##! reachability has to use explicit /etc/hosts entries or DNS. Without this
##! file, glibc falls back to its hardcoded
##! compile-time defaults and the .so files installed by systemd are
##! never loaded — nss-resolve and nss-myhostname become dead code.
##!
##! See nsswitch.conf(5) and systemd's nss-resolve(8) for the full
##! syntax and per-module semantics.
{
  config,
  lib,
  ...
}: let
  cfg = config.aos.nsswitch;
in {
  options.aos.nsswitch = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether to write /etc/nsswitch.conf. Disable only if another
        module is managing it.
      '';
    };

    hosts = lib.mkOption {
      type = lib.types.str;
      default = "files myhostname resolve [!UNAVAIL=return] dns";
      description = ''
        Lookup order for the "hosts" database. The default wires up
        nss-myhostname (local hostname resolution) and nss-resolve
        (systemd-resolved). The [!UNAVAIL=return] guard means: trust
        systemd-resolved's answer when it's reachable; fall through to
        plain DNS when it's genuinely down. Package/container names must
        be explicit in /etc/hosts or DNS.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.etc."nsswitch.conf" = {
      text = ''
        # /etc/nsswitch.conf — Name Service Switch configuration
        # Generated by modules/base/nsswitch.nix — do not edit manually.

        passwd:         files systemd
        group:          files [SUCCESS=merge] systemd
        shadow:         files
        gshadow:        files

        hosts:          ${cfg.hosts}
        networks:       files

        protocols:      files
        services:       files
        ethers:         files
        rpc:            files

        netgroup:       files
      '';
    };
  };
}
