##! modules/base/repart.nix — A/B root partition management module
##!
##! Configures systemd-repart for declarative disk partitioning with support
##! for A/B root partition layouts. systemd-repart reads partition definitions
##! from /etc/repart.d/*.conf and creates, grows, or modifies GPT partitions
##! to match the declared state.
##!
##! This enables the A/B update scheme: two root partitions (root-a, root-b)
##! are maintained so that updates are written to the inactive partition while
##! the active one continues serving. On successful boot, the new partition
##! becomes active. On failure, the boot loader falls back to the previous one.
{
  config,
  pkgs,
  lib,
  ...
}: let
  cfg = config.aos.repart;

  # Generate a repart.d definition file from a name and its attribute set.
  mkRepartConf = name: attrs: let
    # Format each key-value pair as INI-style "Key=Value".
    lines = lib.mapAttrsToList (key: value: "${key}=${toString value}") attrs;
  in ''
    # /etc/repart.d/${name}.conf
    # Generated by modules/base/repart.nix — do not edit manually.

    [Partition]
    ${lib.concatStringsSep "\n" lines}
  '';
in {
  options.aos.repart = {
    ## Enable systemd-repart for declarative GPT partition management.
    ##
    ## # See Also
    ## - `aos.repart.definitions`, `aos.sysupdate`
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Enable systemd-repart for declarative GPT partition management.
        When enabled, partition definitions from /etc/repart.d/ are applied
        at boot to ensure the disk layout matches the declared state.
        Used for A/B root partition schemes and automatic partition creation.
      '';
    };

    ## Partition definitions for systemd-repart.
    ##
    ## # Examples
    ## ```nix
    ## aos.repart.definitions."10-root-a" = {
    ##   Type = "root";
    ##   Label = "root-a";
    ##   SizeMinBytes = "2G";
    ## };
    ## ```
    definitions = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = {};
      description = ''
        Partition definitions for systemd-repart. Each key becomes a file
        in /etc/repart.d/ (e.g. "10-root-a" -> /etc/repart.d/10-root-a.conf).
        Values are attribute sets of repart.d options. Example:

          definitions."10-root-a" = {
            Type = "root";
            Label = "root-a";
            SizeMinBytes = "2G";
            SizeMaxBytes = "4G";
          };
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Generate /etc/repart.d/*.conf files from definitions.
    environment.etc =
      lib.mapAttrs' (
        name: attrs:
          lib.nameValuePair "repart.d/${name}.conf" {
            text = mkRepartConf name attrs;
          }
      )
      cfg.definitions;

    # systemd-repart.service — applies partition definitions at boot.
    # Runs early before filesystems are mounted so partitions are available.
    systemd.services."systemd-repart" = {
      description = "Repartition Root Disk";
      wantedBy = ["initrd.target"];
      before = ["local-fs-pre.target"];
      after = ["systemd-udevd.service"];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.systemd}/bin/systemd-repart --dry-run=no";
        # systemd-repart needs access to block devices and GPT headers.
        ProtectSystem = false;
      };
    };
  };
}
