##! modules/base/swap.nix — Swap and OOM strategy module
##!
##! Configures compressed swap via zram and systemd-oomd for out-of-memory
##! handling. zram creates a compressed block device in RAM that acts as swap,
##! providing better memory utilization without disk I/O. systemd-oomd monitors
##! memory pressure via PSI and kills cgroup subtrees before the kernel OOM
##! killer fires, giving more predictable behavior under memory pressure.
##!
##! The defaults are tuned for server workloads: 50% of RAM as zstd-compressed
##! zram swap, with oomd killing at 60% memory pressure or 90% swap usage.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.aos.swap;
in
{
  options.aos.swap = {
    zram = {
      ## Enable zram compressed swap.
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Enable zram compressed swap. Creates a compressed block device in
          RAM that acts as swap space, improving memory utilization without
          requiring a swap partition or file on disk.
        '';
      };

      ## Size of the zram device (percentage or absolute).
      size = lib.mkOption {
        type = lib.types.str;
        default = "50%";
        description = ''
          Size of the zram device, either as a percentage of total RAM
          (e.g. "50%") or an absolute size (e.g. "4G"). Because zram
          compresses data, the effective swap capacity is typically 2-3x
          the configured size.
        '';
      };

      ## Compression algorithm for zram (zstd, lz4, lzo).
      algorithm = lib.mkOption {
        type = lib.types.str;
        default = "zstd";
        description = ''
          Compression algorithm for zram. Options: "zstd" (best ratio),
          "lz4" (fastest), "lzo" (balanced). zstd is recommended for
          server workloads where compression ratio matters more than
          CPU overhead.
        '';
      };
    };

    oomd = {
      ## Enable systemd-oomd for userspace OOM handling.
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Enable systemd-oomd for userspace OOM handling. oomd uses PSI
          (Pressure Stall Information) to detect memory pressure and
          kills the largest cgroup subtree before the kernel OOM killer
          fires. This provides more predictable and faster recovery.
        '';
      };

      ## Swap usage threshold for oomd process killing.
      swapUsedLimit = lib.mkOption {
        type = lib.types.str;
        default = "90%";
        description = ''
          Swap usage threshold at which oomd begins killing processes.
          When system-wide swap usage exceeds this percentage, oomd
          selects the cgroup with the highest swap usage for termination.
        '';
      };

      ## Memory pressure threshold for oomd action.
      defaultMemoryPressureLimit = lib.mkOption {
        type = lib.types.str;
        default = "60%";
        description = ''
          Memory pressure threshold (via PSI) at which oomd begins
          acting. Expressed as a percentage of time the system spends
          stalled on memory operations over a 10-second window.
        '';
      };
    };
  };

  config = {
    # zram-setup.service — creates and activates the zram swap device.
    # Runs once at boot before swap.target to ensure zram is available early.
    systemd.services."zram-setup" = lib.mkIf cfg.zram.enable {
      description = "Setup zram compressed swap device";
      wantedBy = [ "swap.target" ];
      before = [ "swap.target" ];
      after = [ "systemd-modules-load.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${pkgs.zram-setup}/bin/zram-setup start ${cfg.zram.size} ${cfg.zram.algorithm}";
        ExecStop = "${pkgs.zram-setup}/bin/zram-setup stop";
      };
    };

    # /etc/systemd/zram-generator.conf — declarative zram configuration.
    # Used by systemd-zram-setup@.service if available, and as a reference
    # for the zram-setup oneshot service.
    environment.etc."systemd/zram-generator.conf" = lib.mkIf cfg.zram.enable {
      text = ''
        # /etc/systemd/zram-generator.conf
        # Generated by modules/base/swap.nix — do not edit manually.

        [zram0]
        zram-size = ${cfg.zram.size}
        compression-algorithm = ${cfg.zram.algorithm}
        swap-priority = 100
        fs-type = swap
      '';
    };

    # Ensure the zram kernel module is loaded at boot.
    environment.etc."modules-load.d/aos-zram.conf" = lib.mkIf cfg.zram.enable {
      text = ''
        # zram module — generated by modules/base/swap.nix
        zram
      '';
    };

    # /etc/systemd/oomd.conf — systemd-oomd configuration.
    # Controls when and how oomd kills processes under memory pressure.
    environment.etc."systemd/oomd.conf" = lib.mkIf cfg.oomd.enable {
      text = ''
        # /etc/systemd/oomd.conf
        # Generated by modules/base/swap.nix — do not edit manually.

        [OOM]
        SwapUsedLimit=${cfg.oomd.swapUsedLimit}
        DefaultMemoryPressureLimit=${cfg.oomd.defaultMemoryPressureLimit}
        DefaultMemoryPressureDurationUSec=30s
      '';
    };

    # Enable systemd-oomd.service when oomd is configured.
    systemd.services."systemd-oomd" = lib.mkIf cfg.oomd.enable {
      description = "Userspace Out-Of-Memory (OOM) Killer";
      wantedBy = [ "multi-user.target" ];
      after = [ "systemd-journald.service" ];
      serviceConfig = {
        Type = "notify";
        Restart = "on-failure";
        RestartSec = "5s";
        ExecStart = "/usr/lib/systemd/systemd-oomd";
      };
    };
  };
}
