##! modules/base/tmpfiles.nix — Base tmpfiles.d drop-ins
##!
##! Writes the base runtime directories NixOS ships via
##! systemd.tmpfiles.rules (/run/lock, /var/db, /var/lock symlink) and
##! cleans up the stale shadow-utils lock files that survive a crash.
##! Also routes cryptsetup's shipped tmpfiles.d entry into
##! /etc/tmpfiles.d/ so systemd-tmpfiles picks it up at boot — without
##! this, ${pkgs.cryptsetup}/lib/tmpfiles.d/cryptsetup.conf is invisible
##! to systemd, which only scans /etc, /run, and
##! ${pkgs.systemd}/lib/tmpfiles.d/.
{pkgs, ...}: {
  config = {
    # Base runtime directories and stale-lock cleanup.
    environment.etc."tmpfiles.d/aos-base.conf" = {
      text = ''
        # /etc/tmpfiles.d/aos-base.conf
        # Generated by modules/base/tmpfiles.nix — do not edit manually.

        # Runtime lock directories used by the flock(1) /
        # lockfile-create convention. /var/lock is a compatibility
        # symlink into /run/lock so that stale locks never survive a
        # reboot.
        d  /run/lock                0755 root root - -
        d  /run/apm                 0700 root root - -
        d  /var/db                  0755 root root - -
        L  /var/lock                -    -    -    - ../run/lock

        # shadow-utils (useradd / passwd / vipw) creates these
        # advisory locks and removes them on clean shutdown. If it
        # crashes, the leftover file blocks all further account
        # mutations until a human deletes it. R! removes them
        # unconditionally at boot ("!" = boot only, not runtime).
        R! /etc/group.lock           -    -    -    - -
        R! /etc/passwd.lock          -    -    -    - -
        R! /etc/shadow.lock          -    -    -    - -
      '';
    };

    # systemd's stock home.conf tries to create /home and /srv, and
    # provision.conf tries to create /root/.ssh from credentials. AOS keeps
    # / read-only and routes SSH authorization through /etc/ssh/authorized_keys,
    # so mask those snippets by basename in the higher-priority /etc directory.
    environment.etc."tmpfiles.d/home.conf" = {
      text = ''
        # Masked by modules/base/tmpfiles.nix; /home and /srv are not created on AOS.
      '';
    };
    environment.etc."tmpfiles.d/provision.conf" = {
      text = ''
        # Masked by modules/base/tmpfiles.nix; AOS does not use systemd credential provisioning for root SSH keys.
      '';
    };

    # Route cryptsetup's shipped tmpfiles drop-in into /etc/tmpfiles.d/
    # via symlink so upstream rule changes flow through automatically
    # on the next cryptsetup bump.
    environment.etc."tmpfiles.d/cryptsetup.conf" = {
      source = "${pkgs.cryptsetup}/lib/tmpfiles.d/cryptsetup.conf";
    };
  };
}
