##! Package-owned MariaDB configuration, bootstrap SQL, TLS, and native services.
{
  config,
  lib,
  package,
  dependencies,
  ...
}: let
  cfg = config.aos.mariadb;
  anyServiceEnabled = config.aos.services."mariadb.initialize".enable || config.aos.services."mariadb.main".enable;
  inherit (lib) mkOption;
  types = lib.types;
  operations = config.aos.abilities;
  positiveInt = types.ints.between 1 9007199254740991;
  port = types.ints.between 1 65535;
  address = types.strMatching "[A-Za-z0-9_.:-]+";
  collation = types.strMatching "[A-Za-z0-9_]+";
  sqlMode = types.strMatching "[A-Z0-9_,]*";
  characterSet = types.enum ["utf8mb4" "utf8mb3" "latin1"];
  credentialReference = types.submodule operations.credential.operations.deliver.input;
  credentialConfigured = value: (value.name != null) != (value.resource != null);
  credentialPath = name: operations.credential.operations.deliver.effects."mariadb-${name}".outputs.path;
  account = operations.identity.operations.principal.effects.mariadb.outputs.name;
  group = operations.identity.operations.group.effects.mariadb.outputs.name;
  tlsCertificate = cfg.tls.certificate;
  tlsPrivateKey = cfg.tls.privateKey;
  tlsCa = cfg.tls.ca;
  adminSql = cfg.bootstrap.adminSql;
  replicationSql = cfg.bootstrap.replicationSql;

  boolValue = value:
    if value
    then "ON"
    else "OFF";
  literal = text: text;
  executionPath = value: value;
  credentialContent = name: {
    credentialPath = credentialPath name;
    maximumBytes = 1048576;
  };
  command = entry_point: arguments: {
    executable = {
      path = "${package}/${entry_point}";
      inherit arguments;
    };
    ignore_failure = false;
  };
  runtimeSearchPath = [package.path dependencies.bash.path dependencies.coreutils.path dependencies.sed.path];
  credentials = let
    tlsCredentials =
      lib.optionals cfg.tls.enable [
        {
          name = "tls-certificate";
          reference = tlsCertificate;
        }
        {
          name = "tls-private-key";
          reference = tlsPrivateKey;
        }
      ]
      ++ lib.optional (credentialConfigured tlsCa) {
        name = "tls-ca";
        reference = tlsCa;
      };
    bootstrapCredentials =
      lib.optional (credentialConfigured adminSql) {
        name = "admin-bootstrap-sql";
        reference = adminSql;
      }
      ++ lib.optional (credentialConfigured replicationSql) {
        name = "replication-bootstrap-sql";
        reference = replicationSql;
      };
  in {
    inherit tlsCredentials bootstrapCredentials;
    all = tlsCredentials ++ bootstrapCredentials;
  };
  statePath = operations.filesystem.operations.directory.effects.mariadb-state.outputs.path;
  runtimePath = operations.filesystem.operations.directory.effects.mariadb-runtime.outputs.path;
  logPath = operations.filesystem.operations.directory.effects.mariadb-logs.outputs.path;
  configPath = operations.configuration.operations.file.effects.mariadb-server.outputs.path;
  bootstrapPath = operations.configuration.operations.file.effects.mariadb-bootstrap.outputs.path;
  bootstrapFragments = lib.concatLists (builtins.map (credential: [
      (credentialContent credential.name)
      (literal "\n")
    ])
    credentials.bootstrapCredentials);
  tlsFragments =
    if cfg.tls.enable
    then
      [
        (literal "ssl-cert=")
        (executionPath (credentialPath "tls-certificate"))
        (literal "\nssl-key=")
        (executionPath (credentialPath "tls-private-key"))
        (literal "\n")
      ]
      ++ lib.optionals (credentialConfigured tlsCa) [
        (literal "ssl-ca=")
        (executionPath (credentialPath "tls-ca"))
        (literal "\n")
      ]
    else [(literal "skip-ssl\n")];
  serverFragments =
    [
      (literal "# Generated by the MariaDB package module. Do not edit.\n[client]\nsocket=")
      (executionPath runtimePath)
      (literal ''
        /mariadb.sock
        port=${toString cfg.port}

        [mariadbd]
        bind-address=${cfg.bindAddress}
        port=${toString cfg.port}
        socket=
      '')
      (executionPath runtimePath)
      (literal "/mariadb.sock\npid-file=")
      (executionPath runtimePath)
      (literal "/mariadb.pid\ndatadir=")
      (executionPath statePath)
      (literal "\nlog-error=")
      (executionPath logPath)
      (literal ''
        /error.log
        character-set-server=${cfg.characterSet}
        collation-server=${cfg.collation}
        max-connections=${toString cfg.maxConnections}
        skip-name-resolve=${boolValue cfg.skipNameResolve}
        sql-mode=${cfg.sqlMode}
      '')
    ]
    ++ lib.optionals (credentials.bootstrapCredentials != []) [
      (literal "init-file=")
      (executionPath bootstrapPath)
      (literal "\n")
    ]
    ++ tlsFragments;
  commonStorage.mounts = [
    {
      name = "state";
      source = statePath;
      access = "read-write";
    }
    {
      name = "runtime";
      source = runtimePath;
      access = "read-write";
    }
    {
      name = "logs";
      source = logPath;
      access = "read-write";
    }
  ];
  commonIdentity = {
    principal = operations.identity.operations.principal.effects.mariadb.outputs.name;
    primary_group = operations.identity.operations.group.effects.mariadb.outputs.name;
    supplementary_groups = [];
    ephemeral = false;
    file_creation_mask = "0027";
  };
  commonIsolation = {
    privilege = "unprivileged";
    filesystem = "read-only-system";
    network = "host";
    process_visibility = "host";
    termination_scope = "all-processes";
    temporary_directory = "private";
    devices = [];
    host_paths = [];
    permit_core_dumps = false;
  };
  commonHardening = {
    allow_privilege_escalation = false;
    ambient_privileges = [];
    privilege_bounds = {
      kind = "restricted";
      privileges = [];
    };
    resource_control_delegation = false;
    resource_control_access = "read-only";
    device_access_scope = "shared";
    host_clock_mutation = false;
    host_name_mutation = false;
    operating_system_log_access = false;
    operating_system_extension_access = false;
    operating_system_tunable_access = false;
    lock_execution_personality = true;
    writable_executable_memory = false;
    isolation_domains = [];
    network_families = ["ipv4" "ipv6" "local"];
    memory_pressure_adjustment = 0;
    permit_realtime = false;
    permit_elevated_file_identity = false;
    process_visibility = "all";
    security_label = "aos-pkg-mariadb";
    operation_architectures = [];
    operation_allow = [];
    operation_deny = [];
    denied_operation_action = "return-permission-denied";
    operation_profile = "system-service";
    isolated_identity_mapping = "none";
  };
  initializeService = {
    policy.hardening = commonHardening;
    service = "mariadb-init";
    lifecycle = {
      description = "Initialize MariaDB state";
      execution_model = "oneshot";
      environment_files = [];
      condition = [];
      pre_start = [];
      start = [(command "bin/mariadb-control" ["init" configPath statePath])];
      post_start = [];
      stop = [];
      post_stop = [];
      restart = "never";
      restart_delay_millis = 0;
      configuration_change_action = "none";
      remain_after_exit = true;
      start_timeout_millis = 90000;
      stop_timeout_millis = 60000;
    };
    supervision = {
      startup_protocol = "process";
      notification_access = "none";
    };
    readiness = {
      mechanism = "successful-exit";
      signal_scope = "none";
      timeout_millis = 90000;
    };
    configuration.views = [
      {
        name = "server";
        source = configPath;
        optional = false;
      }
    ];
    environment = {
      variables = {};
      search_path = runtimeSearchPath;
    };
    storage = commonStorage;
    identity = commonIdentity;
    isolation = commonIsolation;
  };
  mainService = {
    policy.hardening = commonHardening;
    service = "mariadb";
    lifecycle = {
      description = "MariaDB database server";
      execution_model = "foreground";
      environment_files = [];
      condition = [];
      pre_start = [];
      start = [(command "bin/mariadb-control" ["run" configPath])];
      post_start = [];
      stop = [];
      post_stop = [];
      restart = "on-failure";
      restart_delay_millis = 5000;
      configuration_change_action = "restart";
      remain_after_exit = false;
      start_timeout_millis = 90000;
      stop_timeout_millis = 60000;
    };
    dependencies = {
      after = [(operations.serviceManagement.operations.realize.effects."mariadb.initialize".outputs.resource) (operations.network.operations.ready.effects.mariadb.outputs.resource)];
      before = [];
      requires = [(operations.serviceManagement.operations.realize.effects."mariadb.initialize".outputs.resource)];
      wants = [(operations.network.operations.ready.effects.mariadb.outputs.resource)];
    };
    supervision = {
      startup_protocol = "notification";
      notification_access = "all-processes";
    };
    readiness = {
      mechanism = "process-signal";
      signal_scope = "all-processes";
      timeout_millis = 90000;
    };
    credentials =
      if credentials.tlsCredentials == []
      then null
      else {
        views =
          builtins.map (credential: {
            inherit (credential) name;
            inherit (credential.reference) encrypted;
            reference = credentialPath credential.name;
            optional = false;
          })
          credentials.tlsCredentials;
      };
    configuration.views =
      [
        {
          name = "server";
          source = configPath;
          optional = false;
        }
      ]
      ++ lib.optional (credentials.bootstrapCredentials != []) {
        name = "bootstrap";
        source = bootstrapPath;
        optional = false;
      };
    environment = {
      variables = {};
      search_path = runtimeSearchPath;
    };
    storage = commonStorage;
    logging = {
      standard_output = "structured";
      standard_error = "structured";
      directories = [];
      directory_mode = "0750";
    };
    identity = commonIdentity;
    isolation = commonIsolation;
    resources.open_files = {
      kind = "maximum";
      value = 65536;
    };
  };
in {
  options.aos.mariadb = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = "Enable the MariaDB database service.";
    };
    bindAddress = mkOption {
      type = address;
      default = "127.0.0.1";
      description = "Address on which MariaDB accepts client connections.";
    };
    port = mkOption {
      type = port;
      default = 3306;
      description = "TCP port on which MariaDB accepts client connections.";
    };
    maxConnections = mkOption {
      type = positiveInt;
      default = 151;
      description = "Maximum simultaneous MariaDB client connections.";
    };
    characterSet = mkOption {
      type = characterSet;
      default = "utf8mb4";
      description = "Default server character set.";
    };
    collation = mkOption {
      type = collation;
      default = "utf8mb4_uca1400_ai_ci";
      description = "Default server collation.";
    };
    skipNameResolve = mkOption {
      type = types.bool;
      default = true;
      description = "Disable DNS lookups while matching client grant entries.";
    };
    sqlMode = mkOption {
      type = sqlMode;
      default = "STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION";
      description = "Comma-separated server SQL modes.";
    };
    tls = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable TLS using credential-backed certificate material.";
      };
      certificate = mkOption {
        type = credentialReference;
        default = {};
        description = "Opaque reference for the PEM server certificate.";
      };
      privateKey = mkOption {
        type = credentialReference;
        default = {};
        description = "Opaque reference for the PEM server private key.";
      };
      ca = mkOption {
        type = credentialReference;
        default = {};
        description = "Optional opaque reference for the client CA bundle.";
      };
    };
    bootstrap = {
      adminSql = mkOption {
        type = credentialReference;
        default = {};
        description = "Optional credential containing idempotent SQL for administrator provisioning.";
      };
      replicationSql = mkOption {
        type = credentialReference;
        default = {};
        description = "Optional credential containing idempotent SQL for replication provisioning.";
      };
    };
  };

  config = lib.mkMerge [
    {
      aos.services = {
        "mariadb.initialize" = lib.mkDefault (initializeService // {enable = lib.mkDefault cfg.enable;});
        "mariadb.main" = lib.mkDefault (mainService // {enable = lib.mkDefault cfg.enable;});
      };
      assertions = [
        {
          assertion =
            !anyServiceEnabled
            || !cfg.tls.enable
            || (
              credentialConfigured tlsCertificate
              && credentialConfigured tlsPrivateKey
            );
          message = "mariadb TLS requires certificate and private-key credential references";
        }
        {
          assertion =
            !anyServiceEnabled
            || cfg.tls.enable
            || builtins.all
            (reference: !credentialConfigured reference)
            [tlsCertificate tlsPrivateKey tlsCa];
          message = "mariadb TLS credentials require mariadb.tls.enable";
        }
      ];
    }
    (lib.mkIf anyServiceEnabled {
      aos.abilities = {
        identity.operations = {
          group.effects.mariadb.input.name = "mariadb";
          principal.effects.mariadb.input = {
            name = "mariadb";
            description = "MariaDB database service";
            home_directory = "/var/lib/aos-pkg-mariadb";
            primary_group = group;
          };
        };
        filesystem.operations.directory.effects = {
          mariadb-state = {
            lifetime = "persistent";
            input = {
              path = "/var/lib/aos-pkg-mariadb";
              mode = "0750";
              owner = account;
              inherit group;
            };
          };
          mariadb-runtime.input = {
            path = "/run/aos-pkg-mariadb";
            mode = "0750";
            owner = account;
            inherit group;
          };
          mariadb-logs = {
            lifetime = "persistent";
            input = {
              path = "/var/log/aos-pkg-mariadb";
              mode = "0750";
              owner = account;
              inherit group;
            };
          };
        };
        network.operations.ready.effects.mariadb.input = {
          scope = "address-configured";
          families = ["ipv4" "ipv6"];
        };
        configuration.operations.file.effects.mariadb-server.input = {
          path = "/etc/aos/packages/mariadb/my.cnf";
          fragments = serverFragments;
          mode = "0640";
          owner = account;
          inherit group;
        };
        credential.operations.deliver.effects = builtins.listToAttrs (builtins.map (credential: {
            name = "mariadb-${credential.name}";
            value.input = credential.reference;
          })
          credentials.all);
      };
    })
    (lib.mkIf (anyServiceEnabled && credentials.bootstrapCredentials != []) {
      aos.abilities.configuration.operations.file.effects.mariadb-bootstrap.input = {
        path = "/etc/aos/packages/mariadb/bootstrap.sql";
        fragments = bootstrapFragments;
        mode = "0600";
        owner = account;
        inherit group;
      };
    })
  ];
}
