/* SPDX-License-Identifier: MIT OR Apache-2.0 */
/* Draft only: requires the coordinated protocol/profile cutover. */
#ifndef CRUCIBLE_NATIVE_CONSOLE_DRAFT_H
#define CRUCIBLE_NATIVE_CONSOLE_DRAFT_H
#include <stdint.h>
#include <stddef.h>
#include <stdatomic.h>

#define CRUCIBLE_NATIVE_CONSOLE_REQUIRED_SHMEM_ABI 31u
#define CRUCIBLE_NATIVE_CONSOLE_REQUIRED_CONTROL_VERSION 4u
#define CRUCIBLE_NATIVE_CONSOLE_REQUIRED_SETUP_SCHEMA 3u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_BYTES 128u
#define CRUCIBLE_NATIVE_CONSOLE_CAPACITY 4096u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_BYTES 256u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_SCHEMA_VERSION 2u
#define CRUCIBLE_NATIVE_CONSOLE_CONTROL_KIND_ACCEPTANCE 1u
#define CRUCIBLE_NATIVE_CONSOLE_CONTROL_KIND_OBSERVATION 2u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_BYTES 128u
#define CRUCIBLE_NATIVE_CONSOLE_SEGMENT_BYTES 525184u
#define CRUCIBLE_NATIVE_CONSOLE_SETUP_HEADER_BYTES 32u
#define CRUCIBLE_NATIVE_CONSOLE_MAX_ISSUED_AUTHORIZATIONS 65536u
#define CRUCIBLE_NATIVE_CONSOLE_MAX_STREAMS 16u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_BITS 31u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_HEADER_BYTES 64u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_ROW_BYTES 64u
#define CRUCIBLE_NATIVE_CONSOLE_PHASE_GRANT 1u
#define CRUCIBLE_NATIVE_CONSOLE_PHASE_COLD_SETUP 2u
#define CRUCIBLE_NATIVE_CONSOLE_PHASE_RESTORE 3u
#define CRUCIBLE_NATIVE_CONSOLE_PHASE_IDLE_SERVICE 4u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_PUBLICATION_OFFSET 0u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_ADVANCE_OFFSET 16u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_REQUEST_OFFSET 24u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_CAPTURE_OFFSET 28u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_FAULT_FRONTIER_OFFSET 32u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_CEILING_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_LAST_ISSUED_PRESENT_OFFSET 48u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_STOP_OFFSET 49u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_KIND_OFFSET 50u
#define CRUCIBLE_NATIVE_CONSOLE_CLAMP_LAST_ISSUED_OFFSET 64u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_PUBLICATION_OFFSET 0u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_MAGIC_OFFSET 8u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_RING_END_OFFSET 16u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_NODE_SEQUENCE_OFFSET 24u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_LOGICAL_PS_OFFSET 32u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_RAW_PREFIX_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_AUTHORIZATION_OFFSET 48u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_AUTHORIZATION_ADVANCE_OFFSET 56u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_LOGICAL_GENERATION_OFFSET 64u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_PROCESS_OFFSET 72u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_REGION_OFFSET 80u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_SLOT_OFFSET 96u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_VCPU_OFFSET 100u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_CLOSED_GENERATION_OFFSET 104u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_CONTROL_BOUNDARY_ACK_OFFSET 108u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_STOPPED_ADVANCE_OFFSET 112u
#define CRUCIBLE_NATIVE_CONSOLE_OPERATION_STOP_RESERVED_OFFSET 120u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_SLOT_OFFSET 8u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_STREAM_OFFSET 12u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_REGION_OFFSET 16u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_PROCESS_OFFSET 32u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_AUTHORIZATION_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_LOGICAL_GENERATION_OFFSET 48u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_NODE_SEQUENCE_OFFSET 56u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_STREAM_SEQUENCE_OFFSET 64u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_LOGICAL_PS_OFFSET 72u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_RAW_PREFIX_OFFSET 80u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_AUTHORIZATION_ADVANCE_OFFSET 88u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_VCPU_OFFSET 96u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_PHASE_OFFSET 100u
#define CRUCIBLE_NATIVE_CONSOLE_RECORD_BYTE_OFFSET 101u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_PUBLICATION_OFFSET 0u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_REGION_OFFSET 8u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_PROCESS_OFFSET 24u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_AUTHORIZATION_OFFSET 32u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_LOGICAL_GENERATION_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_ADVANCE_OFFSET 48u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_PRIOR_SEQUENCE_OFFSET 56u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_PRIOR_RING_END_OFFSET 64u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_ALLOWANCE_OFFSET 72u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_SLOT_OFFSET 76u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_PHASE_TOKEN_OFFSET 80u
#define CRUCIBLE_NATIVE_CONSOLE_AUTH_PHASE_OFFSET 88u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_SEQUENCE_OFFSET 0u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_RING_END_OFFSET 8u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_LOGICAL_PS_OFFSET 16u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_RAW_PREFIX_OFFSET 24u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_AUTHORIZATION_OFFSET 32u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_ACCEPTED_ADVANCE_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_LOGICAL_GENERATION_OFFSET 48u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_PROCESS_OFFSET 56u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_REGION_OFFSET 64u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_SLOT_OFFSET 80u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_REQUEST_OFFSET 84u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_PLAN_HASH_OFFSET 88u
#define CRUCIBLE_NATIVE_CONSOLE_FRONTIER_SEALED_OFFSET 120u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_BITS_OFFSET 8u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_SLOT_OFFSET 12u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_REGION_OFFSET 16u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_PROCESS_OFFSET 32u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_PLAN_HASH_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_RESOLVED_STREAMS_OFFSET 72u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_CAPACITY_OFFSET 104u
#define CRUCIBLE_NATIVE_CONSOLE_CAPABILITY_STRIDE_OFFSET 108u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_LENGTH_OFFSET 12u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_SLOT_OFFSET 16u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_STREAM_COUNT_OFFSET 20u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_CAPACITY_OFFSET 24u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_CAPABILITY_VERSION_OFFSET 28u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_LOGICAL_GENERATION_OFFSET 32u
#define CRUCIBLE_NATIVE_CONSOLE_PLAN_NODE_SEQUENCE_BASE_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_STREAM_ID_OFFSET 0u
#define CRUCIBLE_NATIVE_CONSOLE_STREAM_DEVICE_OFFSET 4u
#define CRUCIBLE_NATIVE_CONSOLE_STREAM_DIRECTION_OFFSET 6u
#define CRUCIBLE_NATIVE_CONSOLE_STREAM_DEVICE_IDENTITY_OFFSET 8u
#define CRUCIBLE_NATIVE_CONSOLE_STREAM_OWNER_MASK_OFFSET 40u
#define CRUCIBLE_NATIVE_CONSOLE_STREAM_SEQUENCE_BASE_OFFSET 48u

/* Atomic words are storage, not a native-structure wire cast. */
typedef struct { _Alignas(64) _Atomic uint64_t words[16]; } CrucibleNativeConsole_record;
_Static_assert(sizeof(CrucibleNativeConsole_record) == 128, "console record size");
_Static_assert(_Alignof(CrucibleNativeConsole_record) == 64, "console record alignment");
_Static_assert(offsetof(CrucibleNativeConsole_record, words) == 0, "console record words");
typedef struct { _Alignas(128) _Atomic uint64_t words[16]; } CrucibleNativeConsole_capability;
_Static_assert(sizeof(CrucibleNativeConsole_capability) == 128, "console capability size");
_Static_assert(_Alignof(CrucibleNativeConsole_capability) == 128, "console capability alignment");
_Static_assert(offsetof(CrucibleNativeConsole_capability, words) == 0, "console capability words");
typedef struct { _Alignas(128) _Atomic uint64_t words[16]; } CrucibleNativeConsole_authorization;
_Static_assert(sizeof(CrucibleNativeConsole_authorization) == 128, "console authorization size");
_Static_assert(_Alignof(CrucibleNativeConsole_authorization) == 128, "console authorization alignment");
_Static_assert(offsetof(CrucibleNativeConsole_authorization, words) == 0, "console authorization words");
typedef struct { _Alignas(128) _Atomic uint64_t words[16]; } CrucibleNativeConsole_frontier;
_Static_assert(sizeof(CrucibleNativeConsole_frontier) == 128, "console frontier size");
_Static_assert(_Alignof(CrucibleNativeConsole_frontier) == 128, "console frontier alignment");
_Static_assert(offsetof(CrucibleNativeConsole_frontier, words) == 0, "console frontier words");
typedef struct { _Alignas(128) _Atomic uint64_t words[16]; } CrucibleNativeConsole_operation_stop;
_Static_assert(sizeof(CrucibleNativeConsole_operation_stop) == 128, "console operation_stop size");
_Static_assert(_Alignof(CrucibleNativeConsole_operation_stop) == 128, "console operation_stop alignment");
_Static_assert(offsetof(CrucibleNativeConsole_operation_stop, words) == 0, "console operation_stop words");
typedef struct { _Alignas(128) _Atomic uint64_t words[32]; } CrucibleNativeConsole_clamp;
_Static_assert(sizeof(CrucibleNativeConsole_clamp) == 256, "console clamp size");
_Static_assert(_Alignof(CrucibleNativeConsole_clamp) == 128, "console clamp alignment");
_Static_assert(offsetof(CrucibleNativeConsole_clamp, words) == 0, "console clamp words");

/* Auth and clamp words must be seqlock-snapshotted. Clamp fields precede
 * the original request Release; matching fields alone confer no phase.
 * Frontier words belong inside
 * the original NodeSlot publication interval before its odd ACK.
 * Decoding a phase label does not confer execution authority. */
#endif
