/* Generated by crucible-shmem. Do not edit by hand. */
#ifndef CRUCIBLE_SHMEM_ABI_H
#define CRUCIBLE_SHMEM_ABI_H

#include <stdatomic.h>
#include <stddef.h>
#include <stdint.h>

#if !defined(__GNUC__) && !defined(__clang__)
#error "crucible_shmem_abi.h requires a compiler with aligned attribute support"
#endif

#define CRUCIBLE_SHMEM_ALIGNED(N) __attribute__((aligned(N)))
#define CRUCIBLE_SHMEM_STATIC_ASSERT(COND, MSG) _Static_assert((COND), MSG)

#define CRUCIBLE_SHMEM_REGION_MAGIC UINT64_C(0x314d485343555243)
#define CRUCIBLE_SHMEM_ABI_VERSION 4u
#define CRUCIBLE_SHMEM_MAX_FRAME_DATA 4608u
#define CRUCIBLE_SHMEM_DEFAULT_QUEUE_CAPACITY 64u
#define CRUCIBLE_SHMEM_COVERAGE_QUEUE_CAPACITY 65536u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_QUEUE_CAPACITY 1024u
#define CRUCIBLE_SHMEM_MAX_NODES 32u
#define CRUCIBLE_SHMEM_RESERVED_SLOTS 3u
#define CRUCIBLE_SHMEM_MAX_VM_NODES 29u
#define CRUCIBLE_SHMEM_SLOT_NET_ROUTER 31u
#define CRUCIBLE_SHMEM_SLOT_BLK_IO 30u
#define CRUCIBLE_SHMEM_SLOT_9P_IO 29u
#define CRUCIBLE_SHMEM_LAYOUT_TARGET_TRIPLE "x86_64-unknown-linux-gnu"
#define CRUCIBLE_SHMEM_FUTEX_PRIVATE 0

#define CRUCIBLE_SHMEM_STATUS_RUNNING 0u
#define CRUCIBLE_SHMEM_STATUS_IDLE 1u
#define CRUCIBLE_SHMEM_STATUS_DONE 2u
#define CRUCIBLE_SHMEM_KIND_VM 0u
#define CRUCIBLE_SHMEM_KIND_NET 1u
#define CRUCIBLE_SHMEM_KIND_BLK 2u
#define CRUCIBLE_SHMEM_KIND_9P 3u

#define CRUCIBLE_SHMEM_REGION_HEADER_SIZE 256u
#define CRUCIBLE_SHMEM_REGION_HEADER_ALIGN 128u
#define CRUCIBLE_SHMEM_REGION_HEADER_MAGIC_OFFSET 0u
#define CRUCIBLE_SHMEM_REGION_HEADER_ABI_VERSION_OFFSET 8u
#define CRUCIBLE_SHMEM_REGION_HEADER_NODE_COUNT_OFFSET 12u
#define CRUCIBLE_SHMEM_REGION_HEADER_QUEUE_CAPACITY_OFFSET 16u
#define CRUCIBLE_SHMEM_REGION_HEADER_RING_COUNT_OFFSET 20u
#define CRUCIBLE_SHMEM_REGION_HEADER_RING_HDR_OFF_OFFSET 24u
#define CRUCIBLE_SHMEM_REGION_HEADER_RING_DATA_OFF_OFFSET 32u
#define CRUCIBLE_SHMEM_REGION_HEADER_ENTRY_STRIDE_OFFSET 40u
#define CRUCIBLE_SHMEM_REGION_HEADER_REGION_SIZE_OFFSET 48u
#define CRUCIBLE_SHMEM_REGION_HEADER_ICOUNT_SHIFT_OFFSET 56u
#define CRUCIBLE_SHMEM_REGION_HEADER_PAUSE_REQUESTED_OFFSET 60u
#define CRUCIBLE_SHMEM_REGION_HEADER_SHUTDOWN_REQUESTED_OFFSET 61u
#define CRUCIBLE_SHMEM_REGION_HEADER_RESERVED_OFFSET 62u
#define CRUCIBLE_SHMEM_REGION_HEADER_RESERVED_LEN 194u

#define CRUCIBLE_SHMEM_NODE_SLOT_SIZE 128u
#define CRUCIBLE_SHMEM_NODE_SLOT_ALIGN 128u
#define CRUCIBLE_SHMEM_NODE_SLOT_CURRENT_ICOUNT_OFFSET 0u
#define CRUCIBLE_SHMEM_NODE_SLOT_CURRENT_NS_OFFSET 8u
#define CRUCIBLE_SHMEM_NODE_SLOT_MAX_ADVANCE_ICOUNT_OFFSET 16u
#define CRUCIBLE_SHMEM_NODE_SLOT_IDLE_WAKE_ICOUNT_OFFSET 24u
#define CRUCIBLE_SHMEM_NODE_SLOT_WAKE_SIGNAL_OFFSET 32u
#define CRUCIBLE_SHMEM_NODE_SLOT_STATUS_OFFSET 36u
#define CRUCIBLE_SHMEM_NODE_SLOT_KIND_OFFSET 37u
#define CRUCIBLE_SHMEM_NODE_SLOT_DEVICE_IO_ACTIVE_OFFSET 38u
#define CRUCIBLE_SHMEM_NODE_SLOT_PAD0_OFFSET 39u
#define CRUCIBLE_SHMEM_NODE_SLOT_PUBLISH_GEN_OFFSET 40u
#define CRUCIBLE_SHMEM_NODE_SLOT_DEVICE_COMPLETION_DEADLINE_ICOUNT_OFFSET 48u
#define CRUCIBLE_SHMEM_NODE_SLOT_RESERVED_OFFSET 56u
#define CRUCIBLE_SHMEM_NODE_SLOT_RESERVED_LEN 72u

#define CRUCIBLE_SHMEM_RING_HEADER_SIZE 128u
#define CRUCIBLE_SHMEM_RING_HEADER_ALIGN 128u
#define CRUCIBLE_SHMEM_RING_HEADER_READ_IDX_OFFSET 0u
#define CRUCIBLE_SHMEM_RING_HEADER_PAD_READ_OFFSET 8u
#define CRUCIBLE_SHMEM_RING_HEADER_WRITE_IDX_OFFSET 64u
#define CRUCIBLE_SHMEM_RING_HEADER_PAD_WRITE_OFFSET 72u
#define CRUCIBLE_SHMEM_RING_HEADER_PAD_READ_LEN 56u
#define CRUCIBLE_SHMEM_RING_HEADER_PAD_WRITE_LEN 56u

#define CRUCIBLE_SHMEM_FRAME_ENTRY_SIZE 4632u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_ALIGN 8u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_DELIVERY_ICOUNT_OFFSET 0u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_SRC_NODE_OFFSET 8u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_SEQ_OFFSET 12u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_LEN_OFFSET 16u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_PAD_OFFSET 18u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_DATA_OFFSET 24u
#define CRUCIBLE_SHMEM_FRAME_ENTRY_PAD_LEN 6u

#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_SIZE 64u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_ALIGN 64u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_CURRENT_ICOUNT_OFFSET 0u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_GUEST_PC_OFFSET 8u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_MAP_INDEX_OFFSET 16u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_VCPU_INDEX_OFFSET 24u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_BLOCK_LEN_OFFSET 28u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_RESERVED_OFFSET 32u
#define CRUCIBLE_SHMEM_COVERAGE_ENTRY_RESERVED_LEN 32u

#define CRUCIBLE_SHMEM_FINGERPRINT_DIGEST_BYTES 32u
#define CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_MAX_VCPUS 8u
#define CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_WORDS 68u
#define CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_SIZE 640u
#define CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_ALIGN 128u
#define CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_GEN_OFFSET 0u
#define CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_RESERVED_OFFSET 4u
#define CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_WORDS_OFFSET 8u

#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_SIZE 4672u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_ALIGN 64u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_CURRENT_ICOUNT_OFFSET 0u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_VCPU_INDEX_OFFSET 8u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_KIND_OFFSET 12u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_PAYLOAD_LEN_OFFSET 14u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_PAYLOAD_OFFSET 16u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_RESERVED_OFFSET 4624u
#define CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_RESERVED_LEN 48u

typedef struct CRUCIBLE_SHMEM_ALIGNED(128) crucible_shmem_region_header {
    _Atomic uint64_t magic;
    _Atomic uint32_t abi_version;
    _Atomic uint32_t node_count;
    _Atomic uint32_t queue_capacity;
    _Atomic uint32_t ring_count;
    _Atomic uint64_t ring_hdr_off;
    _Atomic uint64_t ring_data_off;
    _Atomic uint64_t entry_stride;
    _Atomic uint64_t region_size;
    _Atomic uint32_t icount_shift;
    _Atomic uint8_t pause_requested;
    _Atomic uint8_t shutdown_requested;
    uint8_t reserved[CRUCIBLE_SHMEM_REGION_HEADER_RESERVED_LEN];
} crucible_shmem_region_header;

CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof(crucible_shmem_region_header) == CRUCIBLE_SHMEM_REGION_HEADER_SIZE, "crucible_shmem_region_header size");
CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof(crucible_shmem_region_header) == CRUCIBLE_SHMEM_REGION_HEADER_ALIGN, "crucible_shmem_region_header alignment");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, magic) == CRUCIBLE_SHMEM_REGION_HEADER_MAGIC_OFFSET, "crucible_shmem_region_header.magic offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, abi_version) == CRUCIBLE_SHMEM_REGION_HEADER_ABI_VERSION_OFFSET, "crucible_shmem_region_header.abi_version offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, node_count) == CRUCIBLE_SHMEM_REGION_HEADER_NODE_COUNT_OFFSET, "crucible_shmem_region_header.node_count offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, queue_capacity) == CRUCIBLE_SHMEM_REGION_HEADER_QUEUE_CAPACITY_OFFSET, "crucible_shmem_region_header.queue_capacity offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, ring_count) == CRUCIBLE_SHMEM_REGION_HEADER_RING_COUNT_OFFSET, "crucible_shmem_region_header.ring_count offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, ring_hdr_off) == CRUCIBLE_SHMEM_REGION_HEADER_RING_HDR_OFF_OFFSET, "crucible_shmem_region_header.ring_hdr_off offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, ring_data_off) == CRUCIBLE_SHMEM_REGION_HEADER_RING_DATA_OFF_OFFSET, "crucible_shmem_region_header.ring_data_off offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, entry_stride) == CRUCIBLE_SHMEM_REGION_HEADER_ENTRY_STRIDE_OFFSET, "crucible_shmem_region_header.entry_stride offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, region_size) == CRUCIBLE_SHMEM_REGION_HEADER_REGION_SIZE_OFFSET, "crucible_shmem_region_header.region_size offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, icount_shift) == CRUCIBLE_SHMEM_REGION_HEADER_ICOUNT_SHIFT_OFFSET, "crucible_shmem_region_header.icount_shift offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, pause_requested) == CRUCIBLE_SHMEM_REGION_HEADER_PAUSE_REQUESTED_OFFSET, "crucible_shmem_region_header.pause_requested offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, shutdown_requested) == CRUCIBLE_SHMEM_REGION_HEADER_SHUTDOWN_REQUESTED_OFFSET, "crucible_shmem_region_header.shutdown_requested offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_region_header, reserved) == CRUCIBLE_SHMEM_REGION_HEADER_RESERVED_OFFSET, "crucible_shmem_region_header.reserved offset");

typedef struct CRUCIBLE_SHMEM_ALIGNED(128) crucible_shmem_node_slot {
    _Atomic uint64_t current_icount;
    _Atomic uint64_t current_ns;
    _Atomic uint64_t max_advance_icount;
    _Atomic uint64_t idle_wake_icount;
    _Atomic uint32_t wake_signal;
    _Atomic uint8_t status;
    _Atomic uint8_t kind;
    _Atomic uint8_t device_io_active;
    uint8_t pad0;
    _Atomic uint32_t publish_gen;
    uint8_t pad1[4];
    _Atomic uint64_t device_completion_deadline_icount;
    uint8_t reserved[CRUCIBLE_SHMEM_NODE_SLOT_RESERVED_LEN];
} crucible_shmem_node_slot;

CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof(crucible_shmem_node_slot) == CRUCIBLE_SHMEM_NODE_SLOT_SIZE, "crucible_shmem_node_slot size");
CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof(crucible_shmem_node_slot) == CRUCIBLE_SHMEM_NODE_SLOT_ALIGN, "crucible_shmem_node_slot alignment");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, current_icount) == CRUCIBLE_SHMEM_NODE_SLOT_CURRENT_ICOUNT_OFFSET, "crucible_shmem_node_slot.current_icount offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, current_ns) == CRUCIBLE_SHMEM_NODE_SLOT_CURRENT_NS_OFFSET, "crucible_shmem_node_slot.current_ns offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, max_advance_icount) == CRUCIBLE_SHMEM_NODE_SLOT_MAX_ADVANCE_ICOUNT_OFFSET, "crucible_shmem_node_slot.max_advance_icount offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, idle_wake_icount) == CRUCIBLE_SHMEM_NODE_SLOT_IDLE_WAKE_ICOUNT_OFFSET, "crucible_shmem_node_slot.idle_wake_icount offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, wake_signal) == CRUCIBLE_SHMEM_NODE_SLOT_WAKE_SIGNAL_OFFSET, "crucible_shmem_node_slot.wake_signal offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, status) == CRUCIBLE_SHMEM_NODE_SLOT_STATUS_OFFSET, "crucible_shmem_node_slot.status offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, kind) == CRUCIBLE_SHMEM_NODE_SLOT_KIND_OFFSET, "crucible_shmem_node_slot.kind offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, device_io_active) == CRUCIBLE_SHMEM_NODE_SLOT_DEVICE_IO_ACTIVE_OFFSET, "crucible_shmem_node_slot.device_io_active offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, pad0) == CRUCIBLE_SHMEM_NODE_SLOT_PAD0_OFFSET, "crucible_shmem_node_slot.pad0 offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, publish_gen) == CRUCIBLE_SHMEM_NODE_SLOT_PUBLISH_GEN_OFFSET, "crucible_shmem_node_slot.publish_gen offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, device_completion_deadline_icount) == CRUCIBLE_SHMEM_NODE_SLOT_DEVICE_COMPLETION_DEADLINE_ICOUNT_OFFSET, "crucible_shmem_node_slot.device_completion_deadline_icount offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_node_slot, reserved) == CRUCIBLE_SHMEM_NODE_SLOT_RESERVED_OFFSET, "crucible_shmem_node_slot.reserved offset");

typedef struct CRUCIBLE_SHMEM_ALIGNED(128) crucible_shmem_ring_header {
    _Atomic uint64_t read_idx;
    uint8_t pad_read[CRUCIBLE_SHMEM_RING_HEADER_PAD_READ_LEN];
    _Atomic uint64_t write_idx;
    uint8_t pad_write[CRUCIBLE_SHMEM_RING_HEADER_PAD_WRITE_LEN];
} crucible_shmem_ring_header;

CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof(crucible_shmem_ring_header) == CRUCIBLE_SHMEM_RING_HEADER_SIZE, "crucible_shmem_ring_header size");
CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof(crucible_shmem_ring_header) == CRUCIBLE_SHMEM_RING_HEADER_ALIGN, "crucible_shmem_ring_header alignment");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_ring_header, read_idx) == CRUCIBLE_SHMEM_RING_HEADER_READ_IDX_OFFSET, "crucible_shmem_ring_header.read_idx offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_ring_header, pad_read) == CRUCIBLE_SHMEM_RING_HEADER_PAD_READ_OFFSET, "crucible_shmem_ring_header.pad_read offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_ring_header, write_idx) == CRUCIBLE_SHMEM_RING_HEADER_WRITE_IDX_OFFSET, "crucible_shmem_ring_header.write_idx offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_ring_header, pad_write) == CRUCIBLE_SHMEM_RING_HEADER_PAD_WRITE_OFFSET, "crucible_shmem_ring_header.pad_write offset");

typedef struct crucible_shmem_frame_entry {
    uint64_t delivery_icount;
    uint32_t src_node;
    uint32_t seq;
    uint16_t len;
    uint8_t pad[CRUCIBLE_SHMEM_FRAME_ENTRY_PAD_LEN];
    uint8_t data[CRUCIBLE_SHMEM_MAX_FRAME_DATA];
} crucible_shmem_frame_entry;

CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof(crucible_shmem_frame_entry) == CRUCIBLE_SHMEM_FRAME_ENTRY_SIZE, "crucible_shmem_frame_entry size");
CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof(crucible_shmem_frame_entry) == CRUCIBLE_SHMEM_FRAME_ENTRY_ALIGN, "crucible_shmem_frame_entry alignment");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_frame_entry, delivery_icount) == CRUCIBLE_SHMEM_FRAME_ENTRY_DELIVERY_ICOUNT_OFFSET, "crucible_shmem_frame_entry.delivery_icount offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_frame_entry, src_node) == CRUCIBLE_SHMEM_FRAME_ENTRY_SRC_NODE_OFFSET, "crucible_shmem_frame_entry.src_node offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_frame_entry, seq) == CRUCIBLE_SHMEM_FRAME_ENTRY_SEQ_OFFSET, "crucible_shmem_frame_entry.seq offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_frame_entry, len) == CRUCIBLE_SHMEM_FRAME_ENTRY_LEN_OFFSET, "crucible_shmem_frame_entry.len offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_frame_entry, pad) == CRUCIBLE_SHMEM_FRAME_ENTRY_PAD_OFFSET, "crucible_shmem_frame_entry.pad offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_frame_entry, data) == CRUCIBLE_SHMEM_FRAME_ENTRY_DATA_OFFSET, "crucible_shmem_frame_entry.data offset");

typedef struct CRUCIBLE_SHMEM_ALIGNED(64) crucible_shmem_coverage_entry {
    uint64_t current_icount;
    uint64_t guest_pc;
    uint64_t map_index;
    uint32_t vcpu_index;
    uint32_t block_len;
    uint8_t reserved[CRUCIBLE_SHMEM_COVERAGE_ENTRY_RESERVED_LEN];
} crucible_shmem_coverage_entry;

CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof(crucible_shmem_coverage_entry) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_SIZE, "crucible_shmem_coverage_entry size");
CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof(crucible_shmem_coverage_entry) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_ALIGN, "crucible_shmem_coverage_entry alignment");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_coverage_entry, current_icount) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_CURRENT_ICOUNT_OFFSET, "crucible_shmem_coverage_entry.current_icount offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_coverage_entry, guest_pc) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_GUEST_PC_OFFSET, "crucible_shmem_coverage_entry.guest_pc offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_coverage_entry, map_index) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_MAP_INDEX_OFFSET, "crucible_shmem_coverage_entry.map_index offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_coverage_entry, vcpu_index) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_VCPU_INDEX_OFFSET, "crucible_shmem_coverage_entry.vcpu_index offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_coverage_entry, block_len) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_BLOCK_LEN_OFFSET, "crucible_shmem_coverage_entry.block_len offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_coverage_entry, reserved) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_RESERVED_OFFSET, "crucible_shmem_coverage_entry.reserved offset");

typedef struct CRUCIBLE_SHMEM_ALIGNED(128) crucible_shmem_fingerprint_sample_slot {
    _Atomic uint32_t sample_gen;
    uint32_t reserved;
    _Atomic uint64_t words[CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_WORDS];
} crucible_shmem_fingerprint_sample_slot;

CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof(crucible_shmem_fingerprint_sample_slot) == CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_SIZE, "crucible_shmem_fingerprint_sample_slot size");
CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof(crucible_shmem_fingerprint_sample_slot) == CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_ALIGN, "crucible_shmem_fingerprint_sample_slot alignment");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_fingerprint_sample_slot, sample_gen) == CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_GEN_OFFSET, "crucible_shmem_fingerprint_sample_slot.sample_gen offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_fingerprint_sample_slot, reserved) == CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_RESERVED_OFFSET, "crucible_shmem_fingerprint_sample_slot.reserved offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_fingerprint_sample_slot, words) == CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_SLOT_WORDS_OFFSET, "crucible_shmem_fingerprint_sample_slot.words offset");

typedef struct CRUCIBLE_SHMEM_ALIGNED(64) crucible_shmem_whitebox_marker_entry {
    uint64_t current_icount;
    uint32_t vcpu_index;
    uint16_t kind;
    uint16_t payload_len;
    uint8_t payload[CRUCIBLE_SHMEM_MAX_FRAME_DATA];
    uint8_t reserved[CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_RESERVED_LEN];
} crucible_shmem_whitebox_marker_entry;

CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof(crucible_shmem_whitebox_marker_entry) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_SIZE, "crucible_shmem_whitebox_marker_entry size");
CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof(crucible_shmem_whitebox_marker_entry) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_ALIGN, "crucible_shmem_whitebox_marker_entry alignment");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_whitebox_marker_entry, current_icount) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_CURRENT_ICOUNT_OFFSET, "crucible_shmem_whitebox_marker_entry.current_icount offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_whitebox_marker_entry, vcpu_index) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_VCPU_INDEX_OFFSET, "crucible_shmem_whitebox_marker_entry.vcpu_index offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_whitebox_marker_entry, kind) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_KIND_OFFSET, "crucible_shmem_whitebox_marker_entry.kind offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_whitebox_marker_entry, payload_len) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_PAYLOAD_LEN_OFFSET, "crucible_shmem_whitebox_marker_entry.payload_len offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_whitebox_marker_entry, payload) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_PAYLOAD_OFFSET, "crucible_shmem_whitebox_marker_entry.payload offset");
CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof(crucible_shmem_whitebox_marker_entry, reserved) == CRUCIBLE_SHMEM_WHITEBOX_MARKER_ENTRY_RESERVED_OFFSET, "crucible_shmem_whitebox_marker_entry.reserved offset");

#endif /* CRUCIBLE_SHMEM_ABI_H */
