# tests/vm/apm/trust_anchor.nix — Image-baked registry trust anchor
#
# End-to-end check for the PKI root of trust: a registry config and its
# trust anchor are baked under /etc/apm (exactly the files the
# `aos.apm.registries` module generates), and a fresh consumer verifies
# and syncs the registry on first contact without any manual
# `apr trust pin`. In-band rotation then pins the roster into the
# consumer's writable trusted-keys store.
#
# Runs in a headless Firecracker microVM; the test script is PID 1 and
# may write /etc directly, standing in for the composefs /etc image.
{
  testing,
  pkgs,
  aosPkg,
}: let
  fixtures = import ./fixtures.nix {inherit pkgs aosPkg;};
  nixRuntimeDeps = [
    pkgs.nix
    pkgs.brotli
    pkgs.curl
    pkgs.openssl
    pkgs.sqlite
    pkgs.boost
    pkgs.editline
    pkgs.libsodium
    pkgs.libarchive
    pkgs.gc
    pkgs.lowdown
    pkgs.bzip2
    pkgs.zlib
  ];
  anchorDeps =
    fixtures.commonDeps
    ++ nixRuntimeDeps
    ++ [
      pkgs.findutils
      pkgs.iproute2
      pkgs.python3
      pkgs.zstd
    ];
  nixLibPath = builtins.concatStringsSep ":" (map (pkg: "${pkg}/lib") nixRuntimeDeps);
in {
  trust-anchor = testing.mkVMTest {
    name = "apm-trust-anchor";
    rootfsDeps = anchorDeps;
    memory = 2048;
    testScript = ''
      ${fixtures.setupPreamble}
      export NIX_REMOTE=""
      export NIX_CONF_DIR=/tmp/nix-conf
      export LD_LIBRARY_PATH="${nixLibPath}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      mkdir -p "$NIX_CONF_DIR" /nix/var/nix/db /nix/var/nix/gcroots
      cat > "$NIX_CONF_DIR/nix.conf" << 'NIXCONF'
      experimental-features = nix-command
      sandbox = false
      NIXCONF
      nix-store --init || true
      nix-store --load-db < /aos-registration

      echo "==> Test: baked /etc/apm trust anchor verifies first contact"

      # --- Maintainer side -------------------------------------------------
      $APR keys generate initial --registry anchor-reg \
        > /tmp/anchor-keygen.out 2>&1 || {
        cat /tmp/anchor-keygen.out
        fail "apr keys generate creates maintainer key"
      }
      cat /tmp/anchor-keygen.out
      TRUST_KEY=$(grep -o 'anchor-reg:Ed25519:[A-Za-z0-9+/=]*' /tmp/anchor-keygen.out | head -1)
      KEY_PATH="$HOME/.config/apm/keys/anchor-reg-initial.key"
      assert_file_exists "$KEY_PATH" "generated private key exists"

      $APR create anchor-reg --trust-key "$TRUST_KEY" --key "$KEY_PATH"
      REG_DIR="$REG_STORAGE/anchor-reg"
      assert_file_contains "$REG_DIR/keys.toml" "$TRUST_KEY" \
        "registry roster records the anchor key"

      ANCHOR_SRC=/tmp/anchor-tool-src
      mkdir -p "$ANCHOR_SRC/bin"
      cat > "$ANCHOR_SRC/bin/anchor-tool" << 'TOOLEOF'
      #!/bin/sh
      echo "anchor-tool 1.0.0 executed"
      TOOLEOF
      chmod +x "$ANCHOR_SRC/bin/anchor-tool"
      TOOL_STORE=$(nix-store --add "$ANCHOR_SRC")

      $APR release 1.0.0 \
        --registry anchor-reg \
        --store-path "$TOOL_STORE" \
        --name anchor-tool \
        --description "Trust anchor fixture tool" \
        --license MIT \
        --maintainer anchor@example.invalid \
        --key "$KEY_PATH" \
        --cache-url http://127.0.0.1:18095 \
        --upload-url file:///tmp/anchor-cache \
        > /tmp/anchor-release.out 2>&1 || {
        cat /tmp/anchor-release.out
        fail "apr release publishes signed release"
      }

      ${pkgs.iproute2}/sbin/ip link set lo up || true
      ${pkgs.iproute2}/sbin/ip addr add 127.0.0.1/8 dev lo 2>/dev/null || true
      python3 -m http.server 18094 --bind 127.0.0.1 \
        --directory "$REG_DIR/.git" > /tmp/anchor-origin-http.log 2>&1 &
      python3 -m http.server 18095 --bind 127.0.0.1 \
        --directory /tmp/anchor-cache > /tmp/anchor-cache-http.log 2>&1 &
      for _i in 1 2 3 4 5 6 7 8 9 10; do
        if curl -sf http://127.0.0.1:18094/info/refs >/dev/null; then
          break
        fi
        sleep 1
      done
      curl -sf http://127.0.0.1:18094/info/refs >/dev/null || {
        cat /tmp/anchor-origin-http.log || true
        fail "static origin HTTP server started"
      }

      # --- Bake the anchor (what aos.apm.registries generates) -------------
      mkdir -p /etc/apm/registries.d /etc/apm/trusted-keys.d
      cat > /etc/apm/registries.d/anchor-reg.toml << CFGEOF
      # /etc/apm/registries.d/anchor-reg.toml
      # Generated by modules/base/apm-registries.nix — do not edit manually.
      [registry]
      name = "anchor-reg"
      url = "http://127.0.0.1:18094"
      priority = 50
      enabled = true

      [registry.signing]
      required = true
      public_key = "$TRUST_KEY"
      CFGEOF
      printf '%s\n' "$TRUST_KEY" > /etc/apm/trusted-keys.d/anchor-reg.pub

      # --- Consumer side: first contact, no manual trust pin ---------------
      export HOME=/tmp/anchor-consumer
      export USER=anchoruser
      mkdir -p "$HOME"

      $APM update --registry anchor-reg > /tmp/anchor-update.out 2>&1 || {
        cat /tmp/anchor-update.out
        fail "apm update verifies and syncs via the baked anchor"
      }
      cat /tmp/anchor-update.out
      pass "apm update verifies the baked registry without apr trust pin"

      assert_file_contains /tmp/anchor-update.out "anchor-reg" \
        "apm update reports the anchored registry"

      # The verified roster is pinned into the consumer's writable store.
      assert_file_exists "$HOME/.config/apm/trusted-keys.d/anchor-reg.pub" \
        "sync pins the roster into the writable trusted-keys store"
      assert_file_contains "$HOME/.config/apm/trusted-keys.d/anchor-reg.pub" \
        "$TRUST_KEY" "pinned roster contains the maintainer key"

      $APM search anchor-tool > /tmp/anchor-search.out 2>&1 || true
      cat /tmp/anchor-search.out
      assert_file_contains /tmp/anchor-search.out "anchor-tool" \
        "synced registry resolves the published package"

      check_fail
    '';
  };
}
