[package]
name = "terrane-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true

[[bin]]
name = "terrane"
path = "src/main.rs"

[dependencies]
terrane = { workspace = true, features = ["tokio", "surface-sdk"] }
clap.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
terrane-fs.workspace = true

[lints]
workspace = true
