{
  pkgs,
  lib,
  attrPath ? "checks.crucible.phase2.shmemGeneratedHeader",
  taskIds ? ["T-SHM-3"],
}: let
  crucibleSrc = import ../../pkgs/tools/crucible/_source.nix {inherit lib;};
  cargoDeps = pkgs.fetchCargoDeps {
    src = crucibleSrc;
    sourceRoot = "source/crates";
    hash = import ../../pkgs/tools/crucible/_cargo-deps-hash.nix;
  };

  shmemLib = import ./_crucible-shmem-source.nix {inherit lib;};
  headerGenerator = builtins.readFile ../../crates/crucible-shmem/src/abi_header.rs;
  generatorBin = builtins.readFile ../../crates/crucible-shmem/examples/crucible-shmem-abi-header.rs;
  generatedHeader = builtins.readFile ../../crates/crucible-shmem/include/crucible_shmem_abi.h;
  headerTest = builtins.readFile ../../crates/crucible-shmem/tests/generated_abi_header.rs;
  shmemSpec = builtins.readFile ../../docs/rfcs/0010-crucible/13-shmem-abi.md;
  defaultChecks = builtins.readFile ./default.nix;

  taskList = builtins.concatStringsSep "," taskIds;

  inherit (import ./_lib.nix {inherit lib;}) hasInfix failuresFor forbiddenFor;

  failures =
    failuresFor "crates/crucible-shmem/src/lib.rs" shmemLib [
      {
        label = "generated C header API";
        needle = "pub use abi_header::generated_c_header;";
      }
    ]
    ++ failuresFor "crates/crucible-shmem/src/abi_header.rs" headerGenerator [
      {
        label = "header generator function";
        needle = "pub fn generated_c_header() -> String";
      }
      {
        label = "region header size derived from Rust";
        needle = "REGION_HEADER_SIZE";
      }
      {
        label = "node slot offset derived from Rust";
        needle = "NODE_SLOT_CURRENT_ICOUNT_OFFSET";
      }
      {
        label = "ring header offset derived from Rust";
        needle = "RING_HEADER_WRITE_IDX_OFFSET";
      }
      {
        label = "frame entry offset derived from Rust";
        needle = "FRAME_ENTRY_DATA_OFFSET";
      }
      {
        label = "C static assertion emitter";
        needle = "CRUCIBLE_SHMEM_STATIC_ASSERT";
      }
      {
        label = "offsetof assertion emitter";
        needle = "offsetof({c_type}, {field})";
      }
    ]
    ++ failuresFor "crates/crucible-shmem/examples/crucible-shmem-abi-header.rs" generatorBin [
      {
        label = "command line header generator";
        needle = "crucible_shmem::generated_c_header()";
      }
    ]
    ++ failuresFor "crates/crucible-shmem/include/crucible_shmem_abi.h" generatedHeader [
      {
        label = "generated header warning";
        needle = "Generated by crucible-shmem. Do not edit by hand.";
      }
      {
        label = "region header declaration";
        needle = "crucible_shmem_region_header";
      }
      {
        label = "node slot declaration";
        needle = "crucible_shmem_node_slot";
      }
      {
        label = "ring header declaration";
        needle = "crucible_shmem_ring_header";
      }
      {
        label = "frame entry declaration";
        needle = "crucible_shmem_frame_entry";
      }
      {
        label = "coverage entry declaration";
        needle = "crucible_shmem_coverage_entry";
      }
      {
        label = "region header size static assert";
        needle = "sizeof(crucible_shmem_region_header) == CRUCIBLE_SHMEM_REGION_HEADER_SIZE";
      }
      {
        label = "node slot offset static assert";
        needle = "offsetof(crucible_shmem_node_slot, current_icount) == CRUCIBLE_SHMEM_NODE_SLOT_CURRENT_ICOUNT_OFFSET";
      }
      {
        label = "ring header offset static assert";
        needle = "offsetof(crucible_shmem_ring_header, write_idx) == CRUCIBLE_SHMEM_RING_HEADER_WRITE_IDX_OFFSET";
      }
      {
        label = "frame entry offset static assert";
        needle = "offsetof(crucible_shmem_frame_entry, data) == CRUCIBLE_SHMEM_FRAME_ENTRY_DATA_OFFSET";
      }
      {
        label = "coverage entry offset static assert";
        needle = "offsetof(crucible_shmem_coverage_entry, map_index) == CRUCIBLE_SHMEM_COVERAGE_ENTRY_MAP_INDEX_OFFSET";
      }
    ]
    ++ failuresFor "crates/crucible-shmem/tests/generated_abi_header.rs" headerTest [
      {
        label = "committed header include";
        needle = "include_str!(\"../include/crucible_shmem_abi.h\")";
      }
      {
        label = "byte-for-byte regeneration test";
        needle = "committed_header_matches_generated_rust_layout";
      }
      {
        label = "static assertion coverage test";
        needle = "generated_header_asserts_every_shared_struct_layout";
      }
    ]
    ++ forbiddenFor "crates/crucible-shmem/tests/generated_abi_header.rs" headerTest [
      {
        label = "ignored generated header test";
        needle = "#[ignore";
      }
      {
        label = "placeholder panic";
        needle = "implementation is pending";
      }
    ]
    ++ failuresFor "docs/rfcs/0010-crucible/13-shmem-abi.md" shmemSpec [
    ]
    ++ failuresFor "tests/crucible/default.nix" defaultChecks [
      {
        label = "phase2 exposes shmem generated header check";
        needle = "shmemGeneratedHeader = import ./phase2-shmem-generated-header.nix";
      }
    ];
in
  if failures != []
  then throw "crucible phase2 shmem generated header check failed:\n${builtins.concatStringsSep "\n" failures}"
  else
    pkgs.mkDerivation {
      pname = "crucible-phase2-shmem-generated-header";
      version = "0";
      src = crucibleSrc;

      buildDeps = [
        pkgs.coreutils
        pkgs.diffutils
        pkgs.rust
        pkgs.sed
      ];

      phases = [
        {
          name = "unpack";
          script = ''
            cp -R "$src" source
            chmod -R u+w source
            cd source
          '';
        }
        {
          name = "configure";
          script = ''
            export CARGO_HOME="$TMPDIR/cargo"
            if [ -d source ] && [ -f source/crates/Cargo.toml ]; then
              cd source
            fi
            mkdir -p "$CARGO_HOME" .cargo
            if [ -f "${cargoDeps}/.cargo/config.toml" ]; then
              sed "s|@vendor@|${cargoDeps}|g" "${cargoDeps}/.cargo/config.toml" \
                > .cargo/config.toml
            else
              printf '[source.crates-io]\nreplace-with = "vendored-sources"\n\n[source.vendored-sources]\ndirectory = "${cargoDeps}"\n\n' \
                > .cargo/config.toml
            fi
          '';
        }
        {
          name = "run-shmem-generated-header";
          script = ''
            set -eu
            if [ -d source ] && [ -f source/crates/Cargo.toml ]; then
              cd source
            fi

            cargo test \
              --frozen \
              --offline \
              --target-dir "$TMPDIR/crucible-shmem-generated-header-target" \
              --manifest-path crates/Cargo.toml \
              -p crucible-shmem \
              --test generated_abi_header \
              -- --test-threads=1

            cargo run \
              --frozen \
              --offline \
              --target-dir "$TMPDIR/crucible-shmem-generated-header-target" \
              --manifest-path crates/Cargo.toml \
              -p crucible-shmem \
              --example crucible-shmem-abi-header \
              --quiet \
              > "$TMPDIR/crucible_shmem_abi.h.regenerated"

            diff -u \
              crates/crucible-shmem/include/crucible_shmem_abi.h \
              "$TMPDIR/crucible_shmem_abi.h.regenerated"

            cat > "$TMPDIR/crucible-shmem-header-probe.c" <<'EOF'
            #include "crucible_shmem_abi.h"

            int main(void) {
              return (int)(
                sizeof(crucible_shmem_region_header) +
                sizeof(crucible_shmem_node_slot) +
                sizeof(crucible_shmem_ring_header) +
                sizeof(crucible_shmem_frame_entry) +
                sizeof(crucible_shmem_coverage_entry) +
                offsetof(crucible_shmem_frame_entry, data)
              ) == 0;
            }
            EOF
            cc -std=c11 -Wall -Wextra -Werror \
              -I crates/crucible-shmem/include \
              -c "$TMPDIR/crucible-shmem-header-probe.c" \
              -o "$TMPDIR/crucible-shmem-header-probe.o"
          '';
        }
        {
          name = "write-result";
          script = ''
            set -eu
            mkdir -p "$out"
            cp crates/crucible-shmem/include/crucible_shmem_abi.h "$out/crucible_shmem_abi.h"
            cat > "$out/result" <<'RESULT'
            PASS
            check=${attrPath}
            tasks=${taskList}
            gate=gate:abi-conformance
            generated_header=crucible_shmem_abi.h
            committed_header_diff=checked
            c_static_asserts=compiled
            RESULT
          '';
        }
      ];
    }
