//! Restricted projection of typed authorized provisioning input.
//!
//! Authorization remains entirely typed. This module owns the one filesystem
//! boundary required by Nix evaluation: it materializes the exact authorized
//! module and generated evaluator entry inside private invocation scratch,
//! evaluates the closed provisioning projection, and immediately returns its
//! validated typed plan.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use aos_storage_provisioning::{
    AuthorizedProvisioningInput, CanonicalProvisioningPlan, CanonicalProvisioningSource,
    ProvisioningIntent, ProvisioningMarkerObservation, ProvisioningMarkerState, ProvisioningPlan,
    canonicalize_provisioning_plan, validate_authorized_provisioning_input,
    validate_provisioning_intent, validate_provisioning_marker_observation,
};
use rand::RngCore as _;
use tempfile::Builder;

fn generate_marker_uuid() -> String {
    let mut bytes = [0_u8; 16];
    // This UUID is generated once while authoring the durable provisioning
    // plan and is then carried as checked input.
    #[allow(clippy::disallowed_methods)]
    rand::rng().fill_bytes(&mut bytes);
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    format!(
        "{:02x}{:02x}{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
        bytes[0],
        bytes[1],
        bytes[2],
        bytes[3],
        bytes[4],
        bytes[5],
        bytes[6],
        bytes[7],
        bytes[8],
        bytes[9],
        bytes[10],
        bytes[11],
        bytes[12],
        bytes[13],
        bytes[14],
        bytes[15],
    )
}

/// Evaluates one typed authorized input into its canonical provisioning plan.
///
/// The private scratch files created here are inputs to the restricted Nix
/// process only. They are never used as an operation result, synchronization
/// marker, or cross-provider transport.
///
/// # Errors
///
/// Returns an error when typed input validation fails, the restricted evaluator
/// fails, its output is malformed, or marker normalization rejects the plan.
pub fn evaluate_provisioning_plan(
    request: &ProvisioningIntent,
    input: &AuthorizedProvisioningInput,
    marker: &ProvisioningMarkerObservation,
    nix_instantiate: &Path,
) -> Result<CanonicalProvisioningPlan> {
    validate_provisioning_intent(request)?;
    validate_authorized_provisioning_input(input)?;

    let scratch = Builder::new()
        .prefix("aos-provisioning-plan-")
        .tempdir()
        .context("creating private provisioning evaluator scratch")?;
    let eval_root = scratch.path().join("eval");
    std::fs::create_dir(&eval_root).context("creating provisioning evaluator root")?;

    let host_module = materialize_host_module(&eval_root, input.host_module.as_deref())?;
    let entry = write_evaluator_entry(
        &eval_root,
        Path::new(&input.base_library.store_path),
        host_module.as_deref(),
    )?;
    let plan = run_restricted_evaluation(
        nix_instantiate,
        &entry,
        &eval_root,
        Path::new(&input.base_library.store_path),
        host_module.as_deref(),
    )?;
    let marker_uuid = marker_uuid_for_source(marker, input.source)?;

    canonicalize_provisioning_plan(plan, input.source, request.measured_boot, &marker_uuid)
}

fn materialize_host_module(root: &Path, module: Option<&str>) -> Result<Option<PathBuf>> {
    let Some(module) = module else {
        return Ok(None);
    };
    let path = root.join("host.nix");
    std::fs::write(&path, module.as_bytes()).context("writing private authorized host module")?;
    Ok(Some(path))
}

fn write_evaluator_entry(
    root: &Path,
    base_library: &Path,
    host_module: Option<&Path>,
) -> Result<PathBuf> {
    let operator_modules = host_module
        .map(|path| format!("[ (import {}) ]", nix_path(path)))
        .unwrap_or_else(|| "[]".to_string());
    let expression = format!(
        "# Generated by the typed storage-provisioning evaluator; do not edit.\n\
         let\n\
        \x20 baseLib = import {base};\n\
        \x20 system = baseLib.evalProvisioningConfig {{\n\
        \x20   operatorModules = {operators};\n\
        \x20 }};\n\
         in {{\n\
        \x20 schema = \"aos.provisioning-plan/v1\";\n\
        \x20 storage = system.config.aos.provisioning.storage;\n\
         }}\n",
        base = nix_path(base_library),
        operators = operator_modules,
    );
    let entry = root.join("provisioning-entry.nix");
    std::fs::write(&entry, expression).context("writing provisioning evaluator entry")?;
    Ok(entry)
}

fn run_restricted_evaluation(
    nix_instantiate: &Path,
    entry: &Path,
    eval_root: &Path,
    base_library: &Path,
    host_module: Option<&Path>,
) -> Result<ProvisioningPlan> {
    let mut command = Command::new(nix_instantiate);
    command
        .args(["--store", "dummy://", "--eval", "--strict", "--json"])
        .args(["--option", "restrict-eval", "true"])
        .args(["--option", "allow-import-from-derivation", "false"])
        .arg("-I")
        .arg(eval_root)
        .arg("-I")
        .arg(base_library);
    if let Some(host_module) = host_module {
        command.arg("-I").arg(host_module);
    }
    let output = command
        .arg(entry)
        .output()
        .context("spawning restricted provisioning evaluation")?;
    if !output.status.success() {
        bail!(
            "restricted provisioning evaluation failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    serde_json::from_slice(&output.stdout).context("parsing evaluated provisioning plan")
}

fn marker_uuid_for_source(
    marker: &ProvisioningMarkerObservation,
    source: CanonicalProvisioningSource,
) -> Result<String> {
    validate_provisioning_marker_observation(marker)?;
    match marker.state {
        ProvisioningMarkerState::Absent => Ok(generate_marker_uuid()),
        ProvisioningMarkerState::Completed => {
            let committed = marker.source.context("completed marker has no source")?;
            if committed != source {
                bail!("current storage source differs from the committed provisioning source");
            }
            marker
                .marker_uuid
                .clone()
                .context("completed marker has no UUID")
        }
        ProvisioningMarkerState::Pending => {
            bail!("pending provisioning marker requires explicit recovery")
        }
        ProvisioningMarkerState::Indeterminate => {
            bail!("provisioning marker state is indeterminate")
        }
    }
}

fn nix_path(path: &Path) -> String {
    path.to_string_lossy().replace(' ', "\\ ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn marker(
        state: ProvisioningMarkerState,
        source: Option<CanonicalProvisioningSource>,
        marker_uuid: Option<&str>,
    ) -> ProvisioningMarkerObservation {
        ProvisioningMarkerObservation {
            schema: "aos.storage.provisioning-marker-observation/v1".into(),
            state,
            source,
            marker_uuid: marker_uuid.map(str::to_string),
        }
    }

    #[test]
    fn completed_marker_must_match_the_selected_source() {
        let observed = marker(
            ProvisioningMarkerState::Completed,
            Some(CanonicalProvisioningSource::Operator),
            Some("aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee"),
        );

        assert!(marker_uuid_for_source(&observed, CanonicalProvisioningSource::Fallback).is_err());
        assert_eq!(
            marker_uuid_for_source(&observed, CanonicalProvisioningSource::Operator)
                .expect("matching committed marker"),
            "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee"
        );
    }

    #[test]
    fn unfinished_marker_states_fail_closed() {
        for state in [
            ProvisioningMarkerState::Pending,
            ProvisioningMarkerState::Indeterminate,
        ] {
            let observed = marker(state, None, None);
            assert!(
                marker_uuid_for_source(&observed, CanonicalProvisioningSource::Fallback).is_err()
            );
        }
    }
}
