//! A compact semantic qualification contract for Rust protocol tests.
//!
//! Production policy is generated by the Nix qualification module fixed point.
//! This fixture carries only synthetic identities and mandatory admission floors.

use anyhow::Result;
use aos_release::qualification::QualificationContract;
use serde_json::{Value, json};

/// Builds the smallest current qualification contract that exercises the
/// release protocol's mandatory admission semantics.
///
/// The production contract comes from the Nix module fixed point. This value
/// deliberately contains only synthetic test identities and the validation
/// floors required by [`QualificationContract::validate`].
pub fn contract() -> Result<QualificationContract> {
    let requirements = [
        ("ability-native-adapter-matrix", "staging", "release", true),
        ("ability-crucible-baseline", "staging", "release", false),
        ("ability-native-activation", "staging", "release", false),
        ("ability-native-kubernetes", "staging", "release", false),
        ("ability-native-recovery", "staging", "release", false),
        ("build-integrity", "build", "release", false),
        ("package-function", "staging", "packages", false),
        ("image-installation", "staging", "images", false),
        ("image-lifecycle", "staging", "images", false),
        ("image-update-recovery", "staging", "images", false),
        ("image-observation", "complete", "images", false),
        ("container-lifecycle", "staging", "containers", false),
        ("container-observation", "complete", "containers", false),
        ("staging-delivery", "staging", "release", false),
        ("operator-recovery", "staging", "release", false),
        ("production-recovery", "staging", "release", true),
        ("rollout-health", "rollout", "release", false),
        ("rollout-observation", "complete", "release", false),
    ]
    .into_iter()
    .map(|(id, phase, scope, production_only)| {
        let mut requirement = json!({
            "id": id,
            "phase": phase,
            "scope": scope,
            "method": "automated",
            "checks": [format!("exercise-{id}")],
            "regressions": [],
            "invalidated_by": ["subject", "policy", "executor", "environment"],
            "measurements": measurements_for(id),
        });
        if production_only && id.starts_with("ability-") {
            requirement["production_only"] = json!(true);
        }
        if id == "ability-native-adapter-matrix" {
            requirement["checks"] = json!(["native-adapter-matrix"]);
            requirement["native_operation_spec"] =
                serde_json::to_value(super::native_operation_spec())?;
        }
        Ok(requirement)
    })
    .collect::<Result<Vec<_>>>()?;

    let image_targets = [
        ("disk-x86_64-linux", "x86_64-linux", "kvm", "q35"),
        ("disk-aarch64-linux", "aarch64-linux", "tcg", "virt"),
    ];
    let container_targets = [
        ("container-x86_64-linux", "x86_64-linux"),
        ("container-aarch64-linux", "aarch64-linux"),
    ];
    let targets = image_targets
        .map(|(id, platform, accelerator, machine)| {
            image_target(id, platform, accelerator, machine)
        })
        .into_iter()
        .chain(container_targets.map(|(id, platform)| container_target(id, platform)))
        .collect::<Vec<_>>();
    let claims = image_targets
        .iter()
        .flat_map(|(id, _, _, _)| claims_for(id, "image"))
        .chain(
            container_targets
                .iter()
                .flat_map(|(id, _)| claims_for(id, "container")),
        )
        .collect::<Vec<_>>();

    Ok(serde_json::from_value(json!({
        "schema_version": "aos.release.qualification-contract/v2",
        "id": "aos-system-v2",
        "promises": ["Exercise the release protocol fixture."],
        "exclusions": ["The synthetic fixture makes no production claim."],
        "profiles": profiles(),
        "destinations": destinations(),
        "fitness": fitness(),
        "targets": targets,
        "package_rules": [{
            "name": "fixture",
            "role": "general-catalog",
            "inherit_dependency_obligations": true,
        }],
        "requirements": requirements,
        "claims": claims,
        "support": {
            "default": {
                "kind": "standard",
                "superseded_after_trains": 2,
            },
            "trains": {},
        },
    }))?)
}

fn measurements_for(requirement: &str) -> Value {
    match requirement {
        "image-installation" => json!({
            "reboot_cycles": {"minimum": 10, "maximum": null},
            "cold_boot_cycles": {"minimum": 3, "maximum": null},
        }),
        "image-update-recovery" => json!({
            "update_rollback_cycles": {"minimum": 3, "maximum": null},
        }),
        "container-lifecycle" => json!({
            "lifecycle_cycles": {"minimum": 10, "maximum": null},
        }),
        "image-observation" | "container-observation" => json!({
            "workload_operations": {"minimum": 1, "maximum": null},
            "data_integrity_failures": {"minimum": 0, "maximum": 0},
        }),
        _ => json!({}),
    }
}

fn image_target(id: &str, platform: &str, accelerator: &str, machine: &str) -> Value {
    json!({
        "id": id,
        "platform": platform,
        "kind": "image",
        "required": true,
        "environment": {
            "layers": [
                {
                    "platform": platform,
                    "backend": {"kind": "physical", "board": null, "chipset": null},
                    "cpu": empty_cpu_scope(),
                },
                {
                    "platform": platform,
                    "backend": {
                        "kind": "qemu",
                        "accelerator": accelerator,
                        "machine": machine,
                        "machine_version": null,
                        "version": null,
                        "cpu_model": null,
                    },
                    "cpu": empty_cpu_scope(),
                },
            ],
            "boot": "systemd-boot-uki",
            "security": {
                "secure_boot": true,
                "measured_boot": true,
                "verity": true,
                "encrypted_state": true,
                "persistent_firmware": true,
            },
            "resources": {"cpus": 2, "memory_mib": 8192, "disk_mib": 32768},
            "devices": [
                {
                    "stage": "initrd",
                    "driver": "virtio_blk",
                    "bus": null,
                    "vendor": null,
                    "product": null,
                    "revision": null,
                    "firmware": [],
                },
                {
                    "stage": "initrd",
                    "driver": "virtio_net",
                    "bus": null,
                    "vendor": null,
                    "product": null,
                    "revision": null,
                    "firmware": [],
                },
            ],
            "kernel_options": {"CONFIG_EFI": "y"},
        },
    })
}

fn container_target(id: &str, platform: &str) -> Value {
    let host = json!({
        "platform": "x86_64-linux",
        "backend": {"kind": "physical", "board": null, "chipset": null},
        "cpu": empty_cpu_scope(),
    });
    let container = json!({
        "platform": platform,
        "backend": {
            "kind": "container",
            "runtime": "containerd-runc",
            "version": null,
            "cgroup": null,
            "network": null,
            "volume": null,
        },
        "cpu": empty_cpu_scope(),
    });
    let layers = if platform == "aarch64-linux" {
        vec![
            host,
            json!({
                "platform": platform,
                "backend": {
                    "kind": "qemu",
                    "accelerator": "tcg",
                    "machine": "virt",
                    "machine_version": null,
                    "version": null,
                    "cpu_model": null,
                },
                "cpu": empty_cpu_scope(),
            }),
            container,
        ]
    } else {
        vec![host, container]
    };

    json!({
        "id": id,
        "platform": platform,
        "kind": "container",
        "required": true,
        "environment": {
            "layers": layers,
            "boot": "linux-container",
            "security": {
                "secure_boot": false,
                "measured_boot": false,
                "verity": false,
                "encrypted_state": false,
                "persistent_firmware": false,
            },
            "resources": {"cpus": 1, "memory_mib": 0, "disk_mib": 0},
            "devices": [],
            "kernel_options": {},
        },
    })
}

fn empty_cpu_scope() -> Value {
    json!({"vendors": [], "models": [], "skus": [], "features": []})
}

fn claims_for(target: &str, kind: &str) -> [Value; 2] {
    let mut functions = match kind {
        "image" => vec![
            "image-installation",
            "image-lifecycle",
            "image-update-recovery",
        ],
        _ => vec!["container-lifecycle"],
    };
    let functional = json!({
        "id": format!("{target}-functional"),
        "target": target,
        "requirements": functions,
        "minimum_assurance": "A2",
        "phase": "staging",
        "blocks_release": true,
    });
    functions.push(if kind == "image" {
        "image-observation"
    } else {
        "container-observation"
    });
    let qualified = json!({
        "id": format!("{target}-qualified"),
        "target": target,
        "requirements": functions,
        "minimum_assurance": "A3",
        "phase": "complete",
        "blocks_release": true,
    });

    [functional, qualified]
}

fn profiles() -> Value {
    json!(
        [
            {
                "change_scoped": false,
                "claims": "none",
                "description": "Reproducible, authorized build of the complete closure.",
                "fitness": {},
                "name": "build",
                "override": {
                    "rings": false,
                    "soak_seconds": false
                },
                "require_complete_matrix": false,
                "requirements": [
                    "build-integrity"
                ],
                "review_registry_transaction": false,
                "review_threshold": 0,
                "rollout": {
                    "rings": [
                        {
                            "observe_seconds": 0,
                            "partitions": 256
                        }
                    ]
                },
                "soak_seconds": 0
            },
            {
                "change_scoped": false,
                "claims": "functional",
                "description": "Reviewed functional qualification of every target with fresh environment fitness.",
                "fitness": {
                    "alert-delivery": {
                        "max_age_seconds": 1209600
                    },
                    "authority-recovery": {
                        "max_age_seconds": 7776000
                    },
                    "hub-restore": {
                        "max_age_seconds": 7776000
                    },
                    "storage-restore": {
                        "max_age_seconds": 1209600
                    }
                },
                "name": "functional",
                "override": {
                    "rings": false,
                    "soak_seconds": false
                },
                "require_complete_matrix": false,
                "requirements": [
                    "ability-crucible-baseline",
                    "ability-native-activation",
                    "ability-native-adapter-matrix",
                    "ability-native-kubernetes",
                    "ability-native-recovery",
                    "build-integrity",
                    "package-function",
                    "rollout-health",
                    "staging-delivery"
                ],
                "review_registry_transaction": true,
                "review_threshold": 1,
                "rollout": {
                    "rings": [
                        {
                            "observe_seconds": 0,
                            "partitions": 256
                        }
                    ]
                },
                "soak_seconds": 0
            },
            {
                "change_scoped": true,
                "claims": "functional",
                "description": "Automated exact-byte functional checks on the changed targets.",
                "fitness": {},
                "name": "smoke",
                "override": {
                    "rings": false,
                    "soak_seconds": false
                },
                "require_complete_matrix": false,
                "requirements": [
                    "ability-crucible-baseline",
                    "ability-native-activation",
                    "ability-native-adapter-matrix",
                    "ability-native-kubernetes",
                    "ability-native-recovery",
                    "build-integrity",
                    "package-function",
                    "staging-delivery"
                ],
                "review_registry_transaction": false,
                "review_threshold": 0,
                "rollout": {
                    "rings": [
                        {
                            "observe_seconds": 0,
                            "partitions": 256
                        }
                    ]
                },
                "soak_seconds": 0
            },
            {
                "change_scoped": false,
                "claims": "qualified",
                "description": "Complete-matrix qualification with a week of observation and staged rollout.",
                "fitness": {
                    "alert-delivery": {
                        "max_age_seconds": 1209600
                    },
                    "authority-recovery": {
                        "max_age_seconds": 7776000
                    },
                    "hub-restore": {
                        "max_age_seconds": 7776000
                    },
                    "key-rotation": {
                        "max_age_seconds": 7776000
                    },
                    "storage-restore": {
                        "max_age_seconds": 1209600
                    }
                },
                "name": "soak",
                "override": {
                    "rings": true,
                    "soak_seconds": true
                },
                "require_complete_matrix": true,
                "requirements": [
                    "ability-crucible-baseline",
                    "ability-native-activation",
                    "ability-native-adapter-matrix",
                    "ability-native-kubernetes",
                    "ability-native-recovery",
                    "build-integrity",
                    "package-function",
                    "rollout-health",
                    "rollout-observation",
                    "staging-delivery"
                ],
                "review_registry_transaction": true,
                "review_threshold": 1,
                "rollout": {
                    "rings": [
                        {
                            "observe_seconds": 86400,
                            "partitions": 4
                        },
                        {
                            "observe_seconds": 86400,
                            "partitions": 32
                        },
                        {
                            "observe_seconds": 172800,
                            "partitions": 128
                        },
                        {
                            "observe_seconds": 0,
                            "partitions": 256
                        }
                    ]
                },
                "soak_seconds": 604800
            }
        ]
    )
}

fn destinations() -> Value {
    json!(
        [
            {
                "after": [
                    "staging"
                ],
                "channel": "candidate",
                "profile": "functional",
                "registry_tier": "production",
                "surface": "production"
            },
            {
                "after": ["staging"],
                "channel": "edge",
                "profile": "smoke",
                "registry_tier": "production",
                "surface": "production"
            },
            {
                "after": [
                    "staging"
                ],
                "channel": "stable",
                "profile": "soak",
                "registry_tier": "production",
                "surface": "production"
            },
            {
                "after": [
                    "staging"
                ],
                "channel": "edge",
                "profile": "smoke",
                "registry_tier": "testing",
                "surface": "production"
            },
            {
                "after": [],
                "channel": "candidate",
                "profile": "build",
                "registry_tier": "production",
                "surface": "staging"
            },
            {
                "after": [],
                "channel": "edge",
                "profile": "build",
                "registry_tier": "production",
                "surface": "staging"
            },
            {
                "after": [],
                "channel": "stable",
                "profile": "build",
                "registry_tier": "production",
                "surface": "staging"
            },
            {
                "after": [],
                "channel": "edge",
                "profile": "build",
                "registry_tier": "testing",
                "surface": "staging"
            }
        ]
    )
}

fn fitness() -> Value {
    json!(
        [
            {
                "bindings": [
                    "alert-config"
                ],
                "checks": [
                    "failed-unit-alert-delivered",
                    "acknowledged-by-on-call",
                    "no-secret-material-in-alert"
                ],
                "kind": "alert-delivery",
                "method": "automated"
            },
            {
                "bindings": [
                    "signer-roster"
                ],
                "checks": [
                    "key-custody",
                    "recover-encrypted-authority-backup",
                    "test-signature-per-role-verifies"
                ],
                "kind": "authority-recovery",
                "method": "operator"
            },
            {
                "bindings": [
                    "surface",
                    "hub-schema"
                ],
                "checks": [
                    "isolated-hub-restore",
                    "portable-database-export-import",
                    "anonymous-readback-of-restored-deployment"
                ],
                "kind": "hub-restore",
                "method": "operator"
            },
            {
                "bindings": [
                    "signer-roster",
                    "surface"
                ],
                "checks": [
                    "registry-key-rotation-trust-continuity",
                    "unauthorized-replacement-rejected",
                    "interrupted-publication-single-final-state"
                ],
                "kind": "key-rotation",
                "method": "operator"
            },
            {
                "bindings": [
                    "tooling"
                ],
                "checks": [
                    "independent-encrypted-backup",
                    "restore-to-clean-environment",
                    "offline-verification-of-restored-bundle"
                ],
                "kind": "storage-restore",
                "method": "automated"
            }
        ]
    )
}
