[package]
name = "aos-sandbox-agent"
version = "0.1.0"
edition = "2024"
license.workspace = true

[[bin]]
name = "aos-sandbox-agent"
path = "src/main.rs"

[dependencies]
aos-proto = { path = "../aos-proto" }
aos-sandbox-core = { path = "../aos-sandbox-core" }
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
