[package]
name = "aos-sandbox-agent"
version = "0.1.0"
edition = "2024"
license.workspace = true

[[bin]]
name = "aos-sandbox-agent"
path = "src/main.rs"

[[bin]]
name = "aos-sandbox-exec-gate"
path = "src/bin/aos-sandbox-exec-gate.rs"

[[bin]]
name = "aos-sandbox-guest-root-builder"
path = "src/bin/aos-sandbox-guest-root-builder.rs"

[dependencies]
aos-proto = { path = "../aos-proto" }
aos-sandbox-core = { path = "../aos-sandbox-core" }
aos-sandbox-linux = { path = "../aos-sandbox-linux" }
ed25519-dalek = { workspace = true, features = ["zeroize"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
rustix = { workspace = true, features = ["fs"] }
ssh-key.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[lints]
workspace = true
