# stdenv/bootstrap/stage5-linux-headers.nix — Linux kernel headers from source
#
# Builds sanitized Linux UAPI headers. Manually installs headers needed
# by glibc 2.2.5.
#
# Builder: bash-tcc + coreutils-tcc (stage 4).
#
# Note: We cannot use `make headers_install` because kernel 4.14's
# headers_install needs perl for sanitization scripts, which is not
# available at this stage. The UAPI headers in 4.14+ are already
# separated from kernel-internal headers, so we can copy them directly
# without stripping __KERNEL__ guards.
#
{
  bash, # bash 2.05b (stage 4)
  coreutils, # coreutils-tcc (stage 4)
  gnumake, # GNU Make 3.79.1 from TCC
  buildPlatform,
  ...
}:
let
  system = buildPlatform.system;
  sources = import ./sources.nix;

  src = builtins.fetchTarball {
    url = sources.linuxHeaders.url;
    sha256 = sources.linuxHeaders.sha256;
  };
in
builtins.derivation {
  name = "linux-headers-${sources.linuxHeaders.version}";
  inherit system;
  builder = "${bash}/bin/bash";
  args = [
    "-c"
    ''
      set -eu

      export PATH="${
        builtins.concatStringsSep ":" (
          builtins.map (p: "${p}/bin") [
            bash
            coreutils
            gnumake
          ]
        )
      }"

      SRC=${src}

      # Create output directories
      mkdir $out
      mkdir $out/include

      # ── Copy ALL UAPI headers recursively ─────────────────────────────
      # We need a recursive copy function since posix-tools cp doesn't do -r
      # and coreutils-tcc is not in our deps. Use a simple bash loop.
      copy_dir() {
        local src_dir="$1" dst_dir="$2"
        mkdir -p "$dst_dir"
        for f in "$src_dir"/*; do
          local name
          name=$(basename "$f")
          if test -d "$f"; then
            copy_dir "$f" "$dst_dir/$name"
          elif test -f "$f"; then
            cp "$f" "$dst_dir/$name"
          fi
        done
      }

      # include/uapi/linux/ → include/linux/
      copy_dir $SRC/include/uapi/linux $out/include/linux

      # include/uapi/asm-generic/ → include/asm-generic/
      copy_dir $SRC/include/uapi/asm-generic $out/include/asm-generic

      # arch/x86/include/uapi/asm/ → include/asm/
      copy_dir $SRC/arch/x86/include/uapi/asm $out/include/asm

      # ── Generate version.h ────────────────────────────────────────────
      # LINUX_VERSION_CODE = (major << 16) + (minor << 8) + sublevel
      # 4.14.336: sublevel capped to 254 for 8-bit field
      {
        echo '#define LINUX_VERSION_CODE 266494'
        echo '#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))'
      } > $out/include/linux/version.h

      # ── Generate asm/unistd_32.h from syscall table ───────────────────
      # This file is normally generated by the kernel build. Generate it
      # from the syscall table using shell instead of perl/python.
      {
        echo '#ifndef _ASM_X86_UNISTD_32_H'
        echo '#define _ASM_X86_UNISTD_32_H 1'
        echo
        while read -r nr abi name entry compat; do
          case "$nr" in \#*|"") continue ;; esac
          echo "#define __NR_$name $nr"
        done < $SRC/arch/x86/entry/syscalls/syscall_32.tbl
        echo
        echo '#endif /* _ASM_X86_UNISTD_32_H */'
      } > $out/include/asm/unistd_32.h

      # ── Generate asm/unistd_64.h from syscall table ───────────────────
      {
        echo '#ifndef _ASM_X86_UNISTD_64_H'
        echo '#define _ASM_X86_UNISTD_64_H 1'
        echo
        while read -r nr abi name entry; do
          case "$nr" in \#*|"") continue ;; esac
          case "$abi" in common|64)
            echo "#define __NR_$name $nr"
            ;; esac
        done < $SRC/arch/x86/entry/syscalls/syscall_64.tbl
        echo
        echo '#endif /* _ASM_X86_UNISTD_64_H */'
      } > $out/include/asm/unistd_64.h

      # ── Create stub headers for unsanitized UAPI references ──────────
      # Normally `make headers_install` sanitizes UAPI headers to remove
      # references to kernel-internal headers. Since we can't run that
      # (no perl), provide empty stubs for the referenced non-UAPI headers.

      # linux/compiler.h — referenced by sysctl.h, swab.h, etc
      {
        echo '#ifndef _LINUX_COMPILER_H'
        echo '#define _LINUX_COMPILER_H'
        echo '/* Stub for bootstrap */'
        echo '#include <linux/compiler_types.h>'
        echo '#endif'
      } > $out/include/linux/compiler.h

      # linux/compiler_types.h — referenced by stddef.h
      {
        echo '#ifndef _LINUX_COMPILER_TYPES_H'
        echo '#define _LINUX_COMPILER_TYPES_H'
        echo '/* Stub for bootstrap */'
        echo '#ifndef __user'
        echo '#define __user'
        echo '#endif'
        echo '#ifndef __force'
        echo '#define __force'
        echo '#endif'
        echo '#ifndef __iomem'
        echo '#define __iomem'
        echo '#endif'
        echo '#ifndef __attribute_const__'
        echo '#define __attribute_const__'
        echo '#endif'
        echo '#ifndef __always_inline'
        echo '#define __always_inline inline'
        echo '#endif'
        echo '#ifndef __packed'
        echo '#define __packed __attribute__((packed))'
        echo '#endif'
        echo '#endif'
      } > $out/include/linux/compiler_types.h

      echo "Linux 4.14.336 headers installed to $out/include"
    ''
  ];
}
// {
  meta = {
    description = "Linux kernel headers for userspace, version 4.14.336";
    homepage = "https://www.kernel.org/";
    license = "GPL-2.0-only";
    build = {
      os = "linux";
      cpu = [
        "x86_64"
        "i686"
      ];
    };
    execute = {
      os = "linux";
      cpu = "i686";
    };
  };
}
