# stdenv/bootstrap/stage5-glibc.nix — glibc 2.2.5 from GCC 2.95.3
#
# First real C library in the bootstrap chain. Built by the first GCC
# (TCC-compiled), replacing Mes libc. glibc 2.2.5 is the Guix-proven
# earliest glibc version for source bootstrap.
#
# Builder: bash + stage 4 tools (sed, grep, patch, coreutils)
#
# Build approach: ./configure && make (same as Guix glibc-mesboot0).
# Two Guix-proven patches handle the bootstrap environment:
#   - glibc-boot-2.2.5.patch: Make 4.x support, stdin compilation fix,
#     MES_BOOTSTRAP guards for inline asm / bitfields / div stubs
#   - glibc-bootstrap-system-2.2.5.patch: PATH-based shell lookup
#     (no /bin/sh requirement)
#
# Static only, no threads, no TLS, no shared libs. Sufficient to
# build the self-hosted GCC 2.95.3 in stage5-gcc.nix.
#
# Reference: Guix commencement.scm glibc-mesboot0 definition
#
{
  gcc, # GCC 2.95.3 (TCC-compiled, stage 4)
  binutils, # binutils (TCC-compiled, stage 4)
  linuxHeaders, # linux headers (stage 5)
  bash, # bash 2.05b (stage 4)
  sed, # sed (stage 4)
  grep, # grep (stage 4)
  patch, # patch (stage 4)
  coreutils, # coreutils (stage 4)
  gnumake, # GNU Make (TCC-compiled, stage 4)
  gawk, # GNU awk (TCC-compiled, stage 4)
  diffutils, # diff/cmp (TCC-compiled, stage 4)
  buildPlatform,
  ...
}: let
  system = buildPlatform.system;

  sources = import ./sources.nix;

  src = builtins.fetchTarball {
    url = sources.glibc.url;
    sha256 = sources.glibc.sha256;
  };

  glibc-linuxthreads-src = builtins.fetchTarball {
    url = sources.glibc.linuxthreads.url;
    sha256 = sources.glibc.linuxthreads.sha256;
  };

  patchBootFile = ./patches/glibc-boot-2.2.5.patch;
  patchSystemFile = ./patches/glibc-bootstrap-system-2.2.5.patch;
in
  builtins.derivation {
    name = "glibc-2.2.5";
    inherit system;
    builder = "${bash}/bin/bash";
    args = [
      "-c"
      ''
        set -eu

        export PATH="${
          builtins.concatStringsSep ":" (
            builtins.map (p: "${p}/bin") [
              bash
              sed
              grep
              patch
              coreutils
              gnumake
              gawk
              diffutils
              gcc
              binutils
            ]
          )
        }"
        export CONFIG_SHELL="${bash}/bin/bash"
        export SHELL="${bash}/bin/bash"
        export MAKE="${gnumake}/bin/make"

        # ── Copy source to writable directory ─────────────────────────────
        cp -r ${src} $TMPDIR/src
        chmod -R u+w $TMPDIR/src

        SRC=$TMPDIR/src

        # ── Apply Guix bootstrap patches ───────────────────────────────────
        cd $SRC
        echo "==> Applying glibc-boot-2.2.5.patch"
        patch --force -p1 -i ${patchBootFile}
        echo "==> Applying glibc-bootstrap-system-2.2.5.patch"
        patch --force -p1 -i ${patchSystemFile}

        # ── Prevent autoconf regeneration ──────────────────────────────────
        # Touch all configure scripts to be newer than their .in files
        # so make doesn't try to regenerate them (no autoconf available)
        touch $SRC/configure
        for d in $SRC/sysdeps/*/; do
          test -f "$d/configure" && touch "$d/configure"
        done
        for d in $SRC/sysdeps/*/*/; do
          test -f "$d/configure" && touch "$d/configure"
        done
        for d in $SRC/sysdeps/*/*/*/; do
          test -f "$d/configure" && touch "$d/configure"
        done

        # ── Set up compiler environment ────────────────────────────────────
        # Guix approach: bake MES_BOOTSTRAP defines into CC/CPP so the
        # patches can conditionalize problem spots.
        CPPFLAGS=" -D MES_BOOTSTRAP=1 -D BOOTSTRAP_GLIBC=1"
        CFLAGS=" -L $SRC"
        export CPP="${gcc}/bin/gcc -E $CPPFLAGS"
        export CC="${gcc}/bin/gcc $CPPFLAGS $CFLAGS"

        # ── Configure ──────────────────────────────────────────────────────
        echo "==> Configuring glibc 2.2.5"
        ./configure \
          --disable-shared \
          --enable-static \
          --disable-sanity-checks \
          --build=i686-unknown-linux-gnu \
          --host=i686-unknown-linux-gnu \
          --with-headers=${linuxHeaders}/include \
          --enable-static-nss \
          --without-__thread \
          --without-cvs \
          --without-gd \
          --without-tls \
          --prefix=$out

        # ── Post-configure fixups ──────────────────────────────────────────
        # Fix INSTALL path (relative vs absolute) and ensure SHELL/BASH are set
        sed -i "s|INSTALL = scripts/|INSTALL = \$(..)./scripts/|" config.make
        sed -i "s|BASH = |SHELL = ${bash}/bin/bash\nBASH = |" config.make

        # ── Pre-generate abi-tag.h ───────────────────────────────────────
        # Normally generated by csu/Makefile from the abi-tags file. The
        # before-compile mechanism should ensure it's built before elf/
        # needs it, but in our bootstrap the ordering fails. Pre-generate it.
        # For i686-unknown-linux-gnu matching ".*-.*-linux.*":
        #   ABI_TAG_OS = 0, ABI_TAG_VERSION = 2,0,0
        mkdir -p $SRC/csu
        {
          echo '#define __ABI_TAG_OS 0'
          echo '#ifndef __ABI_TAG_VERSION'
          echo '# define __ABI_TAG_VERSION 2,0,0'
          echo '#endif'
        } > $SRC/csu/abi-tag.h

        # ── Fix gen-sorted.awk (gawk-tcc array indexing bug) ──────────────
        # gawk 3.0.6 compiled with TCC has broken array/counter operations,
        # causing gen-sorted.awk to produce wrong output (only "elf" subdir).
        # Replace gen-sorted.awk with a simple shell script that gawk-tcc
        # won't be involved with. The Makeconfig recipe pipes data through
        # "$(AWK) -f $<" — we replace the awk script with a shell script
        # and change AWK to CONFIG_SHELL in the recipe.
        #
        # The gen-sorted input: "depend X Y" (dep pairs) and bare subdir names.
        # We ignore deps (input order from all-subdirs already has csu first).
        {
          echo '#!/bin/sh'
          echo 'printf "sorted-subdirs ="'
          echo 'while read first rest; do'
          echo '  case "$first" in depend) ;; *) printf " %s" "$first" ;; esac'
          echo 'done'
          echo 'printf "\n"'
        } > $SRC/scripts/gen-sorted.sh
        chmod +x $SRC/scripts/gen-sorted.sh
        # Replace the awk invocation with our shell script
        sed -i 's|$(AWK) -f $<|$(CONFIG_SHELL) $(..)scripts/gen-sorted.sh|' $SRC/Makeconfig

        # ── Fix defs.awk (another gawk-tcc broken script) ───────────────
        # defs.awk processes initfini.s to extract .align value and .end*
        # directives. gawk-tcc's broken arithmetic/comparison means it
        # produces wrong output. Replace with shell script.
        {
          echo '#!/bin/sh'
          echo 'max=0'
          echo 'need_end=0'
          echo 'need_endp=0'
          echo 'while read line; do'
          echo '  case "$line" in'
          echo '    *".endp"*) need_endp=1 ;;'
          echo '    *".end"*) need_end=1 ;;'
          echo '    *".align"*)'
          echo '      val=$(echo "$line" | sed "s/.*\.align[[:space:]]*//" | sed "s/[[:space:]].*//")'
          echo '      case "$val" in [0-9]*) test "$val" -gt "$max" && max="$val" ;; esac'
          echo '      ;;'
          echo '  esac'
          echo 'done'
          echo 'if test "$need_endp" = "1"; then'
          echo '  echo "#define END_INIT .endp _init"'
          echo '  echo "#define END_FINI .endp _fini"'
          echo 'elif test "$need_end" = "1"; then'
          echo '  echo "#define END_INIT .end _init"'
          echo '  echo "#define END_FINI .end _fini"'
          echo 'else'
          echo '  echo "#define END_INIT"'
          echo '  echo "#define END_FINI"'
          echo 'fi'
          echo 'if test "$max" -gt 0 2>/dev/null; then'
          echo '  echo "#define ALIGN .align $max"'
          echo 'else'
          echo '  echo "#define ALIGN"'
          echo 'fi'
          echo 'echo "#include <libc-symbols.h>"'
          echo 'echo "weak_extern (__gmon_start__)"'
        } > $SRC/csu/defs.sh
        chmod +x $SRC/csu/defs.sh
        # Replace $(AWK) -f defs.awk with $(SHELL) defs.sh in csu/Makefile
        sed -i 's|$(AWK) -f defs.awk|$(SHELL) defs.sh|' $SRC/csu/Makefile

        # ── Pre-generate sysd-dirs (gawk-tcc string concat broken) ────────
        # The Makeconfig recipe uses inline gawk to process Subdirs files
        # from the configured sysdeps search path. Both gawk-tcc AND
        # bash-tcc's glob expansion are broken, so we hardcode the result.
        #
        # For i686-unknown-linux-gnu, the configured sysdeps search path
        # includes sysdeps/unix/inet/ and sysdeps/unix/. Their Subdirs
        # files contain:
        #   sysdeps/unix/inet/Subdirs: inet resolv hesiod sunrpc nis nscd streams
        #   sysdeps/unix/Subdirs: login
        echo "==> Pre-generating sysd-dirs"
        {
          echo "sysdep-subdirs = inet resolv hesiod sunrpc nis nscd streams login"
          echo "sysdep-inhibit-subdirs ="
          echo "sysd-dirs-done = t"
        } > $SRC/sysd-dirs
        cat $SRC/sysd-dirs

        # ── Build ──────────────────────────────────────────────────────────
        # Use -k (keep-going) because nss/getent tries to link against
        # resolv/libnss_dns.a and resolv/libresolv.a which are extra-libs
        # only built when --enable-shared. Those optional programs may fail,
        # but the static libc and startup objects are required by every
        # downstream compiler and must never be accepted as missing.
        echo "==> Building glibc 2.2.5 (static)"
        build_status=0
        $MAKE -k SHELL=${bash}/bin/bash || build_status=$?

        missing_build_artifact=0
        for artifact in libc.a csu/crt1.o csu/crti.o csu/crtn.o; do
          if ! test -f "$SRC/$artifact"; then
            echo "FATAL: required bootstrap glibc artifact was not built: $artifact" >&2
            missing_build_artifact=1
          fi
        done
        if test "$missing_build_artifact" != 0; then
          echo "FATAL: glibc make exited with status $build_status and did not produce its required compiler ABI" >&2
          exit 1
        fi

        # ── Install ────────────────────────────────────────────────────────
        echo "==> Installing glibc 2.2.5"
        install_status=0
        $MAKE -k SHELL=${bash}/bin/bash install || install_status=$?

        # A keep-going install can stop before the top-level archive/startfile
        # rules even though the required objects were built successfully.
        # Install the already-validated ABI explicitly, matching the later
        # bootstrap glibc stages.
        mkdir -p "$out/lib"
        cp "$SRC/libc.a" "$out/lib/libc.a"
        cp "$SRC/csu/crt1.o" "$SRC/csu/crti.o" "$SRC/csu/crtn.o" "$out/lib/"

        # ── Ensure gnu/stubs.h exists ──────────────────────────────────────
        # gnu/stubs.h is normally generated by `make install` stubs target.
        # With make -k, this may fail. Create an empty stub so downstream
        # consumers (GCC builds) can include <features.h> which includes it.
        mkdir -p $out/include/gnu
        if ! test -f $out/include/gnu/stubs.h; then
          echo "/* Empty stubs for bootstrap glibc */" > $out/include/gnu/stubs.h
        fi

        for artifact in libc.a crt1.o crti.o crtn.o; do
          if ! test -f "$out/lib/$artifact"; then
            echo "FATAL: required bootstrap glibc artifact was not installed: lib/$artifact" >&2
            exit 1
          fi
        done
        if ! test -f "$out/include/features.h"; then
          echo "FATAL: glibc install exited with status $install_status and did not install include/features.h" >&2
          exit 1
        fi

        echo ""
        echo "glibc 2.2.5 (bootstrap) installed to $out"
      ''
    ];
  }
  // {
    meta = {
      description = "GNU C Library 2.2.5 — bootstrap glibc built with GCC 2.95.3";
      homepage = "https://www.gnu.org/software/libc/";
      license = "LGPL-2.1-or-later";
      build = {
        os = "linux";
        cpu = [
          "x86_64"
          "i686"
        ];
      };
      execute = {
        os = "linux";
        cpu = "i686";
      };
    };
  }
