# stdenv/bootstrap/stage4-binutils220.nix — binutils 2.20.1a from TCC (Mes libc)
#
# Provides GNU as, ld, ar, nm, objcopy, objdump, ranlib, readelf, strip.
# Built with the stage 3 TCC using Mes libc. These tools are needed to
# build GCC 2.95.3, which will then build glibc.
#
# Builder: kaem (from mescc-tools, stage 1). No /bin/sh, no configure.
#
# This stage uses make382 with SHELL pointing to kaem. Make recipes in
# binutils are simple enough (single-command lines) that kaem can serve
# as make's recipe executor. We pre-generate config.h and Makefile fragments
# via builtins.toFile so no configure script is needed.
#
# Alternative: enumerate all compile commands directly. This is more verbose
# but avoids the make-SHELL question entirely. We use make because binutils
# has complex interdependencies between directories that are best expressed
# in Makefiles.
#
{
  tinycc, # Output of stage3-tinycc.nix (TCC with Mes libc)
  mescc-tools, # Output of stage1-mescc-tools.nix
  make382, # GNU Make 3.82 from TCC
  sed409, # GNU sed 4.0.9 from TCC
  grep24, # GNU grep 2.4 from TCC
  patch259, # GNU patch 2.5.9 from TCC
  system ? "x86_64-linux",
}: let
  fetchSrc = {
    name,
    url,
    hash,
  }:
    builtins.derivation {
      inherit name system;
      builder = "builtin:fetchurl";
      inherit url;
      outputHash = hash;
      outputHashMode = "flat";
      outputHashAlgo = "sha256";
      preferLocalBuild = true;
    };

  binutils-src = fetchSrc {
    name = "binutils-2.20.1a.tar.bz2";
    url = "https://mirrors.kernel.org/gnu/binutils/binutils-2.20.1a.tar.bz2";
    hash = "sha256-cdN8lkUTM8XAuEsXAWn9yxOLuyc5fcBigZBdlxfI7WQ=";
  };

  target = "i686-linux-gnu";

  # Pre-generated config.h for libiberty (minimal, no autoconf needed)
  libiberty-config-h = builtins.toFile "libiberty-config.h" ''
    #define HAVE_STDLIB_H 1
    #define HAVE_STRING_H 1
    #define HAVE_UNISTD_H 1
    #define HAVE_SYS_STAT_H 1
    #define HAVE_SYS_TYPES_H 1
    #define HAVE_FCNTL_H 1
    #define HAVE_LIMITS_H 1
    #define HAVE_ERRNO_H 1
  '';

  # Pre-generated config.h for bfd
  bfd-config-h = builtins.toFile "bfd-config.h" ''
    #define PACKAGE "bfd"
    #define PACKAGE_VERSION "2.20.1"
    #define HAVE_STDLIB_H 1
    #define HAVE_STRING_H 1
    #define HAVE_UNISTD_H 1
    #define HAVE_SYS_STAT_H 1
    #define HAVE_FCNTL_H 1
    #define HAVE_ALLOCA_H 1
    #define HAVE_ERRNO_H 1
    #define HAVE_MMAP 0
    #define HAVE_MADVISE 0
    #define HAVE_MPROTECT 0
    #define HAVE_FDOPEN 1
    #define HAVE_GETPAGESIZE 0
    #define HAVE_MKSTEMP 1
    #define HAVE_STRTOULL 1
    #define HAVE_DECL_BASENAME 0
    #define HAVE_DECL_FFS 0
    #define HAVE_DECL_STPCPY 0
    #define HAVE_DECL_STRSTR 1
    #define HAVE_DECL_SNPRINTF 1
    #define HAVE_DECL_VSNPRINTF 1
    #define HAVE_DECL_GETENV 1
    #define HAVE_DECL_MALLOC 1
    #define HAVE_DECL_REALLOC 1
    #define HAVE_DECL_FREE 1
    #define HAVE_STDINT_H 1
    #define HAVE_INTTYPES_H 1
    #define SIZEOF_LONG 4
    #define SIZEOF_LONG_LONG 8
    #define BFD_HOST_64BIT_LONG_LONG 1
    #define BFD_HOST_64_BIT long long
    #define BFD_HOST_U_64_BIT unsigned long long
    #define BFD_HOSTPTR_T unsigned long
    #define HAVE_SYS_PROCFS_H 0
    #define HAVE_SYS_PARAM_H 0
    #define TRAD_CORE 0
    #define DEBUGDIR "/usr/lib/debug"
    #define _GNU_SOURCE 1
  '';

  # Pre-generated bfd-in3.h (normally generated by configure)
  bfd-in3-h = builtins.toFile "bfd-in3.h" ''
    /* Automatically generated - do not edit */
    #define BFD_VERSION 22001
    #define BFD_VERSION_DATE 20091119
    #define BFD_VERSION_STRING "(GNU Binutils) 2.20.1"
    #define REPORT_BUGS_TO "<http://www.sourceware.org/bugzilla/>"
    #define BFD_ARCH_SIZE 32
    #define BFD_DEFAULT_TARGET_SIZE 32
    #define BFD_HOST_64BIT_LONG 0
    #define BFD_HOST_64BIT_LONG_LONG 1
    #define BFD_HOST_LONG_LONG 1
  '';

in
  builtins.derivation {
    name = "binutils-2.20.1";
    inherit system;
    builder = "/bin/sh";
    args = ["-c" ''exec ${mescc-tools}/bin/kaem --verbose --strict --file "$buildScriptPath"''];
    passAsFile = ["buildScript"];
    buildScript = ''
      set -e
      TOOLS=${mescc-tools}/bin
      CC=${tinycc}/bin/tcc
      AR=${tinycc}/bin/tcc
      MAKE=${make382}/bin/make
      SED=${sed409}/bin/sed
      GREP=${grep24}/bin/grep
      PATCH=${patch259}/bin/patch

      cd ''${TMPDIR}
      ''${TOOLS}/unbz2 --file ${binutils-src} --output ''${TMPDIR}/binutils.tar
      ''${TOOLS}/untar --file ''${TMPDIR}/binutils.tar

      SRC=''${TMPDIR}/binutils-2.20.1

      # ── Install pre-generated headers ────────────────────────────────────
      ''${TOOLS}/cp ${libiberty-config-h} ''${SRC}/libiberty/config.h
      ''${TOOLS}/cp ${bfd-config-h} ''${SRC}/bfd/config.h
      ''${TOOLS}/cp ${bfd-in3-h} ''${SRC}/bfd/bfd-in3.h

      # Create an empty config.h for other directories that expect it
      ''${TOOLS}/catm ''${SRC}/binutils/config.h
      ''${TOOLS}/catm ''${SRC}/gas/config.h
      ''${TOOLS}/catm ''${SRC}/ld/config.h
      ''${TOOLS}/catm ''${SRC}/opcodes/config.h
      ''${TOOLS}/catm ''${SRC}/intl/config.h

      # ── Fix yacc-generated files ─────────────────────────────────────────
      # Yacc-generated files declare "void *malloc(YYSIZE_T)" guarded by
      # "! defined _STDLIB_H", but Mes libc uses a different include guard,
      # so both declarations coexist and conflict. Use mescc-tools replace
      # to remove them from key files.
      ''${TOOLS}/replace --file ''${SRC}/gas/itbl-parse.c --output ''${SRC}/gas/itbl-parse.c --match-on "void *malloc (YYSIZE_T);" --replace-with "/* malloc decl removed */"
      ''${TOOLS}/replace --file ''${SRC}/ld/ldgram.c --output ''${SRC}/ld/ldgram.c --match-on "void *malloc (YYSIZE_T);" --replace-with "/* malloc decl removed */"

      # ── Create output directories ────────────────────────────────────────
      ''${TOOLS}/mkdir ''${out}
      ''${TOOLS}/mkdir ''${out}/bin
      ''${TOOLS}/mkdir ''${out}/lib
      ''${TOOLS}/mkdir ''${out}/include

      # ══════════════════════════════════════════════════════════════════════
      # MANUAL BUILD: libiberty
      # ══════════════════════════════════════════════════════════════════════
      cd ''${SRC}/libiberty
      echo "==> Building libiberty"

      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include alloca.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include argv.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include concat.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include cp-demangle.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include cplus-dem.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include dyn-string.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include filename_cmp.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include fibheap.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include fopen_unlocked.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include getopt.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include getopt1.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include getpwd.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include getruntime.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include hashtab.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include hex.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include lbasename.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include lrealpath.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include make-relative-prefix.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include make-temp-file.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include md5.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include objalloc.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include obstack.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include partition.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include pex-unix.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include physmem.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include safe-ctype.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include sort.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include spaces.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include splay-tree.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include strerror.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include strsignal.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include unlink-if-ordinary.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include xatexit.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include xexit.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include xmalloc.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include xmemdup.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include xstrdup.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include xstrerror.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include xstrndup.c

      ''${AR} -ar cr libiberty.a alloca.o argv.o concat.o cp-demangle.o cplus-dem.o dyn-string.o filename_cmp.o fibheap.o fopen_unlocked.o getopt.o getopt1.o getpwd.o getruntime.o hashtab.o hex.o lbasename.o lrealpath.o make-relative-prefix.o make-temp-file.o md5.o objalloc.o obstack.o partition.o pex-unix.o physmem.o safe-ctype.o sort.o spaces.o splay-tree.o strerror.o strsignal.o unlink-if-ordinary.o xatexit.o xexit.o xmalloc.o xmemdup.o xstrdup.o xstrerror.o xstrndup.o

      echo "==> libiberty.a built"

      # ══════════════════════════════════════════════════════════════════════
      # MANUAL BUILD: opcodes
      # ══════════════════════════════════════════════════════════════════════
      cd ''${SRC}/opcodes
      echo "==> Building opcodes"

      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd dis-buf.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd dis-init.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd disassemble.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd i386-dis.c
      ''${CC} -c -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd i386-opc.c

      ''${AR} -ar cr libopcodes.a dis-buf.o dis-init.o disassemble.o i386-dis.o i386-opc.o

      echo "==> libopcodes.a built"

      # ══════════════════════════════════════════════════════════════════════
      # MANUAL BUILD: bfd
      # ══════════════════════════════════════════════════════════════════════
      cd ''${SRC}/bfd
      echo "==> Building bfd"

      # bfd needs some generated headers. Create minimal versions.
      ''${TOOLS}/catm ''${SRC}/bfd/targmatch.h
      ''${TOOLS}/catm ''${SRC}/bfd/elf32-target.h
      ''${TOOLS}/catm ''${SRC}/bfd/elf64-target.h

      BFDI="-D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -DDEFAULT_VECTOR=bfd_elf32_i386_vec -DSELECT_VECS=&bfd_elf32_i386_vec -DSELECT_ARCHITECTURES=&bfd_i386_arch -DHAVE_bfd_elf32_i386_vec"

      ''${CC} -c ''${BFDI} archive.c
      ''${CC} -c ''${BFDI} archures.c
      ''${CC} -c ''${BFDI} bfd.c
      ''${CC} -c ''${BFDI} bfdio.c
      ''${CC} -c ''${BFDI} cache.c
      ''${CC} -c ''${BFDI} coffgen.c
      ''${CC} -c ''${BFDI} corefile.c
      ''${CC} -c ''${BFDI} elf.c
      ''${CC} -c ''${BFDI} elf32.c
      ''${CC} -c ''${BFDI} elf32-i386.c
      ''${CC} -c ''${BFDI} elflink.c
      ''${CC} -c ''${BFDI} elf-strtab.c
      ''${CC} -c ''${BFDI} format.c
      ''${CC} -c ''${BFDI} hash.c
      ''${CC} -c ''${BFDI} ihex.c
      ''${CC} -c ''${BFDI} init.c
      ''${CC} -c ''${BFDI} libbfd.c
      ''${CC} -c ''${BFDI} linker.c
      ''${CC} -c ''${BFDI} merge.c
      ''${CC} -c ''${BFDI} opncls.c
      ''${CC} -c ''${BFDI} reloc.c
      ''${CC} -c ''${BFDI} section.c
      ''${CC} -c ''${BFDI} srec.c
      ''${CC} -c ''${BFDI} stab-syms.c
      ''${CC} -c ''${BFDI} stabs.c
      ''${CC} -c ''${BFDI} syms.c
      ''${CC} -c ''${BFDI} targets.c
      ''${CC} -c ''${BFDI} binary.c
      ''${CC} -c ''${BFDI} tekhex.c
      ''${CC} -c ''${BFDI} verilog.c
      ''${CC} -c ''${BFDI} dwarf1.c
      ''${CC} -c ''${BFDI} dwarf2.c
      ''${CC} -c ''${BFDI} elf-attrs.c
      ''${CC} -c ''${BFDI} elf-eh-frame.c
      ''${CC} -c ''${BFDI} elf-vxworks.c

      ''${AR} -ar cr libbfd.a archive.o archures.o bfd.o bfdio.o cache.o coffgen.o corefile.o elf.o elf32.o elf32-i386.o elflink.o elf-strtab.o format.o hash.o ihex.o init.o libbfd.o linker.o merge.o opncls.o reloc.o section.o srec.o stab-syms.o stabs.o syms.o targets.o binary.o tekhex.o verilog.o dwarf1.o dwarf2.o elf-attrs.o elf-eh-frame.o elf-vxworks.o

      echo "==> libbfd.a built"

      # ══════════════════════════════════════════════════════════════════════
      # MANUAL BUILD: gas (GNU assembler)
      # ══════════════════════════════════════════════════════════════════════
      cd ''${SRC}/gas
      echo "==> Building gas"

      GASI="-D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd -DTARGET_ALIAS=\"${target}\" -DTARGET_CANONICAL=\"${target}\" -DTARGET_CPU=\"i386\" -DDEFAULT_ARCH=\"i386\" -DTARGET_OS=\"linux-gnu\" -DPACKAGE=\"gas\" -DVERSION=\"2.20.1\" -DTARGET_BYTES_BIG_ENDIAN=0 -DTE_LINUX -DOC_ELF -Delf_symbol_type=Elf_Internal_Sym -DBFD_ASSEMBLER"

      ''${CC} -c ''${GASI} app.c
      ''${CC} -c ''${GASI} as.c
      ''${CC} -c ''${GASI} atof-generic.c
      ''${CC} -c ''${GASI} cond.c
      ''${CC} -c ''${GASI} depend.c
      ''${CC} -c ''${GASI} dwarf2dbg.c
      ''${CC} -c ''${GASI} ecoff.c
      ''${CC} -c ''${GASI} ehopt.c
      ''${CC} -c ''${GASI} expr.c
      ''${CC} -c ''${GASI} flonum-copy.c
      ''${CC} -c ''${GASI} flonum-konst.c
      ''${CC} -c ''${GASI} flonum-mult.c
      ''${CC} -c ''${GASI} frags.c
      ''${CC} -c ''${GASI} hash.c
      ''${CC} -c ''${GASI} input-file.c
      ''${CC} -c ''${GASI} input-scrub.c
      ''${CC} -c ''${GASI} listing.c
      ''${CC} -c ''${GASI} literal.c
      ''${CC} -c ''${GASI} macro.c
      ''${CC} -c ''${GASI} messages.c
      ''${CC} -c ''${GASI} output-file.c
      ''${CC} -c ''${GASI} read.c
      ''${CC} -c ''${GASI} remap.c
      ''${CC} -c ''${GASI} sb.c
      ''${CC} -c ''${GASI} stabs.c
      ''${CC} -c ''${GASI} subsegs.c
      ''${CC} -c ''${GASI} symbols.c
      ''${CC} -c ''${GASI} write.c
      ''${CC} -c ''${GASI} config/tc-i386.c
      ''${CC} -c ''${GASI} config/obj-elf.c
      ''${CC} -c ''${GASI} config/atof-ieee.c
      ''${CC} -c ''${GASI} itbl-ops.c

      ''${CC} -static -o ''${out}/bin/as app.o as.o atof-generic.o cond.o depend.o dwarf2dbg.o ecoff.o ehopt.o expr.o flonum-copy.o flonum-konst.o flonum-mult.o frags.o hash.o input-file.o input-scrub.o listing.o literal.o macro.o messages.o output-file.o read.o remap.o sb.o stabs.o subsegs.o symbols.o write.o tc-i386.o obj-elf.o atof-ieee.o itbl-ops.o ''${SRC}/bfd/libbfd.a ''${SRC}/opcodes/libopcodes.a ''${SRC}/libiberty/libiberty.a

      echo "==> as (GNU assembler) built"

      # ══════════════════════════════════════════════════════════════════════
      # MANUAL BUILD: ld (GNU linker)
      # ══════════════════════════════════════════════════════════════════════
      cd ''${SRC}/ld
      echo "==> Building ld"

      LDI="-D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd -DDEFAULT_EMULATION=\"elf_i386\" -DSCRIPTDIR=\"${target}\" -DTARGET=\"${target}\" -DBINDIR=\"''${out}/bin\" -DTOOLBINDIR=\"''${out}/bin\" -DPACKAGE=\"ld\" -DVERSION=\"2.20.1\""

      ''${CC} -c ''${LDI} ldgram.c
      ''${CC} -c ''${LDI} ldlex.c
      ''${CC} -c ''${LDI} ldmain.c
      ''${CC} -c ''${LDI} ldmisc.c
      ''${CC} -c ''${LDI} ldver.c
      ''${CC} -c ''${LDI} ldwrite.c
      ''${CC} -c ''${LDI} ldexp.c
      ''${CC} -c ''${LDI} ldemul.c
      ''${CC} -c ''${LDI} ldlang.c
      ''${CC} -c ''${LDI} ldfile.c
      ''${CC} -c ''${LDI} ldctor.c
      ''${CC} -c ''${LDI} ldcref.c
      ''${CC} -c ''${LDI} ldindr.c
      ''${CC} -c ''${LDI} emultempl/eelf_i386.c
      ''${CC} -c ''${LDI} lexsup.c

      ''${CC} -static -o ''${out}/bin/ld ldgram.o ldlex.o ldmain.o ldmisc.o ldver.o ldwrite.o ldexp.o ldemul.o ldlang.o ldfile.o ldctor.o ldcref.o ldindr.o eelf_i386.o lexsup.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a

      echo "==> ld (GNU linker) built"

      # ══════════════════════════════════════════════════════════════════════
      # MANUAL BUILD: binutils (ar, nm, objcopy, objdump, ranlib, readelf, strip)
      # ══════════════════════════════════════════════════════════════════════
      cd ''${SRC}/binutils
      echo "==> Building binutils"

      BUTI="-D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I../include -I../bfd -DPACKAGE=\"binutils\" -DVERSION=\"2.20.1\" -DTARGET=\"${target}\""

      # ar
      ''${CC} -c ''${BUTI} arparse.c
      ''${CC} -c ''${BUTI} arlex.c
      ''${CC} -c ''${BUTI} ar.c
      ''${CC} -c ''${BUTI} not-ranlib.c
      ''${CC} -c ''${BUTI} arsup.c
      ''${CC} -c ''${BUTI} rename.c
      ''${CC} -c ''${BUTI} is-ranlib.c
      ''${CC} -c ''${BUTI} binemul.c
      ''${CC} -c ''${BUTI} emul_vanilla.c
      ''${CC} -c ''${BUTI} bucomm.c
      ''${CC} -c ''${BUTI} version.c
      ''${CC} -c ''${BUTI} filemode.c

      ''${CC} -static -o ''${out}/bin/ar ar.o arparse.o arlex.o arsup.o rename.o not-ranlib.o binemul.o emul_vanilla.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a

      # ranlib (ar with is-ranlib.o instead of not-ranlib.o)
      ''${CC} -static -o ''${out}/bin/ranlib ar.o arparse.o arlex.o arsup.o rename.o is-ranlib.o binemul.o emul_vanilla.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a

      # nm
      ''${CC} -c ''${BUTI} nm.c
      ''${CC} -static -o ''${out}/bin/nm nm.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a

      # objcopy / strip
      ''${CC} -c ''${BUTI} objcopy.c
      ''${CC} -c ''${BUTI} not-strip.c
      ''${CC} -c ''${BUTI} is-strip.c
      ''${CC} -c ''${BUTI} wrstabs.c

      ''${CC} -static -o ''${out}/bin/objcopy objcopy.o not-strip.o wrstabs.o rename.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a
      ''${CC} -static -o ''${out}/bin/strip objcopy.o is-strip.o wrstabs.o rename.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a

      # objdump
      ''${CC} -c ''${BUTI} -I../opcodes objdump.c
      ''${CC} -c ''${BUTI} dwarf.c
      ''${CC} -c ''${BUTI} prdbg.c
      ''${CC} -c ''${BUTI} debug.c
      ''${CC} -c ''${BUTI} stabs.c
      ''${CC} -c ''${BUTI} rddbg.c
      ''${CC} -c ''${BUTI} rdcoff.c

      ''${CC} -static -o ''${out}/bin/objdump objdump.o dwarf.o prdbg.o debug.o stabs.o rddbg.o rdcoff.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/opcodes/libopcodes.a ''${SRC}/libiberty/libiberty.a

      # readelf (standalone, does not use bfd)
      ''${CC} -c ''${BUTI} readelf.c
      ''${CC} -c ''${BUTI} unwind-ia64.c
      ''${CC} -static -o ''${out}/bin/readelf readelf.o unwind-ia64.o version.o filemode.o ''${SRC}/libiberty/libiberty.a

      # size
      ''${CC} -c ''${BUTI} size.c
      ''${CC} -static -o ''${out}/bin/size size.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a

      # strings
      ''${CC} -c ''${BUTI} strings.c
      ''${CC} -static -o ''${out}/bin/strings strings.o bucomm.o version.o filemode.o ''${SRC}/bfd/libbfd.a ''${SRC}/libiberty/libiberty.a

      echo "==> binutils tools built"

      # ── Create triplet symlinks ──────────────────────────────────────────
      # Install convenience library + headers
      ''${TOOLS}/cp ''${SRC}/bfd/libbfd.a ''${out}/lib/libbfd.a
      ''${TOOLS}/cp ''${SRC}/opcodes/libopcodes.a ''${out}/lib/libopcodes.a
      ''${TOOLS}/cp ''${SRC}/libiberty/libiberty.a ''${out}/lib/libiberty.a

      # Copy necessary headers
      ''${TOOLS}/cp ''${SRC}/include/ansidecl.h ''${out}/include/ansidecl.h
      ''${TOOLS}/cp ''${SRC}/include/symcat.h ''${out}/include/symcat.h
      ''${TOOLS}/cp ''${SRC}/include/bfdlink.h ''${out}/include/bfdlink.h
      ''${TOOLS}/cp ''${SRC}/bfd/bfd.h ''${out}/include/bfd.h

      echo "binutils 2.20.1 installed to ''${out}"
    '';
  }
  // {
    meta = {
      description = "GNU tools for manipulating binaries (linker, assembler, etc.), version 2.20.1a";
      homepage = "https://www.gnu.org/software/binutils/";
      license = "GPL-3.0-or-later";
      platforms = ["i686-linux"];
    };
  }
