//! Linux userfaultfd registration and fault-resolution operations.
//!
//! All requests use the deployed kernel's negotiated feature/ioctl masks.
//! None of these operations establishes QEMU writer or physical-borrow
//! exclusion: that authority belongs to the native accessor/lifecycle owner.

use std::fs::OpenOptions;
use std::io;
use std::mem::{ManuallyDrop, size_of};
use std::os::fd::{AsRawFd, FromRawFd, OwnedFd};
use std::sync::atomic::{AtomicBool, Ordering};

use super::PAGE_BYTES;

const API: u64 = 0xaa;
const FEATURE_WP: u64 = 1;
const FEATURE_THREAD_ID: u64 = 1 << 8;
const REQUIRED_FEATURES: u64 = FEATURE_WP | FEATURE_THREAD_ID;
const REGISTER_MISSING: u64 = 1;
const REGISTER_WP: u64 = 2;
const COPY_DONTWAKE: u64 = 1;
const COPY_WP: u64 = 2;
const WRITEPROTECT_WP: u64 = 1;
const WRITEPROTECT_DONTWAKE: u64 = 2;
const IOCTL_COPY: u8 = 3;
const IOCTL_WAKE: u8 = 2;
const IOCTL_WRITEPROTECT: u8 = 6;

const fn ioctl_number(direction: u64, number: u8, bytes: usize) -> libc::c_ulong {
    ((direction << 30) | ((bytes as u64) << 16) | (API << 8) | number as u64) as libc::c_ulong
}

#[repr(C)]
#[derive(Default)]
struct Api {
    api: u64,
    features: u64,
    ioctls: u64,
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
struct Range {
    start: u64,
    len: u64,
}

#[repr(C)]
#[derive(Default)]
struct Register {
    range: Range,
    mode: u64,
    ioctls: u64,
}

#[repr(C)]
#[derive(Default)]
struct Copy {
    dst: u64,
    src: u64,
    len: u64,
    mode: u64,
    copied: i64,
}

#[repr(C)]
#[derive(Default)]
struct WriteProtect {
    range: Range,
    mode: u64,
}

/// One fault generated by the registered guest mapping.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct FaultEvent {
    /// The faulting guest mapping's host virtual address.
    pub(crate) address: u64,
    /// The Linux thread ID supplied by the kernel.
    pub(crate) thread_id: u32,
    /// Whether the faulting instruction attempts a write.
    pub(crate) write: bool,
    /// Whether this is a synchronous write-protection fault.
    pub(crate) write_protected: bool,
}

/// Retained kernel authority for one QEMU address space.
#[derive(Debug)]
pub(crate) struct Registration {
    descriptor: ManuallyDrop<OwnedFd>,
    retain_authority: AtomicBool,
    negotiated_features: u64,
    effective_uid: u32,
    effective_gid: u32,
}

impl Registration {
    /// Identifies this process-private descriptor for a checked fork custody plan.
    pub(crate) fn raw_descriptor(&self) -> std::os::fd::RawFd {
        self.descriptor.as_raw_fd()
    }

    /// Returns the feature mask reported by the successful kernel negotiation.
    pub(crate) fn negotiated_features(&self) -> u64 {
        self.negotiated_features
    }

    /// Returns the process credentials and capabilities observed at negotiation.
    pub(crate) fn kernel_probe(&self) -> crucible_protocol::ram_control::RamControlKernelProbe {
        crucible_protocol::ram_control::RamControlKernelProbe {
            effective_uid: self.effective_uid,
            effective_gid: self.effective_gid,
            features: self.negotiated_features(),
            mode: crucible_protocol::ram_control::RamControlKernelProbeMode::FullKernel,
        }
    }

    /// Opens and negotiates a kernel-fault-capable userfaultfd.
    ///
    /// # Errors
    /// Returns permission, unsupported-feature, or kernel API errors. It never
    /// silently substitutes UFFD_USER_MODE_ONLY or a weaker registration mode.
    pub(crate) fn open() -> io::Result<Self> {
        if !cfg!(any(target_arch = "x86_64", target_arch = "aarch64")) {
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "unqualified host ioctl architecture",
            ));
        }
        // SAFETY: sysconf takes a scalar query and does not access guest RAM.
        if unsafe { libc::sysconf(libc::_SC_PAGESIZE) } != PAGE_BYTES as libc::c_long {
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "paging requires a qualified 4096-byte host page",
            ));
        }
        let flags = libc::O_CLOEXEC | libc::O_NONBLOCK;
        // SAFETY: userfaultfd takes scalar flags and returns an owned descriptor.
        let mut descriptor = unsafe { libc::syscall(libc::SYS_userfaultfd, flags) };
        if descriptor < 0 {
            let syscall_error = io::Error::last_os_error();
            if !matches!(
                syscall_error.raw_os_error(),
                Some(libc::EPERM | libc::EACCES | libc::ENOSYS)
            ) {
                return Err(syscall_error);
            }
            // Device permissions grant precisely this facility without requiring
            // the syscall's broader capability or global sysctl permission.
            let device = OpenOptions::new().read(true).write(true).open("/dev/userfaultfd")
                .map_err(|error| io::Error::new(error.kind(), format!(
                    "kernel-fault-capable userfaultfd unavailable: syscall {syscall_error}; device {error}",
                )))?;
            // SAFETY: USERFAULTFD_IOC_NEW takes scalar flags and returns a new
            // owned descriptor; the device descriptor remains open for the call.
            descriptor = unsafe {
                libc::ioctl(
                    device.as_raw_fd(),
                    0xaa00,
                    libc::O_CLOEXEC | libc::O_NONBLOCK,
                )
            } as libc::c_long;
            if descriptor < 0 {
                return Err(io::Error::last_os_error());
            }
        }
        let descriptor = i32::try_from(descriptor)
            .map_err(|_| io::Error::other("userfaultfd descriptor exceeds i32"))?;
        // SAFETY: the successful syscall returned a new uniquely owned fd.
        let descriptor = unsafe { OwnedFd::from_raw_fd(descriptor) };
        // SAFETY: credential queries take no arguments and access no guest memory.
        let effective_uid = unsafe { libc::geteuid() };
        // SAFETY: credential queries take no arguments and access no guest memory.
        let effective_gid = unsafe { libc::getegid() };
        let mut registration = Self {
            descriptor: ManuallyDrop::new(descriptor),
            retain_authority: AtomicBool::new(false),
            negotiated_features: 0,
            effective_uid,
            effective_gid,
        };
        let mut api = Api {
            api: API,
            features: REQUIRED_FEATURES,
            ioctls: 0,
        };
        registration.command(ioctl_number(3, 0x3f, size_of::<Api>()), &mut api)?;
        if api.api != API || api.features & REQUIRED_FEATURES != REQUIRED_FEATURES {
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "kernel lacks synchronous WP or fault thread identity",
            ));
        }
        registration.negotiated_features = api.features;
        // EVENT_FORK is deliberately absent: fork first drains this worker,
        // and the child lifecycle hook creates fresh registration before RAM
        // access. A stopped reader cannot acknowledge a synchronous fork event.
        Ok(registration)
    }

    fn command<T>(&self, number: libc::c_ulong, value: &mut T) -> io::Result<()> {
        // SAFETY: callers pair each Linux ioctl number with its repr(C) ABI
        // structure; the mutable reference is valid for the synchronous call.
        if unsafe { libc::ioctl(self.descriptor.as_raw_fd(), number, value) } < 0 {
            return Err(io::Error::last_os_error());
        }
        Ok(())
    }

    /// Retains the final descriptor even if service ownership is unexpectedly lost.
    ///
    /// The mapping owner calls this before its first destructive discard. A
    /// worker panic or engine drop then leaks registration until process exit,
    /// keeping missing guest accesses blocked rather than resolving them to zeros.
    pub(crate) fn retain_until_process_exit(&self) {
        self.retain_authority.store(true, Ordering::Release);
    }

    /// Registers a stable anonymous guest RAM mapping for missing and WP faults.
    ///
    /// # Safety
    /// The caller must retain this mapping and this registration until every
    /// missing page has been restored under native accessor exclusion or QEMU
    /// has completely terminated. No competing registration may own the range.
    ///
    /// # Errors
    /// Returns alignment, mapping capability, or kernel registration errors.
    pub(crate) unsafe fn register(&self, address: u64, length: u64) -> io::Result<()> {
        let range = checked_range(address, length)?;
        let mut request = Register {
            range,
            mode: REGISTER_MISSING | REGISTER_WP,
            ioctls: 0,
        };
        self.command(ioctl_number(3, 0, size_of::<Register>()), &mut request)?;
        let needed = (1 << IOCTL_COPY) | (1 << IOCTL_WAKE) | (1 << IOCTL_WRITEPROTECT);
        if request.ioctls & needed != needed {
            // No contents have been removed yet, so undoing this failed
            // admission cannot expose cold pages or substitute zero contents.
            self.command(ioctl_number(2, 1, size_of::<Range>()), &mut request.range)?;
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "mapping lacks required COPY/WAKE/WRITEPROTECT operations",
            ));
        }
        Ok(())
    }

    /// Obtains one kernel event without blocking the independent service loop.
    ///
    /// # Errors
    /// Returns malformed/unknown events or descriptor errors. Unexpected events
    /// fail the operational service rather than reinterpret missing RAM bytes.
    pub(crate) fn read_fault(&self) -> io::Result<Option<FaultEvent>> {
        let mut message = [0_u8; 32];
        // SAFETY: message is a writable buffer of the Linux uffd_msg ABI size.
        let count = unsafe {
            libc::read(
                self.descriptor.as_raw_fd(),
                message.as_mut_ptr().cast(),
                message.len(),
            )
        };
        if count < 0 {
            let error = io::Error::last_os_error();
            if matches!(
                error.kind(),
                io::ErrorKind::WouldBlock | io::ErrorKind::Interrupted
            ) {
                return Ok(None);
            }
            return Err(error);
        }
        if count != message.len() as isize || message[0] != 0x12 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "unexpected userfaultfd event",
            ));
        }
        let flags = u64::from_ne_bytes(
            message[8..16]
                .try_into()
                .map_err(|_| io::Error::other("invalid fixed-size fault flags"))?,
        );
        if flags & !3 != 0 {
            return Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "unsupported fault flags",
            ));
        }
        Ok(Some(FaultEvent {
            address: u64::from_ne_bytes(
                message[16..24]
                    .try_into()
                    .map_err(|_| io::Error::other("invalid fixed-size fault address"))?,
            ),
            thread_id: u32::from_ne_bytes(
                message[24..28]
                    .try_into()
                    .map_err(|_| io::Error::other("invalid fixed-size fault thread"))?,
            ),
            write: flags & 1 != 0,
            write_protected: flags & 2 != 0,
        }))
    }

    /// Installs verified bytes without waking the guest accessor.
    ///
    /// # Errors
    /// Returns a kernel error or a partial-copy refusal. The owner must preserve
    /// registration and contain QEMU if it cannot complete fault resolution.
    pub(crate) fn populate(&self, address: u64, bytes: &[u8; PAGE_BYTES]) -> io::Result<()> {
        checked_range(address, PAGE_BYTES as u64)?;
        let mut copy = Copy {
            dst: address,
            src: bytes.as_ptr() as u64,
            len: PAGE_BYTES as u64,
            mode: COPY_DONTWAKE | COPY_WP,
            copied: 0,
        };
        self.command(ioctl_number(3, IOCTL_COPY, size_of::<Copy>()), &mut copy)?;
        if copy.copied != PAGE_BYTES as i64 {
            return Err(io::Error::other(
                "userfaultfd did not install a complete page",
            ));
        }
        Ok(())
    }

    /// Changes synchronous page write protection without waking blocked writers.
    ///
    /// # Errors
    /// Returns invalid ranges or a kernel write-protection failure.
    pub(crate) fn protect(&self, address: u64, length: u64, enabled: bool) -> io::Result<()> {
        let mut request = WriteProtect {
            range: checked_range(address, length)?,
            // DONTWAKE is valid only when removing write protection. Kernel
            // enablement rejects WP|DONTWAKE rather than silently accepting it.
            mode: if enabled {
                WRITEPROTECT_WP
            } else {
                WRITEPROTECT_DONTWAKE
            },
        };
        self.command(
            ioctl_number(3, IOCTL_WRITEPROTECT, size_of::<WriteProtect>()),
            &mut request,
        )
    }

    /// Wakes accessors only after all metadata/content changes are committed.
    ///
    /// # Errors
    /// Returns invalid ranges or a kernel wake failure.
    pub(crate) fn wake(&self, address: u64) -> io::Result<()> {
        let mut range = checked_range(address, PAGE_BYTES as u64)?;
        self.command(ioctl_number(2, IOCTL_WAKE, size_of::<Range>()), &mut range)
    }

    /// Waits for descriptor readability with a bounded operational timeout.
    ///
    /// # Errors
    /// Returns descriptor failure, hangup, or a poll syscall error.
    pub(crate) fn wait(&self, timeout_ms: i32) -> io::Result<()> {
        let mut descriptor = libc::pollfd {
            fd: self.descriptor.as_raw_fd(),
            events: libc::POLLIN,
            revents: 0,
        };
        // SAFETY: poll receives one valid mutable pollfd structure.
        let result = unsafe { libc::poll(&mut descriptor, 1, timeout_ms) };
        if result < 0 {
            let error = io::Error::last_os_error();
            if error.kind() != io::ErrorKind::Interrupted {
                return Err(error);
            }
        }
        if descriptor.revents & (libc::POLLERR | libc::POLLHUP | libc::POLLNVAL) != 0 {
            return Err(io::Error::other("userfaultfd service descriptor failed"));
        }
        Ok(())
    }
}

impl Drop for Registration {
    fn drop(&mut self) {
        if !self.retain_authority.load(Ordering::Acquire) {
            // SAFETY: this is the unique descriptor owner and no destructive
            // mapping transition remains admitted when retention is disabled.
            unsafe { ManuallyDrop::drop(&mut self.descriptor) };
        }
    }
}

fn checked_range(address: u64, length: u64) -> io::Result<Range> {
    if length == 0
        || !address.is_multiple_of(PAGE_BYTES as u64)
        || !length.is_multiple_of(PAGE_BYTES as u64)
        || address.checked_add(length).is_none()
    {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "invalid guest paging range",
        ));
    }
    Ok(Range {
        start: address,
        len: length,
    })
}
