##! modules/tests/boot.nix — Core boot verification checks
##!
##! Verifies provider-neutral activation, filesystem, and system identity
##! behavior. The selected manager contributes its own runtime checks.
{
  config,
  lib,
  ...
}: {
  system.checks.system-boot = {
    description = "Core system boot verification";
    checks = [
      {
        name = "configuration-activation";
        description = "the native host configuration lower is active";
        script = ''
          import re
          import shlex

          vm.wait_until_succeeds("test -s /var/lib/profiles/system/current/native-deployment.json", timeout=180)
          configuration_mount_line = vm.succeed("findmnt -no SOURCE,FSTYPE,OPTIONS /etc")
          native_lowers = re.findall(r"/run/etc/native-config-[0-9a-f]{64}/etc", configuration_mount_line)
          assert len(native_lowers) == 1, configuration_mount_line
          native_configuration_path = native_lowers[0]
          vm.succeed("findmnt -t erofs " + shlex.quote(native_configuration_path))
          vm.succeed("test -d /run/etc/system/metadata")
        '';
      }
      {
        name = "os-release";
        description = "/etc/os-release identifies the configured OS name";
        script = ''
          assert 'NAME="${config.aos.system.name}"' in vm.succeed("cat /etc/os-release")
        '';
      }
      {
        name = "hostname";
        description = "hostname is set";
        script = ''
          vm.succeed("test -s /etc/hostname")
        '';
      }
      {
        name = "nix-store-present";
        description = "/nix/store contains system packages";
        script = ''
          vm.succeed("test -d /nix/store")
          vm.succeed("test -e /sbin/init")
        '';
      }
      {
        name = "essential-filesystems";
        description = "proc, sys, dev are mounted";
        script = ''
          vm.succeed("test -d /proc/1")
          vm.succeed("test -d /sys/class")
          vm.succeed("test -c /dev/null")
        '';
      }
      {
        name = "root-read-only";
        description = "root filesystem is mounted read-only (immutable OS design)";
        script = ''
          # The immutable OS design mounts / as ext4 ro; mutable state
          # lives on /var (rw) and /etc is an overlayfs with a tmpfs
          # upper layer. A writable / would undermine the model.
          #
          # `findmnt -O ro /` filters by mount option: exit 0 iff `/`
          # actually carries the `ro` flag. We previously substring-
          # grepped the OPTIONS column for "ro", which silently passed
          # on a writable ext4 root because `errors=remount-ro` (the
          # ext4 default) contains the literal "ro" — exactly the
          # regression we were trying to catch.
          vm.succeed("findmnt -O ro /")
        '';
      }
      {
        name = "etc-three-layer-overlay";
        description = "/etc is the composefs three-layer overlay (spec v12 §1)";
        script = ''
          # The native lower and writable upper are keyed by the EROFS image
          # digest. The image's metadata/content layers retain stable paths
          # across switch-root, independent of profile generation numbers.
          # metacopy=on / redirect_dir=on don't appear in the option
          # line: kernel defaults (CONFIG_OVERLAY_FS_METACOPY=y +
          # CONFIG_OVERLAY_FS_REDIRECT_DIR=y) make them implicit.
          mount_line = vm.succeed("findmnt -no SOURCE,FSTYPE,OPTIONS /etc")
          assert "overlay" in mount_line, f"/etc is not overlayfs: {mount_line!r}"
          for needle in (
              "lowerdir+=/var/etc",
              "lowerdir+=" + native_configuration_path,
              "lowerdir+=/run/etc/system/metadata",
              "datadir+=/run/etc/system/content",
              "upperdir=/run/etc/native-upper-",
          ):
              assert needle in mount_line, \
                  f"/etc overlay missing {needle}: {mount_line!r}"

          # Check the mounted layers remain reachable after the initrd hands
          # /run to the host; mountinfo alone does not establish that.
          vm.succeed("test -d /run/etc/system/metadata")
          vm.succeed("test -d " + shlex.quote(native_configuration_path))
        '';
      }
      {
        name = "system-erofs-mounted";
        description = "system EROFS metadata image is mounted as the bottom lower";
        script = ''
          # Early boot mounts the toplevel's etc-metadata.erofs below
          # /run/etc/system/metadata. The handoff preserves /run, so the
          # mount remains reachable after the host stage takes ownership.
          vm.succeed("findmnt -t erofs /run/etc/system/metadata")
        '';
      }
      {
        name = "machine-id-format";
        description = "/etc/machine-id contains the canonical 32-hex-character host identity";
        script = ''
          # Format: 32 lowercase hex chars + trailing newline (33 bytes).
          # Generated by `tr -d '-' < /proc/sys/kernel/random/uuid`.
          val = vm.succeed("cat /etc/machine-id")
          assert len(val) == 33, f"expected 33 bytes, got {len(val)}"
          assert all(c in '0123456789abcdef\n' for c in val), \
              f"non-hex chars in machine-id: {val!r}"
        '';
      }
    ];
  };
}
