[package]
name = "crucible-daemon"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
crucible-api = { path = "../crucible-api" }
thiserror = { workspace = true }

[dev-dependencies]
crucible = { path = "../crucible" }
crucible-session = { path = "../crucible-session" }
tokio = { workspace = true }
