[package]
name = "crucible-daemon"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
crucible = { path = "../crucible" }
crucible-api = { path = "../crucible-api" }
crucible-campaign = { path = "../crucible-campaign" }
rustix = { workspace = true, features = ["net"] }
thiserror = { workspace = true }

[dev-dependencies]
crucible = { path = "../crucible", features = ["test-double"] }
crucible-protocol = { path = "../crucible-protocol" }
crucible-session = { path = "../crucible-session" }
tempfile = { workspace = true }
tokio = { workspace = true }
