[scenario]
id = "blake3:3a7def56ce688d36d457fa0af222e7611bc8948dafd612697a924c64436fe197"
seed = "0xb6de000000000000000000000000000000000000000000000000000000000000"
app_random_draw_cap = 0

[world]
id = "blake3:9a458fe910f9a1951f3b91e1341acda87c15d15c99a3df392d80e324df37352a"

[[world.node]]
id = "db-0"
arch = "x86_64"
memory_mib = 512
cmdline = "console=ttyS0 quiet store.role=replica cluster=crucible-a3"
smp_vcpus = 1
icount_shift = 7
kernel = "blake3:aae09ed6239f99d3953bd4d6ed40c40e3488798ea1afa1910d34229a05ea0b1d"
root_image = "blake3:72f131eb667fe7780324591a3ca070b130827cc3ef9584cd8d71577ab578da51"
white_box = "enabled"

[world.node.ready_point]
kind = "console_marker"
marker = "ready to accept connections"

[[world.node]]
id = "db-1"
arch = "x86_64"
memory_mib = 512
cmdline = "console=ttyS0 quiet store.role=replica cluster=crucible-a3"
smp_vcpus = 1
icount_shift = 7
kernel = "blake3:aae09ed6239f99d3953bd4d6ed40c40e3488798ea1afa1910d34229a05ea0b1d"
root_image = "blake3:72f131eb667fe7780324591a3ca070b130827cc3ef9584cd8d71577ab578da51"
white_box = "enabled"

[world.node.ready_point]
kind = "console_marker"
marker = "ready to accept connections"

[[world.node]]
id = "db-2"
arch = "x86_64"
memory_mib = 512
cmdline = "console=ttyS0 quiet store.role=replica cluster=crucible-a3"
smp_vcpus = 1
icount_shift = 7
kernel = "blake3:aae09ed6239f99d3953bd4d6ed40c40e3488798ea1afa1910d34229a05ea0b1d"
root_image = "blake3:72f131eb667fe7780324591a3ca070b130827cc3ef9584cd8d71577ab578da51"
white_box = "enabled"

[world.node.ready_point]
kind = "console_marker"
marker = "ready to accept connections"

[[world.link]]
endpoint_a = "db-0"
endpoint_b = "db-1"
latency_nanos = 5000000
jitter_nanos = 1000000
loss_millionths = 0

[[world.link]]
endpoint_a = "db-0"
endpoint_b = "db-2"
latency_nanos = 5000000
jitter_nanos = 1000000
loss_millionths = 0

[[world.link]]
endpoint_a = "db-1"
endpoint_b = "db-2"
latency_nanos = 5000000
jitter_nanos = 1000000
loss_millionths = 0

[plan]
id = "blake3:32af2309e24175bd365f2e888390c83747d32b5eb9f38f6d17e2d21d71f447d3"
kind = "event_graph"

[[plan.event]]
id = "fail-on-inverted-expectation"
policy = "once"

[plan.event.trigger]
kind = "assertion_state"
name = "suspect-must-crash"
state = "violated"

[plan.event.action]
kind = "fail"
reason = "db-0 did not crash"

[properties]
id = "blake3:39cbc5ccc4f7453af7df7416a1579107b25dbd9106b55d5d235651f7f47e0e90"

[[properties.assertion]]
id = "suspect-must-crash"
message = "db-0 must remain crashed"

[properties.assertion.property]
kind = "always"

[properties.assertion.property.predicate]
kind = "node_state"
node = "db-0"
state = "crashed"
