##! acpica — ACPICA user-space tools (iasl ACPI source-language compiler)
##!
##! Built for the `iasl` compiler that EDK2's OVMF build invokes to
##! compile `.asl`/`.dsl` ACPI table sources. The upstream unix
##! makefiles drive the build; only `iasl` is built and installed.
{
  lib,
  mkDerivation,
  fetchurl,
  gnumake,
  flex,
  bison,
  m4,
  stdenv,
}: let
  version = "R2025_04_04";
in
  mkDerivation {
    pname = "acpica";
    qualification.packageProbe = lib.qualification.commandProbe {
      "primary" = {
        "artifacts" = [];
        "expected" = "Iasl accepts both source and generated AML representations.";
        "files" = {
          "probe.asl" = "DefinitionBlock (\"\", \"SSDT\", 2, \"AOS\", \"PROBE\", 1)\n{\n    Name (ANSR, 42)\n}\n";
        };
        "input" = "An ACPI secondary-system-description table containing an integer name.";
        "operation" = "Compile the ASL table to AML, then disassemble the generated bytecode.";
        "steps" = [
          {
            "argv" = [
              "@out@/bin/iasl"
              "-p"
              "probe"
              "probe.asl"
            ];
            "exit_code" = 0;
          }
          {
            "argv" = [
              "@out@/bin/iasl"
              "-d"
              "probe.aml"
            ];
            "exit_code" = 0;
          }
        ];
      };
      "badInput" = {
        "artifacts" = [];
        "expected" = "Iasl rejects the syntax error with a failure status and diagnostic.";
        "files" = {
          "invalid.asl" = "DefinitionBlock (\"\", \"SSDT\", 2, \"AOS\", \"BAD\", 1)\n{\n    Name (ANSR,\n}\n";
        };
        "input" = "An ASL table containing an unterminated Name declaration.";
        "operation" = "Compile the malformed ASL source with iasl.";
        "steps" = [
          {
            "argv" = [
              "@out@/bin/iasl"
              "-p"
              "invalid"
              "invalid.asl"
            ];
            "exit_code" = 255;
            "observes_rejection" = true;
          }
        ];
      };
    };

    inherit version;

    src = fetchurl {
      urls = [
        "https://github.com/acpica/acpica/archive/refs/tags/${version}.tar.gz"
      ];
      hash = "sha256-mZHsEDs2YNF3FXgEBu50CfcFz4esVemjI3Sv/hpvJ1o=";
    };

    buildDeps = [
      gnumake
      flex
      bison
      m4
    ];
    runtimeDeps = [];
    propagatedDeps = [];

    phases = [
      {
        name = "unpack";
        script = ''
          tar xf $src
          cd acpica-${version}
        '';
      }
      {
        name = "build";
        script = ''
          make -j$NIX_BUILD_CORES iasl \
            ${
            if stdenv.hostPlatform.isDarwin
            then "ACPI_HOST=_APPLE"
            else ""
          } \
            YACC=bison \
            LEX=flex \
            NOWERROR=TRUE \
            NOFORTIFY=TRUE
        '';
      }
      {
        name = "install";
        script = ''
          mkdir -p $out/bin
          cp generate/unix/bin/iasl $out/bin/
        '';
      }
    ];

    meta = {
      description = "acpica — ACPI source-language compiler (iasl)";
      homepage = "https://www.acpica.org/";
      license = "Intel-ACPI OR GPL-2.0-only OR BSD-3-Clause";
    };
  }
