##! mdadm — Linux MD (software RAID) array management
##!
##! The initrd creates and assembles the arrays declared through
##! `aos.provisioning.storage.arrays` (modules/services/storage-topology.nix),
##! and stage 2 keeps the same tool, udev rules, and monitor units for hotplug
##! and health. Built from the Makefile-only upstream release; no autoconf.
{
  lib,
  mkDerivation,
  fetchurl,
  gnumake,
  pkg-config,
  systemd,
}: let
  version = "4.4";

  # AOS array policy, compiled in as mdadm's alternate configuration path.
  # mdadm reads /etc/mdadm.conf first and falls back to this file only when
  # that is absent, which is the case in the initrd. Stage 2 installs the same
  # text at /etc/mdadm.conf (modules/services/storage-topology.nix) so both
  # boot phases name arrays identically.
  #
  # - HOMEHOST aos: an array created by AOS carries homehost "aos" in its
  #   superblock and is exposed as /dev/md/<name>. A foreign array from another
  #   machine's disk still assembles but is given a numbered name, so it can
  #   never claim the fixed /dev/md/var identity.
  # - AUTO +1.x -all: assemble only native 1.x metadata; firmware RAID formats
  #   (IMSM, DDF) are outside the AOS storage contract.
  defaultConfig = ''
    # Generated by pkgs/filesystem/mdadm.nix — AOS md array policy.
    DEVICE partitions
    HOMEHOST aos
    AUTO +1.x -all
    CREATE owner=root group=root mode=0600 auto=yes metadata=1.2
  '';
in
  mkDerivation {
    platformSupport = {
      build = [
        {
          abi = ["gnu"];
          os = ["linux"];
        }
      ];
      host = [
        {
          abi = ["gnu"];
          cpu = ["x86_64" "aarch64"];
          os = ["linux"];
        }
      ];
      target = [];
      role = "public-package";
    };
    qualification.packageProbe = lib.qualification.commandProbe {
      primary = {
        input = "The installed target command and its offline query.";
        operation = "Execute the packaged command without network or persistent state.";
        expected = "The target command reports its documented query result.";
        files = {};
        steps = [
          {
            argv = ["@python@" "-c" "import subprocess\nresult = subprocess.run(['@out@/sbin/mdadm', '--version'], capture_output=True, text=True)\nassert result.returncode == 0 and ('mdadm' in result.stdout + result.stderr), (result.returncode, result.stdout, result.stderr)\nprint('mdadm command passed')\n"];
            exit_code = 0;
            stdout.exact = "mdadm command passed\n";
            stderr.exact = "";
          }
        ];
        artifacts = [];
      };
      badInput = {
        input = "An unknown command option or variable.";
        operation = "Parse and reject the invalid request.";
        expected = "The target command fails before performing the operation.";
        files = {};
        steps = [
          {
            argv = ["@python@" "-c" "import subprocess, sys\nresult = subprocess.run(['@out@/sbin/mdadm', '--aos-invalid-option'], capture_output=True, text=True)\nassert result.returncode != 0, (result.returncode, result.stdout, result.stderr)\nsys.stderr.write('mdadm rejected invalid input\\n')\nraise SystemExit(7)\n"];
            exit_code = 7;
            observes_rejection = true;
            stdout.exact = "";
            stderr.exact = "mdadm rejected invalid input\n";
          }
        ];
        artifacts = [];
      };
    };
    pname = "mdadm";
    inherit version;

    src = fetchurl {
      urls = [
        "https://www.kernel.org/pub/linux/utils/raid/mdadm/mdadm-${version}.tar.xz"
        "https://mirrors.kernel.org/linux/utils/raid/mdadm/mdadm-${version}.tar.xz"
      ];
      hash = "sha256-m0iPNe0VPfmZJLX+Qe7TgOhRLejxihGGKMrN1oGx1XM=";
    };

    buildDeps = [
      gnumake
      pkg-config
    ];
    # libudev synchronizes array creation with udev's /dev/md/<name> symlink
    # publication; the udev rules and the monitor units reference systemd.
    runtimeDeps = [systemd];

    phases = [
      {
        name = "unpack";
        script = ''
          tar xf $src
          cd mdadm-${version}
        '';
      }
      {
        name = "build";
        # The plain Makefile honors CC and the CWFLAGS/CXFLAGS pair. Upstream's
        # CWFLAGS carries -Werror, which is not stable across compiler
        # releases, so the warning set is restated without it. BINDIR is the
        # absolute store path because the udev rules and systemd units embed
        # it verbatim; the rootfs has no /sbin/mdadm. CHECK_RUN_DIR=0 skips
        # the /run existence probe that cannot succeed in the build sandbox.
        script = ''
          make -j$NIX_BUILD_CORES \
            CC="$CC" \
            CWFLAGS="-Wall -Wextra -Wno-unused-parameter -Wformat -Wformat-security -fstack-protector-strong -fPIE" \
            CXFLAGS="-O2" \
            CHECK_RUN_DIR=0 \
            BINDIR="$out/sbin" \
            CONFFILE=/etc/mdadm.conf \
            CONFFILE2="$out/etc/mdadm.conf" \
            UDEVDIR="$out/lib/udev" \
            SYSTEMD_DIR="$out/lib/systemd/system" \
            MANDIR="$out/share/man" \
            mdadm mdmon
        '';
      }
      {
        name = "install";
        # The Makefile hardcodes /usr/bin/install and splices $(STRIP) into
        # the install command line; the build environment exports STRIP as
        # the path to the strip binary, which install would treat as a file
        # to copy. Name the coreutils install and clear STRIP explicitly.
        script = ''
          make \
            INSTALL=install \
            STRIP= \
            CHECK_RUN_DIR=0 \
            BINDIR="$out/sbin" \
            CONFFILE=/etc/mdadm.conf \
            CONFFILE2="$out/etc/mdadm.conf" \
            UDEVDIR="$out/lib/udev" \
            SYSTEMD_DIR="$out/lib/systemd/system" \
            MANDIR="$out/share/man" \
            install install-systemd

          mkdir -p $out/etc
          cat > $out/etc/mdadm.conf <<'CONF'
          ${defaultConfig}
          CONF
        '';
      }
    ];

    meta = {
      description = "mdadm — manage Linux MD software RAID arrays";
      homepage = "https://git.kernel.org/pub/scm/utils/mdadm/mdadm.git";
      license = "GPL-2.0-or-later";
    };
  }
