/* SPDX-License-Identifier: Apache-2.0 */
#include "namespace-inspector-manager-query-fixture.h"

const struct aos_fixture_case aos_fixture_cases[] = {
    {
        .name = "canonical-no-fd-replies",
        .fault = AOS_FIXTURE_SUCCESS,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "rights-on-first-get-unit",
        .fault = AOS_FIXTURE_RIGHTS_FIRST_UNIT,
        .fault_call = 0,
        .expected_calls = 1,
        .expected_exit = 254,
    },
    {
        .name = "rights-on-middle-property",
        .fault = AOS_FIXTURE_RIGHTS_MIDDLE_PROPERTY,
        .fault_call = 63,
        .expected_calls = 64,
        .expected_exit = 254,
    },
    {
        .name = "rights-on-second-get-unit",
        .fault = AOS_FIXTURE_RIGHTS_SECOND_UNIT,
        .fault_call = 127,
        .expected_calls = 128,
        .expected_exit = 254,
    },
    {
        /* No later call may turn a silently discarded, unused FD into failure. */
        .name = "rights-on-last-property",
        .fault = AOS_FIXTURE_RIGHTS_LAST_PROPERTY,
        .fault_call = 253,
        .expected_calls = 254,
        .expected_exit = 254,
    },
    {
        .name = "raw-unit-reply-without-fd",
        .fault = AOS_FIXTURE_RAW_UNIT_NO_FD,
        .fault_call = 0,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "raw-property-reply-without-fd",
        .fault = AOS_FIXTURE_RAW_PROPERTY_NO_FD,
        .fault_call = 63,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "unit-invocation-wrong-length",
        .fault = AOS_FIXTURE_UNIT_INVOCATION_WRONG_LENGTH,
        .fault_call = 0,
        .expected_calls = 1,
        .expected_exit = 254,
    },
    {
        .name = "unit-invocation-zero",
        .fault = AOS_FIXTURE_UNIT_INVOCATION_ZERO,
        .fault_call = 0,
        .expected_calls = 1,
        .expected_exit = 254,
    },
    {
        .name = "socket-property-invocation-zero",
        .fault = AOS_FIXTURE_PROPERTY_SOCKET_INVOCATION_ZERO,
        .fault_call = 107,
        .expected_calls = 108,
        .expected_exit = 254,
    },
    {
        .name = "property-unit-id-mismatch",
        .fault = AOS_FIXTURE_PROPERTY_UNIT_ID_MISMATCH,
        .fault_call = 2,
        .expected_calls = 3,
        .expected_exit = 254,
    },
    {
        .name = "property-invocation-mismatch",
        .fault = AOS_FIXTURE_PROPERTY_INVOCATION_MISMATCH,
        .fault_call = 15,
        .expected_calls = 16,
        .expected_exit = 254,
    },
    {
        .name = "property-empty-control-group",
        .fault = AOS_FIXTURE_PROPERTY_EMPTY_CONTROL_GROUP,
        .fault_call = 18,
        .expected_calls = 19,
        .expected_exit = 254,
    },
    {
        .name = "property-zero-control-group-id",
        .fault = AOS_FIXTURE_PROPERTY_ZERO_CONTROL_GROUP_ID,
        .fault_call = 19,
        .expected_calls = 20,
        .expected_exit = 254,
    },
    {
        .name = "property-zero-main-pid",
        .fault = AOS_FIXTURE_PROPERTY_ZERO_MAIN_PID,
        .fault_call = 25,
        .expected_calls = 26,
        .expected_exit = 254,
    },
    {
        .name = "duplicate-unordered-set",
        .fault = AOS_FIXTURE_DUPLICATE_UNORDERED_SET,
        .fault_call = 3,
        .expected_calls = 4,
        .expected_exit = 254,
    },
    {
        .name = "invalid-manager-environment",
        .fault = AOS_FIXTURE_INVALID_MANAGER_ENVIRONMENT,
        .fault_call = 1,
        .expected_calls = 2,
        .expected_exit = 254,
    },
    {
        .name = "duplicate-manager-environment-name",
        .fault = AOS_FIXTURE_DUPLICATE_MANAGER_ENVIRONMENT_NAME,
        .fault_call = 1,
        .expected_calls = 2,
        .expected_exit = 254,
    },
    {
        .name = "wrong-property-order",
        .fault = AOS_FIXTURE_WRONG_PROPERTY,
        .fault_call = 42,
        .expected_calls = 43,
        .expected_exit = 254,
    },
    {
        .name = "trailing-property-variant",
        .fault = AOS_FIXTURE_TRAILING_VARIANT,
        .fault_call = 64,
        .expected_calls = 65,
        .expected_exit = 254,
    },
    {
        .name = "oversize-text-value",
        .fault = AOS_FIXTURE_OVERSIZE_TEXT,
        .fault_call = 2,
        .expected_calls = 3,
        .expected_exit = 254,
    },
    {
        .name = "oversize-array-value",
        .fault = AOS_FIXTURE_OVERSIZE_ARRAY,
        .fault_call = 1,
        .expected_calls = 2,
        .expected_exit = 254,
    },
    {
        .name = "maximum-snapshot-and-control-record",
        .fault = AOS_FIXTURE_MAXIMUM_SNAPSHOT,
        .fault_call = 10,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "snapshot-over-maximum",
        .fault = AOS_FIXTURE_OVERSIZE_SNAPSHOT,
        .fault_call = 10,
        .expected_calls = 127,
        .expected_exit = 254,
    },
    {
        .name = "wrong-unit-identity",
        .fault = AOS_FIXTURE_WRONG_UNIT_IDENTITY,
        .fault_call = 0,
        .expected_calls = 1,
        .expected_exit = 254,
    },
    {
        .name = "wrong-unit-path",
        .fault = AOS_FIXTURE_WRONG_UNIT_PATH,
        .fault_call = 0,
        .expected_calls = 1,
        .expected_exit = 254,
    },
    {
        .name = "declared-fd-without-rights",
        .fault = AOS_FIXTURE_DECLARED_FD_MISSING,
        .fault_call = 63,
        .expected_calls = 64,
        .expected_exit = 254,
    },
    {
        .name = "absolute-deadline-stall",
        .fault = AOS_FIXTURE_STALLED_REPLY,
        .fault_call = 126,
        .expected_calls = 127,
        .expected_exit = 254,
    },
    {
        .name = "entry-extra-fd",
        .fault = AOS_FIXTURE_ENTRY_EXTRA_FD,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "entry-blocking-control",
        .fault = AOS_FIXTURE_ENTRY_BLOCKING_CONTROL,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "entry-missing-passpidfd",
        .fault = AOS_FIXTURE_ENTRY_NO_PASSPIDFD,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "entry-non-pidfd-parent",
        .fault = AOS_FIXTURE_ENTRY_BAD_PIDFD,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "entry-low-nofile-hard-limit",
        .fault = AOS_FIXTURE_ENTRY_LOW_NOFILE,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "entry-nonempty-environment",
        .fault = AOS_FIXTURE_ENTRY_NONEMPTY_ENV,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "start-past-deadline",
        .fault = AOS_FIXTURE_START_PAST_DEADLINE,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "start-over-one-second-deadline",
        .fault = AOS_FIXTURE_START_LONG_DEADLINE,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "start-zero-nonce",
        .fault = AOS_FIXTURE_START_ZERO_NONCE,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "start-wrong-manifest-digest",
        .fault = AOS_FIXTURE_START_WRONG_DIGEST,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "start-wrong-connector",
        .fault = AOS_FIXTURE_START_WRONG_CONNECTOR,
        .expected_calls = 1,
        .expected_exit = 254,
    },
    {
        .name = "start-wrong-connector-pidfd-inode",
        .fault = AOS_FIXTURE_START_WRONG_CONNECTOR_INODE,
        .expected_calls = 1,
        .expected_exit = 254,
    },
    {
        .name = "start-equal-parent-connector",
        .fault = AOS_FIXTURE_START_EQUAL_PARENT_CONNECTOR,
        .expected_calls = 0,
        .expected_exit = 254,
    },
    {
        .name = "start-same-pid-different-pidfd-inode",
        .fault = AOS_FIXTURE_START_SAME_PID_DIFFERENT_INODE,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "start-different-pid-same-pidfd-inode",
        .fault = AOS_FIXTURE_START_DIFFERENT_PID_SAME_INODE,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "start-minimum-identity-format",
        .fault = AOS_FIXTURE_START_MIN_IDENTITY,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "start-maximum-identity-format",
        .fault = AOS_FIXTURE_START_MAX_IDENTITY,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "control-receive-would-block-retry",
        .fault = AOS_FIXTURE_CONTROL_RECEIVE_RETRY,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "control-send-would-block-retry",
        .fault = AOS_FIXTURE_CONTROL_SEND_RETRY,
        .expected_calls = 254,
        .expected_exit = 0,
    },
    {
        .name = "continue-wrong-nonce",
        .fault = AOS_FIXTURE_CONTINUE_WRONG_NONCE,
        .expected_calls = 127,
        .expected_exit = 254,
    },
    {
        .name = "continue-duplicate-record",
        .fault = AOS_FIXTURE_CONTINUE_DUPLICATE,
        .expected_calls = 127,
        .expected_exit = 254,
    },
    {
        .name = "continue-carries-rights",
        .fault = AOS_FIXTURE_CONTINUE_RIGHTS,
        .expected_calls = 127,
        .expected_exit = 254,
    },
};

const size_t aos_fixture_case_count =
    sizeof(aos_fixture_cases) / sizeof(aos_fixture_cases[0]);
