//! Generated C header support for the shared-memory ABI.

use crate::{
    ABI_VERSION, COVERAGE_ENTRY_ALIGN, COVERAGE_ENTRY_BLOCK_LEN_OFFSET,
    COVERAGE_ENTRY_CURRENT_ICOUNT_OFFSET, COVERAGE_ENTRY_GUEST_PC_OFFSET,
    COVERAGE_ENTRY_MAP_INDEX_OFFSET, COVERAGE_ENTRY_RESERVED_OFFSET, COVERAGE_ENTRY_SIZE,
    COVERAGE_ENTRY_VCPU_INDEX_OFFSET, COVERAGE_QUEUE_CAPACITY, DEFAULT_QUEUE_CAPACITY,
    FRAME_ENTRY_ALIGN, FRAME_ENTRY_DATA_OFFSET, FRAME_ENTRY_DELIVERY_ICOUNT_OFFSET,
    FRAME_ENTRY_LEN_OFFSET, FRAME_ENTRY_PAD_OFFSET, FRAME_ENTRY_SEQ_OFFSET, FRAME_ENTRY_SIZE,
    FRAME_ENTRY_SRC_NODE_OFFSET, FUTEX_PRIVATE, KIND_9P, KIND_BLK, KIND_NET, KIND_VM,
    LAYOUT_TARGET_TRIPLE, MAX_FRAME_DATA, MAX_NODES, MAX_VM_NODES, NODE_SLOT_ALIGN,
    NODE_SLOT_CURRENT_ICOUNT_OFFSET, NODE_SLOT_CURRENT_NS_OFFSET,
    NODE_SLOT_DEVICE_COMPLETION_DEADLINE_ICOUNT_OFFSET, NODE_SLOT_DEVICE_IO_ACTIVE_OFFSET,
    NODE_SLOT_IDLE_WAKE_ICOUNT_OFFSET, NODE_SLOT_KIND_OFFSET, NODE_SLOT_MAX_ADVANCE_ICOUNT_OFFSET,
    NODE_SLOT_PAD0_OFFSET, NODE_SLOT_PUBLISH_GEN_OFFSET, NODE_SLOT_RESERVED_OFFSET, NODE_SLOT_SIZE,
    NODE_SLOT_STATUS_OFFSET, NODE_SLOT_WAKE_SIGNAL_OFFSET, REGION_HEADER_ABI_VERSION_OFFSET,
    REGION_HEADER_ALIGN, REGION_HEADER_ENTRY_STRIDE_OFFSET, REGION_HEADER_ICOUNT_SHIFT_OFFSET,
    REGION_HEADER_MAGIC_OFFSET, REGION_HEADER_NODE_COUNT_OFFSET,
    REGION_HEADER_PAUSE_REQUESTED_OFFSET, REGION_HEADER_QUEUE_CAPACITY_OFFSET,
    REGION_HEADER_REGION_SIZE_OFFSET, REGION_HEADER_RESERVED_OFFSET,
    REGION_HEADER_RING_COUNT_OFFSET, REGION_HEADER_RING_DATA_OFF_OFFSET,
    REGION_HEADER_RING_HDR_OFF_OFFSET, REGION_HEADER_SHUTDOWN_REQUESTED_OFFSET, REGION_HEADER_SIZE,
    REGION_MAGIC, RESERVED_SLOTS, RING_HEADER_ALIGN, RING_HEADER_PAD_READ_OFFSET,
    RING_HEADER_PAD_WRITE_OFFSET, RING_HEADER_READ_IDX_OFFSET, RING_HEADER_SIZE,
    RING_HEADER_WRITE_IDX_OFFSET, SLOT_9P_IO, SLOT_BLK_IO, SLOT_NET_ROUTER, STATUS_DONE,
    STATUS_IDLE, STATUS_RUNNING,
};
use crate::{
    FINGERPRINT_DIGEST_BYTES, FINGERPRINT_SAMPLE_MAX_VCPUS, FINGERPRINT_SAMPLE_SLOT_ALIGN,
    FINGERPRINT_SAMPLE_SLOT_GEN_OFFSET, FINGERPRINT_SAMPLE_SLOT_RESERVED_OFFSET,
    FINGERPRINT_SAMPLE_SLOT_SIZE, FINGERPRINT_SAMPLE_SLOT_WORDS_OFFSET, FINGERPRINT_SAMPLE_WORDS,
};

/// Generates the committed `crucible_shmem_abi.h` contents.
///
/// The generated header is derived from the Rust `#[repr(C)]` layout constants
/// in this crate and carries matching C `_Static_assert` checks for every shared
/// struct size, alignment, and field offset.
#[must_use]
pub fn generated_c_header() -> String {
    let mut out = String::new();
    emit_preamble(&mut out);
    emit_constants(&mut out);
    emit_region_header(&mut out);
    emit_node_slot(&mut out);
    emit_ring_header(&mut out);
    emit_frame_entry(&mut out);
    emit_coverage_entry(&mut out);
    emit_fingerprint_sample_slot(&mut out);
    emit_footer(&mut out);
    out
}

fn emit_preamble(out: &mut String) {
    out.push_str("/* Generated by crucible-shmem. Do not edit by hand. */\n");
    out.push_str("#ifndef CRUCIBLE_SHMEM_ABI_H\n");
    out.push_str("#define CRUCIBLE_SHMEM_ABI_H\n\n");
    out.push_str("#include <stdatomic.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdint.h>\n\n");
    out.push_str("#if !defined(__GNUC__) && !defined(__clang__)\n");
    out.push_str(
        "#error \"crucible_shmem_abi.h requires a compiler with aligned attribute support\"\n",
    );
    out.push_str("#endif\n\n");
    out.push_str("#define CRUCIBLE_SHMEM_ALIGNED(N) __attribute__((aligned(N)))\n");
    out.push_str("#define CRUCIBLE_SHMEM_STATIC_ASSERT(COND, MSG) _Static_assert((COND), MSG)\n\n");
}

fn emit_constants(out: &mut String) {
    emit_define_u64_hex(out, "CRUCIBLE_SHMEM_REGION_MAGIC", REGION_MAGIC);
    emit_define_u32(out, "CRUCIBLE_SHMEM_ABI_VERSION", ABI_VERSION);
    emit_define_usize(out, "CRUCIBLE_SHMEM_MAX_FRAME_DATA", MAX_FRAME_DATA);
    emit_define_u32(
        out,
        "CRUCIBLE_SHMEM_DEFAULT_QUEUE_CAPACITY",
        DEFAULT_QUEUE_CAPACITY,
    );
    emit_define_u32(
        out,
        "CRUCIBLE_SHMEM_COVERAGE_QUEUE_CAPACITY",
        COVERAGE_QUEUE_CAPACITY,
    );
    emit_define_usize(out, "CRUCIBLE_SHMEM_MAX_NODES", MAX_NODES);
    emit_define_usize(out, "CRUCIBLE_SHMEM_RESERVED_SLOTS", RESERVED_SLOTS);
    emit_define_usize(out, "CRUCIBLE_SHMEM_MAX_VM_NODES", MAX_VM_NODES);
    emit_define_usize(out, "CRUCIBLE_SHMEM_SLOT_NET_ROUTER", SLOT_NET_ROUTER);
    emit_define_usize(out, "CRUCIBLE_SHMEM_SLOT_BLK_IO", SLOT_BLK_IO);
    emit_define_usize(out, "CRUCIBLE_SHMEM_SLOT_9P_IO", SLOT_9P_IO);
    emit_define_str(
        out,
        "CRUCIBLE_SHMEM_LAYOUT_TARGET_TRIPLE",
        LAYOUT_TARGET_TRIPLE,
    );
    emit_define_bool(out, "CRUCIBLE_SHMEM_FUTEX_PRIVATE", FUTEX_PRIVATE);
    out.push('\n');

    emit_define_u8(out, "CRUCIBLE_SHMEM_STATUS_RUNNING", STATUS_RUNNING);
    emit_define_u8(out, "CRUCIBLE_SHMEM_STATUS_IDLE", STATUS_IDLE);
    emit_define_u8(out, "CRUCIBLE_SHMEM_STATUS_DONE", STATUS_DONE);
    emit_define_u8(out, "CRUCIBLE_SHMEM_KIND_VM", KIND_VM);
    emit_define_u8(out, "CRUCIBLE_SHMEM_KIND_NET", KIND_NET);
    emit_define_u8(out, "CRUCIBLE_SHMEM_KIND_BLK", KIND_BLK);
    emit_define_u8(out, "CRUCIBLE_SHMEM_KIND_9P", KIND_9P);
    out.push('\n');

    emit_layout_constant_group(
        out,
        "REGION_HEADER",
        REGION_HEADER_SIZE,
        REGION_HEADER_ALIGN,
        &[
            ("MAGIC", REGION_HEADER_MAGIC_OFFSET),
            ("ABI_VERSION", REGION_HEADER_ABI_VERSION_OFFSET),
            ("NODE_COUNT", REGION_HEADER_NODE_COUNT_OFFSET),
            ("QUEUE_CAPACITY", REGION_HEADER_QUEUE_CAPACITY_OFFSET),
            ("RING_COUNT", REGION_HEADER_RING_COUNT_OFFSET),
            ("RING_HDR_OFF", REGION_HEADER_RING_HDR_OFF_OFFSET),
            ("RING_DATA_OFF", REGION_HEADER_RING_DATA_OFF_OFFSET),
            ("ENTRY_STRIDE", REGION_HEADER_ENTRY_STRIDE_OFFSET),
            ("REGION_SIZE", REGION_HEADER_REGION_SIZE_OFFSET),
            ("ICOUNT_SHIFT", REGION_HEADER_ICOUNT_SHIFT_OFFSET),
            ("PAUSE_REQUESTED", REGION_HEADER_PAUSE_REQUESTED_OFFSET),
            (
                "SHUTDOWN_REQUESTED",
                REGION_HEADER_SHUTDOWN_REQUESTED_OFFSET,
            ),
            ("RESERVED", REGION_HEADER_RESERVED_OFFSET),
        ],
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_REGION_HEADER_RESERVED_LEN",
        REGION_HEADER_SIZE - REGION_HEADER_RESERVED_OFFSET,
    );
    out.push('\n');

    emit_layout_constant_group(
        out,
        "NODE_SLOT",
        NODE_SLOT_SIZE,
        NODE_SLOT_ALIGN,
        &[
            ("CURRENT_ICOUNT", NODE_SLOT_CURRENT_ICOUNT_OFFSET),
            ("CURRENT_NS", NODE_SLOT_CURRENT_NS_OFFSET),
            ("MAX_ADVANCE_ICOUNT", NODE_SLOT_MAX_ADVANCE_ICOUNT_OFFSET),
            ("IDLE_WAKE_ICOUNT", NODE_SLOT_IDLE_WAKE_ICOUNT_OFFSET),
            ("WAKE_SIGNAL", NODE_SLOT_WAKE_SIGNAL_OFFSET),
            ("STATUS", NODE_SLOT_STATUS_OFFSET),
            ("KIND", NODE_SLOT_KIND_OFFSET),
            ("DEVICE_IO_ACTIVE", NODE_SLOT_DEVICE_IO_ACTIVE_OFFSET),
            ("PAD0", NODE_SLOT_PAD0_OFFSET),
            ("PUBLISH_GEN", NODE_SLOT_PUBLISH_GEN_OFFSET),
            (
                "DEVICE_COMPLETION_DEADLINE_ICOUNT",
                NODE_SLOT_DEVICE_COMPLETION_DEADLINE_ICOUNT_OFFSET,
            ),
            ("RESERVED", NODE_SLOT_RESERVED_OFFSET),
        ],
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_NODE_SLOT_RESERVED_LEN",
        NODE_SLOT_SIZE - NODE_SLOT_RESERVED_OFFSET,
    );
    out.push('\n');

    emit_layout_constant_group(
        out,
        "RING_HEADER",
        RING_HEADER_SIZE,
        RING_HEADER_ALIGN,
        &[
            ("READ_IDX", RING_HEADER_READ_IDX_OFFSET),
            ("PAD_READ", RING_HEADER_PAD_READ_OFFSET),
            ("WRITE_IDX", RING_HEADER_WRITE_IDX_OFFSET),
            ("PAD_WRITE", RING_HEADER_PAD_WRITE_OFFSET),
        ],
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_RING_HEADER_PAD_READ_LEN",
        RING_HEADER_WRITE_IDX_OFFSET - RING_HEADER_PAD_READ_OFFSET,
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_RING_HEADER_PAD_WRITE_LEN",
        RING_HEADER_SIZE - RING_HEADER_PAD_WRITE_OFFSET,
    );
    out.push('\n');

    emit_layout_constant_group(
        out,
        "FRAME_ENTRY",
        FRAME_ENTRY_SIZE,
        FRAME_ENTRY_ALIGN,
        &[
            ("DELIVERY_ICOUNT", FRAME_ENTRY_DELIVERY_ICOUNT_OFFSET),
            ("SRC_NODE", FRAME_ENTRY_SRC_NODE_OFFSET),
            ("SEQ", FRAME_ENTRY_SEQ_OFFSET),
            ("LEN", FRAME_ENTRY_LEN_OFFSET),
            ("PAD", FRAME_ENTRY_PAD_OFFSET),
            ("DATA", FRAME_ENTRY_DATA_OFFSET),
        ],
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_FRAME_ENTRY_PAD_LEN",
        FRAME_ENTRY_DATA_OFFSET - FRAME_ENTRY_PAD_OFFSET,
    );
    out.push('\n');

    emit_layout_constant_group(
        out,
        "COVERAGE_ENTRY",
        COVERAGE_ENTRY_SIZE,
        COVERAGE_ENTRY_ALIGN,
        &[
            ("CURRENT_ICOUNT", COVERAGE_ENTRY_CURRENT_ICOUNT_OFFSET),
            ("GUEST_PC", COVERAGE_ENTRY_GUEST_PC_OFFSET),
            ("MAP_INDEX", COVERAGE_ENTRY_MAP_INDEX_OFFSET),
            ("VCPU_INDEX", COVERAGE_ENTRY_VCPU_INDEX_OFFSET),
            ("BLOCK_LEN", COVERAGE_ENTRY_BLOCK_LEN_OFFSET),
            ("RESERVED", COVERAGE_ENTRY_RESERVED_OFFSET),
        ],
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_COVERAGE_ENTRY_RESERVED_LEN",
        COVERAGE_ENTRY_SIZE - COVERAGE_ENTRY_RESERVED_OFFSET,
    );
    out.push('\n');

    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_FINGERPRINT_DIGEST_BYTES",
        FINGERPRINT_DIGEST_BYTES,
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_MAX_VCPUS",
        FINGERPRINT_SAMPLE_MAX_VCPUS,
    );
    emit_define_usize(
        out,
        "CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_WORDS",
        FINGERPRINT_SAMPLE_WORDS,
    );
    emit_layout_constant_group(
        out,
        "FINGERPRINT_SAMPLE_SLOT",
        FINGERPRINT_SAMPLE_SLOT_SIZE,
        FINGERPRINT_SAMPLE_SLOT_ALIGN,
        &[
            ("GEN", FINGERPRINT_SAMPLE_SLOT_GEN_OFFSET),
            ("RESERVED", FINGERPRINT_SAMPLE_SLOT_RESERVED_OFFSET),
            ("WORDS", FINGERPRINT_SAMPLE_SLOT_WORDS_OFFSET),
        ],
    );
    out.push('\n');
}

fn emit_region_header(out: &mut String) {
    out.push_str("typedef struct CRUCIBLE_SHMEM_ALIGNED(128) crucible_shmem_region_header {\n");
    out.push_str("    _Atomic uint64_t magic;\n");
    out.push_str("    _Atomic uint32_t abi_version;\n");
    out.push_str("    _Atomic uint32_t node_count;\n");
    out.push_str("    _Atomic uint32_t queue_capacity;\n");
    out.push_str("    _Atomic uint32_t ring_count;\n");
    out.push_str("    _Atomic uint64_t ring_hdr_off;\n");
    out.push_str("    _Atomic uint64_t ring_data_off;\n");
    out.push_str("    _Atomic uint64_t entry_stride;\n");
    out.push_str("    _Atomic uint64_t region_size;\n");
    out.push_str("    _Atomic uint32_t icount_shift;\n");
    out.push_str("    _Atomic uint8_t pause_requested;\n");
    out.push_str("    _Atomic uint8_t shutdown_requested;\n");
    out.push_str("    uint8_t reserved[CRUCIBLE_SHMEM_REGION_HEADER_RESERVED_LEN];\n");
    out.push_str("} crucible_shmem_region_header;\n\n");

    emit_static_asserts(
        out,
        "crucible_shmem_region_header",
        "REGION_HEADER",
        &[
            ("magic", "MAGIC"),
            ("abi_version", "ABI_VERSION"),
            ("node_count", "NODE_COUNT"),
            ("queue_capacity", "QUEUE_CAPACITY"),
            ("ring_count", "RING_COUNT"),
            ("ring_hdr_off", "RING_HDR_OFF"),
            ("ring_data_off", "RING_DATA_OFF"),
            ("entry_stride", "ENTRY_STRIDE"),
            ("region_size", "REGION_SIZE"),
            ("icount_shift", "ICOUNT_SHIFT"),
            ("pause_requested", "PAUSE_REQUESTED"),
            ("shutdown_requested", "SHUTDOWN_REQUESTED"),
            ("reserved", "RESERVED"),
        ],
    );
}

fn emit_node_slot(out: &mut String) {
    out.push_str("typedef struct CRUCIBLE_SHMEM_ALIGNED(128) crucible_shmem_node_slot {\n");
    out.push_str("    _Atomic uint64_t current_icount;\n");
    out.push_str("    _Atomic uint64_t current_ns;\n");
    out.push_str("    _Atomic uint64_t max_advance_icount;\n");
    out.push_str("    _Atomic uint64_t idle_wake_icount;\n");
    out.push_str("    _Atomic uint32_t wake_signal;\n");
    out.push_str("    _Atomic uint8_t status;\n");
    out.push_str("    _Atomic uint8_t kind;\n");
    out.push_str("    _Atomic uint8_t device_io_active;\n");
    out.push_str("    uint8_t pad0;\n");
    out.push_str("    _Atomic uint32_t publish_gen;\n");
    out.push_str("    uint8_t pad1[4];\n");
    out.push_str("    _Atomic uint64_t device_completion_deadline_icount;\n");
    out.push_str("    uint8_t reserved[CRUCIBLE_SHMEM_NODE_SLOT_RESERVED_LEN];\n");
    out.push_str("} crucible_shmem_node_slot;\n\n");

    emit_static_asserts(
        out,
        "crucible_shmem_node_slot",
        "NODE_SLOT",
        &[
            ("current_icount", "CURRENT_ICOUNT"),
            ("current_ns", "CURRENT_NS"),
            ("max_advance_icount", "MAX_ADVANCE_ICOUNT"),
            ("idle_wake_icount", "IDLE_WAKE_ICOUNT"),
            ("wake_signal", "WAKE_SIGNAL"),
            ("status", "STATUS"),
            ("kind", "KIND"),
            ("device_io_active", "DEVICE_IO_ACTIVE"),
            ("pad0", "PAD0"),
            ("publish_gen", "PUBLISH_GEN"),
            (
                "device_completion_deadline_icount",
                "DEVICE_COMPLETION_DEADLINE_ICOUNT",
            ),
            ("reserved", "RESERVED"),
        ],
    );
}

fn emit_ring_header(out: &mut String) {
    out.push_str("typedef struct CRUCIBLE_SHMEM_ALIGNED(128) crucible_shmem_ring_header {\n");
    out.push_str("    _Atomic uint64_t read_idx;\n");
    out.push_str("    uint8_t pad_read[CRUCIBLE_SHMEM_RING_HEADER_PAD_READ_LEN];\n");
    out.push_str("    _Atomic uint64_t write_idx;\n");
    out.push_str("    uint8_t pad_write[CRUCIBLE_SHMEM_RING_HEADER_PAD_WRITE_LEN];\n");
    out.push_str("} crucible_shmem_ring_header;\n\n");

    emit_static_asserts(
        out,
        "crucible_shmem_ring_header",
        "RING_HEADER",
        &[
            ("read_idx", "READ_IDX"),
            ("pad_read", "PAD_READ"),
            ("write_idx", "WRITE_IDX"),
            ("pad_write", "PAD_WRITE"),
        ],
    );
}

fn emit_frame_entry(out: &mut String) {
    out.push_str("typedef struct crucible_shmem_frame_entry {\n");
    out.push_str("    uint64_t delivery_icount;\n");
    out.push_str("    uint32_t src_node;\n");
    out.push_str("    uint32_t seq;\n");
    out.push_str("    uint16_t len;\n");
    out.push_str("    uint8_t pad[CRUCIBLE_SHMEM_FRAME_ENTRY_PAD_LEN];\n");
    out.push_str("    uint8_t data[CRUCIBLE_SHMEM_MAX_FRAME_DATA];\n");
    out.push_str("} crucible_shmem_frame_entry;\n\n");

    emit_static_asserts(
        out,
        "crucible_shmem_frame_entry",
        "FRAME_ENTRY",
        &[
            ("delivery_icount", "DELIVERY_ICOUNT"),
            ("src_node", "SRC_NODE"),
            ("seq", "SEQ"),
            ("len", "LEN"),
            ("pad", "PAD"),
            ("data", "DATA"),
        ],
    );
}

fn emit_fingerprint_sample_slot(out: &mut String) {
    out.push_str(&format!(
        "typedef struct CRUCIBLE_SHMEM_ALIGNED({FINGERPRINT_SAMPLE_SLOT_ALIGN}) crucible_shmem_fingerprint_sample_slot {{\n"
    ));
    out.push_str("    _Atomic uint32_t sample_gen;\n");
    out.push_str("    uint32_t reserved;\n");
    out.push_str("    _Atomic uint64_t words[CRUCIBLE_SHMEM_FINGERPRINT_SAMPLE_WORDS];\n");
    out.push_str("} crucible_shmem_fingerprint_sample_slot;\n\n");

    emit_static_asserts(
        out,
        "crucible_shmem_fingerprint_sample_slot",
        "FINGERPRINT_SAMPLE_SLOT",
        &[
            ("sample_gen", "GEN"),
            ("reserved", "RESERVED"),
            ("words", "WORDS"),
        ],
    );
}

fn emit_coverage_entry(out: &mut String) {
    out.push_str(&format!(
        "typedef struct CRUCIBLE_SHMEM_ALIGNED({COVERAGE_ENTRY_ALIGN}) crucible_shmem_coverage_entry {{\n"
    ));
    out.push_str("    uint64_t current_icount;\n");
    out.push_str("    uint64_t guest_pc;\n");
    out.push_str("    uint64_t map_index;\n");
    out.push_str("    uint32_t vcpu_index;\n");
    out.push_str("    uint32_t block_len;\n");
    out.push_str("    uint8_t reserved[CRUCIBLE_SHMEM_COVERAGE_ENTRY_RESERVED_LEN];\n");
    out.push_str("} crucible_shmem_coverage_entry;\n\n");

    emit_static_asserts(
        out,
        "crucible_shmem_coverage_entry",
        "COVERAGE_ENTRY",
        &[
            ("current_icount", "CURRENT_ICOUNT"),
            ("guest_pc", "GUEST_PC"),
            ("map_index", "MAP_INDEX"),
            ("vcpu_index", "VCPU_INDEX"),
            ("block_len", "BLOCK_LEN"),
            ("reserved", "RESERVED"),
        ],
    );
}

fn emit_static_asserts(
    out: &mut String,
    c_type: &str,
    layout_prefix: &str,
    fields: &[(&str, &str)],
) {
    out.push_str(&format!(
        "CRUCIBLE_SHMEM_STATIC_ASSERT(sizeof({c_type}) == CRUCIBLE_SHMEM_{layout_prefix}_SIZE, \"{c_type} size\");\n"
    ));
    out.push_str(&format!(
        "CRUCIBLE_SHMEM_STATIC_ASSERT(_Alignof({c_type}) == CRUCIBLE_SHMEM_{layout_prefix}_ALIGN, \"{c_type} alignment\");\n"
    ));
    for (field, offset_suffix) in fields {
        out.push_str(&format!(
            "CRUCIBLE_SHMEM_STATIC_ASSERT(offsetof({c_type}, {field}) == CRUCIBLE_SHMEM_{layout_prefix}_{offset_suffix}_OFFSET, \"{c_type}.{field} offset\");\n"
        ));
    }
    out.push('\n');
}

fn emit_layout_constant_group(
    out: &mut String,
    prefix: &str,
    size: usize,
    align: usize,
    offsets: &[(&str, usize)],
) {
    emit_define_usize(out, &format!("CRUCIBLE_SHMEM_{prefix}_SIZE"), size);
    emit_define_usize(out, &format!("CRUCIBLE_SHMEM_{prefix}_ALIGN"), align);
    for (field, offset) in offsets {
        emit_define_usize(
            out,
            &format!("CRUCIBLE_SHMEM_{prefix}_{field}_OFFSET"),
            *offset,
        );
    }
}

fn emit_define_bool(out: &mut String, name: &str, value: bool) {
    let value = if value { 1 } else { 0 };
    out.push_str(&format!("#define {name} {value}\n"));
}

fn emit_define_str(out: &mut String, name: &str, value: &str) {
    out.push_str(&format!("#define {name} \"{value}\"\n"));
}

fn emit_define_u8(out: &mut String, name: &str, value: u8) {
    out.push_str(&format!("#define {name} {value}u\n"));
}

fn emit_define_u32(out: &mut String, name: &str, value: u32) {
    out.push_str(&format!("#define {name} {value}u\n"));
}

fn emit_define_u64_hex(out: &mut String, name: &str, value: u64) {
    out.push_str(&format!("#define {name} UINT64_C(0x{value:016x})\n"));
}

fn emit_define_usize(out: &mut String, name: &str, value: usize) {
    out.push_str(&format!("#define {name} {value}u\n"));
}

fn emit_footer(out: &mut String) {
    out.push_str("#endif /* CRUCIBLE_SHMEM_ABI_H */\n");
}
