// Command aos-cloud-sql-reader observes one source-selected read-only snapshot.
//
// Configuration and credentials arrive through inherited private descriptors.
// The query is generated by the exact immutable AOS collector source selected
// at build time. No supplied SQL, writable executor, proxy, or remote /proc
// identity is admitted. Output preserves the server's actual JSON text bytes.
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"time"

	"cloud.google.com/go/cloudsqlconn"
	"github.com/jackc/pgx/v5"
)

const (
	maxConfig     = 128 << 10
	maxQuery      = 32 << 10
	maxRows       = 512 << 10
	maxCredential = 64 << 10
	maxWork       = 100 * time.Second
)

// These are actual package inputs, supplied by the hermetic source recipe.
// An unbound development executable refuses before reading credentials.
var pythonPath, querySourcePath, querySourceSHA, readerSourceSHA string

type configuration struct {
	Version          int             `json:"version"`
	ConnectionName   string          `json:"connectionName"`
	IPType           string          `json:"ipType"`
	Database         string          `json:"database"`
	Role             string          `json:"role"`
	Deployment       string          `json:"deployment"`
	Checkpoints      json.RawMessage `json:"checkpoints"`
	QuerySHA256      string          `json:"querySha256"`
	CutoffUnixNanos  string          `json:"cutoffUnixNanos"`
	MaximumWorkNanos string          `json:"maximumWorkNanos"`
}

type processPin struct {
	PID              int    `json:"pid"`
	OwnerUID         int    `json:"ownerUid"`
	StartTicks       string `json:"startTicks"`
	ExecutableSHA256 string `json:"executableSha256"`
}

func digest(raw []byte) string {
	value := sha256.Sum256(raw)
	return hex.EncodeToString(value[:])
}

func decode(raw []byte, result any) error {
	fields := json.NewDecoder(bytes.NewReader(raw))
	opening, err := fields.Token()
	if err != nil || opening != json.Delim('{') {
		return errors.New("read-only observation object refused")
	}
	seen := map[string]bool{}
	for fields.More() {
		name, err := fields.Token()
		key, ok := name.(string)
		if err != nil || !ok || seen[key] {
			return errors.New("read-only observation duplicate field refused")
		}
		seen[key] = true
		if err := fields.Decode(new(json.RawMessage)); err != nil {
			return errors.New("read-only observation field refused")
		}
	}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(result); err != nil {
		return errors.New("read-only observation schema refused")
	}
	if err := decoder.Decode(new(any)); err != io.EOF {
		return errors.New("read-only observation trailing data refused")
	}
	return nil
}

func bounded(source io.Reader, maximum int64) ([]byte, error) {
	raw, err := io.ReadAll(io.LimitReader(source, maximum+1))
	if err != nil || int64(len(raw)) > maximum {
		return nil, errors.New("read-only observation input bound refused")
	}
	return raw, nil
}

func privateDescriptor(number string, maximum int64) ([]byte, error) {
	fd, err := strconv.Atoi(number)
	if err != nil || fd < 3 {
		return nil, errors.New("private inherited input descriptor refused")
	}
	stream := os.NewFile(uintptr(fd), "private-input")
	defer stream.Close()
	before, err := stream.Stat()
	if err != nil || !before.Mode().IsRegular() || before.Mode().Perm()&0077 != 0 || before.Size() > maximum {
		return nil, errors.New("private input custody refused")
	}
	identity, ok := before.Sys().(*syscall.Stat_t)
	if !ok || identity.Uid != uint32(os.Getuid()) || identity.Nlink != 1 {
		return nil, errors.New("private input owner or link custody refused")
	}
	raw, err := bounded(io.NewSectionReader(stream, 0, maximum+1), maximum)
	after, statErr := stream.Stat()
	if err != nil || statErr != nil || after.Size() != before.Size() || int64(len(raw)) != before.Size() ||
		!after.ModTime().Equal(before.ModTime()) {
		return nil, errors.New("private input changed or incomplete")
	}
	observed := after.Sys().(*syscall.Stat_t)
	if observed.Dev != identity.Dev || observed.Ino != identity.Ino || observed.Nlink != identity.Nlink ||
		observed.Mode != identity.Mode || observed.Uid != identity.Uid || observed.Gid != identity.Gid ||
		observed.Ctim != identity.Ctim {
		return nil, errors.New("private input inode custody changed")
	}
	return raw, nil
}

func installed(path string, maximum int64) ([]byte, error) {
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil || filepath.Clean(path) != path || resolved != path ||
		!regexp.MustCompile(`^/nix/store/[0-9a-z]{32}-[^/]+/.+`).MatchString(path) {
		return nil, errors.New("source-built input path refused")
	}
	store, err := os.Stat("/nix/store")
	if err != nil {
		return nil, errors.New("immutable store custody unavailable")
	}
	owner := store.Sys().(*syscall.Stat_t).Uid
	for current := path; current != "/nix/store"; current = filepath.Dir(current) {
		info, err := os.Lstat(current)
		if err != nil || info.Mode().Perm()&0222 != 0 || info.Sys().(*syscall.Stat_t).Uid != owner {
			return nil, errors.New("immutable source ancestor refused")
		}
	}
	stream, err := os.Open(path)
	if err != nil {
		return nil, errors.New("immutable source open refused")
	}
	defer stream.Close()
	return bounded(stream, maximum)
}

func selfPin() (processPin, error) {
	raw, err := os.ReadFile("/proc/self/stat")
	if err != nil {
		return processPin{}, errors.New("local reader lifetime unavailable")
	}
	fields := strings.Fields(string(raw[strings.LastIndexByte(string(raw), ')')+1:]))
	if len(fields) < 20 {
		return processPin{}, errors.New("local reader lifetime shape refused")
	}
	stream, err := os.Open("/proc/self/exe")
	if err != nil {
		return processPin{}, errors.New("local reader executable unavailable")
	}
	defer stream.Close()
	hash := sha256.New()
	if _, err := io.Copy(hash, stream); err != nil {
		return processPin{}, errors.New("local reader executable observation refused")
	}
	return processPin{os.Getpid(), os.Getuid(), fields[19], hex.EncodeToString(hash.Sum(nil))}, nil
}

func observationContext(selected configuration, now time.Time) (context.Context, context.CancelFunc, error) {
	if selected.Version != 1 || !regexp.MustCompile(`^[a-z][a-z0-9-]{0,62}:[a-z][a-z0-9-]{0,62}:[a-z][a-z0-9-]{0,62}$`).MatchString(selected.ConnectionName) ||
		(selected.IPType != "public" && selected.IPType != "private" && selected.IPType != "psc") ||
		!regexp.MustCompile(`^[a-z][a-z0-9_]{0,62}$`).MatchString(selected.Database) ||
		!regexp.MustCompile(`^[a-z][a-z0-9_]{0,62}$`).MatchString(selected.Role) ||
		!regexp.MustCompile(`^[a-z0-9-]{1,128}$`).MatchString(selected.Deployment) ||
		!regexp.MustCompile(`^[0-9a-f]{64}$`).MatchString(selected.QuerySHA256) {
		return nil, nil, errors.New("selected read-only resource refused")
	}
	decimal := regexp.MustCompile(`^[1-9][0-9]{0,19}$`)
	if !decimal.MatchString(selected.CutoffUnixNanos) || !decimal.MatchString(selected.MaximumWorkNanos) {
		return nil, nil, errors.New("original observation cutoff refused")
	}
	cutoff, err := strconv.ParseInt(selected.CutoffUnixNanos, 10, 64)
	work, workErr := strconv.ParseInt(selected.MaximumWorkNanos, 10, 64)
	if err != nil || workErr != nil || work <= 0 || work > int64(maxWork) {
		return nil, nil, errors.New("bounded observation duration refused")
	}
	remaining := time.Unix(0, cutoff).Sub(now)
	if remaining <= 2*time.Second {
		return nil, nil, errors.New("original observation window elapsed")
	}
	if time.Duration(work) > remaining-2*time.Second {
		work = int64(remaining - 2*time.Second)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(work))
	return ctx, cancel, nil
}

const generator = `import hashlib,json,runpy,sys
raw=sys.stdin.buffer.read(131073)
if len(raw)>131072: raise ValueError('bound')
source=runpy.run_path(sys.argv[1])
selected=source['native_sql_json'](raw)
source['native_sql_closed'](selected,{'version','connectionName','ipType','database','role','deployment','checkpoints','querySha256','cutoffUnixNanos','maximumWorkNanos'})
query=source['native_sql_query'](selected['checkpoints'],selected['deployment'],selected['role']).encode()
if hashlib.sha256(query).hexdigest()!=selected['querySha256']: raise ValueError('query binding')
sys.stdout.buffer.write(query)
`

func generatedQuery(ctx context.Context, raw []byte) ([]byte, error) {
	source, err := installed(querySourcePath, 1<<20)
	if err != nil || querySourceSHA == "" || readerSourceSHA == "" || digest(source) != querySourceSHA {
		return nil, errors.New("actual query source binding refused")
	}
	if _, err := installed(pythonPath, 128<<20); err != nil {
		return nil, errors.New("actual source-built Python binding refused")
	}
	command := exec.CommandContext(ctx, pythonPath, "-B", "-E", "-c", generator, querySourcePath)
	command.Env = []string{"LANG=C.UTF-8"}
	command.Stdin = bytes.NewReader(raw)
	command.WaitDelay = time.Second
	stdout, err := command.StdoutPipe()
	if err != nil {
		return nil, errors.New("source query pipe refused")
	}
	// Generator exceptions may include input metadata. They never enter logs.
	command.Stderr = io.Discard
	if err := command.Start(); err != nil {
		return nil, errors.New("source query generator unavailable")
	}
	query, readErr := bounded(stdout, maxQuery)
	if readErr != nil && command.Process != nil {
		command.Process.Kill()
	}
	if err := command.Wait(); err != nil || readErr != nil || len(query) == 0 {
		return nil, errors.New("source-selected query refused")
	}
	return query, nil
}

func queryRows(ctx context.Context, selected configuration, query, adc, password []byte) ([]byte, error) {
	dialer, err := cloudsqlconn.NewDialer(ctx, cloudsqlconn.WithCredentialsJSON(adc), cloudsqlconn.WithLazyRefresh())
	if err != nil {
		return nil, errors.New("official connector credentials refused")
	}
	defer dialer.Close()
	config, err := pgx.ParseConfig("dbname=unused user=unused password=unused sslmode=disable")
	if err != nil {
		return nil, errors.New("source-fixed database configuration refused")
	}
	config.Database, config.User, config.Password = selected.Database, selected.Role, string(password)
	config.ConnectTimeout = 15 * time.Second
	config.MaxProtocolMessageBodyLen = maxRows + (16 << 10)
	config.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
	config.RuntimeParams["default_transaction_read_only"] = "on"
	config.RuntimeParams["statement_timeout"] = "15000"
	config.RuntimeParams["lock_timeout"] = "5000"
	config.DialFunc = func(ctx context.Context, _, _ string) (net.Conn, error) {
		var option cloudsqlconn.DialOption
		switch selected.IPType {
		case "public":
			option = cloudsqlconn.WithPublicIP()
		case "private":
			option = cloudsqlconn.WithPrivateIP()
		case "psc":
			option = cloudsqlconn.WithPSC()
		default:
			return nil, errors.New("unselected connector network refused")
		}
		return dialer.Dial(ctx, selected.ConnectionName, option)
	}
	connection, err := pgx.ConnectConfig(ctx, config)
	if err != nil {
		return nil, errors.New("official connector database authentication refused")
	}
	defer connection.Close(ctx)
	results, err := connection.PgConn().Exec(ctx, string(query)).ReadAll()
	if err != nil || len(results) > 8 {
		return nil, errors.New("read-only selected query refused or unknown")
	}
	var row []byte
	for _, result := range results {
		if len(result.Rows) == 0 {
			continue
		}
		if row != nil || len(result.Rows) != 1 || len(result.Rows[0]) != 1 || len(result.Rows[0][0]) > maxRows {
			return nil, errors.New("read-only exact row framing refused")
		}
		row = result.Rows[0][0]
	}
	if len(row) == 0 {
		return nil, errors.New("read-only selected snapshot is absent")
	}
	// These are checked server facts, not a normalization of NULL endpoints.
	var observed struct {
		Database   string            `json:"database"`
		User       string            `json:"user"`
		ReadOnly   string            `json:"readOnly"`
		Isolation  string            `json:"isolation"`
		Admissions []json.RawMessage `json:"admissions"`
		Chunks     []json.RawMessage `json:"chunks"`
	}
	if json.Unmarshal(row, &observed) != nil || observed.Database != selected.Database || observed.User != selected.Role ||
		observed.ReadOnly != "on" || observed.Isolation != "repeatable read" ||
		len(observed.Admissions)+len(observed.Chunks) > 64 {
		return nil, errors.New("actual snapshot database role or bound refused")
	}
	return row, nil
}

func run(arguments []string) error {
	if len(arguments) != 4 {
		return errors.New("expected inherited configuration, two private inputs, and owned start barrier")
	}
	startFD, err := strconv.Atoi(arguments[3])
	if err != nil || startFD < 3 {
		return errors.New("owned start descriptor refused")
	}
	start := os.NewFile(uintptr(startFD), "owned-start")
	barrier, startErr := bounded(start, 2)
	start.Close()
	if startErr != nil || !bytes.Equal(barrier, []byte{1}) {
		return errors.New("owned source supervisor start refused")
	}
	raw, err := privateDescriptor(arguments[0], maxConfig)
	if err != nil {
		return err
	}
	var selected configuration
	if err := decode(raw, &selected); err != nil {
		return err
	}
	ctx, cancel, err := observationContext(selected, time.Now())
	if err != nil {
		return err
	}
	defer cancel()
	query, err := generatedQuery(ctx, raw)
	if err != nil {
		return err
	}
	adc, err := privateDescriptor(arguments[1], maxCredential)
	if err != nil {
		return err
	}
	password, err := privateDescriptor(arguments[2], maxCredential)
	if err != nil || len(password) == 0 {
		return errors.New("private database authentication input refused")
	}
	before, err := selfPin()
	if err != nil {
		return err
	}
	started := time.Now()
	rows, err := queryRows(ctx, selected, query, adc, password)
	if err != nil {
		return err
	}
	after, err := selfPin()
	cutoff, cutoffErr := strconv.ParseInt(selected.CutoffUnixNanos, 10, 64)
	if err != nil || cutoffErr != nil || before != after || ctx.Err() != nil || time.Now().UnixNano() > cutoff {
		return errors.New("reader lifetime or original cutoff changed")
	}
	header, err := json.Marshal(map[string]any{"version": 1, "claim": "source_checked_official_connector_snapshot",
		"connectionName": selected.ConnectionName, "ipType": selected.IPType,
		"querySha256": digest(query), "rowsSha256": digest(rows),
		"readerBefore": before, "readerAfter": after, "beforeUnixNanos": strconv.FormatInt(started.UnixNano(), 10),
		"afterUnixNanos": strconv.FormatInt(time.Now().UnixNano(), 10), "elapsedNanos": strconv.FormatInt(time.Since(started).Nanoseconds(), 10),
		"querySourceSha256": querySourceSHA, "connectorSourceSha256": readerSourceSHA,
		"remoteProcessCustody": nil, "peerCertificateObservation": nil})
	if err != nil || len(header) > 16<<10 {
		return errors.New("bounded reader receipt refused")
	}
	if err := binary.Write(os.Stdout, binary.BigEndian, uint32(len(header))); err != nil {
		return err
	}
	if _, err := os.Stdout.Write(header); err != nil {
		return err
	}
	_, err = os.Stdout.Write(rows)
	return err
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		// Driver errors can include credentials or URLs. Keep a fixed refusal.
		fmt.Fprintln(os.Stderr, "Readonly managed SQL observation refused or incomplete")
		os.Exit(1)
	}
}
