##! Package-owned OpenSSH configuration and native service dependencies.
{
  config,
  lib,
  package,
  ...
}: let
  cfg = config.aos.services.ssh;
  types = lib.types;
  operations = config.aos.abilities;
  authorizedKeysDirectory = "ssh/authorized_keys";
  authorizedKeysPath = "/etc/${authorizedKeysDirectory}";
  boundedString = types.str;
  boundedStrings = types.listOf boundedString;
  authorizedKeysCommand = types.submodule {
    options = {
      executable = lib.mkOption {
        type = types.submodule {
          options = {
            path = lib.mkOption {type = types.deferred types.str;};
            arguments = lib.mkOption {
              type = types.listOf (types.deferred types.str);
              default = [];
            };
          };
        };
      };
      user = lib.mkOption {type = types.str;};
    };
  };
  command = entryPoint: arguments: {
    executable = {
      path = "${package}/${entryPoint}";
      inherit arguments;
    };
    ignore_failure = false;
  };
  serviceLifecycle = {
    description,
    executionModel,
    start,
    remainAfterExit ? false,
    restart ? "never",
    restartDelayMillis ? 0,
    configurationChangeAction ? "restart",
  }: {
    inherit description start restart;
    execution_model = executionModel;
    environment_files = [];
    condition = [];
    pre_start = [];
    post_start = [];
    stop = [];
    post_stop = [];
    restart_delay_millis = restartDelayMillis;
    configuration_change_action = configurationChangeAction;
    remain_after_exit = remainAfterExit;
    start_timeout_millis = 90000;
    stop_timeout_millis = 90000;
  };

  sshdConfigPrefix = ''
    # /etc/ssh/sshd_config - generated by the OpenSSH package module.
    # Hardened OpenSSH server configuration. Do not edit manually.

    Port ${toString cfg.port}
    AddressFamily any
    ListenAddress 0.0.0.0
    ListenAddress ::

    HostKey /var/etc/ssh/ssh_host_ed25519_key

    PermitRootLogin ${cfg.permitRootLogin}
    PasswordAuthentication ${
      if cfg.passwordAuthentication
      then "yes"
      else "no"
    }
    KbdInteractiveAuthentication ${
      if cfg.kbdInteractiveAuthentication
      then "yes"
      else "no"
    }
    PubkeyAuthentication yes
    UsePAM ${
      if cfg.usePAM
      then "yes"
      else "no"
    }
    AuthorizedKeysFile ${cfg.authorizedKeysFile}
    MaxAuthTries ${toString cfg.maxAuthTries}

    ChallengeResponseAuthentication no
    HostbasedAuthentication no
    PermitEmptyPasswords no

    Ciphers ${builtins.concatStringsSep "," cfg.allowedCiphers}
    KexAlgorithms ${builtins.concatStringsSep "," cfg.allowedKexAlgorithms}
    MACs ${builtins.concatStringsSep "," cfg.allowedMACs}

    X11Forwarding ${
      if cfg.x11Forwarding
      then "yes"
      else "no"
    }
    PrintMotd no
    ${lib.optionalString (cfg.banner != null) "Banner ${cfg.banner}"}
    PrintLastLog yes
    TCPKeepAlive yes
    UseDNS no

    StrictModes yes
    PermitUserEnvironment no
    AllowAgentForwarding no
    AllowTcpForwarding no
    PermitTunnel no
    MaxSessions 10
    MaxStartups 10:30:60
    LoginGraceTime 30

    SyslogFacility AUTH
    LogLevel VERBOSE

  '';
  sshdConfigSuffix = ''

    ClientAliveInterval 300
    ClientAliveCountMax 3
  '';
  authorizedKeysCommandFragments = lib.optionals (cfg.authorizedKeysCommand != null) [
    "AuthorizedKeysCommand "
    cfg.authorizedKeysCommand.executable.path
    " ${builtins.concatStringsSep " " cfg.authorizedKeysCommand.executable.arguments}\nAuthorizedKeysCommandUser ${cfg.authorizedKeysCommand.user}\n"
  ];
  configurationFragments =
    [sshdConfigPrefix]
    ++ authorizedKeysCommandFragments
    ++ [
      "\nSubsystem sftp ${package}/libexec/sftp-server"
      sshdConfigSuffix
    ];
  keygen = {
    service = "sshd-keygen";
    autoStart = false;
    lifecycle = serviceLifecycle {
      description = "Generate SSH host keys";
      executionModel = "oneshot";
      remainAfterExit = true;
      start = [
        (command
          "libexec/aos-openssh-host-key"
          [])
      ];
    };
    dependencies = {
      prerequisites = [(operations.filesystem.operations.directory.effects.ssh-host-keys.outputs.resource)];
      after = [];
      before = [];
      requires = [];
      wants = [];
    };
    readiness = {
      mechanism = "successful-exit";
      signal_scope = "none";
      timeout_millis = 90000;
    };
    environment = {
      variables = {};
      search_path = [];
    };
  };
  hostPolicyReadiness = {
    service = "aos-ssh-ready";
    autoStart = false;
    lifecycle = serviceLifecycle {
      description = "Wait for live AOS host authentication policy";
      executionModel = "oneshot";
      remainAfterExit = true;
      start = [
        (command
          "libexec/aos-openssh-host-policy-wait"
          [])
      ];
    };
    readiness = {
      mechanism = "successful-exit";
      signal_scope = "none";
      timeout_millis = 20000;
    };
    environment = {
      variables = {};
      search_path = [];
    };
  };
  daemon = {
    service = "sshd";
    lifecycle = serviceLifecycle {
      description = "OpenSSH daemon";
      executionModel = "foreground";
      restart = "on-failure";
      restartDelayMillis = 5000;
      start = [
        (command
          "sbin/sshd"
          ["-D" "-f" "/etc/ssh/sshd_config"])
      ];
    };
    dependencies = {
      after = [
        (operations.network.operations.ready.effects.ssh.outputs.resource)
        (operations.serviceManagement.operations.realize.effects."ssh.sshd-keygen".outputs.resource)
        (operations.serviceManagement.operations.realize.effects."ssh.aos-ssh-ready".outputs.resource)
      ];
      before = [];
      requires = [(operations.serviceManagement.operations.realize.effects."ssh.sshd-keygen".outputs.resource)];
      wants = [
        (operations.network.operations.ready.effects.ssh.outputs.resource)
        (operations.serviceManagement.operations.realize.effects."ssh.aos-ssh-ready".outputs.resource)
      ];
      prerequisites = [
        (operations.filesystem.operations.directory.effects.ssh-privilege-separation.outputs.resource)
        (operations.configuration.operations.file.effects.ssh.outputs.resource)
      ];
    };
    supervision = {
      startup_protocol = "notification";
      notification_access = "main-process";
    };
    readiness = {
      mechanism = "process-signal";
      signal_scope = "main-process";
      timeout_millis = 90000;
    };
    reload = {
      strategy = "signal";
      commands = [];
      signal = "HUP";
      completion = "command-exit";
    };
    termination = {
      signal = "TERM";
      final_signal = "KILL";
      send_to_all_processes = false;
    };
    # The manager preserves image/operator-authored public keys and also creates
    # the default directory on hosts without a baked key. The daemon only reads it.
    configuration.views = [
      {
        name = "authorized-keys";
        source = authorizedKeysPath;
        optional = false;
      }
    ];
    directories.managed = [
      {
        path = "sshd";
        purpose = "runtime";
        mode = "0755";
        retention = "restart";
        owner = "root";
        group = "root";
      }
      {
        path = authorizedKeysDirectory;
        purpose = "configuration";
        mode = "0755";
        retention = "persistent";
        owner = "root";
        group = "root";
      }
    ];
    logging = {
      standard_output = "structured";
      standard_error = "structured";
      directories = [];
      directory_mode = "0750";
    };
  };
in {
  options.aos.services = lib.mkOption {
    type = lib.types.lazyAttrsOf (lib.types.submodule ({name, ...}: {
      options = lib.optionalAttrs (name == "ssh") {
        banner = lib.mkOption {
          type = types.nullOr (types.strMatching "/.*");
          default = null;
          description = "Absolute pre-authentication banner file, or null to disable it.";
        };
        port = lib.mkOption {
          type = types.ints.between 1 65535;
          default = 22;
          description = "TCP port on which the OpenSSH server listens.";
        };
        permitRootLogin = lib.mkOption {
          type = types.enum ["yes" "prohibit-password" "forced-commands-only" "no"];
          default = "prohibit-password";
          description = "Root login policy enforced by the OpenSSH server.";
        };
        passwordAuthentication = lib.mkOption {
          type = types.bool;
          default = false;
          description = "Allow password authentication.";
        };
        kbdInteractiveAuthentication = lib.mkOption {
          type = types.bool;
          default = false;
          description = "Allow keyboard-interactive authentication.";
        };
        usePAM = lib.mkOption {
          type = types.bool;
          default = true;
          description = "Use PAM for account and session management.";
        };
        x11Forwarding = lib.mkOption {
          type = types.bool;
          default = false;
          description = "Allow X11 forwarding.";
        };
        maxAuthTries = lib.mkOption {
          type = types.ints.between 1 1024;
          default = 3;
          description = "Maximum authentication attempts per connection.";
        };
        allowedCiphers = lib.mkOption {
          type = boundedStrings;
          default = [
            "chacha20-poly1305@openssh.com"
            "aes256-gcm@openssh.com"
            "aes128-gcm@openssh.com"
          ];
          description = "Allowed symmetric ciphers.";
        };
        allowedKexAlgorithms = lib.mkOption {
          type = boundedStrings;
          default = ["curve25519-sha256" "curve25519-sha256@libssh.org"];
          description = "Allowed key exchange algorithms.";
        };
        allowedMACs = lib.mkOption {
          type = boundedStrings;
          default = ["hmac-sha2-512-etm@openssh.com" "hmac-sha2-256-etm@openssh.com"];
          description = "Allowed message authentication algorithms.";
        };
        authorizedKeysFile = lib.mkOption {
          type = boundedString;
          default = "${authorizedKeysPath}/%u";
          description = "Path pattern used to find authorized keys.";
        };
        authorizedKeysCommand = lib.mkOption {
          type = types.nullOr authorizedKeysCommand;
          default = null;
          extensible = true;
          description = "Symbolic package command used to look up authorized keys.";
        };
      };
    }));
    default = {};
  };

  config = lib.mkMerge [
    {
      aos.services = {
        ssh = lib.mkDefault daemon;
        "ssh.sshd-keygen" = lib.mkDefault (keygen // {enable = lib.mkDefault cfg.enable;});
        "ssh.aos-ssh-ready" = lib.mkDefault (hostPolicyReadiness // {enable = lib.mkDefault cfg.enable;});
      };
    }
    (lib.mkIf cfg.enable {
      system.checks.ssh = import ./runtime-tests.nix {inherit cfg lib;};
      aos.pam.packageServices = lib.mkIf cfg.usePAM {
        sshd = {
          unixAuth = cfg.passwordAuthentication;
          startSession = true;
          setLoginUid = true;
        };
      };
      aos.abilities = {
        identity.operations = {
          group.effects.ssh.input = {
            name = "sshd";
            requested_id = 198;
          };
          principal.effects.ssh.input = {
            name = "sshd";
            requested_id = 198;
            description = "OpenSSH Privilege Separation";
            home_directory = "/var/empty";
            primary_group = operations.identity.operations.group.effects.ssh.outputs.name;
          };
        };
        filesystem.operations.directory.effects = {
          ssh-host-keys = {
            lifetime = "persistent";
            input = {
              path = "/var/etc/ssh";
              mode = "0755";
              owner = "root";
              group = "root";
            };
          };
          ssh-privilege-separation.input = {
            path = "/var/empty";
            mode = "0755";
            owner = "root";
            group = "root";
          };
        };
        configuration.operations.file.effects.ssh.input = {
          path = "/etc/ssh/sshd_config";
          fragments = configurationFragments;
          mode = "0444";
        };
        network.operations.ready.effects.ssh.input = {
          scope = "address-configured";
          families = ["ipv4" "ipv6"];
        };
      };
      aos.networkPolicy = {
        enable = lib.mkDefault true;
        ingress.ssh.endpoints = [
          {
            transport = "tcp";
            port = cfg.port;
          }
        ];
      };
    })
  ];
}
