##! Package-owned OpenSSH configuration and service declarations.
{
  config,
  lib,
  packageName,
  ...
}: let
  cfg = config.aos.services.ssh;
  abilityTypes = lib.abilities.types;
  serviceManagement = lib.abilities.interfaces.serviceManagement;
  serviceTypes = serviceManagement.types;
  interfaces = serviceManagement.interfaces;
  resultOf = lib.abilities.resultOf;
  consumerInstance = "ssh";

  boundedString = abilityTypes.string {
    maxLength = abilityTypes.limits.maxStringLength;
    syntax = null;
  };
  boundedStrings = abilityTypes.list {
    element = boundedString;
    maxItems = 256;
  };
  authorizedKeysCommand = abilityTypes.record {
    fields = {
      executable = abilityTypes.artifactPathReference;
      arguments = boundedStrings;
      user = abilityTypes.principalName;
    };
  };
  producer = key: interface: parameters:
    serviceManagement.forProducer {
      inherit consumerInstance key interface parameters;
    };
  command = artifact: entryPoint: arguments: {
    executable = {
      inherit artifact arguments;
      entry_point = entryPoint;
    };
    ignore_failure = false;
  };
  serviceLifecycle = {
    description,
    executionModel,
    start,
    remainAfterExit ? false,
    restart ? "never",
    restartDelayMillis ? 0,
    configurationChangeAction ? "restart",
  }: {
    inherit description start restart;
    execution_model = executionModel;
    environment_files = [];
    condition = [];
    pre_start = [];
    post_start = [];
    stop = [];
    post_stop = [];
    restart_delay_millis = restartDelayMillis;
    configuration_change_action = configurationChangeAction;
    remain_after_exit = remainAfterExit;
    start_timeout_millis = 90000;
    stop_timeout_millis = 90000;
  };

  sshdConfigPrefix = ''
    # /etc/ssh/sshd_config - generated by the OpenSSH package ability module.
    # Hardened OpenSSH server configuration. Do not edit manually.

    Port ${toString cfg.port}
    AddressFamily any
    ListenAddress 0.0.0.0
    ListenAddress ::

    HostKey /var/etc/ssh/ssh_host_ed25519_key

    PermitRootLogin ${cfg.permitRootLogin}
    PasswordAuthentication ${
      if cfg.passwordAuthentication
      then "yes"
      else "no"
    }
    KbdInteractiveAuthentication ${
      if cfg.kbdInteractiveAuthentication
      then "yes"
      else "no"
    }
    PubkeyAuthentication yes
    UsePAM ${
      if cfg.usePAM
      then "yes"
      else "no"
    }
    AuthorizedKeysFile ${cfg.authorizedKeysFile}
    MaxAuthTries ${toString cfg.maxAuthTries}

    ChallengeResponseAuthentication no
    HostbasedAuthentication no
    PermitEmptyPasswords no

    Ciphers ${builtins.concatStringsSep "," cfg.allowedCiphers}
    KexAlgorithms ${builtins.concatStringsSep "," cfg.allowedKexAlgorithms}
    MACs ${builtins.concatStringsSep "," cfg.allowedMACs}

    X11Forwarding ${
      if cfg.x11Forwarding
      then "yes"
      else "no"
    }
    PrintMotd no
    ${lib.optionalString (cfg.banner != null) "Banner ${cfg.banner}"}
    PrintLastLog yes
    TCPKeepAlive yes
    UseDNS no

    StrictModes yes
    PermitUserEnvironment no
    AllowAgentForwarding no
    AllowTcpForwarding no
    PermitTunnel no
    MaxSessions 10
    MaxStartups 10:30:60
    LoginGraceTime 30

    SyslogFacility AUTH
    LogLevel VERBOSE

  '';
  sshdConfigSuffix = ''

    ClientAliveInterval 300
    ClientAliveCountMax 3
  '';
  authorizedKeysCommandFragments = lib.optionals (cfg.authorizedKeysCommand != null) [
    {
      kind = "literal";
      text = "AuthorizedKeysCommand ";
    }
    {
      kind = "artifact-file-path";
      reference = cfg.authorizedKeysCommand.executable;
    }
    {
      kind = "literal";
      text =
        " ${builtins.concatStringsSep " " cfg.authorizedKeysCommand.arguments}\n"
        + "AuthorizedKeysCommandUser ${cfg.authorizedKeysCommand.user}\n";
    }
  ];

  group = producer "sshd-group" interfaces.groupResolution {
    name = "sshd";
    allocation = "managed";
    requested_id = 198;
  };
  principal = producer "sshd-principal" interfaces.principalResolution {
    name = "sshd";
    allocation = "managed";
    requested_id = 198;
    description = "OpenSSH Privilege Separation";
    home_directory = "/var/empty";
    login_access = "disabled";
    primary_group = resultOf "sshd-group" "group-name";
    supplementary_groups = [];
  };
  localFilesystems = producer "local-filesystems" interfaces.filesystemReadiness {
    scope = "local-filesystems";
  };
  network = producer "network-readiness" interfaces.networkReadiness {
    scope = "configured-connectivity";
    address_families = ["ipv4" "ipv6"];
  };
  hostKeyStorage = producer "host-key-storage" interfaces.persistentStorageAllocation {
    name = "openssh-host-keys";
    purpose = "state";
    mode = "0700";
    requested_path = "/var/etc/ssh";
    owner = "root";
    group = "root";
  };
  ingress = producer "network-ingress" lib.abilities.interfaces.networkPolicy.interfaces.ingress {
    endpoints = [
      {
        transport = "tcp";
        port = cfg.port;
      }
    ];
    prerequisites = [];
  };
  configurationSource = serviceManagement.forConfiguration {
    inherit serviceTypes consumerInstance;
    declaration = {
      name = "sshd-config-source";
      source = {
        kind = "interpolated-text";
        fragments =
          [
            {
              kind = "literal";
              text = sshdConfigPrefix;
            }
          ]
          ++ authorizedKeysCommandFragments
          ++ [
            {
              kind = "literal";
              text = "\nSubsystem sftp ";
            }
            {
              kind = "artifact-file-path";
              reference = {
                artifact = lib.abilities.packageOutput {};
                path = "libexec/sftp-server";
              };
            }
            {
              kind = "literal";
              text = sshdConfigSuffix;
            }
          ];
        maximum_size_bytes = abilityTypes.limits.maxDocumentBytes;
      };
      mode = "0444";
    };
  };
  filesystemEntries = serviceManagement.forProducers {
    inherit consumerInstance;
    interface = interfaces.filesystemEntry;
    methods = ["materialize" "observe" "release"];
    producers = [
      {
        key = "sshd-config";
        parameters = {
          name = "sshd-config";
          entry = {
            kind = "copied-file";
            source = {
              kind = "execution-path";
              resource = resultOf "sshd-config-source" "resource";
              path = resultOf "sshd-config-source" "planned-path";
            };
            maximum_size_bytes = abilityTypes.limits.maxSafeInteger;
          };
          destination = "/etc/ssh/sshd_config";
          owner = "root";
          group = "root";
          mode = "0444";
          prerequisites = [
            (resultOf "sshd-config-source" "resource")
            (resultOf "local-filesystems" "resource")
          ];
        };
      }
      {
        key = "authorized-keys-directory";
        parameters = {
          name = "ssh-authorized-keys-directory";
          entry.kind = "directory";
          destination = "/etc/ssh/authorized_keys";
          owner = "root";
          group = "root";
          mode = "0755";
          prerequisites = [(resultOf "local-filesystems" "resource")];
        };
      }
      {
        key = "privilege-separation-directory";
        parameters = {
          name = "sshd-privilege-separation-directory";
          entry.kind = "directory";
          destination = "/var/empty";
          owner = "root";
          group = "root";
          mode = "0755";
          prerequisites = [(resultOf "local-filesystems" "resource")];
        };
      }
    ];
  };

  keygen = serviceManagement.forService {
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "sshd-keygen";
      enabled = false;
      lifecycle = serviceLifecycle {
        description = "Generate SSH host keys";
        executionModel = "oneshot";
        remainAfterExit = true;
        start = [
          (command
            (lib.abilities.packageOutput {})
            "libexec/aos-openssh-host-key"
            [])
        ];
      };
      dependencies = {
        prerequisites = [(resultOf "host-key-storage" "resource")];
        after = [];
        before = [];
        requires = [];
        wants = [];
      };
      readiness = {
        mechanism = "successful-exit";
        signal_scope = "none";
        timeout_millis = 90000;
      };
      environment = {
        variables = {};
        search_path = [];
      };
    };
  };
  hostPolicyReadiness = serviceManagement.forService {
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "aos-ssh-ready";
      enabled = false;
      lifecycle = serviceLifecycle {
        description = "Wait for live AOS host authentication policy";
        executionModel = "oneshot";
        remainAfterExit = true;
        start = [
          (command
            (lib.abilities.packageOutput {})
            "libexec/aos-openssh-host-policy-wait"
            [])
        ];
      };
      readiness = {
        mechanism = "successful-exit";
        signal_scope = "none";
        timeout_millis = 20000;
      };
      environment = {
        variables = {};
        search_path = [];
      };
    };
  };
  daemon = serviceManagement.forService {
    inherit serviceTypes consumerInstance;
    declaration = {
      service = "sshd";
      enabled = true;
      lifecycle = serviceLifecycle {
        description = "OpenSSH daemon";
        executionModel = "foreground";
        restart = "on-failure";
        restartDelayMillis = 5000;
        start = [
          (command
            (lib.abilities.packageOutput {})
            "sbin/sshd"
            ["-D" "-f" "/etc/ssh/sshd_config"])
        ];
      };
      dependencies = {
        after = [
          (resultOf "network-readiness" "resource")
          (resultOf "sshd-keygen-lifecycle" "resource")
          (resultOf "aos-ssh-ready-lifecycle" "resource")
        ];
        before = [];
        requires = [(resultOf "sshd-keygen-lifecycle" "resource")];
        wants = [
          (resultOf "network-readiness" "resource")
          (resultOf "aos-ssh-ready-lifecycle" "resource")
        ];
        prerequisites = [
          (resultOf "authorized-keys-directory" "resource")
          (resultOf "privilege-separation-directory" "resource")
          (resultOf "sshd-config" "resource")
        ];
      };
      supervision = {
        startup_protocol = "notification";
        notification_access = "main-process";
      };
      readiness = {
        mechanism = "process-signal";
        signal_scope = "main-process";
        timeout_millis = 90000;
      };
      reload = {
        strategy = "signal";
        commands = [];
        signal = "HUP";
        completion = "command-exit";
      };
      termination = {
        signal = "TERM";
        final_signal = "KILL";
        send_to_all_processes = false;
      };
      directories.managed = [
        {
          path = "sshd";
          purpose = "runtime";
          mode = "0755";
          retention = "restart";
          owner = "root";
          group = "root";
        }
      ];
      logging = {
        standard_output = "structured";
        standard_error = "structured";
        directories = [];
        directory_mode = "0750";
      };
    };
  };

  fragments = [
    group
    principal
    localFilesystems
    network
    hostKeyStorage
    ingress
    configurationSource
    filesystemEntries
    keygen
    hostPolicyReadiness
    daemon
  ];
  definitions = builtins.map serviceManagement.splitDefinition fragments;
in {
  options.aos.services = lib.mkOption {
    type = lib.types.lazyAttrsOf (lib.types.submodule ({name, ...}: {
      options = lib.optionalAttrs (name == "ssh") {
        banner = lib.mkOption {
          type = abilityTypes.optional serviceTypes.hostPath;
          default = null;
          description = "Absolute pre-authentication banner file, or null to disable it.";
        };
        enable = lib.mkOption {
          type = abilityTypes.boolean;
          default = true;
          description = "Enable the OpenSSH server.";
        };
        port = lib.mkOption {
          type = abilityTypes.integer {
            minimum = 1;
            maximum = 65535;
          };
          default = 22;
          description = "TCP port on which the OpenSSH server listens.";
        };
        permitRootLogin = lib.mkOption {
          type = abilityTypes.enum ["yes" "prohibit-password" "forced-commands-only" "no"];
          default = "prohibit-password";
          description = "Root login policy enforced by the OpenSSH server.";
        };
        passwordAuthentication = lib.mkOption {
          type = abilityTypes.boolean;
          default = false;
          description = "Allow password authentication.";
        };
        kbdInteractiveAuthentication = lib.mkOption {
          type = abilityTypes.boolean;
          default = false;
          description = "Allow keyboard-interactive authentication.";
        };
        usePAM = lib.mkOption {
          type = abilityTypes.boolean;
          default = true;
          description = "Use PAM for account and session management.";
        };
        x11Forwarding = lib.mkOption {
          type = abilityTypes.boolean;
          default = false;
          description = "Allow X11 forwarding.";
        };
        maxAuthTries = lib.mkOption {
          type = abilityTypes.integer {
            minimum = 1;
            maximum = 1024;
          };
          default = 3;
          description = "Maximum authentication attempts per connection.";
        };
        allowedCiphers = lib.mkOption {
          type = boundedStrings;
          default = [
            "chacha20-poly1305@openssh.com"
            "aes256-gcm@openssh.com"
            "aes128-gcm@openssh.com"
          ];
          description = "Allowed symmetric ciphers.";
        };
        allowedKexAlgorithms = lib.mkOption {
          type = boundedStrings;
          default = ["curve25519-sha256" "curve25519-sha256@libssh.org"];
          description = "Allowed key exchange algorithms.";
        };
        allowedMACs = lib.mkOption {
          type = boundedStrings;
          default = ["hmac-sha2-512-etm@openssh.com" "hmac-sha2-256-etm@openssh.com"];
          description = "Allowed message authentication algorithms.";
        };
        authorizedKeysFile = lib.mkOption {
          type = boundedString;
          default = "/etc/ssh/authorized_keys/%u";
          description = "Path pattern used to find authorized keys.";
        };
        authorizedKeysCommand = lib.mkOption {
          type = abilityTypes.optional authorizedKeysCommand;
          default = null;
          extensible = true;
          description = "Symbolic package command used to look up authorized keys.";
        };
      };
    }));
    default = {};
  };

  config = lib.mkMerge [
    {aos.services.ssh = {};}
    {aos.abilities = lib.mkMerge (builtins.map (entry: entry.declarations) definitions);}
    (lib.mkIf cfg.enable {
      aos.pam.packageServices = lib.mkIf cfg.usePAM {
        sshd = {
          unixAuth = cfg.passwordAuthentication;
          startSession = true;
          setLoginUid = true;
        };
      };
      aos.abilities.runtimeChecks.ssh = {
        description = "SSH server checks";
        checks = [
          {
            name = "sshd-config";
            description = "sshd_config exists";
            script = ''
              vm.succeed("test -f /etc/ssh/sshd_config")
            '';
          }
          {
            name = "password-auth-disabled";
            description = "Password authentication is disabled";
            script = ''
              assert "PasswordAuthentication no" in vm.succeed("cat /etc/ssh/sshd_config")
            '';
          }
          {
            name = "sshd-use-pam";
            description = "sshd is configured to use PAM";
            script = ''
              assert "UsePAM ${
                if cfg.usePAM
                then "yes"
                else "no"
              }" in vm.succeed("cat /etc/ssh/sshd_config")
            '';
          }
          {
            name = "sshd-pam-config";
            description = "/etc/pam.d/sshd is present";
            script = ''
              vm.succeed("test -f /etc/pam.d/sshd")
            '';
          }
          {
            name = "sshd-pam-env-rule";
            description = "sshd PAM session stack invokes pam_env";
            script = ''
              assert "pam_env.so" in vm.succeed("cat /etc/pam.d/sshd")
            '';
          }
          {
            name = "pam-environment-has-path";
            description = "/etc/pam/environment publishes PATH";
            script = ''
              assert "PATH" in vm.succeed("cat /etc/pam/environment")
            '';
          }
          {
            name = "sshd-pam-limits-rule";
            description = "sshd PAM session stack invokes pam_limits";
            script = ''
              assert "pam_limits.so" in vm.succeed("cat /etc/pam.d/sshd")
            '';
          }
          {
            name = "ssh-noninteractive-inherits-path";
            description = "non-interactive ssh inherits the system PATH via pam_env";
            script = ''
              import textwrap

              vm.succeed(
                  textwrap.dedent(r"""
                      set -e
                      ssh-keygen -t ed25519 -N "" -f /tmp/aos-test-key -q
                      cat /tmp/aos-test-key.pub > /etc/ssh/authorized_keys/root
                  """).strip()
              )
              ssh_output = vm.wait_until_succeeds(
                  textwrap.dedent(r"""
                      ssh -i /tmp/aos-test-key \
                        -o StrictHostKeyChecking=no \
                        -o UserKnownHostsFile=/dev/null \
                        -o BatchMode=yes \
                        -o LogLevel=ERROR \
                        root@127.0.0.1 'echo $PATH'
                  """).strip(),
                  timeout=30,
              )
              assert "/run/current-system/sw/bin" in ssh_output, (
                  f"non-interactive ssh PATH missing expected entries: {ssh_output!r}"
              )
            '';
          }
        ];
      };
    })
    (lib.mkIf cfg.enable {
      aos.abilities = lib.mkMerge (
        [{instances.${consumerInstance} = {};}]
        ++ builtins.map (entry: entry.configured) definitions
      );
    })
  ];
}
