#ifndef _AOS_IOAUDIO_TYPES_H_
#define _AOS_IOAUDIO_TYPES_H_

enum {
  INPUT_MICROPHONE = 0x0201,
  OUTPUT_SPEAKER = 0x0301,
  OUTPUT_HEADPHONES = 0x0302,
  EXTERNAL_LINE_CONNECTOR = 0x0603,
};

#endif
