##! glibc-locales — UTF-8 locale data for AOS programs
{
  mkDerivation,
  buildPackages,
}: let
  version = buildPackages.glibc.version;
in
  mkDerivation {
    pname = "glibc-locales";
    inherit version;

    # localedef is a build-time generator; the emitted unarchived locale tree
    # is data consumed by the target libc.
    buildDeps = [buildPackages.glibc.bin];
    runtimeDeps = [];
    propagatedDeps = [];

    phases = [
      {
        name = "install";
        script = ''
          mkdir -p "$out/lib/locale"
          I18NPATH="${buildPackages.glibc.bin}/share/i18n" \
            "${buildPackages.glibc.bin}/bin/localedef" \
              --no-archive \
              --inputfile=C \
              --charmap=UTF-8 \
              "$out/lib/locale/C.UTF-8"
        '';
      }
    ];

    meta = {
      description = "UTF-8 locale data generated by the AOS C library";
      homepage = "https://www.gnu.org/software/libc/";
      license = "LGPL-2.1-or-later";
    };
  }
