//! Reopens the exact source-selected outer capability codec without root cycles.
//!
//! The original flat metadata root continues to bind original compatibility
//! contracts. The outer selection names that root, its original scenario and
//! the complete authored demand body as explicit positive dependencies. It is
//! regenerated by installed policy; JSON shape or media type cannot select it.

use crucible::{
    node_admission::{CAPABILITY_SELECTION_MEDIA_TYPE, CapabilitySelection},
    node_state::{StateError, VerifiedStateContent},
};
use crucible_node_contract::{ContentRef, canonical};

use super::source::error;
use crate::{
    node_observed_executor::factory::{NodeObservedError, refused},
    node_scenario::NodeScenario,
};

pub(super) struct CapabilityMetadata {
    selection: ContentRef,
    selection_body: Vec<u8>,
    requirements: ContentRef,
    requirements_body: Vec<u8>,
    dependencies: Vec<ContentRef>,
    credit: super::archive_credit::ArchiveCredit,
}

impl CapabilityMetadata {
    pub(super) fn new<'a>(
        baseline: &'a NodeScenario,
        selected: &'a NodeScenario,
        metadata_root: &ContentRef,
        metadata_members: impl Iterator<Item = &'a ContentRef>,
    ) -> Result<Self, NodeObservedError> {
        let reference = &selected.world.scenario_ref;
        if reference.media_type != CAPABILITY_SELECTION_MEDIA_TYPE {
            return Err(refused("preserving capability selection has another codec"));
        }
        let selection_body = body(selected, reference)?;
        let selection: CapabilitySelection =
            serde_json::from_value(canonical::parse_json(selection_body, 1024 * 1024)?)?;
        if selection.format != crucible::node_admission::CAPABILITY_SELECTION_FORMAT
            || selection.schema_version != 1
            || selection.base_scenario_ref != baseline.world.scenario_ref
            || selection.bindings.len() != baseline.compatibility.len()
            || baseline.world.node_bindings != selected.world.node_bindings
            || baseline.compatibility != selected.compatibility
        {
            return Err(refused("outer capability codec changes original contracts"));
        }
        for (binding, expected) in selection.bindings.iter().zip(&baseline.compatibility) {
            if binding.node != expected.node_id
                || binding.compatibility_hash != expected.identity()?
            {
                return Err(refused(
                    "outer capability binding differs from installed source",
                ));
            }
        }
        let requirements_body = body(selected, &selection.requirements_ref)?;
        if requirements_body.len() > 1024 * 1024 || selection_body.len() > 1024 * 1024 {
            return Err(refused(
                "outer capability codec exceeds original byte credit",
            ));
        }
        let credit = super::archive_credit::ArchiveCredit::new(
            metadata_root,
            reference,
            baseline.owners.len(),
            metadata_members.chain(
                baseline
                    .content
                    .iter()
                    .chain(&selected.content)
                    .map(|object| &object.reference),
            ),
        )?;
        let mut dependencies = vec![
            metadata_root.clone(),
            selection.base_scenario_ref,
            selection.requirements_ref.clone(),
            credit.reference().clone(),
        ];
        dependencies.sort();
        dependencies.dedup();
        Ok(Self {
            selection: reference.clone(),
            selection_body: selection_body.to_vec(),
            requirements: selection.requirements_ref,
            requirements_body: requirements_body.to_vec(),
            dependencies,
            credit,
        })
    }

    pub(super) fn contains(&self, reference: &ContentRef) -> bool {
        reference == &self.selection
            || reference == &self.requirements
            || reference == self.credit.reference()
    }

    pub(super) fn credit(&self) -> &super::archive_credit::ArchiveCredit {
        &self.credit
    }

    pub(super) fn dependencies(
        &self,
        reference: &ContentRef,
        bytes: &[u8],
        maximum: usize,
    ) -> Result<Option<Vec<ContentRef>>, StateError> {
        if reference == self.credit.reference() {
            if bytes != self.credit.body() {
                return Err(error("original complete archive credit body differs"));
            }
            return Ok(Some(Vec::new()));
        }
        if reference == &self.requirements {
            if bytes != self.requirements_body {
                return Err(error("original raw capability demand bytes differ"));
            }
            return Ok(Some(Vec::new()));
        }
        if reference != &self.selection {
            return Ok(None);
        }
        if bytes != self.selection_body || maximum < self.dependencies.len() {
            return Err(error(
                "original outer capability codec or dependency credit differs",
            ));
        }
        let mut dependencies = Vec::new();
        dependencies
            .try_reserve_exact(self.dependencies.len())
            .map_err(error)?;
        dependencies.extend(self.dependencies.iter().cloned());
        Ok(Some(dependencies))
    }

    pub(super) fn authenticate_complete(
        &self,
        content: &VerifiedStateContent,
    ) -> Result<(), StateError> {
        self.credit
            .authenticate(
                self.credit.reference(),
                content.get(self.credit.reference()),
            )
            .map_err(error)?;
        for (reference, bytes) in [
            (&self.selection, self.selection_body.as_slice()),
            (&self.requirements, self.requirements_body.as_slice()),
        ] {
            if content.get(reference) != Some(bytes) {
                return Err(error(
                    "signed original capability body is absent or differs",
                ));
            }
            reference.verify(bytes).map_err(error)?;
        }
        for reference in &self.dependencies {
            let bytes = content.get(reference).ok_or_else(|| {
                error("signed outer capability dependency is absent or has another full reference")
            })?;
            reference.verify(bytes).map_err(error)?;
        }
        Ok(())
    }
}

fn body<'a>(
    scenario: &'a NodeScenario,
    reference: &ContentRef,
) -> Result<&'a [u8], NodeObservedError> {
    let bytes = scenario
        .content
        .iter()
        .find(|object| &object.reference == reference)
        .ok_or_else(|| refused("source-selected capability object is absent"))?
        .bytes
        .as_slice();
    reference.verify(bytes)?;
    Ok(bytes)
}
