##! zram-generator — systemd generator for compressed swap and filesystems
{
  mkDerivation,
  fetchCargoDeps,
  fetchurl,
  rust,
  jq,
  pkg-config,
  lowdown,
  systemd,
}: let
  version = "1.2.1";
  upstreamSrc = fetchurl {
    urls = ["https://github.com/systemd/zram-generator/archive/refs/tags/v${version}.tar.gz"];
    hash = "sha256-nILNPbOG6C+6Kt/gHD0JQ2yenP48qLs0HX64gnaMWK8=";
  };
  src = mkDerivation {
    pname = "zram-generator-source";
    inherit version;
    src = upstreamSrc;
    buildDeps = [];
    runtimeDeps = [];
    propagatedDeps = [];
    phases = [
      {
        name = "unpack";
        script = ''
          tar xf "$src"
          cd zram-generator-${version}
        '';
      }
      {
        name = "install";
        script = ''
          mkdir -p "$out"
          cp -R . "$out/"
          cp ${./zram-generator.Cargo.lock} "$out/Cargo.lock"
        '';
      }
    ];
  };
  cargoDeps = fetchCargoDeps {
    inherit src;
    hash = "sha256-Nzrv8uaCpUeGraGe+DFNfO5hcIfK7p7AB0YbfW1EHdc=";
  };
in
  mkDerivation {
    pname = "zram-generator";
    inherit version src;

    buildDeps = [rust jq pkg-config lowdown];
    runtimeDeps = [systemd];
    propagatedDeps = [];
    disallowedReferences = [cargoDeps rust];

    passthru.systemdUnitInventory = {
      system = ["lib/systemd/system/systemd-zram-setup@.service"];
      user = [];
    };

    phases = [
      {
        name = "unpack";
        script = ''
          cp -R "$src" source
          chmod -R u+w source
          cd source
        '';
      }
      {
        name = "patch";
        script = ''
          # The integration harness replaces /proc/self/exe so generated units
          # remain path-independent. Use an absolute synthetic target because
          # glibc requires the executable link used for $ORIGIN expansion to
          # begin at the filesystem root when the test later spawns diff.
          sed -i 's|symlink("zram-generator",|symlink("/zram-generator",|' \
            tests/test_cases.rs
          find tests -type f -exec sed -i \
            's|# Automatically generated by zram-generator|# Automatically generated by /zram-generator|' \
            {} +
        '';
      }
      {
        name = "configure";
        script = ''
          export CARGO_HOME="$TMPDIR/cargo"
          export CARGO_INCREMENTAL=0
          mkdir -p "$CARGO_HOME" .cargo
          cat > .cargo/config.toml <<EOF
          [source.crates-io]
          replace-with = "vendored-sources"

          [source.vendored-sources]
          directory = "${cargoDeps}"
          EOF
        '';
      }
      {
        name = "build";
        script = ''
          export SYSTEMD_UTIL_DIR=${systemd}/lib/systemd
          cargo build --release --frozen --offline -j"$NIX_BUILD_CORES"

          sed \
            's|@SYSTEMD_SYSTEM_GENERATOR_DIR@|'"$out"'/lib/systemd/system-generators|' \
            units/systemd-zram-setup@.service.in \
            > units/systemd-zram-setup@.service

          lowdown -Tman man/zram-generator.md > man/zram-generator.8
          lowdown -Tman man/zram-generator.conf.md > man/zram-generator.conf.5
        '';
      }
      {
        name = "check";
        script = ''
          export SYSTEMD_UTIL_DIR=${systemd}/lib/systemd
          cargo test --release --frozen --offline
        '';
      }
      {
        name = "install";
        script = ''
          install -Dm755 target/release/zram-generator "$out/bin/zram-generator"
          mkdir -p "$out/lib/systemd/system-generators"
          ln -s ../../../bin/zram-generator \
            "$out/lib/systemd/system-generators/zram-generator"
          install -Dm644 units/systemd-zram-setup@.service \
            "$out/lib/systemd/system/systemd-zram-setup@.service"
          install -Dm644 zram-generator.conf.example \
            "$out/share/doc/zram-generator/zram-generator.conf.example"
          install -Dm644 man/zram-generator.8 "$out/share/man/man8/zram-generator.8"
          install -Dm644 man/zram-generator.conf.5 "$out/share/man/man5/zram-generator.conf.5"
        '';
      }
    ];

    checks = {
      testing,
      self,
      ...
    }: {
      tool = testing.mkToolCheck {
        pname = "tool-zram-generator";
        tool = self;
        command = "test -x ${self}/lib/systemd/system-generators/zram-generator && test -f ${self}/lib/systemd/system/systemd-zram-setup@.service";
      };
    };

    meta = {
      description = "Generates systemd units for compressed swap and filesystems on zram";
      homepage = "https://github.com/systemd/zram-generator";
      license = "MIT";
      mainProgram = "zram-generator";
    };
  }
